// Auto-generated by scripts/fetch-camp-schedule.mjs — ESPN camp-week slate only.
// Not tonight's scoreboard. Do not treat these as live scores.

export interface CampScheduleGame {
  dateIso: string;
  when: string;
  away: string;
  home: string;
  tv: string;
  venue: string;
}

export const campScheduleMeta = {
  fetchedAt: "2026-09-04T13:08:34.525Z",
  source: "ESPN scoreboard",
  windowStart: "2026-10-03",
  windowEnd: "2026-10-10",
  label: "ESPN camp-week slate — not tonight",
};

export const campScheduleGames: CampScheduleGame[] = [
  {dateIso:"2026-10-03",when:"10/3 - 7:00 PM EDT",away:"MIA",home:"TOR",tv:"",venue:"Videotron Centre"},
  {dateIso:"2026-10-04",when:"10/4 - 7:00 PM EDT",away:"UTA",home:"DEN",tv:"",venue:"CU Events Center"},
  {dateIso:"2026-10-05",when:"10/5 - 7:00 PM EDT",away:"MEM",home:"ATL",tv:"",venue:"State Farm Arena"},
  {dateIso:"2026-10-05",when:"10/5 - 7:00 PM EDT",away:"PHX",home:"DET",tv:"",venue:"Little Caesars Arena"},
  {dateIso:"2026-10-05",when:"10/5 - 7:00 PM EDT",away:"NYK",home:"PHI",tv:"",venue:"Xfinity Mobile Arena"},
  {dateIso:"2026-10-05",when:"10/5 - 8:00 PM EDT",away:"MIN",home:"MIL",tv:"",venue:"Fiserv Forum"},
  {dateIso:"2026-10-05",when:"10/5 - 10:00 PM EDT",away:"LAL",home:"SAC",tv:"",venue:"Golden 1 Center"},
  {dateIso:"2026-10-06",when:"10/6 - 7:00 PM EDT",away:"BRK",home:"CHA",tv:"",venue:"Spectrum Center"},
  {dateIso:"2026-10-06",when:"10/6 - 8:00 PM EDT",away:"NOP",home:"OKC",tv:"",venue:"BOK Center"},
  {dateIso:"2026-10-06",when:"10/6 - 9:00 PM EDT",away:"DEN",home:"UTA",tv:"",venue:"Delta Center"},
  {dateIso:"2026-10-06",when:"10/6 - 10:00 PM EDT",away:"LAL",home:"GSW",tv:"",venue:"Chase Center"},
  {dateIso:"2026-10-07",when:"10/7 - 7:00 PM EDT",away:"MIN",home:"IND",tv:"",venue:"Hilton Coliseum"},
  {dateIso:"2026-10-07",when:"10/7 - 8:00 PM EDT",away:"ORL",home:"MEM",tv:"",venue:"FedExForum"},
  {dateIso:"2026-10-07",when:"10/7 - 8:00 PM EDT",away:"MIL",home:"OKC",tv:"",venue:"Paycom Center"},
  {dateIso:"2026-10-07",when:"10/7 - 8:00 PM EDT",away:"PHX",home:"CHI",tv:"",venue:"United Center"},
  {dateIso:"2026-10-07",when:"10/7 - 10:00 PM EDT",away:"GSW",home:"POR",tv:"",venue:"Moda Center"},
  {dateIso:"2026-10-08",when:"10/8 - 7:00 PM EDT",away:"BOS",home:"CLE",tv:"",venue:"Rocket Arena"},
  {dateIso:"2026-10-08",when:"10/8 - 7:30 PM EDT",away:"NOP",home:"MIA",tv:"",venue:"Kaseya Center"},
  {dateIso:"2026-10-08",when:"10/8 - 7:30 PM EDT",away:"PHI",home:"BRK",tv:"",venue:"Barclays Center"},
  {dateIso:"2026-10-08",when:"10/8 - 7:30 PM EDT",away:"WAS",home:"NYK",tv:"",venue:"Madison Square Garden"},
  {dateIso:"2026-10-08",when:"10/8 - 8:00 PM EDT",away:"ATL",home:"SAS",tv:"",venue:"Frost Bank Center"},
  {dateIso:"2026-10-08",when:"10/8 - 10:30 PM EDT",away:"SAC",home:"LAL",tv:"",venue:"crypto.com Arena"},
  {dateIso:"2026-10-09",when:"10/9 - 8:00 AM EDT",away:"HOU",home:"DAL",tv:"",venue:"Venetian Arena"},
  {dateIso:"2026-10-09",when:"10/9 - 8:00 PM EDT",away:"MEM",home:"CHI",tv:"",venue:"United Center"},
  {dateIso:"2026-10-10",when:"10/10 - 6:30 PM EDT",away:"LAC",home:"TOR",tv:"",venue:"Rogers Arena"},
  {dateIso:"2026-10-10",when:"10/10 - 7:00 PM EDT",away:"ATL",home:"IND",tv:"",venue:"Gainbridge Fieldhouse"},
  {dateIso:"2026-10-10",when:"10/10 - 7:00 PM EDT",away:"DET",home:"WAS",tv:"",venue:"Capital One Arena"},
  {dateIso:"2026-10-10",when:"10/10 - 8:00 PM EDT",away:"MIN",home:"MIA",tv:"",venue:"Kaseya Center"},
  {dateIso:"2026-10-10",when:"10/10 - 8:00 PM EDT",away:"PHI",home:"BOS",tv:"",venue:"TD Garden"},
  {dateIso:"2026-10-10",when:"10/10 - 8:30 PM EDT",away:"SAC",home:"GSW",tv:"",venue:"Chase Center"},
  {dateIso:"2026-10-10",when:"10/10 - 10:30 PM EDT",away:"SAS",home:"PHX",tv:"",venue:"Mortgage Matchup Center"},
];
