// Auto-generated Clutch Factor Rankings data
// Weekly rankings of the NBA's most clutch performers

export interface ClutchPlayer {
  rank: number;
  player: string;
  team: string;
  clutchRating: number;
  clutchPts: number;
  clutchFgPct: number;
  clutchFtPct: number;
  gameWinners: number;
  clutchPlusMinus: number;
  biggestMoment: string;
  trend: "up" | "down" | "stable";
}

export interface ClutchData {
  generatedDate: string;
  weekLabel: string;
  players: ClutchPlayer[];
  clutchKing: { player: string; team: string; description: string };
  worstInClutch: { player: string; team: string; description: string };
  weeklyHighlight: string;
}

export const clutchData: ClutchData = {
  generatedDate: "April 20, 2026",
  weekLabel: "Week of April 20–26, 2026",
  players: [
    {
      rank: 1,
      player: "Shai Gilgeous-Alexander",
      team: "OKC",
      clutchRating: 98,
      clutchPts: 8.4,
      clutchFgPct: 61.2,
      clutchFtPct: 94.7,
      gameWinners: 6,
      clutchPlusMinus: 14.2,
      biggestMoment: "With 1.8 seconds left and OKC down one in Memphis, SGA caught a baseline inbound, pump-faked Ja Morant into the air, drew the foul, and drained both free throws without so much as a blink. The Grizzlies crowd went silent; the Thunder bench erupted.",
      trend: "up",
    },
    {
      rank: 2,
      player: "Paolo Banchero",
      team: "ORL",
      clutchRating: 96,
      clutchPts: 7.8,
      clutchFgPct: 58.3,
      clutchFtPct: 91.2,
      gameWinners: 4,
      clutchPlusMinus: 11.7,
      biggestMoment: "Trailing Detroit by three with 2:14 remaining, Banchero attacked off the dribble, converted a spinning floater through contact, hit the and-one free throw, and then on the next possession, buried a pull-up mid-range jumper over Cade Cunningham to seal the road upset and send the Magic bench into a frenzy.",
      trend: "up",
    },
    {
      rank: 3,
      player: "Jayson Tatum",
      team: "BOS",
      clutchRating: 95,
      clutchPts: 7.6,
      clutchFgPct: 55.9,
      clutchFtPct: 88.4,
      gameWinners: 5,
      clutchPlusMinus: 12.9,
      biggestMoment: "In Boston's tightest game of the week against Cleveland, Tatum dribbled out a pick-and-roll at the top of the key, stepped back into a 27-footer with Evan Mobley flying at him, and buried the three to push the Celtics lead to four with 48 ticks left — the kind of shot that makes an arena collective exhale.",
      trend: "stable",
    },
    {
      rank: 4,
      player: "Damian Lillard",
      team: "POR",
      clutchRating: 93,
      clutchPts: 8.1,
      clutchFgPct: 52.7,
      clutchFtPct: 96.1,
      gameWinners: 4,
      clutchPlusMinus: 8.3,
      biggestMoment: "Despite Portland's difficult week, Lillard delivered a vintage moment against Utah — pulling up from 31 feet with a hand in his face, draining the buzzer-beater to force overtime, and then pumping his chest at the logo on the floor as the Moda Center shook like it was 2019 again.",
      trend: "up",
    },
    {
      rank: 5,
      player: "Jaylen Brown",
      team: "BOS",
      clutchRating: 91,
      clutchPts: 6.9,
      clutchFgPct: 54.1,
      clutchFtPct: 87.5,
      gameWinners: 3,
      clutchPlusMinus: 10.4,
      biggestMoment: "When Tatum picked up his fifth foul with 3:30 left against Indiana, Brown took the reins without hesitation — posting up Bennedict Mathurin, drawing a foul, hitting both free throws, and then stripping a Tyrese Haliburton dribble-drive to effectively ice the game himself.",
      trend: "up",
    },
    {
      rank: 6,
      player: "Victor Wembanyama",
      team: "SAS",
      clutchRating: 90,
      clutchPts: 6.2,
      clutchFgPct: 57.8,
      clutchFtPct: 79.3,
      gameWinners: 2,
      clutchPlusMinus: 9.8,
      biggestMoment: "In San Antonio's wire-to-wire battle with Dallas, Wembanyama pinned a Luka Dončić floater attempt against the glass with 1:11 remaining — his third block of the fourth quarter — then glided the length of the court to finish an alley-oop for the dagger bucket that made it a two-possession game.",
      trend: "up",
    },
    {
      rank: 7,
      player: "Luka Dončić",
      team: "DAL",
      clutchRating: 89,
      clutchPts: 7.3,
      clutchFgPct: 49.6,
      clutchFtPct: 82.1,
      gameWinners: 3,
      clutchPlusMinus: 6.7,
      biggestMoment: "Down three against Denver with 90 seconds left, Dončić posted Jamal Murray on the elbow, spun baseline for a silky mid-range two, then immediately fouled Murray on the ensuing possession before drawing a charge on Aaron Gordon to give Dallas a chance they ultimately couldn't convert.",
      trend: "stable",
    },
    {
      rank: 8,
      player: "Nikola Jokić",
      team: "DEN",
      clutchRating: 88,
      clutchPts: 5.9,
      clutchFgPct: 56.4,
      clutchFtPct: 80.7,
      gameWinners: 3,
      clutchPlusMinus: 9.1,
      biggestMoment: "Against Dallas in a one-point game with 1:42 left, Jokić received the ball at the elbow, pump-faked twice to get Michael Finney II airborne, drew the foul, and converted both free throws — then delivered a no-look dime to Christian Braun cutting baseline that functionally ended the Mavericks' last real hope.",
      trend: "stable",
    },
    {
      rank: 9,
      player: "Devin Booker",
      team: "PHX",
      clutchRating: 87,
      clutchPts: 7.2,
      clutchFgPct: 50.3,
      clutchFtPct: 90.6,
      gameWinners: 3,
      clutchPlusMinus: 5.4,
      biggestMoment: "With Phoenix needing every win to stay in the play-in picture, Booker exploded for 9 clutch-time points against Sacramento — including a pull-up three over De'Aaron Fox with 1:03 left that put the Suns up for good, a shot he celebrated with a cold, practiced stare back at his own bench.",
      trend: "up",
    },
    {
      rank: 10,
      player: "Anthony Edwards",
      team: "MIN",
      clutchRating: 86,
      clutchPts: 6.8,
      clutchFgPct: 48.9,
      clutchFtPct: 85.3,
      gameWinners: 2,
      clutchPlusMinus: 7.6,
      biggestMoment: "Ant-Man took over against Golden State in the final 2:30, blowing past Steph Curry off the dribble for a rim-rattling left-hand finish, then snarling at the Warriors bench before calmly draining two pressure free throws to seal Minnesota's fourth consecutive win.",
      trend: "up",
    },
    {
      rank: 11,
      player: "Tyrese Haliburton",
      team: "IND",
      clutchRating: 84,
      clutchPts: 5.4,
      clutchFgPct: 47.2,
      clutchFtPct: 88.9,
      gameWinners: 2,
      clutchPlusMinus: 6.2,
      biggestMoment: "Haliburton orchestrated Indiana's comeback from nine down in the fourth against Miami — threading a behind-the-back pass through traffic to Myles Turner for a dunk, then hitting a floater in traffic to cut the deficit to one before Indiana ultimately ran out of time.",
      trend: "stable",
    },
    {
      rank: 12,
      player: "Cade Cunningham",
      team: "DET",
      clutchRating: 82,
      clutchPts: 6.1,
      clutchFgPct: 44.8,
      clutchFtPct: 83.7,
      gameWinners: 2,
      clutchPlusMinus: 3.1,
      biggestMoment: "Against Chicago in a play-in-position clash, Cunningham engineered a methodical 9-2 clutch-time run — hitting a step-back two to tie it, finding Ausar Thompson for a corner three, then icing the win at the free-throw line with the Pistons faithful finally breathing again.",
      trend: "down",
    },
    {
      rank: 13,
      player: "Donovan Mitchell",
      team: "CLE",
      clutchRating: 81,
      clutchPts: 6.4,
      clutchFgPct: 46.3,
      clutchFtPct: 84.2,
      gameWinners: 2,
      clutchPlusMinus: 4.8,
      biggestMoment: "Spida saved Cleveland's most important win of the week against New York — catching a Darius Garland skip pass in the corner with one second on the shot clock, rising over Josh Hart, and burying a three-ball that gave the Cavaliers the lead they never relinquished in a crucial East seeding battle.",
      trend: "stable",
    },
    {
      rank: 14,
      player: "Franz Wagner",
      team: "ORL",
      clutchRating: 80,
      clutchPts: 5.7,
      clutchFgPct: 53.1,
      clutchFtPct: 80.0,
      gameWinners: 1,
      clutchPlusMinus: 8.3,
      biggestMoment: "In Orlando's road upset of Detroit, Wagner attacked a switching defense relentlessly in the final four minutes, getting to the line four times and converting all four free throws while also delivering a crafty bounce pass to a cutting Banchero that extended the Magic lead to five with under a minute left.",
      trend: "up",
    },
    {
      rank: 15,
      player: "Kevin Durant",
      team: "PHX",
      clutchRating: 79,
      clutchPts: 5.8,
      clutchFgPct: 52.6,
      clutchFtPct: 88.1,
      gameWinners: 1,
      clutchPlusMinus: 2.9,
      biggestMoment: "KD bailed out Phoenix's late-game execution woes against Utah with a vintage 19-footer off the glass with 34 seconds left — a shot so effortless and automatic that it felt less like an NBA game-winner and more like a man completing a routine chore he's done ten thousand times before.",
      trend: "stable",
    },
    {
      rank: 16,
      player: "Jalen Brunson",
      team: "NYK",
      clutchRating: 77,
      clutchPts: 5.6,
      clutchFgPct: 45.7,
      clutchFtPct: 87.5,
      gameWinners: 1,
      clutchPlusMinus: 1.8,
      biggestMoment: "Brunson kept New York's slim playoff hopes alive against Toronto by absorbing two brutal charges in the final three minutes and somehow still finding the energy to drain a step-back mid-range over Immanuel Quickley — a play that drew a standing ovation from the Garden crowd who know their guy is always there.",
      trend: "down",
    },
    {
      rank: 17,
      player: "Trae Young",
      team: "ATL",
      clutchRating: 74,
      clutchPts: 5.2,
      clutchFgPct: 41.3,
      clutchFtPct: 89.4,
      gameWinners: 1,
      clutchPlusMinus: -1.4,
      biggestMoment: "In Atlanta's most meaningful win of the month against Charlotte, Young baited Kelly Oubre Jr. into a foul on a three-point attempt with 1:17 left — missing all three free throws initially seemed disastrous, but the referees mercifully called a lane violation, giving him another attempt that he knocked down to keep Atlanta alive.",
      trend: "down",
    },
    {
      rank: 18,
      player: "Chet Holmgren",
      team: "OKC",
      clutchRating: 72,
      clutchPts: 4.1,
      clutchFgPct: 49.2,
      clutchFtPct: 76.3,
      gameWinners: 0,
      clutchPlusMinus: 5.7,
      biggestMoment: "Holmgren's biggest clutch contribution came not with a shot but with a sequence of plays — a timely block on a Devin Booker drive, an offensive rebound putback to extend an OKC possession, and a deflection on the ensuing defensive possession that collectively swung a game the Thunder nearly gave away.",
      trend: "stable",
    },
    {
      rank: 19,
      player: "Joel Embiid",
      team: "PHI",
      clutchRating: 68,
      clutchPts: 5.1,
      clutchFgPct: 40.6,
      clutchFtPct: 72.8,
      gameWinners: 0,
      clutchPlusMinus: -6.3,
      biggestMoment: "Embiid did put together one legitimate clutch sequence against Washington — posting up Kyle Kuzma for a thunderous dunk and then swatting a Johnny Davis pull-up on the other end — but it came in a game the Sixers were already losing by double digits, which somewhat diluted the drama.",
      trend: "down",
    },
    {
      rank: 20,
      player: "Zach LaVine",
      team: "CHI",
      clutchRating: 61,
      clutchPts: 4.3,
      clutchFgPct: 37.1,
      clutchFtPct: 70.2,
      gameWinners: 0,
      clutchPlusMinus: -9.1,
      biggestMoment: "LaVine did flash his full highlight reel in a single clutch-time possession against Detroit — a stepback three that banged off the back iron, rebounded by himself off sheer hustle, followed by a driving layup that also rimmed out — a microcosm of a season that has promised more than it has delivered when the lights burn brightest.",
      trend: "down",
    },
  ],
  clutchKing: {
    player: "Shai Gilgeous-Alexander",
    team: "OKC",
    description:
      "There is simply no one in the NBA right now who you want with the ball and the game on the line more than Shai Gilgeous-Alexander. His 98 clutch rating is the product of a metronomic consistency that borders on the supernatural — a 61.2% field goal percentage in clutch situations, six game-winners on the season, and a +14.2 plus-minus that tells you the Thunder don't just survive late-game situations, they thrive in them. SGA doesn't speed up when the game slows down; if anything, he gets more deliberate, more surgical, more unhurried — like a man who has been waiting patiently all game for exactly this moment. His performance this week in Memphis, draining two ice-water free throws with 1.8 seconds left after a perfectly executed pump-fake, was the latest entry in what is becoming one of the great clutch resumes of his generation.",
  },
  worstInClutch: {
    player: "Zach LaVine",
    team: "CHI",
    description:
      "Zach LaVine is, by any reasonable measure, one of the most gifted athletes the NBA has ever produced — a chiseled, spring-loaded scoring machine who can do things with a basketball that most players only dream about. So it is with genuine sympathy, and just a touch of bewildered amusement, that we present him with this week's Worst in Clutch distinction. A 37.1% clutch field goal percentage, zero game-winners, and a ghastly -9.1 clutch plus-minus paint the picture of a player whose extraordinary talents somehow evaporate in the moments that matter most, like a magician whose best tricks only work when no one is really watching. Chicago fans have been told for years that LaVine is a franchise cornerstone, a closer, a guy you build around — and maybe he still is. But the scoreboard in the final five minutes has been delivering a different memo with remarkable consistency, and at some point even the most loyal Bulls faithful have to wonder when it gets read.",
  },
  weeklyHighlight:
    "The week of April 20–26 delivered everything a basketball purist could ask for — buzzer-beaters, last-second collapses, a stunning upset, and the slow, grinding drama of playoff seeding being decided one clutch possession at a time. The biggest story was unquestionably Paolo Banchero's coronation in Detroit, where Orlando's 23-year-old centerpiece authored back-to-back late-game buckets to topple the East's top seed on their own floor, announcing in the clearest possible terms that the Magic are not merely a playoff participant but a genuine threat. Meanwhile, Shai Gilgeous-Alexander continued his quiet, inexorable march toward clutch immortality, his Memphis free throws this week landing in the same pantheon as the ice-cold, last-possession moments that have defined Oklahoma City's remarkable 65-win season. At the other end of the spectrum, Philadelphia's late-game woes deepened — Joel Embiid's -6.3 clutch plus-minus is becoming a serious concern as the playoffs approach, and the Sixers are running out of regular season opportunities to find answers. Damian Lillard provided the week's most electric individual moment with a 31-foot buzzer-beater against Utah, a reminder that even on a disappointing Portland team, the game's most natural closer still has a flair for the theatrical. As the regular season draws to a close and every possession takes on playoff weight, the separation between the closers and the pretenders is becoming impossible to ignore.",
};