// Auto-generated Draft Stock Tracker data
// Weekly big board and scouting reports for the 2026 NBA Draft

export interface DraftProspect {
  rank: number; prevRank: number; name: string; school: string;
  position: string; height: string; age: number; scoutingGrade: number;
  projection: string; bestFit: string[]; strengths: string[]; weaknesses: string[];
  comparison: string; weeklyNote: string; trend: "rising" | "falling" | "stable";
  stats: { ppg: number; rpg: number; apg: number; fgPct: number; threePct: number };
}

export interface TeamNeed {
  team: string; record: string; lotteryOdds: string;
  primaryNeed: string; secondaryNeed: string; bestProspectFit: string; note: string;
}

export interface DraftData {
  generatedDate: string; weekLabel: string; classYear: number;
  bigBoard: DraftProspect[]; risers: { name: string; change: number; reason: string }[];
  fallers: { name: string; change: number; reason: string }[];
  tankWatch: TeamNeed[]; weeklyScoutReport: string;
}

export const draftData: DraftData = {
  generatedDate: "May 18, 2026",
  weekLabel: "Week of May 18–24, 2026",
  classYear: 2026,
  bigBoard: [
    {
      rank: 1,
      prevRank: 1,
      name: "Darryn Peterson",
      school: "Kansas",
      position: "SG/SF",
      height: "6'6\"",
      age: 18,
      scoutingGrade: 98,
      projection: "Top-3 Pick",
      bestFit: ["OKC", "SAS", "DET"],
      strengths: ["Elite shot creation off the dribble", "Advanced defensive IQ", "NBA-ready athleticism", "High-end playmaking vision"],
      weaknesses: ["Three-point consistency needs refinement", "Can force iso situations", "Still developing as off-ball mover"],
      comparison: "Paul George with higher offensive ceiling",
      weeklyNote: "Peterson dominated the Big 12 Tournament and locked up consensus #1 status after scouts raved about his pre-draft combine measurements. His 7'1\" wingspan was the headline this week.",
      trend: "stable",
      stats: { ppg: 22.4, rpg: 5.8, apg: 4.2, fgPct: 0.467, threePct: 0.361 },
    },
    {
      rank: 2,
      prevRank: 3,
      name: "Noa Essengue",
      school: "Ratiopharm Ulm (Germany)",
      position: "PF/SF",
      height: "6'9\"",
      age: 18,
      scoutingGrade: 96,
      projection: "Top-3 Pick",
      bestFit: ["SAS", "DET", "CLE"],
      strengths: ["Freakish length and mobility", "Face-up scoring versatility", "Fluid ball-handling for size", "Defensive switchability"],
      weaknesses: ["Three-point volume low", "Interior toughness still developing", "Thin frame vs. NBA bigs"],
      comparison: "Jonathan Kuminga with better shot-making instincts",
      weeklyNote: "Essengue's BBL playoff run turned heads globally — he dropped 28/9 against Bayern Munich with three blocks. His stock jumped two spots after the most impressive individual performance of any prospect this week.",
      trend: "rising",
      stats: { ppg: 17.8, rpg: 7.4, apg: 2.1, fgPct: 0.511, threePct: 0.334 },
    },
    {
      rank: 3,
      prevRank: 2,
      name: "Tre Johnson",
      school: "Texas",
      position: "SG",
      height: "6'5\"",
      age: 18,
      scoutingGrade: 95,
      projection: "Top-3 Pick",
      bestFit: ["MIA", "PHX", "ORL"],
      strengths: ["Elite catch-and-shoot ability", "Advanced pull-up three-point game", "Crafty off-ball movement", "High basketball IQ"],
      weaknesses: ["Average athleticism by NBA standards", "Inconsistent playmaking", "Below-average defensive effort"],
      comparison: "Devin Booker with a quicker release",
      weeklyNote: "Johnson slid one spot after Peterson's combine performance stole the spotlight, but his scoring profile remains elite. Pre-draft workouts have teams raving about his shot-making off any action.",
      trend: "falling",
      stats: { ppg: 24.3, rpg: 3.9, apg: 3.1, fgPct: 0.452, threePct: 0.388 },
    },
    {
      rank: 4,
      prevRank: 4,
      name: "Ace Bailey",
      school: "Rutgers",
      position: "SF/PF",
      height: "6'10\"",
      age: 18,
      scoutingGrade: 94,
      projection: "Top-5 Pick",
      bestFit: ["DET", "BOS", "MIN"],
      strengths: ["Exceptional scoring instincts", "Size and skill combo rare at age 18", "High-arcing pull-up jumper", "Motor and competitiveness"],
      weaknesses: ["Three-point mechanics inconsistent", "Turnover-prone in pick-and-roll", "Needs to improve lateral quickness"],
      comparison: "Khris Middleton with 30 more lbs of upside",
      weeklyNote: "Bailey's measured combine wingspan of 7'3\" was the second-best of any prospect this cycle. Teams picking in the 4–7 range are actively war-gaming scenarios to land him.",
      trend: "stable",
      stats: { ppg: 19.6, rpg: 7.2, apg: 2.4, fgPct: 0.441, threePct: 0.327 },
    },
    {
      rank: 5,
      prevRank: 5,
      name: "Dylan Harper",
      school: "Rutgers",
      position: "PG/SG",
      height: "6'6\"",
      age: 19,
      scoutingGrade: 93,
      projection: "Top-5 Pick",
      bestFit: ["ORL", "CHA", "PHX"],
      strengths: ["Exceptional size for a lead guard", "Craft and touch in the mid-range", "Natural scoring ability in transition", "Calm under pressure"],
      weaknesses: ["Three-point shooting volume low", "Can be passive in half-court sets", "Conditioning questioned"],
      comparison: "Donovan Mitchell with Ron Harper's body",
      weeklyNote: "Harper and Bailey make Rutgers the most loaded draft school in years. Harper's individual workout videos circulating this week reminded teams why he was the consensus #1 at the start of the season.",
      trend: "stable",
      stats: { ppg: 21.2, rpg: 4.7, apg: 5.5, fgPct: 0.471, threePct: 0.318 },
    },
    {
      rank: 6,
      prevRank: 7,
      name: "Jalil Bethea",
      school: "Indiana",
      position: "SG/PG",
      height: "6'4\"",
      age: 18,
      scoutingGrade: 91,
      projection: "Top-8 Pick",
      bestFit: ["PHX", "POR", "MIA"],
      strengths: ["Elite burst and first-step speed", "Ferocious on-ball defender", "Pick-and-roll creator at high level", "Competitive fire"],
      weaknesses: ["Shooting mechanics invite doubt", "Shot selection erratic", "Reading second-side defense still developing"],
      comparison: "Ja Morant defensive intensity meets CJ McCollum scoring",
      weeklyNote: "Bethea rose one spot following an electrifying pre-draft workout where he clocked the second-fastest lane agility time at the combine. Multiple teams in the 6–10 range have him as their top non-consensus target.",
      trend: "rising",
      stats: { ppg: 18.7, rpg: 3.4, apg: 4.8, fgPct: 0.438, threePct: 0.342 },
    },
    {
      rank: 7,
      prevRank: 6,
      name: "VJ Edgecombe",
      school: "Baylor",
      position: "SG/SF",
      height: "6'5\"",
      age: 19,
      scoutingGrade: 90,
      projection: "Top-10 Pick",
      bestFit: ["CLE", "TOR", "HOU"],
      strengths: ["Explosive above-the-rim athlete", "Motor and transition scoring", "Perimeter defense elite", "Strong finisher"],
      weaknesses: ["Three-point shooting inconsistent", "Half-court creation limited", "Turnover-prone against pressure"],
      comparison: "Anfernee Simons with elite athleticism",
      weeklyNote: "Edgecombe's stock dipped slightly this week amid questions about his three-point sustainability — he shot 34.7% on the year but only 28% in the final month. Teams want answers during individual workouts.",
      trend: "falling",
      stats: { ppg: 17.3, rpg: 4.6, apg: 2.9, fgPct: 0.458, threePct: 0.347 },
    },
    {
      rank: 8,
      prevRank: 8,
      name: "Johni Broome",
      school: "Auburn",
      position: "C/PF",
      height: "6'10\"",
      age: 22,
      scoutingGrade: 89,
      projection: "Top-10 Pick",
      bestFit: ["DEN", "SAS", "BOS"],
      strengths: ["High-BB IQ post scorer", "Excellent rebounder", "Surprising playmaking for a big", "Consistent mid-range game"],
      weaknesses: ["Age (22) limits upside ceiling", "Three-point range still developing", "Lateral mobility vs. PF/C switches"],
      comparison: "Jaren Jackson Jr. without the shot-blocking elite tier, more consistent scorer",
      weeklyNote: "Broome met with seven teams this week and impressed across the board. His maturity and readiness are seen as a plug-and-play asset for contenders. The age question keeps him from climbing higher.",
      trend: "stable",
      stats: { ppg: 18.1, rpg: 10.7, apg: 2.8, fgPct: 0.523, threePct: 0.298 },
    },
    {
      rank: 9,
      prevRank: 10,
      name: "Kasparas Jakucionis",
      school: "Illinois",
      position: "PG",
      height: "6'5\"",
      age: 19,
      scoutingGrade: 88,
      projection: "Top-12 Pick",
      bestFit: ["POR", "TOR", "LAC"],
      strengths: ["Elite court vision and passing", "Size and feel for the position", "Solid three-point shooter", "Natural playmaker"],
      weaknesses: ["Athletic limitations vs. elite PGs", "Finishing through contact needs work", "Defensive effort inconsistent"],
      comparison: "Mike Conley with Nikola Jokic-lite vision",
      weeklyNote: "Jakucionis rose one spot after his passing highlights from the Big Ten Tournament resurfaced during combine week. His 7.4 APG in March was the best of any draft-eligible player in the country.",
      trend: "rising",
      stats: { ppg: 15.4, rpg: 4.2, apg: 7.4, fgPct: 0.449, threePct: 0.368 },
    },
    {
      rank: 10,
      prevRank: 9,
      name: "Khaman Maluach",
      school: "Duke",
      position: "C",
      height: "7'2\"",
      age: 18,
      scoutingGrade: 87,
      projection: "Top-12 Pick",
      bestFit: ["CHA", "MIA", "PHI"],
      strengths: ["Elite rim protection and shot-altering", "Exceptional vertical for 7'2\"", "Lob threat and finisher", "High motor"],
      weaknesses: ["Offensive game limited outside 8 feet", "Foul trouble tendency", "Ball-handling untrustworthy"],
      comparison: "Walker Kessler with more athleticism and higher offensive ceiling",
      weeklyNote: "Maluach fell one spot as Jakucionis's combine performance generated buzz. His defensive metrics at Duke remain elite, but teams at 9–14 are questioning if he can contribute enough offensively as a rookie.",
      trend: "falling",
      stats: { ppg: 11.2, rpg: 8.9, apg: 0.9, fgPct: 0.614, threePct: 0.0 },
    },
    {
      rank: 11,
      prevRank: 12,
      name: "Labaron Philon",
      school: "Alabama",
      position: "PG",
      height: "6'3\"",
      age: 19,
      scoutingGrade: 86,
      projection: "Top-15 Pick",
      bestFit: ["GSW", "ORL", "ATL"],
      strengths: ["Explosive scoring guard", "Elite pull-up shooting", "Strong ball-handler under pressure", "Competitive defender"],
      weaknesses: ["Slightly undersized", "Decision-making in high-leverage spots", "Three-point consistency (volume shooter)"],
      comparison: "De'Aaron Fox with a more polished jump shot",
      weeklyNote: "Philon rose one spot after a standout performance at a closed pre-draft workout hosted by Golden State. The Warriors are reportedly smitten and have him circled if they keep their pick.",
      trend: "rising",
      stats: { ppg: 16.8, rpg: 3.2, apg: 5.1, fgPct: 0.446, threePct: 0.357 },
    },
    {
      rank: 12,
      prevRank: 11,
      name: "Egor Demin",
      school: "BYU",
      position: "PG/SG",
      height: "6'9\"",
      age: 18,
      scoutingGrade: 85,
      projection: "Top-15 Pick",
      bestFit: ["TOR", "SAS", "OKC"],
      strengths: ["Rare size for a guard", "Advanced passing and playmaking vision", "Long-term two-way potential", "European skill development"],
      weaknesses: ["Shooting reliability needs refinement", "Athleticism pedestrian for NBA", "Strength vs. physical guards"],
      comparison: "Luka Doncic athleticism tier but Ricky Rubio passing instincts",
      weeklyNote: "Demin's unique 6'9\" point guard frame keeps teams intrigued despite a roller-coaster freshman season at BYU. Fell one spot as shooting concerns lingered from March film review sessions.",
      trend: "falling",
      stats: { ppg: 13.6, rpg: 5.1, apg: 6.2, fgPct: 0.421, threePct: 0.329 },
    },
    {
      rank: 13,
      prevRank: 13,
      name: "Thomas Sorber",
      school: "Georgetown",
      position: "C/PF",
      height: "6'11\"",
      age: 19,
      scoutingGrade: 84,
      projection: "Lottery Pick",
      bestFit: ["HOU", "CLE", "DEN"],
      strengths: ["Excellent passing big", "Interior scoring via footwork", "Defensive versatility", "High feel for the game"],
      weaknesses: ["Perimeter shooting unproven", "Injury history (foot)", "Conference competition level"],
      comparison: "Domantas Sabonis without the elite rebounding at this stage",
      weeklyNote: "Sorber's medicals came back clean this week, clearing a significant hurdle after his foot issue in February. Teams had him in medical risk territory; that concern is now largely resolved.",
      trend: "stable",
      stats: { ppg: 16.4, rpg: 9.3, apg: 3.6, fgPct: 0.549, threePct: 0.0 },
    },
    {
      rank: 14,
      prevRank: 15,
      name: "Maxime Raynaud",
      school: "Stanford",
      position: "C",
      height: "7'1\"",
      age: 22,
      scoutingGrade: 83,
      projection: "Lottery Fringe",
      bestFit: ["GSW", "LAL", "MIA"],
      strengths: ["Legitimate three-point shooting center", "High IQ interior scoring", "Excellent free-throw shooter", "Pick-and-pop threat"],
      weaknesses: ["Athleticism below NBA center average", "Slow lateral movement defensively", "Age (22) limits projection ceiling"],
      comparison: "Brook Lopez with better post footwork, less athleticism",
      weeklyNote: "Raynaud rose one spot as the pre-draft process rewards his basketball IQ and shooting. Teams needing a floor-spacing big adore his ability to shoot threes off the dribble as a center.",
      trend: "rising",
      stats: { ppg: 20.1, rpg: 11.2, apg: 1.8, fgPct: 0.536, threePct: 0.378 },
    },
    {
      rank: 15,
      prevRank: 14,
      name: "Asa Newell",
      school: "Georgia",
      position: "PF/C",
      height: "6'11\"",
      age: 18,
      scoutingGrade: 82,
      projection: "Lottery Fringe",
      bestFit: ["POR", "PHX", "CHA"],
      strengths: ["Elite athleticism and length", "Rim-running finishing", "Defensive upside extremely high", "Shot-blocking instincts"],
      weaknesses: ["Offensive game raw", "Three-point shooting project", "Needs physical development"],
      comparison: "Jaren Jackson Jr. Year 1 raw version with more upside athletically",
      weeklyNote: "Newell dropped one spot as teams prefer the sure-thing production of Raynaud. However, his long-term upside keeps him in the top-15 conversation; one team with an early-20s pick called him their \"highest-ceiling sleeper.\"",
      trend: "falling",
      stats: { ppg: 12.7, rpg: 7.8, apg: 1.2, fgPct: 0.518, threePct: 0.267 },
    },
    {
      rank: 16,
      prevRank: 16,
      name: "Jeremiah Fears",
      school: "Oklahoma",
      position: "PG",
      height: "6'3\"",
      age: 18,
      scoutingGrade: 81,
      projection: "Mid First Round",
      bestFit: ["PHI", "ATL", "LAC"],
      strengths: ["Elite downhill speed", "Natural scoring instincts", "Advanced floater game", "Clutch performer in late-game"],
      weaknesses: ["Three-point shooting volume too low", "On-ball defense needs attention", "Slight frame"],
      comparison: "Isaiah Thomas with plus length and better playmaking upside",
      weeklyNote: "Fears is locked in at 16 this week. Teams 14–20 universally have him as a viable selection, praising his scoring upside per possession as one of the best in the draft outside the top-5.",
      trend: "stable",
      stats: { ppg: 17.9, rpg: 3.1, apg: 4.7, fgPct: 0.441, threePct: 0.319 },
    },
    {
      rank: 17,
      prevRank: 18,
      name: "Hugo Gonzalez",
      school: "Real Madrid (Spain)",
      position: "SG/SF",
      height: "6'7\"",
      age: 19,
      scoutingGrade: 80,
      projection: "Mid First Round",
      bestFit: ["SAS", "OKC", "TOR"],
      strengths: ["Advanced shot-making off movement", "Defensive instincts for age", "High IQ backdoor cutting", "Playmaking from the wing"],
      weaknesses: ["Still adjusting to elite athleticism globally", "Needs strength added", "NBA pace adjustment unknown"],
      comparison: "Mikal Bridges with a more active offensive skill set",
      weeklyNote: "Gonzalez climbed one spot after his EuroLeague playoffs performance where he averaged 14.3 PPG on 41% from three. Spanish media reporting that NBA teams have flooded Real Madrid with interview requests.",
      trend: "rising",
      stats: { ppg: 11.4, rpg: 3.8, apg: 2.4, fgPct: 0.489, threePct: 0.411 },
    },
    {
      rank: 18,
      prevRank: 17,
      name: "Koa Peat",
      school: "Arizona",
      position: "PF",
      height: "6'8\"",
      age: 19,
      scoutingGrade: 79,
      projection: "Mid First Round",
      bestFit: ["MIN", "DET", "BOS"],
      strengths: ["NBA-ready strength and physicality", "Strong offensive rebounder", "Interior scoring reliability", "Motor and hustle plays"],
      weaknesses: ["Three-point shooting unproven", "Half-court creation limited", "Positional defensive versatility"],
      comparison: "Zion Williamson minus top-tier athleticism, more skilled post game",
      weeklyNote: "Peat dropped one spot as wing prospects continue to be prioritized in the modern NBA. His upside as a physical power forward is legitimate, but teams want more evidence he can space the floor.",
      trend: "falling",
      stats: { ppg: 14.3, rpg: 8.4, apg: 1.6, fgPct: 0.553, threePct: 0.291 },
    },
    {
      rank: 19,
      prevRank: 19,
      name: "Liam McNeeley",
      school: "Connecticut",
      position: "SF",
      height: "6'7\"",
      age: 18,
      scoutingGrade: 78,
      projection: "Mid First Round",
      bestFit: ["ORL", "HOU", "IND"],
      strengths: ["Pure scorer with three-point ability", "Fluid mechanics and quick release", "Soft touch in mid-range", "Competitive motor"],
      weaknesses: ["Athleticism may not translate fully", "Playmaking off the dribble limited", "Defensive engagement inconsistent"],
      comparison: "Gordon Hayward with more reliable shooting",
      weeklyNote: "McNeeley is a steady presence at 19. His shooting reputation is iron-clad across the league, and his UConn pedigree under a championship program adds polish teams value.",
      trend: "stable",
      stats: { ppg: 16.2, rpg: 5.2, apg: 2.1, fgPct: 0.448, threePct: 0.382 },
    },
    {
      rank: 20,
      prevRank: 21,
      name: "Nique Clifford",
      school: "Colorado State",
      position: "SF/PF",
      height: "6'7\"",
      age: 22,
      scoutingGrade: 77,
      projection: "Late First Round",
      bestFit: ["GSW", "MIA", "TOR"],
      strengths: ["Elite three-point shooter for size", "Versatile defender", "High basketball IQ", "Unselfish team player"],
      weaknesses: ["Age (22) narrows projection window", "Not a primary creator", "Athleticism average by NBA wing standards"],
      comparison: "Sam Hauser with plus athleticism and better defense",
      weeklyNote: "Clifford rose one spot after a standout showing at the Portsmouth Invitational. He shot 6-of-9 from three across two games and showcased a defensive versatility that grabbed attention from multiple contending teams.",
      trend: "rising",
      stats: { ppg: 18.9, rpg: 7.3, apg: 2.7, fgPct: 0.484, threePct: 0.421 },
    },
    {
      rank: 21,
      prevRank: 20,
      name: "Collin Murray-Boyles",
      school: "South Carolina",
      position: "PF",
      height: "6'7\"",
      age: 19,
      scoutingGrade: 76,
      projection: "Late First Round",
      bestFit: ["CLE", "DEN", "OKC"],
      strengths: ["Excellent defensive engagement", "Versatile switching ability", "Good motor and toughness", "Improved mid-range"],
      weaknesses: ["Three-point shooting project", "Offensive creation limited", "Shot creation against length"],
      comparison: "Jaren Jackson Jr. without the shot-blocking volume, stronger defender overall",
      weeklyNote: "Murray-Boyles dropped one spot but remains a highly coveted defensive-first forward. Several SEC coaches said he's the best defender in the class and teams building winning cultures are taking note.",
      trend: "falling",
      stats: { ppg: 14.1, rpg: 7.9, apg: 1.9, fgPct: 0.502, threePct: 0.274 },
    },
    {
      rank: 22,
      prevRank: 22,
      name: "Will Riley",
      school: "Illinois",
      position: "SF/SG",
      height: "6'8\"",
      age: 18,
      scoutingGrade: 75,
      projection: "Late First Round",
      bestFit: ["PHX", "ATL", "POR"],
      strengths: ["Exceptional size and fluidity for wing", "Soft touch from mid-range", "Good instincts as secondary creator", "Upside profile very high"],
      weaknesses: ["Production inconsistent at Illinois", "Conditioning flagged", "Three-point reliability on the fringe"],
      comparison: "Kevin Durant's movement patterns on a smaller scale, Andrew Wiggins production comparison",
      weeklyNote: "Riley is a polarizing prospect teams can't ignore. His physical profile screams first-round, but his consistency issues keep him at 22. One lottery team anonymously said he's their favorite player to fall to the mid-20s.",
      trend: "stable",
      stats: { ppg: 13.8, rpg: 4.4, apg: 2.2, fgPct: 0.432, threePct: 0.341 },
    },
    {
      rank: 23,
      prevRank: 24,
      name: "Rasheer Fleming",
      school: "St. Bonaventure",
      position: "PF/SF",
      height: "6'8\"",
      age: 22,
      scoutingGrade: 74,
      projection: "Late First Round",
      bestFit: ["BOS", "MIN", "LAL"],
      strengths: ["Excellent three-point shooter", "Versatile defensive matchup", "High IQ team-first player", "NBA-ready body"],
      weaknesses: ["Competition level question", "Not a primary ball-handler", "Creation against NBA athleticism TBD"],
      comparison: "Dorian Finney-Smith with better shooting and more offensive punch",
      weeklyNote: "Fleming rose one spot after his Portsmouth Invitational performance convinced skeptics his mid-major production translates. His 45.5% three-point shooting on high volume over four years is nearly impossible to ignore.",
      trend: "rising",
      stats: { ppg: 16.6, rpg: 6.8, apg: 1.8, fgPct: 0.512, threePct: 0.455 },
    },
    {
      rank: 24,
      prevRank: 23,
      name: "Walter Clayton Jr.",
      school: "Florida",
      position: "PG/SG",
      height: "6'3\"",
      age: 22,
      scoutingGrade: 73,
      projection: "Late First / Early Second",
      bestFit: ["LAC", "PHI", "ATL"],
      strengths: ["Elite shot-maker", "Big-game performer with championship pedigree", "Excellent shot off movement", "Veteran poise"],
      weaknesses: ["Age (22) limits ceiling projection", "Average athleticism", "Playmaking inconsistency in half-court"],
      comparison: "D.J. Augustin with better scoring, Tyus Jones playmaking hybrid",
      weeklyNote: "Clayton dropped one spot as youth prospects with more upside crowd the bottom of the first round. His NCAA Tournament heroics remain fresh in scouts' minds, but the age factor is the controlling variable here.",
      trend: "falling",
      stats: { ppg: 18.7, rpg: 3.8, apg: 4.3, fgPct: 0.462, threePct: 0.403 },
    },
    {
      rank: 25,
      prevRank: 25,
      name: "Braylon Mullins",
      school: "Duke",
      position: "SG",
      height: "6'4\"",
      age: 18,
      scoutingGrade: 72,
      projection: "Late First Round",
      bestFit: ["HOU", "ORL", "CHA"],
      strengths: ["Gifted scorer with pull-up proficiency", "Quick release and form", "High ceiling athleticism", "Defensive tools are there"],
      weaknesses: ["Finishing at rim inconsistent", "Turnover-prone under pressure", "Limited playmaking for others"],
      comparison: "Malik Monk with better size and more upside",
      weeklyNote: "Mullins is locked at 25 heading into the homestretch of pre-draft season. Duke brand travels well and multiple teams at the back end of the lottery are scheduling private workouts for next week.",
      trend: "stable",
      stats: { ppg: 14.7, rpg: 3.6, apg: 2.8, fgPct: 0.443, threePct: 0.359 },
    },
    {
      rank: 26,
      prevRank: 27,
      name: "Kon Knueppel",
      school: "Duke",
      position: "SG/SF",
      height: "6'6\"",
      age: 18,
      scoutingGrade: 71,
      projection: "Late First Round",
      bestFit: ["SAS", "GSW", "MIA"],
      strengths: ["High IQ mover without the ball", "Reliable three-point shooter", "Smart off-ball reads", "Good teammate and culture fit"],
      weaknesses: ["Creation off the dribble limited", "Average athleticism for modern wings", "Not a lockdown defender"],
      comparison: "Luke Kennard with better defense and movement shooting",
      weeklyNote: "Knueppel rose one spot as teams grew more comfortable with his shooting profile. His ability to play within a system without needing creation reps makes him a low-risk, high-value late first-rounder.",
      trend: "rising",
      stats: { ppg: 14.1, rpg: 3.9, apg: 2.4, fgPct: 0.467, threePct: 0.401 },
    },
    {
      rank: 27,
      prevRank: 26,
      name: "Maliq Brown",
      school: "Syracuse",
      position: "SF/PF",
      height: "6'7\"",
      age: 20,
      scoutingGrade: 70,
      projection: "Late First / Early Second",
      bestFit: ["OKC", "MIN", "DET"],
      strengths: ["Elite on-ball defender", "Switchable length and lateral movement", "Strong rebounder for wing", "High motor every possession"],
      weaknesses: ["Offense is a work in progress", "Three-point shooting 28% career", "Will need time before contributing offensively"],
      comparison: "Ron Artest energy and defense without the scoring yet, Matisse Thybulle type",
      weeklyNote: "Brown dropped one spot as offensive concerns at the back end of the first round sharpen. Defensive metrics show he's a top-5 wing defender in the class but teams need more than that at pick 27.",
      trend: "falling",
      stats: { ppg: 11.3, rpg: 6.7, apg: 2.1, fgPct: 0.447, threePct: 0.281 },
    },
    {
      rank: 28,
      prevRank: 28,
      name: "Yves Missi",
      school: "Gonzaga",
      position: "C",
      height: "7'0\"",
      age: 20,
      scoutingGrade: 69,
      projection: "Late First / Early Second",
      bestFit: ["CLE", "BOS", "NOP"],
      strengths: ["Excellent rim protector", "Efficient finisher in pick-and-roll", "Good passing instincts for a center", "High motor rebounder"],
      weaknesses: ["Offensive range extremely limited", "Foul-drawing rate too high", "Pick-and-pop shooting non-existent"],
      comparison: "Clint Capela with better passing and higher energy",
      weeklyNote: "Missi is steady at 28. Teams view him as a complementary center who can protect the paint and run actions immediately. His limitations on offense are known quantities at this point.",
      trend: "stable",
      stats: { ppg: 12.8, rpg: 9.4, apg: 1.7, fgPct: 0.621, threePct: 0.0 },
    },
    {
      rank: 29,
      prevRank: 30,
      name: "Eric Reibe",
      school: "Wake Forest",
      position: "C/PF",
      height: "7'1\"",
      age: 20,
      scoutingGrade: 68,
      projection: "Late First / Second Round",
      bestFit: ["LAL", "PHX", "POR"],
      strengths: ["Physical presence and size", "Improved face-up game", "Good hands and catching radius", "Block and alter shots"],
      weaknesses: ["Footwork against quick bigs", "Range doesn't extend beyond 15 feet", "Motor is inconsistent"],
      comparison: "Robin Lopez with better upside athletically",
      weeklyNote: "Reibe climbed one spot after a strong pre-draft workout showcase where his footwork showed notable improvement from his season film. A sleeper candidate to hear his name called late in the first.",
      trend: "rising",
      stats: { ppg: 13.4, rpg: 8.1, apg: 1.4, fgPct: 0.567, threePct: 0.0 },
    },
    {
      rank: 30,
      prevRank: 29,
      name: "Caleb Wilson",
      school: "Northwestern",
      position: "PF/C",
      height: "6'10\"",
      age: 20,
      scoutingGrade: 67,
      projection: "Second Round",
      bestFit: ["TOR", "GSW", "OKC"],
      strengths: ["Three-point shooting for size", "Smart mover and cutter", "High-floor contributor", "Excellent academic/pro character reviews"],
      weaknesses: ["Below average athleticism", "Not a versatile defender", "Production came against weak Big Ten competition"],
      comparison: "Davis Bertans with better rebounding and athleticism",
      weeklyNote: "Wilson dropped one spot as Reibe's pre-draft improvements pushed him to the borderline. However, his ability to stretch the floor as a stretch-five in a modern offense keeps him right on the first-round bubble.",
      trend: "falling",
      stats: { ppg: 15.2, rpg: 7.6, apg: 2.3, fgPct: 0.498, threePct: 0.389 },
    },
  ],
  risers: [
    {
      name: "Noa Essengue",
      change: 2,
      reason: "Dominant BBL playoff performance (28 pts, 9 reb, 3 blk vs Bayern Munich) combined with elite combine measurements solidified his top-3 status and generated the most scout buzz of any international prospect this week.",
    },
    {
      name: "Jalil Bethea",
      change: 1,
      reason: "Recorded the second-fastest lane agility time at the combine and wowed scouts with his on-ball defensive intensity. Multiple teams in the 6–10 range have elevated him to their top non-consensus target.",
    },
    {
      name: "Labaron Philon",
      change: 1,
      reason: "Standout closed pre-draft workout at Golden State impressed front office decision-makers. His pull-up shooting and defensive effort in 1-on-1 drills were described as \"lottery-worthy\" by two independent evaluators.",
    },
  ],
  fallers: [
    {
      name: "VJ Edgecombe",
      change: -1,
      reason: "Three-point sustainability questions emerged after final-month shooting data (28% in March vs 34.7% season) circulated among front offices. Teams want clarification in individual workouts before locking in their boards.",
    },
    {
      name: "Tre Johnson",
      change: -1,
      reason: "Darryn Peterson's elite combine measurements and Noa Essengue's playoff heroics pushed him to 3. Johnson's game itself remains elite — the movement is relative and not a reflection of any diminished evaluation.",
    },
    {
      name: "Walter Clayton Jr.",
      change: -1,
      reason: "Age-22 ceiling concerns are winning the internal debate at several front offices picking in the 20–28 range. Youth prospects with higher upside are crowding the back of the first round and forcing Clayton down.",
    },
  ],
  tankWatch: [
    {
      team: "GSW",
      record: "41-41",
      lotteryOdds: "3.0%",
      primaryNeed: "Scoring Wing",
      secondaryNeed: "Point Guard",
      bestProspectFit: "Labaron Philon",
      note: "Golden State is right at the cut line and could miss the playoffs, triggering a lottery pick. With a potential pick in the 11–17 range, Philon's explosive scoring fits perfectly alongside their modern motion system.",
    },
    {
      team: "LAC",
      record: "42-40",
      lotteryOdds: "2.5%",
      primaryNeed: "Point Guard",
      secondaryNeed: "Big Man",
      bestProspectFit: "Kasparas Jakucionis",
      note: "The Clippers are in rebuild mode with an aging core. A lottery selection gives them a chance at a long-term point guard solution, and Jakucionis's vision and size would be a foundational piece for years.",
    },
    {
      team: "POR",
      record: "42-40",
      lotteryOdds: "2.5%",
      primaryNeed: "Wing Scorer",
      secondaryNeed: "Stretch Big",
      bestProspectFit: "Will Riley",
      note: "Portland continues its measured rebuild and a pick in the late teens to early 20s would be ideal for Riley's polarizing upside. His physical profile matches exactly what Portland wants to build around long-term.",
    },
    {
      team: "PHX",
      record: "45-37",
      lotteryOdds: "1.5%",
      primaryNeed: "Scoring Guard",
      secondaryNeed: "Two-Way Wing",
      bestProspectFit: "Jalil Bethea",
      note: "Phoenix's six-game skid has them in freefall and their pick positioning matters if it conveys this year. Bethea's explosive scoring and defensive energy would invigorate a locker room that desperately needs youth.",
    },
    {
      team: "ORL",
      record: "45-37",
      lotteryOdds: "1.5%",
      primaryNeed: "Playmaking Guard",
      secondaryNeed: "Floor Spacer",
      bestProspectFit: "Jeremiah Fears",
      note: "Orlando needs a dynamic scoring guard to complement their frontcourt core. Fears's downhill speed and late-game scoring instincts would accelerate a young roster already trending toward playoff contention.",
    },
    {
      team: "PHI",
      record: "45-37",
      lotteryOdds: "1.5%",
      primaryNeed: "Wing Defender",
      secondaryNeed: "Playmaking Guard",
      bestProspectFit: "Hugo Gonzalez",
      note: "Philadelphia's six-game losing streak has cost them dearly in seeding and their developmental pick could land mid-to-late lottery fringe. Gonzalez's two-way wing profile fits their long-term identity post-reset.",
    },
    {
      team: "CHA",
      record: "44-38",
      lotteryOdds: "1.0%",
      primaryNeed: "Rim Protector",
      secondaryNeed: "Shot Creator",
      bestProspectFit: "Khaman Maluach",
      note: "Charlotte has quietly put together a solid season but remains outside the top seed tier. A late first-round pick at a center position is what their roster construction needs, and Maluach is the ideal low-risk/high-upside fit.",
    },
    {
      team: "MIA",
      record: "43-39",
      lotteryOdds: "0.5%",
      primaryNeed: "Two-Way Wing",
      secondaryNeed: "Point Guard",
      bestProspectFit: "Nique Clifford",
      note: "Miami culture demands high-IQ team-first players and Clifford fits the mold precisely. His three-point shooting and defensive versatility in the Pat Riley system is a recipe for immediate contribution.",
    },
  ],
  weeklyScoutReport: "The 2026 NBA Draft pre-draft process hit full stride this week with the combine delivering its biggest headlines — Darryn Peterson's 7'1\" wingspan measurement locked in his consensus #1 status while Noa Essengue's BBL playoff explosion generated the most international buzz since Victor Wembanyama's 2023 emergence. The class continues to be defined by elite wing talent at the top and genuine depth at the guard position throughout the teens and 20s, giving rebuilding teams multiple viable directions at virtually every pick. Medicals cleared for Thomas Sorber represent the biggest positive development for a prospect's stock this week, while three-point shooting sustainability questions around VJ Edgecombe are the week's defining scouting debate. With the lottery drawing approaching and several borderline teams still battling for playoff positioning, the draft board remains more fluid than at any point this season.",
};