// Auto-generated Draft Stock Tracker data
// Weekly big board and scouting reports for the 2026 NBA Draft

export interface DraftProspect {
  rank: number; prevRank: number; name: string; school: string;
  position: string; height: string; age: number; scoutingGrade: number;
  projection: string; bestFit: string[]; strengths: string[]; weaknesses: string[];
  comparison: string; weeklyNote: string; trend: "rising" | "falling" | "stable";
  stats: { ppg: number; rpg: number; apg: number; fgPct: number; threePct: number };
}

export interface TeamNeed {
  team: string; record: string; lotteryOdds: string;
  primaryNeed: string; secondaryNeed: string; bestProspectFit: string; note: string;
}

export interface DraftData {
  generatedDate: string; weekLabel: string; classYear: number;
  bigBoard: DraftProspect[]; risers: { name: string; change: number; reason: string }[];
  fallers: { name: string; change: number; reason: string }[];
  tankWatch: TeamNeed[]; weeklyScoutReport: string;
}

export const draftData: DraftData = {
  generatedDate: "September 14, 2026",
  weekLabel: "Week of September 14–20, 2026",
  classYear: 2026,
  bigBoard: [
    {
      rank: 1,
      prevRank: 1,
      name: "Tre Johnson",
      school: "Texas",
      position: "SG",
      height: "6'6\"",
      age: 19,
      scoutingGrade: 98,
      projection: "Top-3 Pick",
      bestFit: ["GSW", "OKC", "HOU"],
      strengths: ["Elite shot creation off the dribble", "NBA-ready frame and athleticism", "Advanced footwork in mid-range", "High basketball IQ", "Consistent three-point stroke"],
      weaknesses: ["Can over-rely on isolation sets", "Needs refinement as a passer", "Defensive effort inconsistent vs. elite competition"],
      comparison: "Young Devin Booker with stronger handle",
      weeklyNote: "Johnson turned in a spectacular performance at the adidas Nations showcase, dropping 34 points on efficient shooting and cementing his hold on the No. 1 spot heading into the season.",
      trend: "stable",
      stats: { ppg: 24.3, rpg: 4.1, apg: 3.2, fgPct: 48.2, threePct: 38.7 },
    },
    {
      rank: 2,
      prevRank: 3,
      name: "Darryn Peterson",
      school: "Kansas",
      position: "SG/SF",
      height: "6'5\"",
      age: 18,
      scoutingGrade: 96,
      projection: "Top-3 Pick",
      bestFit: ["SAS", "DET", "NYK"],
      strengths: ["Explosive athleticism", "Versatile scoring repertoire", "High-motor defender", "Elite transition play", "Projects as two-way wing"],
      weaknesses: ["Three-point consistency still developing", "Small hands affect ball security", "Decision-making in half-court needs growth"],
      comparison: "Combo of Brandon Ingram athleticism with OG Anunoby defensive tools",
      weeklyNote: "Peterson rocketed up one spot after an elite showing at the Nike skills academy, where scouts raved about his defensive intensity and improved pull-up jumper. Legitimate No. 1 conversation underway.",
      trend: "rising",
      stats: { ppg: 19.8, rpg: 5.6, apg: 3.8, fgPct: 46.5, threePct: 34.2 },
    },
    {
      rank: 3,
      prevRank: 2,
      name: "Noa Essengue",
      school: "Ratiopharm Ulm (Germany)",
      position: "PF/SF",
      height: "6'9\"",
      age: 18,
      scoutingGrade: 95,
      projection: "Top-3 Pick",
      bestFit: ["SAS", "OKC", "MIN"],
      strengths: ["Rare combination of size and ball-handling", "Fluid scorer at three levels", "Advanced feel for the game", "Excellent shot-making over length", "Eurobasket pedigree"],
      weaknesses: ["Needs to add functional strength", "Transition from European game takes time", "Rebounding effort inconsistent"],
      comparison: "Early-career Franz Wagner with superior shot creation",
      weeklyNote: "Essengue slides one spot after Peterson's standout week, but scouts remain extremely bullish. His EuroLeague preseason debut is circled on calendars for late September.",
      trend: "falling",
      stats: { ppg: 17.2, rpg: 6.3, apg: 2.9, fgPct: 47.8, threePct: 36.1 },
    },
    {
      rank: 4,
      prevRank: 4,
      name: "Liam McNeeley",
      school: "UConn",
      position: "SF",
      height: "6'7\"",
      age: 19,
      scoutingGrade: 93,
      projection: "Top-5 Pick",
      bestFit: ["GSW", "BOS", "TOR"],
      strengths: ["Elite catch-and-shoot ability", "Strong off-ball movement", "High-character competitor", "NBA-ready body", "Winning pedigree at UConn"],
      weaknesses: ["Limited self-creation off the dribble", "Athleticism is good but not elite", "Shot selection can be overly conservative"],
      comparison: "Joe Harris with better size and secondary playmaking",
      weeklyNote: "McNeeley is locked in at No. 4, impressing scouts with his film-room preparation and IQ at UConn's fall sessions. His floor is perhaps the safest in the class.",
      trend: "stable",
      stats: { ppg: 16.4, rpg: 5.1, apg: 2.1, fgPct: 49.3, threePct: 41.2 },
    },
    {
      rank: 5,
      prevRank: 6,
      name: "Yaxel Lendeborg",
      school: "Michigan",
      position: "PF/C",
      height: "6'9\"",
      age: 20,
      scoutingGrade: 91,
      projection: "Top-7 Pick",
      bestFit: ["HOU", "OKC", "DEN"],
      strengths: ["Exceptional rebounding instincts", "High-energy motor", "Versatile defender who can switch", "Improving face-up game", "Block shot threat"],
      weaknesses: ["Perimeter shooting range still limited", "Offensive creation needs development", "Foul trouble has been recurring issue"],
      comparison: "Draymond Green offensive role, with Jarrett Allen's rim protection",
      weeklyNote: "Lendeborg climbs one after a dominant showing in Michigan's fall practices leaked via program media. His defensive versatility is drawing comparisons to some of the best big men in this decade's drafts.",
      trend: "rising",
      stats: { ppg: 14.7, rpg: 10.2, apg: 3.4, fgPct: 54.1, threePct: 28.3 },
    },
    {
      rank: 6,
      prevRank: 5,
      name: "Egor Demin",
      school: "BYU",
      position: "PG",
      height: "6'9\"",
      age: 18,
      scoutingGrade: 90,
      projection: "Top-8 Pick",
      bestFit: ["SAS", "TOR", "PHI"],
      strengths: ["Extraordinary passing vision for his size", "Elite court general at 6'9\"", "Crafty off-ball scorer", "Excellent feel and pace control", "International experience"],
      weaknesses: ["Outside shooting reliability needs work", "Slender frame absorbs punishment poorly", "Can be too fancy with passes"],
      comparison: "Luka Doncic's passing archetype at a younger developmental stage",
      weeklyNote: "Demin slips one spot as Lendeborg climbs past him, but his arrow remains pointed up. Scouts raving about his ability to orchestrate the BYU offense with veteran poise at 18.",
      trend: "stable",
      stats: { ppg: 13.2, rpg: 4.8, apg: 8.1, fgPct: 43.6, threePct: 31.4 },
    },
    {
      rank: 7,
      prevRank: 7,
      name: "Jalil Bethea",
      school: "South Carolina",
      position: "SG",
      height: "6'4\"",
      age: 18,
      scoutingGrade: 89,
      projection: "Top-10 Pick",
      bestFit: ["PHX", "LAL", "MIA"],
      strengths: ["Explosive first step", "Natural scorer at all three levels", "Excellent free throw drawing ability", "Competitive defensive instincts", "Strong with ball in pick-and-roll"],
      weaknesses: ["Turnover-prone when pressed", "Three-point percentage dipped late last season", "Needs to improve off-ball awareness"],
      comparison: "Immanuel Quickley with more scoring upside and size",
      weeklyNote: "Bethea holds steady at No. 7. South Carolina's coaching staff has reportedly given him more autonomy in the offense this fall, which scouts believe will showcase his playmaking chops more fully.",
      trend: "stable",
      stats: { ppg: 18.9, rpg: 3.7, apg: 4.2, fgPct: 44.8, threePct: 33.6 },
    },
    {
      rank: 8,
      prevRank: 9,
      name: "Kasparas Jakucionis",
      school: "Illinois",
      position: "PG/SG",
      height: "6'5\"",
      age: 19,
      scoutingGrade: 88,
      projection: "Top-10 Pick",
      bestFit: ["LAC", "POR", "CLE"],
      strengths: ["Outstanding playmaker and shot creator", "International IQ and savvy", "Excellent pull-up mid-range game", "Can play on or off the ball", "Good size for the position"],
      weaknesses: ["Defensive engagement needs consistency", "Gets caught gambling for steals", "Floater game still developing"],
      comparison: "Bogdan Bogdanovic with better athleticism and playmaking upside",
      weeklyNote: "Jakucionis climbs one spot following glowing reports from Illinois's media day, where he reportedly looked sharper and more assertive running the point. His stock is quietly rising.",
      trend: "rising",
      stats: { ppg: 16.7, rpg: 3.9, apg: 5.6, fgPct: 45.3, threePct: 35.8 },
    },
    {
      rank: 9,
      prevRank: 8,
      name: "Camron Kimball",
      school: "Auburn",
      position: "C/PF",
      height: "6'10\"",
      age: 20,
      scoutingGrade: 87,
      projection: "Top-12 Pick",
      bestFit: ["GSW", "LAL", "ORL"],
      strengths: ["Elite rim protector", "Exceptional pick-and-roll finisher", "Excellent hands and catch radius", "Strong lob threat", "Consistent motor"],
      weaknesses: ["Offensive range extends only to mid-post", "Can be sealed off by stronger bigs", "Free throw shooting (58%) is a liability"],
      comparison: "Clint Capela with better passing and improved footwork",
      weeklyNote: "Kimball drops one as Jakucionis moves up, but remains firmly in the lottery conversation. Auburn's frontcourt depth will give him a chance to show expanded skills this season.",
      trend: "stable",
      stats: { ppg: 13.1, rpg: 9.4, apg: 1.3, fgPct: 61.7, threePct: 0.0 },
    },
    {
      rank: 10,
      prevRank: 10,
      name: "Jeremiah Fears",
      school: "Oklahoma",
      position: "PG",
      height: "6'3\"",
      age: 18,
      scoutingGrade: 86,
      projection: "Top-12 Pick",
      bestFit: ["SAS", "CHA", "TOR"],
      strengths: ["Blazing first step and change of direction", "Advanced shot creation off dribble", "Clutch performer", "Excellent free throw shooter (86%)", "High-upside two-way PG"],
      weaknesses: ["Frame is still slight at 175 lbs", "Three-point shot goes cold in stretches", "Occasionally too fast for his own offense"],
      comparison: "Tyrese Maxey at the same stage, with a higher ceiling if strength develops",
      weeklyNote: "Fears is rock-solid at No. 10 entering fall. Oklahoma's new motion-heavy system is tailor-made to highlight his speed and decision-making. Multiple lottery teams have already visited Norman.",
      trend: "stable",
      stats: { ppg: 17.6, rpg: 3.2, apg: 5.9, fgPct: 43.1, threePct: 34.9 },
    },
    {
      rank: 11,
      prevRank: 11,
      name: "Drake Powell",
      school: "North Carolina",
      position: "SF/SG",
      height: "6'6\"",
      age: 19,
      scoutingGrade: 85,
      projection: "Top-15 Pick",
      bestFit: ["NYK", "MIA", "BOS"],
      strengths: ["Elite athleticism and wing length", "Improving jump shot mechanics", "High-energy perimeter defender", "Strong transition scorer", "Competitive nature"],
      weaknesses: ["Half-court shot creation still raw", "Turnover issues in tight spaces", "Three-point shot needs refinement"],
      comparison: "Josh Giddey's athleticism with stronger defensive tools",
      weeklyNote: "Powell is steady at No. 11. UNC coaches have publicly praised his off-season shooting work, and scouts want to see those improvements translate when the lights come on in November.",
      trend: "stable",
      stats: { ppg: 14.3, rpg: 5.8, apg: 2.7, fgPct: 45.9, threePct: 32.1 },
    },
    {
      rank: 12,
      prevRank: 12,
      name: "Karter Knox",
      school: "Kentucky",
      position: "SF/PF",
      height: "6'8\"",
      age: 19,
      scoutingGrade: 84,
      projection: "Top-15 Pick",
      bestFit: ["DEN", "PHX", "POR"],
      strengths: ["Fluid scoring at multiple levels", "Outstanding footwork in post and mid-range", "Good passer for his position", "Kentucky pedigree and big-game experience", "Versatile defender"],
      weaknesses: ["Three-point volume too low", "Lacks elite burst to beat NBA defenders off dribble", "Conditioning can fade late in games"],
      comparison: "Tobias Harris with better passing instincts",
      weeklyNote: "Knox is holding at No. 12 as Kentucky's fall program ramps up. The staff's decision to feature him in more pick-and-roll actions could significantly boost his draft stock.",
      trend: "stable",
      stats: { ppg: 15.9, rpg: 6.2, apg: 2.4, fgPct: 47.2, threePct: 30.8 },
    },
    {
      rank: 13,
      prevRank: 14,
      name: "Will Riley",
      school: "Illinois",
      position: "SG/SF",
      height: "6'7\"",
      age: 18,
      scoutingGrade: 83,
      projection: "Mid Lottery",
      bestFit: ["ATL", "PHI", "ORL"],
      strengths: ["Elite three-point shooting (41%+)", "Intelligent off-ball movement", "Good size and length for the position", "Smooth shooting mechanics", "Winning teammate"],
      weaknesses: ["Athleticism is average for the position", "Doesn't create much off the dribble", "Tends to disappear in physical matchups"],
      comparison: "Duncan Robinson with better size and developing playmaking",
      weeklyNote: "Riley rises one spot after showcasing a more aggressive attacking mindset at Illinois's open practice. Scouts are starting to re-evaluate his ceiling if the pull-up game continues to develop.",
      trend: "rising",
      stats: { ppg: 14.1, rpg: 4.3, apg: 1.9, fgPct: 46.8, threePct: 41.3 },
    },
    {
      rank: 14,
      prevRank: 13,
      name: "Labaron Philon",
      school: "Alabama",
      position: "PG",
      height: "6'2\"",
      age: 18,
      scoutingGrade: 82,
      projection: "Mid Lottery",
      bestFit: ["CHA", "LAC", "GSW"],
      strengths: ["Explosive quickness and pressure-on-ball defense", "Fearless attacking mentality", "Excellent pull-up floater", "High motor on both ends", "Clutch shot-maker"],
      weaknesses: ["Height and length limiting on defense", "Turnover rate too high against pressure", "Outside shooting (32%) needs work"],
      comparison: "Elfrid Payton's pressure defense paired with Tyus Jones's craft",
      weeklyNote: "Philon drops one as Riley moves past him, but remains a high-value pick. Alabama's up-tempo offense should be a perfect showcase for his attacking guard play.",
      trend: "falling",
      stats: { ppg: 16.2, rpg: 3.1, apg: 6.4, fgPct: 44.6, threePct: 32.1 },
    },
    {
      rank: 15,
      prevRank: 15,
      name: "Tounde Yessoufou",
      school: "Elan Chalon (France)",
      position: "SG/SF",
      height: "6'6\"",
      age: 19,
      scoutingGrade: 81,
      projection: "Mid Lottery",
      bestFit: ["SAS", "DET", "MIN"],
      strengths: ["Tremendous athleticism and burst", "Advanced defensive instincts", "Improving three-point shot", "Slashing and finishing ability", "Excellent hands"],
      weaknesses: ["Shot mechanics under pressure need refinement", "Offensive creation from standstill is limited", "Limited North American exposure"],
      comparison: "Matisse Thybulle with more offensive upside",
      weeklyNote: "Yessoufou holds at 15 as scouts await his Pro A minutes this fall. Teams are intrigued by his elite defensive tools and believe the offensive game is closer to NBA-ready than his numbers suggest.",
      trend: "stable",
      stats: { ppg: 11.4, rpg: 4.8, apg: 1.6, fgPct: 47.1, threePct: 35.6 },
    },
    {
      rank: 16,
      prevRank: 17,
      name: "Dink Pate",
      school: "Georgia",
      position: "C",
      height: "7'0\"",
      age: 20,
      scoutingGrade: 80,
      projection: "Late Lottery",
      bestFit: ["HOU", "DEN", "CLE"],
      strengths: ["Dominant shot-blocker with 7'4\" wingspan", "Improved touch around the basket", "Excellent screen-setter", "Pick-and-roll synergy with guards", "Emerging offensive footwork"],
      weaknesses: ["Shooting range capped at 12 feet", "Foul prone when attacking", "Speed in transition below average"],
      comparison: "Brook Lopez in a lob-heavy role with better athleticism",
      weeklyNote: "Pate rises one after a quietly impressive fall session at Georgia. His improved drop-step and baby hook are drawing attention from big-man scouts who believe he can be a 15-point producer.",
      trend: "rising",
      stats: { ppg: 13.8, rpg: 8.7, apg: 1.1, fgPct: 58.3, threePct: 0.0 },
    },
    {
      rank: 17,
      prevRank: 16,
      name: "Nique Clifford",
      school: "Colorado State",
      position: "SF/PF",
      height: "6'7\"",
      age: 21,
      scoutingGrade: 79,
      projection: "Late Lottery",
      bestFit: ["POR", "MIA", "TOR"],
      strengths: ["Seasoned scorer with complete offensive arsenal", "Excellent rebounding for his position", "High-IQ passer", "Reliable from three (38%)", "Leadership and experience"],
      weaknesses: ["Age (21) is a concern for ceiling", "Lateral quickness may limit NBA defense", "Hasn't faced elite competition consistently"],
      comparison: "Paul Millsap's scoring versatility with slightly better range",
      weeklyNote: "Clifford slips one as Pate's momentum builds, but his proven production at the college level keeps him firmly in the lottery conversation. Older prospects with his skill set translate well.",
      trend: "falling",
      stats: { ppg: 20.1, rpg: 8.9, apg: 3.1, fgPct: 48.7, threePct: 38.2 },
    },
    {
      rank: 18,
      prevRank: 18,
      name: "Thomas Sorber",
      school: "Georgetown",
      position: "C/PF",
      height: "6'10\"",
      age: 19,
      scoutingGrade: 78,
      projection: "Late Lottery",
      bestFit: ["PHX", "ORL", "ATL"],
      strengths: ["Elite passing big with 5+ APG", "Soft touch on floaters", "Mobile for a center", "High basketball IQ", "Improved three-point range"],
      weaknesses: ["Defensive anchor role still developing", "Back-to-basket scoring limited", "Inconsistent effort on glass"],
      comparison: "Domantas Sabonis with better mobility and lottery-level upside",
      weeklyNote: "Sorber is steady at 18 and teams love his passing upside. Georgetown's system will ask him to play-make even more this year, which should only help his case.",
      trend: "stable",
      stats: { ppg: 14.2, rpg: 7.6, apg: 5.1, fgPct: 52.4, threePct: 31.7 },
    },
    {
      rank: 19,
      prevRank: 20,
      name: "Bryson Tucker",
      school: "UCLA",
      position: "SG",
      height: "6'4\"",
      age: 19,
      scoutingGrade: 77,
      projection: "Top-20 Pick",
      bestFit: ["LAC", "MIA", "NYK"],
      strengths: ["Elite pull-up shooter", "Crafty shot creation off movement screens", "Good defensive hands", "Reliable mid-range scorer", "Plays fast but in control"],
      weaknesses: ["Slight frame struggles to finish through contact", "Below-average passer in traffic", "Perimeter defense can be passive"],
      comparison: "Jordan Nwora with better athleticism and improved playmaking",
      weeklyNote: "Tucker climbs one spot after UCLA's coaching staff raved about his expanded playmaking role in fall workouts. His pull-up shooting is among the best in the class.",
      trend: "rising",
      stats: { ppg: 17.4, rpg: 3.4, apg: 2.8, fgPct: 45.7, threePct: 37.9 },
    },
    {
      rank: 20,
      prevRank: 19,
      name: "Johni Broome",
      school: "Auburn",
      position: "C/PF",
      height: "6'10\"",
      age: 22,
      scoutingGrade: 76,
      projection: "Top-20 Pick",
      bestFit: ["DEN", "MIN", "CLE"],
      strengths: ["Proven elite rebounder", "Physical post presence", "Block shot ability", "High-character leader", "Reliable face-up 15-footer"],
      weaknesses: ["Age (22) significantly caps upside", "Offense too back-to-basket for modern NBA", "Limited mobility in pick-and-roll defense"],
      comparison: "Nikola Vucevic without the three-point range but with better defensive effort",
      weeklyNote: "Broome slips one as younger bigs gain momentum, but his senior production is elite. His sheer dominance at Auburn for multiple seasons is hard to ignore on any board.",
      trend: "falling",
      stats: { ppg: 19.7, rpg: 11.1, apg: 2.3, fgPct: 55.8, threePct: 28.6 },
    },
    {
      rank: 21,
      prevRank: 21,
      name: "Marcus Foster Jr.",
      school: "Michigan State",
      position: "PG/SG",
      height: "6'3\"",
      age: 19,
      scoutingGrade: 75,
      projection: "Top-25 Pick",
      bestFit: ["POR", "GSW", "TOR"],
      strengths: ["Excellent court vision and passing", "Solid three-point shooter (37%)", "Heady defender", "Winning team-first mentality", "Good in pick-and-roll"],
      weaknesses: ["Explosiveness is average", "Struggles finishing against shot-blockers", "Not an elite ball-handler yet"],
      comparison: "Kyle Lowry's competitive DNA with Cade Cunningham's shooting versatility",
      weeklyNote: "Foster is holding steady at 21. Michigan State's system under Izzo is expected to put him in leadership roles early, and scouts value that kind of pressure-testing heading into June.",
      trend: "stable",
      stats: { ppg: 13.6, rpg: 3.8, apg: 5.7, fgPct: 44.2, threePct: 37.1 },
    },
    {
      rank: 22,
      prevRank: 22,
      name: "Jalen Haralson",
      school: "Notre Dame",
      position: "SF",
      height: "6'7\"",
      age: 20,
      scoutingGrade: 74,
      projection: "Top-25 Pick",
      bestFit: ["PHI", "CHA", "LAL"],
      strengths: ["Length and versatility on defense", "Smooth scorer in transition", "Improving three-point shot (35%)", "Good rebounder for a wing", "Hard-nosed competitor"],
      weaknesses: ["Half-court offense too passive", "Needs to improve shot creation vs. physicality", "Average athleticism at NBA level"],
      comparison: "Mikal Bridges with a less polished offensive game but bigger frame",
      weeklyNote: "Haralson is stable at 22. Notre Dame scouts note that he's been the most vocal on-court communicator in fall sessions — a trait that front offices increasingly prioritize in wing prospects.",
      trend: "stable",
      stats: { ppg: 13.9, rpg: 6.1, apg: 2.2, fgPct: 46.4, threePct: 35.3 },
    },
    {
      rank: 23,
      prevRank: 23,
      name: "Hugo Gonzalez",
      school: "Real Madrid (Spain)",
      position: "PG/SG",
      height: "6'5\"",
      age: 18,
      scoutingGrade: 73,
      projection: "Top-25 Pick",
      bestFit: ["SAS", "OKC", "DET"],
      strengths: ["Exceptional feel and basketball IQ", "Euro-style floater game", "Good passer off the drive", "Defensively instinctive", "Mature on-court demeanor"],
      weaknesses: ["NBA athleticism questions remain", "Outside shot still streaky", "Will need buyout period"],
      comparison: "Ricky Rubio's playmaking instincts with Darius Garland's scoring touch",
      weeklyNote: "Gonzalez holds at 23 as Real Madrid enters preseason. EuroLeague games starting next month will be critical proving grounds — scouts have three weeks circled to evaluate him in high-level competition.",
      trend: "stable",
      stats: { ppg: 10.3, rpg: 3.2, apg: 5.8, fgPct: 43.9, threePct: 33.4 },
    },
    {
      rank: 24,
      prevRank: 25,
      name: "Derik Queen",
      school: "Maryland",
      position: "C/PF",
      height: "6'10\"",
      age: 19,
      scoutingGrade: 72,
      projection: "Top-30 Pick",
      bestFit: ["LAC", "ATL", "POR"],
      strengths: ["Tremendous passing for a big (4.5 APG)", "Natural finisher at the rim", "Good touch on mid-range jumper", "Improving three-point range", "Strong hands"],
      weaknesses: ["Rim protection is below average for a center", "Lateral mobility in drop coverage", "Can be outmuscled by veteran NBA bigs"],
      comparison: "Nikola Jokic's passing instincts in a more athletic, project-level package",
      weeklyNote: "Queen climbs one spot after Maryland's coaching staff confirmed he will start the year as the team's primary ball initiator — a significant vote of confidence that scouts are taking note of.",
      trend: "rising",
      stats: { ppg: 15.3, rpg: 8.2, apg: 4.5, fgPct: 53.6, threePct: 29.8 },
    },
    {
      rank: 25,
      prevRank: 24,
      name: "Adou Thiero",
      school: "Arkansas",
      position: "SF/PF",
      height: "6'7\"",
      age: 20,
      scoutingGrade: 71,
      projection: "Top-30 Pick",
      bestFit: ["MIA", "ORL", "PHX"],
      strengths: ["Explosive dunker and lob threat", "Elite athleticism and second-jump ability", "Tenacious on-ball defender", "Improving spot-up shooting", "High energy off the bench"],
      weaknesses: ["Outside shooting (31%) needs significant improvement", "Ball-handling limits creation", "Foul trouble recurring issue"],
      comparison: "Jonathan Isaac's athleticism with less offensive polish but higher motor",
      weeklyNote: "Thiero slides one as Queen moves up. He remains a polarizing prospect — pure athletes with his tools always have a home in the NBA, but the shooting development is critical to watch this season.",
      trend: "falling",
      stats: { ppg: 12.8, rpg: 6.9, apg: 1.4, fgPct: 51.2, threePct: 31.4 },
    },
    {
      rank: 26,
      prevRank: 26,
      name: "Aiden Sherrell",
      school: "Murray State",
      position: "C",
      height: "6'11\"",
      age: 21,
      scoutingGrade: 70,
      projection: "Top-30 Pick",
      bestFit: ["GSW", "TOR", "DEN"],
      strengths: ["Elite shot-blocker (3.8 BPG)", "Mobile big who can run the floor", "Reliable post-up scorer", "Improving perimeter touch", "High-character player"],
      weaknesses: ["Level of competition at Murray State", "Limited pick-and-pop ability", "Turnover rate as ball-handler too high"],
      comparison: "Rudy Gobert's rim protection archetype with slightly better offensive versatility",
      weeklyNote: "Sherrell holds at 26. The Murray State schedule will draw scrutiny, but his shot-blocking numbers are legitimate regardless of opponent. Pre-draft camps in the spring will be make-or-break.",
      trend: "stable",
      stats: { ppg: 16.4, rpg: 9.8, apg: 1.2, fgPct: 57.3, threePct: 22.1 },
    },
    {
      rank: 27,
      prevRank: 28,
      name: "Rashad Williams",
      school: "Wake Forest",
      position: "SG/PG",
      height: "6'2\"",
      age: 20,
      scoutingGrade: 69,
      projection: "Mid Second Round",
      bestFit: ["POR", "CHA", "LAC"],
      strengths: ["Elite shot-maker under pressure", "Quick release from three", "Strong free throw drawing ability", "Good feel in transition offense", "Plays with veteran composure"],
      weaknesses: ["Lacks ideal NBA size at 6'2\"", "Average defender at next level", "Too many pull-up attempts in half-court"],
      comparison: "Jordan Goodwin's energy with Bones Hyland's scoring upside",
      weeklyNote: "Williams climbs one as Wake Forest's new system opens up more scoring lanes for him. His tape from last year's ACC tournament was quietly one of the best individual performances in the class.",
      trend: "rising",
      stats: { ppg: 19.2, rpg: 3.6, apg: 4.1, fgPct: 43.7, threePct: 36.8 },
    },
    {
      rank: 28,
      prevRank: 27,
      name: "Moustapha Thiam",
      school: "Alabama",
      position: "C/PF",
      height: "7'0\"",
      age: 19,
      scoutingGrade: 68,
      projection: "Mid Second Round",
      bestFit: ["HOU", "OKC", "NYK"],
      strengths: ["Exceptional size and wingspan (7'5\")", "Natural shot-blocker", "Emerging face-up game", "Potential elite rim protector", "Hard worker in practice"],
      weaknesses: ["Still very raw offensively", "Foul prone (5.1 per 40 minutes)", "Conditioning and stamina need work"],
      comparison: "Early Bismack Biyombo with a higher offensive ceiling if shooting develops",
      weeklyNote: "Thiam slips one as his offensive rawness remains a concern, but no one in the class has more physical upside at the center position. His minute-by-minute improvement at Alabama is worth monitoring.",
      trend: "falling",
      stats: { ppg: 9.7, rpg: 7.4, apg: 0.8, fgPct: 55.9, threePct: 18.3 },
    },
    {
      rank: 29,
      prevRank: 29,
      name: "Isaiah Wilkins",
      school: "Virginia",
      position: "SF/PF",
      height: "6'8\"",
      age: 21,
      scoutingGrade: 67,
      projection: "Late Second Round",
      bestFit: ["BOS", "DET", "MIN"],
      strengths: ["Tenacious positional defender", "Strong rebounder for his position", "Reliable spot-up three (36%)", "Excellent team defender with IQ", "UVA system translates well to NBA"],
      weaknesses: ["Explosive athleticism is below average", "Limited offensive creation off the dribble", "Age reduces upside projection"],
      comparison: "Dorian Finney-Smith with better feel and shooting efficiency",
      weeklyNote: "Wilkins is holding at 29. Virginia's system continues to produce NBA players and his defensive profile is a known commodity to scouts. A strong senior season could nudge him into the first round.",
      trend: "stable",
      stats: { ppg: 10.4, rpg: 6.7, apg: 1.8, fgPct: 47.6, threePct: 36.1 },
    },
    {
      rank: 30,
      prevRank: 30,
      name: "Asa Newell",
      school: "Georgia",
      position: "PF/C",
      height: "6'10\"",
      age: 18,
      scoutingGrade: 66,
      projection: "Late Second Round",
      bestFit: ["ATL", "POR", "LAL"],
      strengths: ["Elite length and physical tools", "Developing skill set with high upside", "Good hands and catch radius", "Energetic rebounder", "Youth gives room to grow"],
      weaknesses: ["Offense is extremely raw", "Decision-making still developing", "Prone to losing defensive assignment"],
      comparison: "Jaren Jackson Jr. if the outside shot never fully comes — all the tools, needs the polish",
      weeklyNote: "Newell rounds out the board at No. 30. At 18, he is the youngest player in the top 30 and scouts are tracking his development closely. Georgia's frontcourt spotlight will determine whether he rises or falls.",
      trend: "stable",
      stats: { ppg: 9.2, rpg: 6.8, apg: 0.9, fgPct: 49.4, threePct: 24.7 },
    },
  ],
  risers: [
    {
      name: "Darryn Peterson",
      change: 1,
      reason: "Dominant showing at Nike Skills Academy — defensive intensity and improved pull-up jumper have multiple scouts moving him into No. 1 conversations ahead of the college season.",
    },
    {
      name: "Yaxel Lendeborg",
      change: 1,
      reason: "Leaked Michigan practice footage showing expanded offensive skill set and elite switchability has scouts re-evaluating his ceiling as a modern two-way power forward.",
    },
    {
      name: "Will Riley",
      change: 1,
      reason: "Illinois fall practice reports indicate a more aggressive, attack-first mentality that has scouts upgrading their ceiling projections if the pull-up game continues to diversify his scoring.",
    },
  ],
  fallers: [
    {
      name: "Noa Essengue",
      change: -1,
      reason: "Slides one spot due to Peterson's momentum rather than any performance concern. EuroLeague preseason debut in late September will be a significant stock checkpoint.",
    },
    {
      name: "Labaron Philon",
      change: -1,
      reason: "Three-point shooting concerns (32%) resurfaced after Alabama fall scrimmage footage surfaced. Teams want to see improved outside shooting before committing to a top-10 projection.",
    },
    {
      name: "Adou Thiero",
      change: -1,
      reason: "Shooting development (31% from three) remains the central concern and no significant improvement has been documented in fall workouts. Athletic upside still draws interest but floor is a worry.",
    },
  ],
  tankWatch: [
    {
      team: "GSW",
      record: "41-41",
      lotteryOdds: "9.0%",
      primaryNeed: "Primary ball-handler / franchise PG",
      secondaryNeed: "Wing scorer",
      bestProspectFit: "Jeremiah Fears",
      note: "Golden State sits at .500 and faces a critical offseason identity question. Without a franchise cornerstone post-Steph era, the front office may be eyeing a late-season tank to secure lottery positioning. Fears or Demin would immediately upgrade their PG situation.",
    },
    {
      team: "LAC",
      record: "42-40",
      lotteryOdds: "7.5%",
      primaryNeed: "Playmaking guard",
      secondaryNeed: "Rim protector",
      bestProspectFit: "Kasparas Jakucionis",
      note: "The Clippers find themselves in no-man's land at .512. With an aging core and no clear path to contention, missing the playoffs could be the best outcome. Jakucionis fits their need for a lead guard who can initiate and score.",
    },
    {
      team: "POR",
      record: "42-40",
      lotteryOdds: "7.5%",
      primaryNeed: "Wing scorer / two-way forward",
      secondaryNeed: "Playmaking PG",
      bestProspectFit: "Drake Powell",
      note: "Portland is in a quasi-rebuild while keeping competitive. Slipping out of the playoffs would put them in prime position for a top-12 pick. Powell's combination of athleticism and two-way potential is exactly the profile they need.",
    },
    {
      team: "PHX",
      record: "45-37",
      lotteryOdds: "4.5%",
      primaryNeed: "Scoring wing",
      secondaryNeed: "Playmaking big",
      bestProspectFit: "Jalil Bethea",
      note: "Phoenix has lost six straight and looks like a play-in team at best. A lottery pick would be transformative. Bethea's shot creation and guard play could give them the dynamic scorer they desperately need alongside their veterans.",
    },
    {
      team: "MIN",
      record: "49-33",
      lotteryOdds: "1.5%",
      primaryNeed: "Perimeter shooting",
      secondaryNeed: "Secondary ball-handler",
      bestProspectFit: "Liam McNeeley",
      note: "Minnesota is solidly in the playoffs but owns future pick rights that could convey. They are not actively tanking, but the front office is monitoring the draft class closely as they look to build around their core.",
    },
    {
      team: "DEN",
      record: "54-28",
      lotteryOdds: "0.8%",
      primaryNeed: "Athletic wing defender",
      secondaryNeed: "Backup center",
      bestProspectFit: "Noa Essengue",
      note: "Denver has dropped five straight and looks fatigued heading into the postseason stretch. Their own pick is unlikely to convey in the lottery, but they hold several future assets. The front office will be watching Essengue closely for a potential trade-up target.",
    },
    {
      team: "ATL",
      record: "46-36",
      lotteryOdds: "2.5%",
      primaryNeed: "Point guard of the future",
      secondaryNeed: "Athletic power forward",
      bestProspectFit: "Egor Demin",
      note: "Atlanta continues to struggle and is trending toward the play-in. Their pick situation gives them some flexibility, and Demin's unique 6'9\" playmaker archetype would be a fascinating complement to their wing-heavy roster.",
    },
    {
      team: "LAL",
      record: "53-29",
      lotteryOdds: "0.4%",
      primaryNeed: "Wing defender / secondary scorer",
      secondaryNeed: "Depth big",
      bestProspectFit: "Darryn Peterson",
      note: "The Lakers have dropped five straight and look vulnerable in the West. Their own first-round pick is owed elsewhere, but they are already scouting Peterson as a franchise-building piece to acquire via trade. Two-way wing exactly matches their stated long-term vision.",
    },
  ],
  weeklyScoutReport: "The 2026 NBA Draft class continues to separate itself as one of the deepest in recent memory, with multiple prospects capable of going No. 1 overall and genuine two-way talent sprinkled throughout the first round. The pre-college-season showcase circuit has provided scouts with critical data points — most notably Darryn Peterson's explosive Nike Skills Academy performance, which has him firmly in the conversation to push Tre Johnson from the top spot. Internationally, Noa Essengue's EuroLeague debut looms large in late September as the most anticipated evaluator event of the month, with teams holding top-five picks eager to confirm what the scouting community has been buzzing about for a year. With the college season still weeks away, the big board remains fluid — but the gap between the elite tier (Johnson, Peterson, Essengue) and the rest of the lottery has never been more apparent.",
};