// Auto-generated Draft Stock Tracker data
// Weekly big board and scouting reports for the 2026 NBA Draft

export interface DraftProspect {
  rank: number;
  prevRank: number;
  name: string;
  school: string;
  position: string;
  height: string;
  age: number;
  scoutingGrade: number;
  projection: string;
  bestFit: string[];
  strengths: string[];
  weaknesses: string[];
  comparison: string;
  weeklyNote: string;
  trend: "rising" | "falling" | "stable";
  stats: { ppg: number; rpg: number; apg: number; fgPct: number; threePct: number };
}

export interface TeamNeed {
  team: string;
  record: string;
  lotteryOdds: string;
  primaryNeed: string;
  secondaryNeed: string;
  bestProspectFit: string;
  note: string;
}

export interface DraftData {
  generatedDate: string;
  weekLabel: string;
  classYear: number;
  bigBoard: DraftProspect[];
  risers: { name: string; change: number; reason: string }[];
  fallers: { name: string; change: number; reason: string }[];
  tankWatch: TeamNeed[];
  weeklyScoutReport: string;
}

export const draftData: DraftData = {
  generatedDate: "March 24, 2026",
  weekLabel: "Week of March 22-28, 2026",
  classYear: 2026,
  bigBoard: [
    { rank: 1, prevRank: 1, name: "AJ Dybantsa", school: "Utah", position: "SF", height: "6'9\"", age: 19, scoutingGrade: 98, projection: "No. 1 Pick", bestFit: ["BKN", "MEM", "UTA"], strengths: ["Elite shot creation", "NBA-ready frame", "Versatile scorer"], weaknesses: ["Defensive consistency", "Shot selection"], comparison: "Paul George", weeklyNote: "Dybantsa dominated in Utah's Sweet 16 win with 32 points and 8 rebounds. His pull-up three-point shooting is the best in college basketball. Consensus No. 1 pick.", trend: "stable", stats: { ppg: 22.8, rpg: 6.4, apg: 3.2, fgPct: 47.5, threePct: 38.2 } },
    { rank: 2, prevRank: 2, name: "Cameron Boozer", school: "Duke", position: "PF", height: "6'10\"", age: 19, scoutingGrade: 95, projection: "Top 3 Pick", bestFit: ["BKN", "WAS", "MEM"], strengths: ["Post scoring", "Passing vision", "Basketball IQ"], weaknesses: ["Lateral quickness", "Perimeter defense"], comparison: "Chris Bosh", weeklyNote: "Boozer posted 24 points and 11 rebounds in Duke's tournament win. His footwork in the post is the best in this class. The debate for No. 2 is between him and Flagg's little brother.", trend: "stable", stats: { ppg: 20.1, rpg: 9.8, apg: 3.5, fgPct: 52.3, threePct: 34.1 } },
    { rank: 3, prevRank: 4, name: "Ace Bailey", school: "Rutgers", position: "SF/PF", height: "6'9\"", age: 20, scoutingGrade: 94, projection: "Top 3 Pick", bestFit: ["UTA", "WAS", "CHI"], strengths: ["Two-way versatility", "Length", "Transition scoring"], weaknesses: ["Half-court creation", "Free throw shooting"], comparison: "Scottie Barnes", weeklyNote: "Bailey exploded for 28 points against Alabama in the tournament, showing improved shot-making off the dribble. His stock is surging at the right time.", trend: "rising", stats: { ppg: 18.5, rpg: 7.2, apg: 2.8, fgPct: 48.9, threePct: 35.6 } },
    { rank: 4, prevRank: 3, name: "Dylan Harper", school: "Rutgers", position: "PG/SG", height: "6'6\"", age: 19, scoutingGrade: 93, projection: "Top 5 Pick", bestFit: ["MEM", "CHI", "NOP"], strengths: ["Scoring instinct", "Playmaking", "Size at guard"], weaknesses: ["Defensive effort", "Turnover-prone"], comparison: "James Harden", weeklyNote: "Harper had a quieter week with 18 points as Bailey took over in their tournament game. Still a top-5 lock but Bailey outplayed him head-to-head.", trend: "falling", stats: { ppg: 21.3, rpg: 4.1, apg: 6.8, fgPct: 44.2, threePct: 36.8 } },
    { rank: 5, prevRank: 5, name: "Kasparas Jakucionis", school: "Illinois", position: "PG", height: "6'5\"", age: 20, scoutingGrade: 91, projection: "Top 5 Pick", bestFit: ["WAS", "UTA", "POR"], strengths: ["Court vision", "Change of pace", "Clutch shooting"], weaknesses: ["Strength", "Finishing through contact"], comparison: "Luka Doncic (lite)", weeklyNote: "Jakucionis orchestrated Illinois' Elite 8 run with 22 points and 11 assists. His feel for the game is special. International scouts are raving.", trend: "stable", stats: { ppg: 17.8, rpg: 3.5, apg: 8.2, fgPct: 45.1, threePct: 37.4 } },
    { rank: 6, prevRank: 7, name: "Tre Johnson", school: "Texas", position: "SG", height: "6'5\"", age: 19, scoutingGrade: 90, projection: "Top 7 Pick", bestFit: ["CHI", "NOP", "SAC"], strengths: ["Shot-making", "Mid-range mastery", "Scoring versatility"], weaknesses: ["Playmaking", "Defensive positioning"], comparison: "Devin Booker", weeklyNote: "Johnson scored 30 in Texas' tournament upset over Kansas. His mid-range game is the most polished in the draft. Rising fast.", trend: "rising", stats: { ppg: 19.6, rpg: 3.8, apg: 2.9, fgPct: 46.3, threePct: 39.1 } },
    { rank: 7, prevRank: 6, name: "Jalil Bethea", school: "Miami", position: "SG", height: "6'5\"", age: 19, scoutingGrade: 89, projection: "Top 7 Pick", bestFit: ["MEM", "POR", "SAC"], strengths: ["Three-point shooting", "Off-ball movement", "Catch-and-shoot"], weaknesses: ["Ball handling", "Creating own shot"], comparison: "Klay Thompson", weeklyNote: "Bethea was quiet in Miami's loss — 12 points on 4-of-13 shooting. His tournament performance may cost him a spot or two.", trend: "falling", stats: { ppg: 17.2, rpg: 3.1, apg: 2.4, fgPct: 44.8, threePct: 41.2 } },
    { rank: 8, prevRank: 8, name: "Khaman Maluach", school: "Duke", position: "C", height: "7'2\"", age: 19, scoutingGrade: 88, projection: "Lottery", bestFit: ["NOP", "CHI", "SAC"], strengths: ["Rim protection", "Length", "Lob threat"], weaknesses: ["Perimeter skills", "Free throws"], comparison: "Mitchell Robinson (with upside)", weeklyNote: "Maluach had 14 points, 12 rebounds, and 5 blocks in Duke's win. His defensive impact is undeniable. Teams picking 7-10 are very interested.", trend: "stable", stats: { ppg: 12.4, rpg: 9.8, apg: 1.2, fgPct: 62.1, threePct: 18.5 } },
    { rank: 9, prevRank: 10, name: "Egor Demin", school: "BYU", position: "PG", height: "6'8\"", age: 19, scoutingGrade: 87, projection: "Lottery", bestFit: ["POR", "SAC", "NOP"], strengths: ["Size for position", "Passing", "Vision"], weaknesses: ["Athleticism", "Defensive intensity"], comparison: "Lonzo Ball", weeklyNote: "Demin ran the show in BYU's tournament appearance with 16 points and 9 assists. His size at point guard is tantalizing. Moving up boards.", trend: "rising", stats: { ppg: 14.8, rpg: 5.2, apg: 7.1, fgPct: 43.5, threePct: 33.8 } },
    { rank: 10, prevRank: 9, name: "Nolan Traore", school: "NBA G League Ignite", position: "PG", height: "6'4\"", age: 19, scoutingGrade: 86, projection: "Lottery", bestFit: ["CHI", "WAS", "MEM"], strengths: ["Explosiveness", "Transition", "Defensive upside"], weaknesses: ["Shooting consistency", "Decision making"], comparison: "De'Aaron Fox", weeklyNote: "Traore showcased his speed in the G League showcase with 21 points and 7 assists. His shooting still needs work but the tools are elite.", trend: "stable", stats: { ppg: 16.5, rpg: 3.2, apg: 6.8, fgPct: 42.8, threePct: 30.2 } },
    { rank: 11, prevRank: 11, name: "Collin Murray-Boyles", school: "South Carolina", position: "PF", height: "6'8\"", age: 20, scoutingGrade: 85, projection: "Lottery", bestFit: ["WAS", "POR", "CHI"], strengths: ["Physicality", "Rebounding", "Motor"], weaknesses: ["Three-point range", "Passing"], comparison: "Draymond Green (offensive)", weeklyNote: "Murray-Boyles is the most physical player in this draft. He had 18 and 14 in South Carolina's tournament win. A blue-collar All-Star candidate.", trend: "stable", stats: { ppg: 15.8, rpg: 10.1, apg: 2.1, fgPct: 51.2, threePct: 28.5 } },
    { rank: 12, prevRank: 13, name: "VJ Edgecombe", school: "Baylor", position: "SG", height: "6'4\"", age: 19, scoutingGrade: 84, projection: "Lottery", bestFit: ["SAC", "NOP", "MEM"], strengths: ["Athleticism", "Attacking the rim", "Transition"], weaknesses: ["Shooting range", "Size"], comparison: "Jalen Green", weeklyNote: "Edgecombe had 25 and 6 in Baylor's Sweet 16 appearance. His explosiveness is special. Teams love his two-way upside.", trend: "rising", stats: { ppg: 16.2, rpg: 3.8, apg: 3.1, fgPct: 45.5, threePct: 32.8 } },
    { rank: 13, prevRank: 12, name: "Liam McNeeley", school: "UConn", position: "SF", height: "6'7\"", age: 19, scoutingGrade: 83, projection: "Lottery", bestFit: ["POR", "CHI", "WAS"], strengths: ["Versatility", "IQ", "Shooting"], weaknesses: ["Athleticism", "First step"], comparison: "Tobias Harris (prime)", weeklyNote: "McNeeley was solid but unspectacular in UConn's loss — 16 points and 5 rebounds. His floor is high but his ceiling questions persist.", trend: "falling", stats: { ppg: 14.5, rpg: 5.4, apg: 2.8, fgPct: 46.2, threePct: 37.5 } },
    { rank: 14, prevRank: 14, name: "Jeremiah Fears", school: "Oklahoma", position: "PG", height: "6'3\"", age: 19, scoutingGrade: 82, projection: "Mid-First Round", bestFit: ["SAC", "WAS", "POR"], strengths: ["Scoring burst", "Toughness", "Leadership"], weaknesses: ["Size", "Efficiency"], comparison: "Jamal Murray", weeklyNote: "Fears dropped 24 in Oklahoma's tournament game. His competitiveness is unmatched in this class. A winner.", trend: "stable", stats: { ppg: 17.1, rpg: 2.8, apg: 4.5, fgPct: 42.1, threePct: 34.8 } },
    { rank: 15, prevRank: 15, name: "Asa Newell", school: "Georgia", position: "PF", height: "6'10\"", age: 19, scoutingGrade: 81, projection: "Mid-First Round", bestFit: ["NOP", "MEM", "CHI"], strengths: ["Defensive versatility", "Shot blocking", "Mobility"], weaknesses: ["Offensive polish", "Three-point shot"], comparison: "Jaren Jackson Jr. (lite)", weeklyNote: "Newell had a monster defensive game — 4 blocks and 3 steals in Georgia's upset win. His defensive tools are tantalizing.", trend: "stable", stats: { ppg: 11.8, rpg: 7.5, apg: 1.8, fgPct: 48.2, threePct: 29.4 } },
    { rank: 16, prevRank: 18, name: "Rasheer Fleming", school: "Indiana", position: "PF/C", height: "6'11\"", age: 20, scoutingGrade: 80, projection: "Mid-First Round", bestFit: ["POR", "WAS", "SAC"], strengths: ["Rim running", "Energy", "Rebounding"], weaknesses: ["Perimeter skills", "Free throws"], comparison: "Clint Capela", weeklyNote: "Fleming had a huge week — 20/13 double-double in Indiana's win. His motor is relentless. Rising on team boards.", trend: "rising", stats: { ppg: 13.2, rpg: 9.1, apg: 1.5, fgPct: 58.4, threePct: 22.1 } },
    { rank: 17, prevRank: 16, name: "Tucker DeVries", school: "Iowa State", position: "SF", height: "6'7\"", age: 21, scoutingGrade: 79, projection: "Mid-First Round", bestFit: ["CHI", "MEM", "NOP"], strengths: ["Shooting", "Basketball IQ", "Toughness"], weaknesses: ["Athleticism", "Creation off dribble"], comparison: "Joe Ingles", weeklyNote: "DeVries was efficient with 17 points in Iowa State's win. He doesn't wow you but he makes every team better.", trend: "stable", stats: { ppg: 15.4, rpg: 4.8, apg: 2.5, fgPct: 47.8, threePct: 40.2 } },
    { rank: 18, prevRank: 17, name: "Kon Knueppel", school: "Duke", position: "SG", height: "6'6\"", age: 20, scoutingGrade: 78, projection: "Mid-First Round", bestFit: ["SAC", "POR", "WAS"], strengths: ["Shot-making", "Size", "Off-ball movement"], weaknesses: ["Lateral speed", "On-ball defense"], comparison: "Duncan Robinson (plus)", weeklyNote: "Knueppel had 15 points in Duke's tournament win but deferred to Boozer and Maluach. His shooting will translate immediately.", trend: "stable", stats: { ppg: 14.8, rpg: 3.2, apg: 2.1, fgPct: 44.5, threePct: 42.1 } },
    { rank: 19, prevRank: 19, name: "Hugo Gonzalez", school: "Real Madrid", position: "PG", height: "6'3\"", age: 19, scoutingGrade: 77, projection: "Mid-First Round", bestFit: ["MEM", "NOP", "WAS"], strengths: ["Pick-and-roll mastery", "Floater game", "Court management"], weaknesses: ["Athleticism", "Finishing at rim"], comparison: "Jose Alvarado (bigger)", weeklyNote: "Gonzalez had 14 assists in a EuroLeague game this week. His feel for the pick-and-roll is ahead of any college guard. Stash-and-develop candidate.", trend: "stable", stats: { ppg: 11.2, rpg: 2.8, apg: 7.5, fgPct: 43.8, threePct: 35.2 } },
    { rank: 20, prevRank: 20, name: "Jase Richardson", school: "Michigan State", position: "PG", height: "6'3\"", age: 19, scoutingGrade: 76, projection: "Mid-First Round", bestFit: ["CHI", "SAC", "POR"], strengths: ["Leadership", "Poise", "Two-way play"], weaknesses: ["Ceiling questions", "Shooting off dribble"], comparison: "Marcus Smart", weeklyNote: "Richardson led Michigan State to the Sweet 16 with gritty play — 15 points, 6 assists, 4 steals. A Tom Izzo product through and through.", trend: "stable", stats: { ppg: 13.5, rpg: 3.8, apg: 5.2, fgPct: 43.2, threePct: 33.5 } },
    { rank: 21, prevRank: 22, name: "Braylon Mullins", school: "Clemson", position: "SG", height: "6'4\"", age: 20, scoutingGrade: 75, projection: "Late First Round", bestFit: ["POR", "NOP", "WAS"], strengths: ["Three-point shooting", "Quick release", "Movement shooting"], weaknesses: ["Creation", "Defense"], comparison: "Buddy Hield", weeklyNote: "Mullins hit 6 threes in Clemson's tournament game. His shooting range is limitless.", trend: "rising", stats: { ppg: 15.8, rpg: 2.5, apg: 1.8, fgPct: 44.2, threePct: 42.8 } },
    { rank: 22, prevRank: 21, name: "Labaron Philon", school: "Alabama", position: "PG", height: "6'3\"", age: 19, scoutingGrade: 74, projection: "Late First Round", bestFit: ["MEM", "CHI", "WAS"], strengths: ["Speed", "Penetration", "Passing"], weaknesses: ["Shooting", "Size"], comparison: "Immanuel Quickley", weeklyNote: "Philon had 13 points and 8 assists in Alabama's loss. His speed is elite but he needs to develop a reliable jumper.", trend: "stable", stats: { ppg: 12.8, rpg: 2.4, apg: 5.8, fgPct: 41.5, threePct: 30.8 } },
    { rank: 23, prevRank: 23, name: "Trentyn Flowers", school: "Overtime Elite", position: "SF", height: "6'8\"", age: 19, scoutingGrade: 73, projection: "Late First Round", bestFit: ["SAC", "NOP", "POR"], strengths: ["Wingspan", "Versatility", "Defensive potential"], weaknesses: ["Strength", "Consistency"], comparison: "Herb Jones", weeklyNote: "Flowers impressed at the OTE showcase with his defensive versatility. His length disrupts everything.", trend: "stable", stats: { ppg: 14.2, rpg: 5.5, apg: 2.2, fgPct: 45.8, threePct: 31.5 } },
    { rank: 24, prevRank: 25, name: "Nique Clifford", school: "Colorado State", position: "SF", height: "6'6\"", age: 22, scoutingGrade: 72, projection: "Late First Round", bestFit: ["CHI", "MEM", "WAS"], strengths: ["Motor", "Rebounding for position", "Mid-range"], weaknesses: ["Age", "Three-point range"], comparison: "Josh Hart", weeklyNote: "Clifford's tournament run has been incredible — 22/10/5 line against Marquette. He's the most NBA-ready player outside the lottery.", trend: "rising", stats: { ppg: 17.5, rpg: 8.2, apg: 3.5, fgPct: 48.5, threePct: 33.2 } },
    { rank: 25, prevRank: 24, name: "Dink Pate", school: "Arizona", position: "SF", height: "6'8\"", age: 19, scoutingGrade: 71, projection: "Late First Round", bestFit: ["POR", "NOP", "SAC"], strengths: ["Athleticism", "Cutting", "Defensive potential"], weaknesses: ["Shooting", "Ball handling"], comparison: "Aaron Gordon (lite)", weeklyNote: "Pate had 14 and 7 in Arizona's tournament exit. His raw tools are exciting but the skill development is a project.", trend: "falling", stats: { ppg: 12.1, rpg: 5.8, apg: 1.5, fgPct: 46.5, threePct: 28.8 } },
    { rank: 26, prevRank: 26, name: "BJ Edwards", school: "Tennessee", position: "PG", height: "6'1\"", age: 21, scoutingGrade: 70, projection: "Late First Round", bestFit: ["WAS", "MEM", "CHI"], strengths: ["Toughness", "Leadership", "Defense"], weaknesses: ["Size", "Shooting volume"], comparison: "Tyus Jones", weeklyNote: "Edwards ran Tennessee's offense efficiently in the tournament — 11 points and 8 assists in a close loss.", trend: "stable", stats: { ppg: 11.5, rpg: 2.8, apg: 6.2, fgPct: 44.8, threePct: 36.5 } },
    { rank: 27, prevRank: 28, name: "Miles Byrd", school: "San Diego State", position: "SG/SF", height: "6'6\"", age: 20, scoutingGrade: 69, projection: "Late First Round", bestFit: ["SAC", "POR", "NOP"], strengths: ["3-and-D profile", "Defensive instincts", "Length"], weaknesses: ["Creation", "Consistency"], comparison: "Matisse Thybulle (with shooting)", weeklyNote: "Byrd had 4 steals and 3 threes in SDSU's upset win. His defensive versatility is intriguing for playoff teams.", trend: "rising", stats: { ppg: 13.2, rpg: 4.5, apg: 1.8, fgPct: 43.5, threePct: 37.8 } },
    { rank: 28, prevRank: 27, name: "Jaylen Wells", school: "Washington State", position: "SG", height: "6'5\"", age: 21, scoutingGrade: 68, projection: "Late First Round", bestFit: ["CHI", "WAS", "MEM"], strengths: ["Scoring punch", "Pull-up shooting", "Confidence"], weaknesses: ["Defense", "Decision making"], comparison: "Jordan Clarkson", weeklyNote: "Wells scored 21 in Washington State's tournament loss. His scoring ability off the bench is immediate NBA value.", trend: "stable", stats: { ppg: 16.8, rpg: 3.2, apg: 2.5, fgPct: 43.8, threePct: 35.5 } },
    { rank: 29, prevRank: 29, name: "Carter Bryant", school: "Arizona", position: "PF", height: "6'9\"", age: 19, scoutingGrade: 67, projection: "Late First Round", bestFit: ["POR", "NOP", "MEM"], strengths: ["Shooting at size", "Floor spacing", "Basketball IQ"], weaknesses: ["Strength", "Rim protection"], comparison: "Kelly Olynyk", weeklyNote: "Bryant had a quiet 10 points in Arizona's exit but his shooting translates. A stretch-four for the modern NBA.", trend: "stable", stats: { ppg: 11.8, rpg: 5.2, apg: 1.8, fgPct: 45.2, threePct: 38.5 } },
    { rank: 30, prevRank: 30, name: "Eric Dixon", school: "Villanova", position: "PF/C", height: "6'8\"", age: 23, scoutingGrade: 66, projection: "Late First Round", bestFit: ["CHI", "WAS", "SAC"], strengths: ["Post scoring", "Passing from post", "Rebounding"], weaknesses: ["Age", "Athleticism", "Foot speed"], comparison: "Al Jefferson (modern)", weeklyNote: "Dixon had 22 and 10 in Villanova's season-ending loss. The most productive player in college basketball — the question is whether it translates.", trend: "stable", stats: { ppg: 20.2, rpg: 8.5, apg: 2.8, fgPct: 52.1, threePct: 34.8 } },
  ],
  risers: [
    { name: "Ace Bailey", change: 1, reason: "Exploded for 28 points in tournament — showed improved shot-making that silenced doubters" },
    { name: "Tre Johnson", change: 1, reason: "30-point tournament performance showed mid-range mastery teams crave" },
    { name: "Nique Clifford", change: 1, reason: "22/10/5 tournament line proved he's the most NBA-ready wing outside the lottery" },
  ],
  fallers: [
    { name: "Dylan Harper", change: -1, reason: "Outplayed by teammate Bailey in tournament — questions about being a true No. 1 option" },
    { name: "Jalil Bethea", change: -1, reason: "4-for-13 shooting in tournament loss raised shot-creation concerns" },
    { name: "Liam McNeeley", change: -1, reason: "Solid but unspectacular 16 points in UConn loss — ceiling questions linger" },
  ],
  tankWatch: [
    { team: "BKN", record: "17-52", lotteryOdds: "14.0%", primaryNeed: "Franchise Wing", secondaryNeed: "Point Guard", bestProspectFit: "AJ Dybantsa", note: "Brooklyn owns the best lottery odds and needs a franchise cornerstone. Dybantsa is the dream scenario." },
    { team: "UTA", record: "20-49", lotteryOdds: "12.5%", primaryNeed: "Point Guard", secondaryNeed: "Wing Scorer", bestProspectFit: "Kasparas Jakucionis", note: "Jazz need a floor general to pair with Markkanen (if he stays). Jakucionis' size and vision are perfect." },
    { team: "MEM", record: "23-45", lotteryOdds: "10.5%", primaryNeed: "Wing Scorer", secondaryNeed: "Rim Protector", bestProspectFit: "Tre Johnson", note: "Memphis needs scoring help next to Ja. Johnson's shot-making fills a major void." },
    { team: "WAS", record: "15-54", lotteryOdds: "14.0%", primaryNeed: "Everything", secondaryNeed: "Star Wing", bestProspectFit: "Cameron Boozer", note: "Washington is in full rebuild mode. Any top-3 pick is a win. Boozer's two-way game is ideal." },
    { team: "CHI", record: "28-41", lotteryOdds: "4.5%", primaryNeed: "Point Guard", secondaryNeed: "Wing Depth", bestProspectFit: "Dylan Harper", note: "Bulls need a lead guard badly. Harper's scoring and playmaking would transform this roster." },
    { team: "NOP", record: "22-47", lotteryOdds: "10.5%", primaryNeed: "Wing", secondaryNeed: "Center", bestProspectFit: "Ace Bailey", note: "Pelicans need to rebuild around Zion. A versatile wing like Bailey would complement perfectly." },
    { team: "SAC", record: "27-42", lotteryOdds: "6.0%", primaryNeed: "Wing Defender", secondaryNeed: "Center", bestProspectFit: "Collin Murray-Boyles", note: "Sacramento's defense has been atrocious. A physical, defensive-first forward is the priority." },
    { team: "POR", record: "34-36", lotteryOdds: "1.5%", primaryNeed: "Star Wing", secondaryNeed: "Point Guard", bestProspectFit: "Egor Demin", note: "Blazers may sneak into the lottery if they fade. A point guard with Demin's size would be transformative." },
  ],
  weeklyScoutReport: "March Madness has reshuffled the draft board significantly. AJ Dybantsa remains the consensus No. 1 after a dominant Sweet 16 performance, but the real movement is in the 3-7 range. Ace Bailey's 28-point explosion against Alabama vaulted him past teammate Dylan Harper, while Tre Johnson's 30-point masterpiece for Texas has him climbing into the top 6. The tournament is doing what it always does — separating the stars from the pretenders. Cameron Boozer's steady brilliance at Duke has him locked at No. 2, and Kasparas Jakucionis' court vision continues to dazzle scouts. The biggest question heading into the Elite 8: can any of the mid-round risers sustain their tournament momentum, or will we see the familiar regression to pre-March rankings?",
};
