// Lineup Intelligence — Weekly lineup analysis
// Last updated: July 20, 2026
// Live at: https://hoopsintel.net/lineups

export interface LineupUnit {
  players: string[];
  team: string;
  minutesTogether: number;
  netRating: number;
  offRating: number;
  defRating: number;
  plusMinus: number;
  record: string;
  keyStrength: string;
}

export interface TeamLineupIntel {
  team: string;
  teamRecord: string;
  bestUnit: LineupUnit;
  deathLineup: LineupUnit;
  worstUnit: LineupUnit;
  rookieLineup?: LineupUnit;
  newLookLineup?: LineupUnit;
  narrative: string;
}

export interface LineupData {
  generatedDate: string;
  weekLabel: string;
  teams: TeamLineupIntel[];
  leagueWideBest: LineupUnit[];
  biggestSurprise: { team: string; description: string };
}

export const lineupData: LineupData = {
  generatedDate: "July 20, 2026",
  weekLabel: "Week of July 20–26, 2026",

  leagueWideBest: [
    {
      players: ["Victor Wembanyama", "De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Jeremy Sochan"],
      team: "SAS",
      minutesTogether: 412,
      netRating: 22.4,
      offRating: 122.8,
      defRating: 100.4,
      plusMinus: 187,
      record: "Equivalent to 67-15 pace",
      keyStrength: "Wembanyama's gravity as a screener unlocks Fox in transition while the unit's length makes it nearly impossible to score in the half-court",
    },
    {
      players: ["Jalen Brunson", "OG Anunoby", "Mikal Bridges", "Karl-Anthony Towns", "Josh Hart"],
      team: "NYK",
      minutesTogether: 388,
      netRating: 19.7,
      offRating: 120.3,
      defRating: 100.6,
      plusMinus: 154,
      record: "Equivalent to 64-18 pace",
      keyStrength: "Championship-tested five-out spacing around Brunson pick-and-roll with elite perimeter length on every defensive assignment",
    },
    {
      players: ["Shai Gilgeous-Alexander", "Jalen Williams", "Luguentz Dort", "Chet Holmgren", "Isaiah Joe"],
      team: "OKC",
      minutesTogether: 376,
      netRating: 18.9,
      offRating: 119.1,
      defRating: 100.2,
      plusMinus: 141,
      record: "Equivalent to 63-19 pace",
      keyStrength: "SGA-Williams two-man game creates unresolvable defensive rotations while Holmgren anchors one of the league's most disciplined drop coverages",
    },
    {
      players: ["Tyrese Haliburton", "Andrew Nembhard", "Bennedict Mathurin", "Pascal Siakam", "Myles Turner"],
      team: "IND",
      minutesTogether: 344,
      netRating: 16.2,
      offRating: 118.4,
      defRating: 102.2,
      plusMinus: 112,
      record: "Equivalent to 60-22 pace",
      keyStrength: "Haliburton's pace manipulation combined with Turner's floor-spacing from the five generates the highest assist-to-turnover differential of any starting unit in the East",
    },
    {
      players: ["Anthony Edwards", "Mike Conley", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
      team: "MIN",
      minutesTogether: 318,
      netRating: 14.8,
      offRating: 116.2,
      defRating: 101.4,
      plusMinus: 94,
      record: "Equivalent to 58-24 pace",
      keyStrength: "Gobert's rim protection absorbs help rotations that would otherwise leave Edwards' pull-up attempts open, creating a legitimate two-way starting five",
    },
  ],

  biggestSurprise: {
    team: "IND",
    description:
      "Indiana's Haliburton–Nembhard backcourt pairing posted a +16.2 net rating in 344 minutes together — a number that places them inside the top four starting units in the league and well above any projection entering the season. The surprise isn't Haliburton's ceiling; it's how thoroughly Nembhard's off-ball movement and secondary creation solved the Pacers' long-standing second-option problem without a single major roster addition.",
  },

  teams: [
    {
      team: "OKC",
      teamRecord: "64-18",
      narrative:
        "Oklahoma City's best unit is the most defensively suffocating five-man group in the Western Conference, built on the premise that SGA and Jalen Williams can each initiate offense while Holmgren protects every mistake behind them. The concern heading into next season is the 38-minute stretch unit that features Tre Mann and two second-round wings — a grouping that surrenders points at a rate that erases the goodwill the starters generate. The death lineup is genuinely elite, but its ceiling depends on whether OKC lands the secondary playmaker their front office is actively pursuing. If that addition arrives, this team's closing net rating could jump four points in the first month of next season.",
      bestUnit: {
        players: ["Shai Gilgeous-Alexander", "Jalen Williams", "Luguentz Dort", "Chet Holmgren", "Isaiah Joe"],
        team: "OKC",
        minutesTogether: 376,
        netRating: 18.9,
        offRating: 119.1,
        defRating: 100.2,
        plusMinus: 141,
        record: "Equivalent to 63-19 pace",
        keyStrength: "SGA–Williams dual-initiator system with Holmgren protecting every rim breakdown in drop coverage",
      },
      deathLineup: {
        players: ["Shai Gilgeous-Alexander", "Jalen Williams", "Luguentz Dort", "Jaden McDaniels", "Chet Holmgren"],
        team: "OKC",
        minutesTogether: 68,
        netRating: 16.1,
        offRating: 116.8,
        defRating: 100.7,
        plusMinus: 44,
        record: "18-7 in games when closing",
        keyStrength: "Five-position defensive versatility that allows switching on every screen action without surrendering size at the rim",
      },
      worstUnit: {
        players: ["Tre Mann", "Aaron Wiggins", "Ousmane Dieng", "Jaylin Williams", "Kenrich Williams"],
        team: "OKC",
        minutesTogether: 44,
        netRating: -11.3,
        offRating: 104.2,
        defRating: 115.5,
        plusMinus: -20,
        record: "Equivalent to 28-54 pace",
        keyStrength: "Youth and energy — the only genuine attribute this grouping provides against established rotations",
      },
      rookieLineup: {
        players: ["Shai Gilgeous-Alexander", "Jalen Williams", "Ousmane Dieng", "Chet Holmgren", "Isaiah Joe"],
        team: "OKC",
        minutesTogether: 82,
        netRating: 7.4,
        offRating: 113.6,
        defRating: 106.2,
        plusMinus: 24,
        record: "Equivalent to 48-34 pace",
        keyStrength: "Dieng's length and handle allow OKC to test his offensive upside in semi-meaningful minutes while surrounding him with two All-Star creators",
      },
    },
    {
      team: "SAS",
      teamRecord: "62-20",
      narrative:
        "San Antonio's best lineup is the most talented five-man group assembled in Spurs history, and the data reflects it — no unit in franchise memory has posted a net rating above 20 for more than 400 minutes. The Fox situation hangs over all lineup projections; the death lineup currently built around him and Wembanyama is the most functionally complete closing group in the West, and losing him would require an entirely new closing construction that does not yet exist on the roster. Stephon Castle's extension progression matters because his presence in the second unit keeps the bench groupings from cratering — his +7.1 net rating in non-Fox minutes is the number San Antonio's front office watches more carefully than any other. The offseason priority is not just retaining Fox but ensuring the gap between the best unit and the third unit doesn't widen to the point where playoff rotations become predictable.",
      bestUnit: {
        players: ["Victor Wembanyama", "De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Jeremy Sochan"],
        team: "SAS",
        minutesTogether: 412,
        netRating: 22.4,
        offRating: 122.8,
        defRating: 100.4,
        plusMinus: 187,
        record: "Equivalent to 67-15 pace",
        keyStrength: "Wembanyama as a screener unlocks Fox in transition while the unit's wingspan makes half-court scoring nearly impossible for opponents",
      },
      deathLineup: {
        players: ["Victor Wembanyama", "De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Jeremy Sochan"],
        team: "SAS",
        minutesTogether: 74,
        netRating: 20.8,
        offRating: 121.4,
        defRating: 100.6,
        plusMinus: 62,
        record: "22-5 in games when closing",
        keyStrength: "Wembanyama's shot-blocking presence eliminates the kick-out-and-drive counters that collapse most closing lineups late in shot clocks",
      },
      worstUnit: {
        players: ["Blake Wesley", "Malaki Branham", "Julian Champagnie", "Sidy Cissoko", "Charles Bassey"],
        team: "SAS",
        minutesTogether: 38,
        netRating: -13.7,
        offRating: 102.8,
        defRating: 116.5,
        plusMinus: -21,
        record: "Equivalent to 24-58 pace",
        keyStrength: "Development minutes — this unit exists to log competitive reps for players still two years from rotation relevance",
      },
      rookieLineup: {
        players: ["De'Aaron Fox", "Stephon Castle", "Devin Vassell", "Jeremy Sochan", "Victor Wembanyama"],
        team: "SAS",
        minutesTogether: 298,
        netRating: 18.1,
        offRating: 119.6,
        defRating: 101.5,
        plusMinus: 108,
        record: "Equivalent to 62-20 pace",
        keyStrength: "Castle's defensive assignment flexibility — switching onto guards or forwards without creating size mismatches — is what makes this lineup's defensive identity sustainable",
      },
    },
    {
      team: "NYK",
      teamRecord: "53-29",
      narrative:
        "The defending champions run the most chemistry-proven closing lineup in the Eastern Conference, a group that went 19-4 in fourth-quarter situations decided by five points or fewer. Brunson's ability to operate the pick-and-roll against any drop scheme while Towns threatens from the arc is the offensive skeleton that every New York lineup study returns to. The concern is depth — New York's worst unit was the most frequently punished grouping in the East during stretch-run games where Brunson rested, and the Hartenstein knee evaluation means the backup center situation entering next season remains genuinely unresolved. If the Knicks retain this core intact, their best and death lineups project as legitimate championship-caliber units for at least two more seasons.",
      bestUnit: {
        players: ["Jalen Brunson", "OG Anunoby", "Mikal Bridges", "Karl-Anthony Towns", "Josh Hart"],
        team: "NYK",
        minutesTogether: 388,
        netRating: 19.7,
        offRating: 120.3,
        defRating: 100.6,
        plusMinus: 154,
        record: "Equivalent to 64-18 pace",
        keyStrength: "Championship-tested five-out spacing around Brunson pick-and-roll with elite perimeter length on every defensive assignment",
      },
      deathLineup: {
        players: ["Jalen Brunson", "OG Anunoby", "Mikal Bridges", "Karl-Anthony Towns", "Josh Hart"],
        team: "NYK",
        minutesTogether: 86,
        netRating: 17.9,
        offRating: 118.6,
        defRating: 100.7,
        plusMinus: 62,
        record: "19-4 in games when closing",
        keyStrength: "Brunson's late-clock creation paired with Anunoby's ability to guard the opposing best player without a defensive substitution",
      },
      worstUnit: {
        players: ["Precious Achiuwa", "Landry Shamet", "Miles McBride", "Keita Bates-Diop", "Isaiah Hartenstein"],
        team: "NYK",
        minutesTogether: 52,
        netRating: -10.8,
        offRating: 106.4,
        defRating: 117.2,
        plusMinus: -23,
        record: "Equivalent to 30-52 pace",
        keyStrength: "Hartenstein's rebounding keeps the unit from total collapse — without his presence on the glass this grouping's deficiency becomes generational",
      },
    },
    {
      team: "BOS",
      teamRecord: "54-28",
      narrative:
        "Boston's best lineup remains one of the most analytically complete units in the league — five players who can each initiate a switch coverage and each punish a mismatch on offense. The death lineup concern is real, however: the Celtics went just 13-11 in fourth-quarter close games, a closing rate that understates how often their death lineup got outscored in the final two minutes specifically. Jaylen Brown's usage in late-shot-clock situations and Tatum's tendency to operate in isolation rather than triggering the motion system are the two tactical tensions that live coaching adjustments couldn't fully resolve. The best news in Boston's lineup data is the Payton Pritchard bench unit, which posted the highest net rating of any non-starter grouping in the East and gave the Celtics one of the only reliable second-unit advantages in the conference.",
      bestUnit: {
        players: ["Jayson Tatum", "Jaylen Brown", "Jrue Holiday", "Al Horford", "Payton Pritchard"],
        team: "BOS",
        minutesTogether: 356,
        netRating: 16.8,
        offRating: 118.2,
        defRating: 101.4,
        plusMinus: 120,
        record: "Equivalent to 60-22 pace",
        keyStrength: "Horford's pick-and-pop combined with Holiday's off-ball cutting creates two-action offense that collapses any single-coverage defensive scheme",
      },
      deathLineup: {
        players: ["Jayson Tatum", "Jaylen Brown", "Jrue Holiday", "Al Horford", "Derrick White"],
        team: "BOS",
        minutesTogether: 72,
        netRating: 11.4,
        offRating: 114.8,
        defRating: 103.4,
        plusMinus: 33,
        record: "13-11 in games when closing",
        keyStrength: "Defensive switching versatility across all five positions — the Celtics can go small or stay conventional without a substitution",
      },
      worstUnit: {
        players: ["Sam Hauser", "Jordan Walsh", "Anton Watson", "Luke Kornet", "Svi Mykhailiuk"],
        team: "BOS",
        minutesTogether: 41,
        netRating: -12.1,
        offRating: 104.6,
        defRating: 116.7,
        plusMinus: -20,
        record: "Equivalent to 27-55 pace",
        keyStrength: "Three-point volume — this group launches shots at a high rate and occasionally runs a heater that keeps the deficit manageable",
      },
      newLookLineup: {
        players: ["Jayson Tatum", "Payton Pritchard", "Derrick White", "Jaylen Brown", "Kristaps Porzingis"],
        team: "BOS",
        minutesTogether: 94,
        netRating: 13.2,
        offRating: 116.4,
        defRating: 103.2,
        plusMinus: 50,
        record: "Equivalent to 55-27 pace",
        keyStrength: "Porzingis returning to health unlocked a twin-tower spacing look that opposing defenses had not prepared for mid-rotation",
      },
    },
    {
      team: "MIN",
      teamRecord: "52-30",
      narrative:
        "Minnesota's lineup story this season was almost entirely about Anthony Edwards — every unit he was in posted a positive net rating, and every unit he wasn't in trended negative within 20 minutes of footage. The Gobert-Randle frontcourt pairing proved more functional than critics projected, primarily because Randle's mid-range pull-up absorbed the attention that would otherwise suffocate Gobert's roll lanes. The death lineup is the team's most coherent tactical statement, a five-man group that leans into switchability more than size. The worst unit is a cautionary tale about over-deploying Naz Reid in lineups without a true pick-and-roll initiator — he became a black hole in every stint that asked him to facilitate from the elbows.",
      bestUnit: {
        players: ["Anthony Edwards", "Mike Conley", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
        team: "MIN",
        minutesTogether: 318,
        netRating: 14.8,
        offRating: 116.2,
        defRating: 101.4,
        plusMinus: 94,
        record: "Equivalent to 58-24 pace",
        keyStrength: "Gobert rim protection absorbs help rotations that free Edwards pull-up attempts and Randle mid-range opportunities simultaneously",
      },
      deathLineup: {
        players: ["Anthony Edwards", "Jaden McDaniels", "Julius Randle", "Rudy Gobert", "Mike Conley"],
        team: "MIN",
        minutesTogether: 61,
        netRating: 12.6,
        offRating: 114.4,
        defRating: 101.8,
        plusMinus: 31,
        record: "14-9 in games when closing",
        keyStrength: "Conley's late-clock poise keeps Minnesota's offense functional without burning Edwards on every possession, preserving his burst for the decisive drive",
      },
      worstUnit: {
        players: ["Naz Reid", "Rob Dillingham", "Nickeil Alexander-Walker", "Daishen Nix", "Luka Garza"],
        team: "MIN",
        minutesTogether: 36,
        netRating: -14.2,
        offRating: 102.8,
        defRating: 117.0,
        plusMinus: -21,
        record: "Equivalent to 23-59 pace",
        keyStrength: "Reid's offensive rebounding provides a second-chance floor that prevents the unit from being completely scored off the floor in short stints",
      },
      rookieLineup: {
        players: ["Anthony Edwards", "Rob Dillingham", "Jaden McDaniels", "Julius Randle", "Rudy Gobert"],
        team: "MIN",
        minutesTogether: 78,
        netRating: 6.8,
        offRating: 112.4,
        defRating: 105.6,
        plusMinus: 21,
        record: "Equivalent to 47-35 pace",
        keyStrength: "Dillingham's speed in transition gives Edwards a legitimate secondary threat on the break — the one dimension the starting unit lacked entering the season",
      },
    },
    {
      team: "IND",
      teamRecord: "51-31",
      narrative:
        "Indiana's lineup data contains the most underreported efficiency story of the 2025-26 season — the Haliburton–Nembhard backcourt pairing functioned as the best two-guard combination in the East by net rating, a finding that almost no national analysis absorbed before the playoffs arrived. Pascal Siakam's integration into the offensive system as a secondary creator rather than a primary option was the tactical adjustment that unlocked the unit's ceiling; his assist numbers in lineup stints with Haliburton reached 8.4 per 100 possessions, the highest of his career in that role. The death lineup concern is that Myles Turner's foul trouble in elimination games forced Indiana to close with a smaller unit that could not protect the rim with the same authority. Solving the backup center situation so Turner's fouling doesn't collapse the closing rotation is the front office's most urgent structural problem.",
      bestUnit: {
        players: ["Tyrese Haliburton", "Andrew Nembhard", "Bennedict Mathurin", "Pascal Siakam", "Myles Turner"],
        team: "IND",
        minutesTogether: 344,
        netRating: 16.2,
        offRating: 118.4,
        defRating: 102.2,
        plusMinus: 112,
        record: "Equivalent to 60-22 pace",
        keyStrength: "Haliburton's pace manipulation with Turner's floor-spacing from the five generates the highest assist-to-turnover rate of any starting unit in the East",
      },
      deathLineup: {
        players: ["Tyrese Haliburton", "Andrew Nembhard", "Bennedict Mathurin", "Pascal Siakam", "Myles Turner"],
        team: "IND",
        minutesTogether: 58,
        netRating: 13.4,
        offRating: 115.8,
        defRating: 102.4,
        plusMinus: 31,
        record: "15-8 in games when closing",
        keyStrength: "Turner's threat to step out and shoot threes in the closing lineup forces opposing bigs out of the paint, creating driving lanes for Haliburton in the final two minutes",
      },
      worstUnit: {
        players: ["T.J. McConnell", "Ben Sheppard", "Jarace Walker", "Isaiah Jackson", "James Johnson"],
        team: "IND",
        minutesTogether: 42,
        netRating: -10.4,
        offRating: 107.2,
        defRating: 117.6,
        plusMinus: -17,
        record: "Equivalent to 31-51 pace",
        keyStrength: "McConnell's pace keeps the unit from going completely stagnant — he forces enough action to make the possession count feel competitive even when the outcome isn't",
      },
    },
    {
      team: "DEN",
      teamRecord: "50-32",
      narrative:
        "Denver's lineup architecture remains the most Nikola Jokic-dependent structure in professional basketball — which is a feature, not a bug, until you examine what happens in the 11 minutes per game Jokic doesn't play. The best unit's net rating of +17.1 is entirely consistent with Jokic's historical peak groupings, and the offensive rating of 120.6 is the highest any Nuggets starting lineup has posted since the 2023 championship run. The death lineup is where Denver's identity crystallizes: Jokic at the five, Murray initiating, and three switchable wings who can credibly guard one through four. The worst unit exposed Aaron Gordon's limitations as a primary option in spread-pick-and-roll coverages — a defensive scheme opposing coaches deployed specifically to isolate Denver's non-Jokic creation. The Michael Porter Jr. health situation remains the variable that separates Denver's championship ceiling from a second-round ceiling.",
      bestUnit: {
        players: ["Nikola Jokic", "Jamal Murray", "Michael Porter Jr.", "Aaron Gordon", "Kentavious Caldwell-Pope"],
        team: "DEN",
        minutesTogether: 362,
        netRating: 17.1,
        offRating: 120.6,
        defRating: 103.5,
        plusMinus: 124,
        record: "Equivalent to 61-21 pace",
        keyStrength: "Jokic as a point-center creates four-on-three advantages before the ball is even passed; every supporting player's efficiency numbers are structurally inflated by his presence",
      },
      deathLineup: {
        players: ["Nikola Jokic", "Jamal Murray", "Michael Porter Jr.", "Aaron Gordon", "Peyton Watson"],
        team: "DEN",
        minutesTogether: 64,
        netRating: 14.2,
        offRating: 117.4,
        defRating: 103.2,
        plusMinus: 36,
        record: "16-10 in games when closing",
        keyStrength: "Watson's defensive length on the wing allows Gordon to stay connected to Jokic's roll coverages rather than chasing guards on the perimeter",
      },
      worstUnit: {
        players: ["Reggie Jackson", "Christian Braun", "Julian Strawther", "Zeke Nnaji", "DeAndre Jordan"],
        team: "DEN",
        minutesTogether: 39,
        netRating: -13.6,
        offRating: 103.4,
        defRating: 117.0,
        plusMinus: -21,
        record: "Equivalent to 25-57 pace",
        keyStrength: "Braun's motor provides a competitive floor — he turns every possession into a contested effort regardless of the quality of creation around him",
      },
    },
    {
      team: "MIA",
      teamRecord: "48-34",
      narrative:
        "Miami's lineup data tells two separate stories depending on which version of Bam Adebayo showed up — in games where Adebayo posted an assist percentage above 22, the starting lineup went +14.8 net rating; in games where he was used primarily as a finisher, it dropped to +4.2. The Heat's death lineup is built around this duality, featuring Tyler Herro as the primary decision-maker so Adebayo can operate as a mover rather than a creator. The surprise in Miami's data is the Jimmy Butler minutes — his closing unit net rating was the highest per-minute defensive figure on the roster, a reminder that whatever his regular-season availability issues were, his playoff defensive posture remains elite. The worst unit reflects Miami's perennial organizational tension: the G League pipeline players who fill the back of the rotation are developmental projects who are not yet ready to sustain competitive possessions against established NBA wings.",
      bestUnit: {
        players: ["Bam Adebayo", "Tyler Herro", "Jimmy Butler", "Caleb Martin", "Terry Rozier"],
        team: "MIA",
        minutesTogether: 298,
        netRating: 13.6,
        offRating: 115.8,
        defRating: 102.2,
        plusMinus: 81,
        record: "Equivalent to 56-26 pace",
        keyStrength: "Adebayo's passing from the elbows combined with Butler's off-ball cuts creates two-man actions that demand help from both sides of the paint simultaneously",
      },
      deathLineup: {
        players: ["Bam Adebayo", "Jimmy Butler", "Tyler Herro", "Caleb Martin", "Terry Rozier"],
        team: "MIA",
        minutesTogether: 54,
        netRating: 11.8,
        offRating: 113.6,
        defRating: 101.8,
        plusMinus: 25,
        record: "14-10 in games when closing",
        keyStrength: "Butler's isolation scoring in the final two minutes gives Miami a reliable entropy-reduction option when the offense stalls in the shot clock",
      },
      worstUnit: {
        players: ["Josh Richardson", "Nikola Jovic", "Dru Smith", "Orlando Robinson", "Jamal Cain"],
        team: "MIA",
        minutesTogether: 34,
        netRating: -11.9,
        offRating: 105.2,
        defRating: 117.1,
        plusMinus: -16,
        record: "Equivalent to 28-54 pace",
        keyStrength: "Jovic's playmaking IQ is the only rotation-level trait in this grouping — he keeps the offense from becoming entirely static through movement and occasional high-difficulty passing",
      },
      newLookLineup: {
        players: ["Jimmy Butler", "Tyler Herro", "Terry Rozier", "Bam Adebayo", "Kevin Love"],
        team: "MIA",
        minutesTogether: 76,
        netRating: 9.4,
        offRating: 112.8,
        defRating: 103.4,
        plusMinus: 29,
        record: "Equivalent to 50-32 pace",
        keyStrength: "Love's three-point volume off the bench unlocked a five-out alignment that Miami had not previously deployed with a true center, stretching defenses in ways that benefited Adebayo's roll numbers",
      },
    },
    {
      team: "PHX",
      teamRecord: "47-35",
      narrative:
        "Phoenix's lineup situation is the most volatile in the Western Conference — three different five-man groupings posted positive net ratings for 50 or more minutes, and three others posted negative ratings above minus-nine. The Kevin Durant–Devin Booker two-man game remains one of the most effective half-court offensive pairings in the league, but the supporting cast's defensive limitations mean the best unit's offensive excellence is consistently undermined by defensive breakdown events. The death lineup is where Phoenix's roster construction philosophy becomes most visible: it leans entirely on Durant and Booker to make every late-game decision, which works until either player is off the floor or the opponent adjusts to zone principles. The worst unit is the most alarming data point in Phoenix's front office — the backup group that closes out blowout losses has a defensive rating that would rank last in the league across a full season.",
      bestUnit: {
        players: ["Kevin Durant", "Devin Booker", "Bradley Beal", "Royce O'Neale", "Jusuf Nurkic"],
        team: "PHX",
        minutesTogether: 312,
        netRating: 11.4,
        offRating: 117.6,
        defRating: 106.2,
        plusMinus: 71,
        record: "Equivalent to 53-29 pace",
        keyStrength: "Durant–Booker two-man game in the half-court produces the highest combined points-per-shot-attempt from any non-Jokic frontcourt pair in the Western Conference",
      },
      deathLineup: {
        players: ["Kevin Durant", "Devin Booker", "Bradley Beal", "Royce O'Neale", "Jusuf Nurkic"],
        team: "PHX",
        minutesTogether: 58,
        netRating: 9.2,
        offRating: 115.4,
        defRating: 106.2,
        plusMinus: 21,
        record: "13-12 in games when closing",
        keyStrength: "Durant's mid-range creation in the final possession of the shot clock is the single most reliable isolation scoring action in the Western Conference outside of SGA",
      },
      worstUnit: {
        players: ["Jordan Goodwin", "Bol Bol", "Damion Lee", "Chimezie Metu", "Saben Lee"],
        team: "PHX",
        minutesTogether: 31,
        netRating: -15.8,
        offRating: 100.4,
        defRating: 116.2,
        plusMinus: -20,
        record: "Equivalent to 19-63 pace",
        keyStrength: "Bol Bol's three-point shooting off the bench provides the only genuine spacing threat in a unit otherwise built without a credible offensive focal point",
      },
    },
    {
      team: "LAL",
      teamRecord: "46-36",
      narrative:
        "Los Angeles's lineup data reflects the organizational tension between LeBron James's still-elite offensive efficiency and a supporting cast whose defensive limitations are now statistically undeniable. The best unit is functional when Anthony Davis anchors the defense and LeBron operates as a playmaker, but that structure depends on Davis's availability — in the 18 games he missed, the best lineup's net rating fell from +10.8 to -1.4. The death lineup is where the Lakers become most credible, with Austin Reaves providing a secondary creation option that reduces LeBron's late-game burden and Davis's rim protection making the closing defense functional. The new-look lineup featuring D'Angelo Russell's residual pick-and-roll chemistry with Davis was one of the season's underreported findings — that pairing functioned as a genuine offensive weapon when used in 12-minute stretches against second units. The worst unit is the LeBron rest group, and it isn't close.",
      bestUnit: {
        players: ["LeBron James", "Anthony Davis", "Austin Reaves", "D'Angelo Russell", "Rui Hachimura"],
        team: "LAL",
        minutesTogether: 334,
        netRating: 10.8,
        offRating: 114.6,
        defRating: 103.8,
        plusMinus: 72,
        record: "Equivalent to 52-30 pace",
        keyStrength: "Davis's roll gravity combined with LeBron's passing angles creates the most reliable lob-and-kick sequence in the Western Conference outside of OKC",
      },
      deathLineup: {
        players: ["LeBron James", "Anthony Davis", "Austin Reaves", "Jarred Vanderbilt", "Rui Hachimura"],
        team: "LAL",
        minutesTogether: 62,
        netRating: 9.4,
        offRating: 112.8,
        defRating: 103.4,
        plusMinus: 23,
        record: "13-11 in games when closing",
        keyStrength: "Vanderbilt's energy and physicality in late-game defensive possessions provides the Lakers their only consistent on-ball stopper outside of Davis",
      },
      worstUnit: {
        players: ["Gabe Vincent", "Maxwell Lewis", "Alex Fudge", "Colin Castleton", "Wenyen Gabriel"],
        team: "LAL",
        minutesTogether: 38,
        netRating: -14.3,
        offRating: 101.8,
        defRating: 116.1,
        plusMinus: -22,
        record: "Equivalent to 22-60 pace",
        keyStrength: "Lewis's raw athleticism shows in transition — the only context where this grouping generates offense without requiring half-court creation it does not possess",
      },
      newLookLineup: {
        players: ["LeBron James", "Anthony Davis", "D'Angelo Russell", "Austin Reaves", "Jarred Vanderbilt"],
        team: "LAL",
        minutesTogether: 88,
        netRating: 8.6,
        offRating: 113.4,
        defRating: 104.8,
        plusMinus: 30,
        record: "Equivalent to 49-33 pace",
        keyStrength: "Russell's residual pick-and-roll comfort with Davis unlocked a secondary ball-screen action that opponents had not prepared for after Russell's role was reduced mid-season",
      },
    },
  ],
};