// AUTO-GENERATED by scripts/sync-line-movement.mjs — seed retained when slate is empty.

export interface LineOpenerArchiveGame {
  awayTeam: string;
  homeTeam: string;
  openingSpread: string;
  closingSpread?: string;
}

export interface LineOpenerArchiveEdition {
  editionDate: string;
  games: LineOpenerArchiveGame[];
}

/** Recent opener (and optional closer) snapshots for Betting Intel history. */
export const lineOpenersArchive: LineOpenerArchiveEdition[] = [
  {
    editionDate: "October 6, 2026",
    games: [
      {
        awayTeam: "LAL",
        homeTeam: "GSW",
        openingSpread: "GSW -2.0",
        closingSpread: "GSW -1.0",
      },
      {
        awayTeam: "BRK",
        homeTeam: "CHA",
        openingSpread: "CHA -1.5",
        closingSpread: "CHA -2.0",
      },
      {
        awayTeam: "NOP",
        homeTeam: "OKC",
        openingSpread: "OKC -5.0",
        closingSpread: "OKC -5.5",
      },
      {
        awayTeam: "DEN",
        homeTeam: "UTA",
        openingSpread: "DEN -1.5",
        closingSpread: "UTA -1.0",
      }
    ],
  }
];
