// AUTO-GENERATED by scripts/sync-line-movement.mjs — do not edit by hand.

export interface LineMovementRow {
  awayTeam: string;
  homeTeam: string;
  openingSpread: string;
  closingSpread: string;
  updatedAt: string;
}

export const lineMovementEditionDate = "May 26, 2026";

export const lineMovementRows: LineMovementRow[] = [
  {
    awayTeam: "OKC",
    homeTeam: "SAS",
    openingSpread: "OKC -1.5",
    closingSpread: "SAS -2.0",
    updatedAt: "2026-05-27T09:21:34.065Z",
  }
];
