// Lineup Intelligence — Weekly lineup analysis
// Last updated: March 23, 2026
// Live at: https://hoopsintel.net/lineups

// ═══════════════════════════════════════════════════════════
// INTERFACES
// ═══════════════════════════════════════════════════════════

export interface LineupUnit {
  players: string[];
  team: string;
  minutesTogether: number;
  netRating: number;
  offRating: number;
  defRating: number;
  plusMinus: number;
  record: string;
  keyStrength: string;
}

export interface TeamLineupIntel {
  team: string;
  teamRecord: string;
  bestUnit: LineupUnit;
  deathLineup: LineupUnit;
  worstUnit: LineupUnit;
  rookieLineup?: LineupUnit;
  newLookLineup?: LineupUnit;
  narrative: string;
}

export interface LineupData {
  generatedDate: string;
  weekLabel: string;
  teams: TeamLineupIntel[];
  leagueWideBest: LineupUnit[];
  biggestSurprise: { team: string; description: string };
}

// ═══════════════════════════════════════════════════════════
// DATA — Week of March 22–28, 2026
// ═══════════════════════════════════════════════════════════

export const lineupData: LineupData = {
  generatedDate: "March 23, 2026",
  weekLabel: "Week of March 22–28, 2026",
  leagueWideBest: [
    {
      players: ["Shai Gilgeous-Alexander", "Jalen Williams", "Lu Dort", "Chet Holmgren", "Isaiah Hartenstein"],
      team: "OKC",
      minutesTogether: 482,
      netRating: 18.4,
      offRating: 121.6,
      defRating: 103.2,
      plusMinus: 187,
      record: "Equivalent to 64-18 pace",
      keyStrength: "Elite two-way versatility — top-5 offense AND defense when this five shares the floor",
    },
    {
      players: ["Victor Wembanyama", "Devin Vassell", "Jeremy Sochan", "Stephon Castle", "Chris Paul"],
      team: "SAS",
      minutesTogether: 410,
      netRating: 16.2,
      offRating: 118.8,
      defRating: 102.6,
      plusMinus: 164,
      record: "Equivalent to 61-21 pace",
      keyStrength: "Wemby's rim protection + Chris Paul's floor generalship = basketball nirvana",
    },
    {
      players: ["Cade Cunningham", "Jaden Ivey", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
      team: "DET",
      minutesTogether: 394,
      netRating: 14.8,
      offRating: 117.2,
      defRating: 102.4,
      plusMinus: 152,
      record: "Equivalent to 59-23 pace",
      keyStrength: "Length and athleticism — forces turnovers at the highest rate of any starting five",
    },
    {
      players: ["Jayson Tatum", "Jaylen Brown", "Derrick White", "Jrue Holiday", "Kristaps Porziņģis"],
      team: "BOS",
      minutesTogether: 356,
      netRating: 13.5,
      offRating: 119.4,
      defRating: 105.9,
      plusMinus: 138,
      record: "Equivalent to 57-25 pace",
      keyStrength: "Five capable three-point shooters with elite perimeter defense",
    },
    {
      players: ["Luka Dončić", "Anthony Davis", "Austin Reaves", "Rui Hachimura", "Max Christie"],
      team: "LAL",
      minutesTogether: 368,
      netRating: 12.1,
      offRating: 118.8,
      defRating: 106.7,
      plusMinus: 128,
      record: "Equivalent to 56-26 pace",
      keyStrength: "Luka-AD two-man game is the most devastating pick-and-roll combo in the league",
    },
  ],
  biggestSurprise: {
    team: "ATL",
    description: "The Hawks' closing lineup of Young-NAW-Johnson-Hunter-Okongwu has a +22.3 net rating in 68 clutch minutes over the 11-game winning streak — the best clutch unit in the NBA this month. Jalen Johnson's emergence as a closer has transformed Atlanta from a play-in team to a legitimate second-round threat.",
  },
  teams: [
    {
      team: "OKC",
      teamRecord: "55-15",
      bestUnit: {
        players: ["Shai Gilgeous-Alexander", "Jalen Williams", "Lu Dort", "Chet Holmgren", "Isaiah Hartenstein"],
        team: "OKC",
        minutesTogether: 482,
        netRating: 18.4,
        offRating: 121.6,
        defRating: 103.2,
        plusMinus: 187,
        record: "Equivalent to 64-18 pace",
        keyStrength: "Elite two-way versatility — top-5 offense AND defense",
      },
      deathLineup: {
        players: ["Shai Gilgeous-Alexander", "Jalen Williams", "Lu Dort", "Chet Holmgren", "Alex Caruso"],
        team: "OKC",
        minutesTogether: 112,
        netRating: 21.7,
        offRating: 119.2,
        defRating: 97.5,
        plusMinus: 62,
        record: "18-2 in games when closing",
        keyStrength: "Caruso replaces Hartenstein for switchable perimeter defense — opponents shoot 29% from three against this unit",
      },
      worstUnit: {
        players: ["Aaron Wiggins", "Kenrich Williams", "Jaylin Williams", "Ousmane Dieng", "Cason Wallace"],
        team: "OKC",
        minutesTogether: 86,
        netRating: -3.2,
        offRating: 101.4,
        defRating: 104.6,
        plusMinus: -12,
        record: "Bench-heavy garbage time minutes",
        keyStrength: "Defense remains passable even with all reserves — a testament to OKC's system",
      },
      narrative: "The Thunder's starting five is the best lineup in basketball by a wide margin. Their +18.4 net rating is historically elite — tracking with the best lineups of the last decade. The death lineup swapping Caruso for Hartenstein is even more devastating defensively. OKC's depth means even their worst unit barely loses minutes. This is a championship-caliber roster top to bottom.",
    },
    {
      team: "SAS",
      teamRecord: "51-18",
      bestUnit: {
        players: ["Victor Wembanyama", "Devin Vassell", "Jeremy Sochan", "Stephon Castle", "Chris Paul"],
        team: "SAS",
        minutesTogether: 410,
        netRating: 16.2,
        offRating: 118.8,
        defRating: 102.6,
        plusMinus: 164,
        record: "Equivalent to 61-21 pace",
        keyStrength: "Wemby anchors a defense that allows just 102.6 points per 100 possessions",
      },
      deathLineup: {
        players: ["Victor Wembanyama", "Devin Vassell", "Stephon Castle", "Chris Paul", "Keldon Johnson"],
        team: "SAS",
        minutesTogether: 94,
        netRating: 19.3,
        offRating: 120.1,
        defRating: 100.8,
        plusMinus: 54,
        record: "15-3 in games when closing",
        keyStrength: "Keldon's shooting gives Wemby maximum driving lanes — 56% from three in clutch minutes",
      },
      worstUnit: {
        players: ["Zach Collins", "Blake Wesley", "Malaki Branham", "Sandro Mamukelashvili", "Julian Champagnie"],
        team: "SAS",
        minutesTogether: 68,
        netRating: -6.8,
        offRating: 98.2,
        defRating: 105.0,
        plusMinus: -18,
        record: "Deep bench minutes only",
        keyStrength: "Spacing remains adequate — Collins provides solid screen-setting",
      },
      narrative: "San Antonio's starting five is the second-best unit in basketball. The Wemby-CP3 connection is basketball poetry — Paul's court vision meets Wemby's gravitational pull on defenses. The death lineup with Keldon Johnson has been devastating in clutch situations. The only concern is the steep drop-off to the deep bench, but Pop rarely needs to go there.",
    },
    {
      team: "DET",
      teamRecord: "49-19",
      bestUnit: {
        players: ["Cade Cunningham", "Jaden Ivey", "Ausar Thompson", "Tobias Harris", "Jalen Duren"],
        team: "DET",
        minutesTogether: 394,
        netRating: 14.8,
        offRating: 117.2,
        defRating: 102.4,
        plusMinus: 152,
        record: "Equivalent to 59-23 pace",
        keyStrength: "League-leading turnover rate forced — 18.2 turnovers per game against this unit",
      },
      deathLineup: {
        players: ["Cade Cunningham", "Jaden Ivey", "Ausar Thompson", "Tobias Harris", "Isaiah Stewart"],
        team: "DET",
        minutesTogether: 88,
        netRating: 15.9,
        offRating: 115.4,
        defRating: 99.5,
        plusMinus: 48,
        record: "16-2 in games when closing",
        keyStrength: "Stewart's physicality + Ausar's perimeter lockdown = nothing easy at the rim or the arc",
      },
      worstUnit: {
        players: ["Marcus Sasser", "Simone Fontecchio", "Isaiah Livers", "Marvin Bagley III", "James Wiseman"],
        team: "DET",
        minutesTogether: 52,
        netRating: -8.4,
        offRating: 96.8,
        defRating: 105.2,
        plusMinus: -16,
        record: "Garbage time only",
        keyStrength: "Size — Bagley and Wiseman provide rim protection in blowouts",
      },
      narrative: "Detroit's starting five might be the most disruptive defensive unit in basketball. Ausar Thompson's perimeter defense combined with Duren's rim protection creates a wall that opposing offenses crash into. Cade orchestrates the offense with surgical precision. The death lineup with Stewart replacing Duren adds even more physicality. The Pistons' biggest weakness is their deep bench — but with a 49-19 record, they rarely need it.",
    },
    {
      team: "LAL",
      teamRecord: "44-25",
      bestUnit: {
        players: ["Luka Dončić", "Anthony Davis", "Austin Reaves", "Rui Hachimura", "Max Christie"],
        team: "LAL",
        minutesTogether: 368,
        netRating: 12.1,
        offRating: 118.8,
        defRating: 106.7,
        plusMinus: 128,
        record: "Equivalent to 56-26 pace",
        keyStrength: "Luka-AD pick-and-roll is the most efficient two-man action in the NBA",
      },
      deathLineup: {
        players: ["Luka Dončić", "Anthony Davis", "Austin Reaves", "Rui Hachimura", "Gabe Vincent"],
        team: "LAL",
        minutesTogether: 76,
        netRating: 16.4,
        offRating: 122.3,
        defRating: 105.9,
        plusMinus: 42,
        record: "14-4 in games when closing",
        keyStrength: "Vincent's shooting unlocks maximum spacing for Luka — 42% from three in crunch time",
      },
      worstUnit: {
        players: ["D'Angelo Russell", "Cam Reddish", "Jarred Vanderbilt", "Christian Wood", "Jaxson Hayes"],
        team: "LAL",
        minutesTogether: 44,
        netRating: -11.2,
        offRating: 102.1,
        defRating: 113.3,
        plusMinus: -20,
        record: "Limited usage — only in blowouts",
        keyStrength: "Vanderbilt's energy provides rebounding and hustle plays",
      },
      narrative: "The Lakers' starting five has been the hottest unit in the West over the last two weeks. The Luka-AD connection is approaching all-time great two-man game status — their pick-and-roll efficiency is off the charts. The seven-game winning streak has been powered by this group's fourth-quarter dominance. The death lineup with Gabe Vincent provides floor spacing that turns Luka into an even more dangerous closer. The deep bench is a liability, but JJ Redick has wisely minimized their minutes.",
    },
    {
      team: "BOS",
      teamRecord: "46-23",
      bestUnit: {
        players: ["Jayson Tatum", "Jaylen Brown", "Derrick White", "Jrue Holiday", "Kristaps Porziņģis"],
        team: "BOS",
        minutesTogether: 356,
        netRating: 13.5,
        offRating: 119.4,
        defRating: 105.9,
        plusMinus: 138,
        record: "Equivalent to 57-25 pace",
        keyStrength: "Five 3-point shooters + elite perimeter defense = no weaknesses to exploit",
      },
      deathLineup: {
        players: ["Jayson Tatum", "Jaylen Brown", "Derrick White", "Jrue Holiday", "Al Horford"],
        team: "BOS",
        minutesTogether: 102,
        netRating: 14.8,
        offRating: 117.6,
        defRating: 102.8,
        plusMinus: 52,
        record: "15-3 in games when closing",
        keyStrength: "Championship-tested closing unit — Horford's veteran IQ replaces KP's rim protection with switchability",
      },
      worstUnit: {
        players: ["Payton Pritchard", "Sam Hauser", "Oshae Brissett", "Luke Kornet", "Jordan Walsh"],
        team: "BOS",
        minutesTogether: 48,
        netRating: -4.1,
        offRating: 108.3,
        defRating: 112.4,
        plusMinus: -8,
        record: "Blowout minutes only",
        keyStrength: "Pritchard's shooting keeps the floor spaced even in reserve units",
      },
      narrative: "Boston's starting five remains one of the league's elite units. The five-out attack with Porziņģis at center creates driving lanes that Tatum and Brown exploit ruthlessly. The championship-tested death lineup with Horford replacing KP provides more switching versatility for playoff matchups. The Celtics' 3-game winning streak has coincided with Tatum rounding into his best form. This is a team gearing up for another deep postseason run.",
    },
    {
      team: "ATL",
      teamRecord: "38-31",
      bestUnit: {
        players: ["Trae Young", "Nickeil Alexander-Walker", "Jalen Johnson", "De'Andre Hunter", "Onyeka Okongwu"],
        team: "ATL",
        minutesTogether: 298,
        netRating: 10.2,
        offRating: 116.8,
        defRating: 106.6,
        plusMinus: 94,
        record: "Equivalent to 54-28 pace",
        keyStrength: "Johnson's versatility allows seamless switching between small and big lineups",
      },
      deathLineup: {
        players: ["Trae Young", "Nickeil Alexander-Walker", "Jalen Johnson", "De'Andre Hunter", "Onyeka Okongwu"],
        team: "ATL",
        minutesTogether: 68,
        netRating: 22.3,
        offRating: 120.4,
        defRating: 98.1,
        plusMinus: 44,
        record: "11-0 in the winning streak when closing",
        keyStrength: "Best clutch unit in the NBA this month — opponents shoot 31% in final 5 minutes against this group",
      },
      worstUnit: {
        players: ["Bogdan Bogdanović", "Dyson Daniels", "Jalen Johnson", "Larry Nance Jr.", "Clint Capela"],
        team: "ATL",
        minutesTogether: 62,
        netRating: -5.6,
        offRating: 100.8,
        defRating: 106.4,
        plusMinus: -14,
        record: "Used sparingly during streak",
        keyStrength: "Defensive rebounding — Capela and Nance own the glass",
      },
      narrative: "Atlanta's closing lineup is the story of the season. The same five that starts also closes — and in clutch minutes during the 11-game streak, they've been historically dominant. The +22.3 net rating in clutch situations is absurd. Jalen Johnson has evolved into a two-way star who guards 1-through-5 and orchestrates the offense. Trae Young's willingness to defer in crunch time to Johnson and NAW has been the key unlock. This is a team built for the playoffs.",
    },
    {
      team: "MIN",
      teamRecord: "43-27",
      bestUnit: {
        players: ["Anthony Edwards", "Julius Randle", "Jaden McDaniels", "Mike Conley", "Rudy Gobert"],
        team: "MIN",
        minutesTogether: 342,
        netRating: 11.6,
        offRating: 115.4,
        defRating: 103.8,
        plusMinus: 116,
        record: "Equivalent to 55-27 pace",
        keyStrength: "Gobert's rim protection + McDaniels' perimeter lockdown = the league's most suffocating defense",
      },
      deathLineup: {
        players: ["Anthony Edwards", "Julius Randle", "Jaden McDaniels", "Mike Conley", "Naz Reid"],
        team: "MIN",
        minutesTogether: 84,
        netRating: 13.2,
        offRating: 118.6,
        defRating: 105.4,
        plusMinus: 38,
        record: "12-4 in games when closing",
        keyStrength: "Reid's shooting at the 5 creates space for Edwards to operate in isolation",
      },
      worstUnit: {
        players: ["Bones Hyland", "Nickeil Alexander-Walker", "Kyle Anderson", "Naz Reid", "Luka Garza"],
        team: "MIN",
        minutesTogether: 38,
        netRating: 2.4,
        offRating: 112.6,
        defRating: 110.2,
        plusMinus: 4,
        record: "Positive even without starters",
        keyStrength: "Hyland and Reid provide bench scoring punch — this unit has held its own during Edwards' absence",
      },
      newLookLineup: {
        players: ["Julius Randle", "Jaden McDaniels", "Mike Conley", "Rudy Gobert", "Bones Hyland"],
        team: "MIN",
        minutesTogether: 48,
        netRating: 8.6,
        offRating: 114.2,
        defRating: 105.6,
        plusMinus: 16,
        record: "2-0 in Edwards' absence",
        keyStrength: "Hyland's scoring fills the Edwards void — 50+ combined points with Randle in back-to-back wins",
      },
      narrative: "Minnesota's best unit with Edwards is elite — but the real story this week is how they've survived without him. The Randle-Hyland-Conley-McDaniels-Gobert lineup has gone 2-0 with a +8.6 net rating. Bones Hyland has been the revelation, sliding into Edwards' scoring role seamlessly. The depth here is legitimate and could be the difference in a deep playoff run. When Edwards returns, this team will be even more dangerous.",
    },
    {
      team: "HOU",
      teamRecord: "41-27",
      bestUnit: {
        players: ["Kevin Durant", "Alperen Sengun", "Fred VanVleet", "Dillon Brooks", "Jabari Smith Jr."],
        team: "HOU",
        minutesTogether: 372,
        netRating: 9.4,
        offRating: 116.2,
        defRating: 106.8,
        plusMinus: 102,
        record: "Equivalent to 53-29 pace",
        keyStrength: "Durant-Sengun pick-and-roll creates elite looks — Sengun's passing from the elbow is elite",
      },
      deathLineup: {
        players: ["Kevin Durant", "Alperen Sengun", "Fred VanVleet", "Dillon Brooks", "Amen Thompson"],
        team: "HOU",
        minutesTogether: 72,
        netRating: 11.8,
        offRating: 117.4,
        defRating: 105.6,
        plusMinus: 30,
        record: "12-5 in games when closing",
        keyStrength: "Amen Thompson's speed and defensive versatility — switches 1-through-4 in crunch time",
      },
      worstUnit: {
        players: ["Tari Eason", "Cam Whitmore", "Steven Adams", "Jeff Green", "Aaron Holiday"],
        team: "HOU",
        minutesTogether: 56,
        netRating: -7.8,
        offRating: 99.4,
        defRating: 107.2,
        plusMinus: -18,
        record: "Struggled without stars on the floor",
        keyStrength: "Eason's motor — provides energy and rebounding even when shots don't fall",
      },
      narrative: "Houston's starting five has been solid all season but the Rockets just lost two straight at home for the first time since January. The Durant-Sengun connection remains elite, but Dillon Brooks' defensive lapses against Luka in the Lakers game exposed a vulnerability. The death lineup with Amen Thompson provides more defensive versatility. Houston needs to regroup quickly — they've fallen 2.5 games behind the Lakers for the 3-seed.",
    },
    {
      team: "DEN",
      teamRecord: "43-27",
      bestUnit: {
        players: ["Nikola Jokić", "Jamal Murray", "Michael Porter Jr.", "Aaron Gordon", "Christian Braun"],
        team: "DEN",
        minutesTogether: 316,
        netRating: 10.8,
        offRating: 120.2,
        defRating: 109.4,
        plusMinus: 98,
        record: "Equivalent to 54-28 pace",
        keyStrength: "Jokic's passing + MPJ/Murray shooting = the highest-rated offense of any starting five",
      },
      deathLineup: {
        players: ["Nikola Jokić", "Jamal Murray", "Michael Porter Jr.", "Aaron Gordon", "Kentavious Caldwell-Pope"],
        team: "DEN",
        minutesTogether: 68,
        netRating: 14.6,
        offRating: 121.8,
        defRating: 107.2,
        plusMinus: 34,
        record: "13-4 in games when closing",
        keyStrength: "Championship-tested closing unit — KCP's 3-and-D replaces Braun for perimeter shooting",
      },
      worstUnit: {
        players: ["Reggie Jackson", "Peyton Watson", "Zeke Nnaji", "DeAndre Jordan", "Julian Strawther"],
        team: "DEN",
        minutesTogether: 44,
        netRating: -9.6,
        offRating: 97.8,
        defRating: 107.4,
        plusMinus: -16,
        record: "Deep bench struggles mightily",
        keyStrength: "Watson provides occasional rim protection and shot-blocking",
      },
      narrative: "Denver's starting five has the highest offensive rating of any lineup in the league. The Jokic-Murray-MPJ trio is scoring at a pace that defies defensive schemes. Murray's return to form over the last four games has been critical — his 20-point night in Memphis was his best in weeks. The concern remains the bench: Denver's reserve unit is among the worst in the league. But when Jokic plays 35+ minutes, none of that matters.",
    },
    {
      team: "TOR",
      teamRecord: "39-29",
      bestUnit: {
        players: ["Brandon Ingram", "Scottie Barnes", "RJ Barrett", "Immanuel Quickley", "Jakob Poeltl"],
        team: "TOR",
        minutesTogether: 186,
        netRating: 11.4,
        offRating: 118.6,
        defRating: 107.2,
        plusMinus: 56,
        record: "Equivalent to 55-27 pace",
        keyStrength: "Three elite scorers (Ingram, Barnes, Barrett) create matchup nightmares for any defense",
      },
      deathLineup: {
        players: ["Brandon Ingram", "Scottie Barnes", "RJ Barrett", "Immanuel Quickley", "Jakob Poeltl"],
        team: "TOR",
        minutesTogether: 42,
        netRating: 14.2,
        offRating: 120.8,
        defRating: 106.6,
        plusMinus: 22,
        record: "5-1 since the trade",
        keyStrength: "Ingram's isolation scoring in crunch time — 48% FG in the final 5 minutes since joining Toronto",
      },
      worstUnit: {
        players: ["Gary Trent Jr.", "Gradey Dick", "Chris Boucher", "Kelly Olynyk", "Ochai Agbaji"],
        team: "TOR",
        minutesTogether: 36,
        netRating: -6.2,
        offRating: 104.6,
        defRating: 110.8,
        plusMinus: -10,
        record: "Bench unit needs work",
        keyStrength: "Three-point shooting — Dick and Trent provide floor spacing",
      },
      newLookLineup: {
        players: ["Brandon Ingram", "Scottie Barnes", "RJ Barrett", "Immanuel Quickley", "Jakob Poeltl"],
        team: "TOR",
        minutesTogether: 186,
        netRating: 11.4,
        offRating: 118.6,
        defRating: 107.2,
        plusMinus: 56,
        record: "5-1 since the Ingram trade",
        keyStrength: "Ingram has scored 28+ in three straight games — the trade is already paying dividends",
      },
      narrative: "The Ingram trade has transformed Toronto from a good team into a legitimate contender. The new starting five has a +11.4 net rating in 186 minutes together — and it's only getting better as they build chemistry. Ingram's three consecutive 28-point games have been masterful. The closing unit is the same as the starting five, which speaks to their trust in this group. Toronto at 39-29 is the East's most dangerous rising team.",
    },
  ],
};
