// AUTO-GENERATED by scripts/sync-line-movement.mjs — seed retained when slate is empty.

export interface LineOpenerArchiveGame {
  awayTeam: string;
  homeTeam: string;
  openingSpread: string;
  closingSpread?: string;
}

export interface LineOpenerArchiveEdition {
  editionDate: string;
  games: LineOpenerArchiveGame[];
}

/** Recent opener (and optional closer) snapshots for Betting Intel history. */
export const lineOpenersArchive: LineOpenerArchiveEdition[] = [
  {
    editionDate: "October 5, 2026",
    games: [
      {
        awayTeam: "NYK",
        homeTeam: "PHI",
        openingSpread: "NYK -2.0",
        closingSpread: "NYK -2.5",
      },
      {
        awayTeam: "MEM",
        homeTeam: "ATL",
        openingSpread: "ATL -3.0",
        closingSpread: "ATL -3.0",
      },
      {
        awayTeam: "PHX",
        homeTeam: "DET",
        openingSpread: "DET -1.5",
        closingSpread: "DET -1.5",
      },
      {
        awayTeam: "MIN",
        homeTeam: "MIL",
        openingSpread: "MIL -3.0",
        closingSpread: "MIL -3.5",
      },
      {
        awayTeam: "LAL",
        homeTeam: "SAC",
        openingSpread: "SAC -1.0",
        closingSpread: "SAC -1.5",
      }
    ],
  }
];
