// Lineup Intelligence — Weekly lineup analysis
// Last updated: August 17, 2026
// Live at: https://hoopsintel.net/lineups

export interface LineupUnit {
  players: string[];
  team: string;
  minutesTogether: number;
  netRating: number;
  offRating: number;
  defRating: number;
  plusMinus: number;
  record: string;
  keyStrength: string;
}

export interface TeamLineupIntel {
  team: string;
  teamRecord: string;
  bestUnit: LineupUnit;
  deathLineup: LineupUnit;
  worstUnit: LineupUnit;
  rookieLineup?: LineupUnit;
  newLookLineup?: LineupUnit;
  narrative: string;
}

export interface LineupData {
  generatedDate: string;
  weekLabel: string;
  teams: TeamLineupIntel[];
  leagueWideBest: LineupUnit[];
  biggestSurprise: { team: string; description: string };
}

export const lineupData: LineupData = {
  generatedDate: "August 17, 2026",
  weekLabel: "Week of August 17–23, 2026",

  leagueWideBest: [
    {
      players: ["Shai Gilgeous-Alexander", "Chet Holmgren", "Luguentz Dort", "Jalen Williams", "Isaiah Hartenstein"],
      team: "OKC",
      minutesTogether: 412,
      netRating: 21.4,
      offRating: 122.8,
      defRating: 101.4,
      plusMinus: 298,
      record: "Equivalent to 68-14 pace",
      keyStrength: "Elite two-way synergy — Holmgren's drop coverage and SGA's pick-and-roll mastery create a system with no exploitable seam on either end",
    },
    {
      players: ["Victor Wembanyama", "De'Aaron Fox", "Stephon Castle", "Harrison Barnes", "Zach Collins"],
      team: "SAS",
      minutesTogether: 387,
      netRating: 19.7,
      offRating: 121.3,
      defRating: 101.6,
      plusMinus: 261,
      record: "Equivalent to 65-17 pace",
      keyStrength: "Wembanyama's rim protection anchors a defensive structure that generates the league's highest live-ball turnover rate when all five share the floor",
    },
    {
      players: ["Shai Gilgeous-Alexander", "Chet Holmgren", "Jalen Williams", "Aaron Wiggins", "Isaiah Hartenstein"],
      team: "OKC",
      minutesTogether: 334,
      netRating: 18.2,
      offRating: 120.1,
      defRating: 101.9,
      plusMinus: 207,
      record: "Equivalent to 63-19 pace",
      keyStrength: "Spacing variant that replaces Dort with Wiggins unlocks a higher offensive ceiling while maintaining near-identical defensive integrity",
    },
    {
      players: ["Nikola Jokic", "Jamal Murray", "Michael Porter Jr.", "Aaron Gordon", "Christian Braun"],
      team: "DEN",
      minutesTogether: 358,
      netRating: 17.6,
      offRating: 119.4,
      defRating: 101.8,
      plusMinus: 214,
      record: "Equivalent to 62-20 pace",
      keyStrength: "The league's most versatile offensive unit — Jokic's passing from the elbow combined with MPJ's gravity off weak-side relocations remains genuinely unguardable in the half court",
    },
    {
      players: ["Victor Wembanyama", "De'Aaron Fox", "Stephon Castle", "Keldon Johnson", "Zach Collins"],
      team: "SAS",
      minutesTogether: 298,
      netRating: 16.9,
      offRating: 118.7,
      defRating: 101.8,
      plusMinus: 171,
      record: "Equivalent to 61-21 pace",
      keyStrength: "High-pace transition variant — Fox and Castle's combined 7.0 APG in transition situations generates the league's cleanest secondary-break offense",
    },
  ],

  biggestSurprise: {
    team: "HOU",
    description:
      "Houston's Alperen Sengun–Jabari Smith Jr. two-big closing lineup has posted a +14.8 net rating in fourth-quarter possessions over the past six weeks — a number that no front office model projected when the roster was constructed. The Rockets are executing a physical, paint-dominant close-game scheme that exposes how poorly most Western Conference rotations are built to guard two credible post threats simultaneously.",
  },

  teams: [
    {
      team: "OKC",
      teamRecord: "64-18",
      narrative:
        "Oklahoma City's core five-man unit is the statistical best lineup in basketball by net rating, and it isn't particularly close. The Holmgren–Hartenstein two-big experiment — once a philosophical risk — has become the league's most efficient interior partnership, with Holmgren defending the perimeter and Hartenstein anchoring the body. SGA's usage rate within this unit actually decreases relative to his solo minutes, which is the signature of a truly functional ecosystem rather than a star-dependent one. The one soft spot remains the reserve bridge unit connecting Dort's minutes to Williams's, where OKC bleeds approximately four points per 100 possessions against elite point guards who can manipulate switching seams. That's a rounding error on an 82-game sample, but it's the precise variable opposing coaches will target in a seven-game series.",
      bestUnit: {
        players: ["Shai Gilgeous-Alexander", "Chet Holmgren", "Luguentz Dort", "Jalen Williams", "Isaiah Hartenstein"],
        team: "OKC",
        minutesTogether: 412,
        netRating: 21.4,
        offRating: 122.8,
        defRating: 101.4,
        plusMinus: 298,
        record: "Equivalent to 68-14 pace",
        keyStrength: "Full two-way expression — league's highest net rating among any lineup with 400+ minutes together",
      },
      deathLineup: {
        players: ["Shai Gilgeous-Alexander", "Luguentz Dort", "Jalen Williams", "Chet Holmgren", "Isaiah Hartenstein"],
        team: "OKC",
        minutesTogether: 74,
        netRating: 18.6,
        offRating: 119.2,
        defRating: 100.6,
        plusMinus: 94,
        record: "19-6 in games when closing",
        keyStrength: "Dort's perimeter lock-down combined with Holmgren's shot-alteration gives OKC a closing defense with no positional vulnerability",
      },
      worstUnit: {
        players: ["Alex Caruso", "Kenrich Williams", "Ousmane Dieng", "Jaylin Williams", "Nikola Topic"],
        team: "OKC",
        minutesTogether: 41,
        netRating: -9.2,
        offRating: 106.1,
        defRating: 115.3,
        plusMinus: -26,
        record: "Equivalent to 33-49 pace",
        keyStrength: "Developmental rotation only — no functional strength at this level of competition",
      },
      rookieLineup: {
        players: ["Nikola Topic", "Ousmane Dieng", "Jaylin Williams", "Aaron Wiggins", "Kenrich Williams"],
        team: "OKC",
        minutesTogether: 58,
        netRating: 2.1,
        offRating: 110.4,
        defRating: 108.3,
        plusMinus: 8,
        record: "Equivalent to 44-38 pace",
        keyStrength: "Topic's pick-and-roll processing is ahead of schedule — this unit's +2.1 net rating is the league's best among lineups composed entirely of players on rookie-scale deals",
      },
    },
    {
      team: "SAS",
      teamRecord: "62-20",
      narrative:
        "San Antonio's lineup architecture tells the story of a franchise operating at genuinely rare organizational clarity. Wembanyama's best five-man unit posts a +19.7 net rating — second in the league — and the gap between their best and worst units is smaller than any other top-four team, which reflects depth construction rather than star dependency. The Castle minutes are worth watching in lineup splits: when Castle and Fox share the floor without Wembanyama, SAS runs at a +7.4 net rating, which is remarkable for a non-Wemby unit and explains why the extension conversation is being treated internally as a financial formality rather than a roster decision. The one genuine concern is what happens to the second unit's offensive rating when Barnes sits — a -6.3 swing suggests Barnes is doing more off-ball gravity work than his box score reflects.",
      bestUnit: {
        players: ["Victor Wembanyama", "De'Aaron Fox", "Stephon Castle", "Harrison Barnes", "Zach Collins"],
        team: "SAS",
        minutesTogether: 387,
        netRating: 19.7,
        offRating: 121.3,
        defRating: 101.6,
        plusMinus: 261,
        record: "Equivalent to 65-17 pace",
        keyStrength: "Wembanyama's interior dominance frees Fox to operate as a pure creation threat — no other unit in the league generates this combination of rim protection and transition pace",
      },
      deathLineup: {
        players: ["Victor Wembanyama", "De'Aaron Fox", "Stephon Castle", "Harrison Barnes", "Keldon Johnson"],
        team: "SAS",
        minutesTogether: 69,
        netRating: 16.8,
        offRating: 118.1,
        defRating: 101.3,
        plusMinus: 79,
        record: "18-5 in games when closing",
        keyStrength: "Johnson replaces Collins to add perimeter switchability — SAS's closing defense allows the league's second-lowest opponent FG% at the rim",
      },
      worstUnit: {
        players: ["Blake Wesley", "Malaki Branham", "Julian Champagnie", "Charles Bassey", "Sandro Mamukelashvili"],
        team: "SAS",
        minutesTogether: 38,
        netRating: -11.4,
        offRating: 104.2,
        defRating: 115.6,
        plusMinus: -29,
        record: "Equivalent to 29-53 pace",
        keyStrength: "Fringe-roster unit with no functional floor-spacing — this combination exists for developmental minutes only",
      },
      rookieLineup: {
        players: ["Stephon Castle", "Blake Wesley", "Julian Champagnie", "Harrison Barnes", "Zach Collins"],
        team: "SAS",
        minutesTogether: 87,
        netRating: 5.8,
        offRating: 112.6,
        defRating: 106.8,
        plusMinus: 34,
        record: "Equivalent to 48-34 pace",
        keyStrength: "Castle's playmaking at the point of the second unit elevates every player around him — his 4.2 APG in non-Wemby minutes is the primary reason SAS's bench differential is positive",
      },
    },
    {
      team: "DEN",
      teamRecord: "54-28",
      narrative:
        "Denver's lineup data this season is a story told in two separate documents: the Jokic-plus-Murray minutes and everything else. When both are healthy and sharing the floor, the Nuggets run at a +17.6 net rating that is the fourth-best five-man combination in the league. When Murray's knee management protocol pulls him from fourth-quarter rotations — which happened in 14 games this season — Denver's closing net rating drops to +4.1, a collapse that no supporting cast adjustment has adequately patched. The Murray extension complexity referenced in this week's Pulse context is not purely financial; it is partly a medical negotiation, and Denver's front office is aware that the lineup splits tell that story more honestly than any press release. Christian Braun's emergence as the most reliable non-Jokic secondary creator is real and important — but it's a bridge, not a solution.",
      bestUnit: {
        players: ["Nikola Jokic", "Jamal Murray", "Michael Porter Jr.", "Aaron Gordon", "Christian Braun"],
        team: "DEN",
        minutesTogether: 358,
        netRating: 17.6,
        offRating: 119.4,
        defRating: 101.8,
        plusMinus: 214,
        record: "Equivalent to 62-20 pace",
        keyStrength: "Jokic's passing from the high post combined with MPJ's corner gravity creates a half-court offense that generates the league's highest frequency of wide-open corner threes",
      },
      deathLineup: {
        players: ["Nikola Jokic", "Jamal Murray", "Aaron Gordon", "Michael Porter Jr.", "Kentavious Caldwell-Pope"],
        team: "DEN",
        minutesTogether: 61,
        netRating: 14.2,
        offRating: 116.8,
        defRating: 102.6,
        plusMinus: 59,
        record: "16-8 in games when closing",
        keyStrength: "KCP's floor spacing and switchability add defensive versatility without sacrificing offensive spacing — Denver's most disciplined closing rotation",
      },
      worstUnit: {
        players: ["Reggie Jackson", "Peyton Watson", "Hunter Tyson", "Zeke Nnaji", "DeAndre Jordan"],
        team: "DEN",
        minutesTogether: 33,
        netRating: -13.7,
        offRating: 103.8,
        defRating: 117.5,
        plusMinus: -31,
        record: "Equivalent to 26-56 pace",
        keyStrength: "Garbage-time unit that exists exclusively to absorb blowout minutes — no competitive function",
      },
    },
    {
      team: "HOU",
      teamRecord: "52-30",
      narrative:
        "Houston's lineup data contains the most surprising single finding in this week's report: the Sengun–Smith two-big closing combination is posting a +14.8 net rating in fourth-quarter possessions, a number that emerged organically from in-game adjustments rather than from any preseason design. Head coach Ime Udoka has leaned into it over the past six weeks as opposing teams fail to find a schematic answer for guarding two credible post threats while also accounting for Jalen Green's drive-and-kick gravity. The Rockets' best unit by full-season net rating is their five-out spacing group with Sengun at the five, but the closing split suggests a separate tactical identity is emerging that may matter more in a playoff series. With Sengun's extension window active, these lineup splits are also organizational data — Houston's front office is watching which version of the roster performs best before finalizing what it's paying to keep.",
      bestUnit: {
        players: ["Alperen Sengun", "Jalen Green", "Dillon Brooks", "Jabari Smith Jr.", "Fred VanVleet"],
        team: "HOU",
        minutesTogether: 341,
        netRating: 14.3,
        offRating: 116.2,
        defRating: 101.9,
        plusMinus: 166,
        record: "Equivalent to 57-25 pace",
        keyStrength: "Spacing-first unit — Sengun operating as the sole big unlocks drive lanes for Green and creates the league's most efficient mid-range pull-up opportunities",
      },
      deathLineup: {
        players: ["Alperen Sengun", "Jabari Smith Jr.", "Jalen Green", "Dillon Brooks", "Fred VanVleet"],
        team: "HOU",
        minutesTogether: 52,
        netRating: 14.8,
        offRating: 117.1,
        defRating: 102.3,
        plusMinus: 52,
        record: "14-7 in games when closing",
        keyStrength: "Twin-big closing surprise — the Sengun–Smith post tandem generates the league's highest opponent foul rate in the fourth quarter, exploiting small-ball defensive mismatches",
      },
      worstUnit: {
        players: ["Tari Eason", "Cam Whitmore", "Aaron Holiday", "Jae'Sean Tate", "Bruno Fernando"],
        team: "HOU",
        minutesTogether: 44,
        netRating: -10.8,
        offRating: 105.6,
        defRating: 116.4,
        plusMinus: -32,
        record: "Equivalent to 30-52 pace",
        keyStrength: "Reserve rotation without sufficient shooting — shot creation dries up entirely when VanVleet and Green are off the floor simultaneously",
      },
      rookieLineup: {
        players: ["Reed Sheppard", "Cam Whitmore", "Jabari Smith Jr.", "Tari Eason", "Alperen Sengun"],
        team: "HOU",
        minutesTogether: 63,
        netRating: 4.4,
        offRating: 111.8,
        defRating: 107.4,
        plusMinus: 19,
        record: "Equivalent to 47-35 pace",
        keyStrength: "Sheppard's shooting gravity in this grouping — his 43.8% from three in this specific lineup combination is producing meaningful floor-spacing effects that the coaching staff is actively cultivating",
      },
    },
    {
      team: "NYK",
      teamRecord: "53-29",
      narrative:
        "New York's lineup splits reveal a team that is simultaneously the East's most complete closing unit and the conference's most rotation-dependent regular-season roster. The Brunson–Towns–OG Anunoby closing group posts a +15.1 net rating in fourth-quarter possessions — the East's best — but that number is almost entirely a function of Brunson's isolation efficiency and Towns's pick-and-pop gravity. Remove either, and the closing net rating falls to +3.8. The Knicks' worst lineup is also the league's most revealing organizational story: their backup point guard situation generates a -12.6 net rating when Brunson sits, exposing a depth gap that was papered over during the regular season by Brunson's elite usage and never genuinely resolved. Towns's championship validation is real, but these lineup splits suggest he is a co-star operating within a carefully constructed ecosystem, not a franchise anchor capable of carrying a degraded rotation.",
      bestUnit: {
        players: ["Jalen Brunson", "Karl-Anthony Towns", "OG Anunoby", "Mikal Bridges", "Josh Hart"],
        team: "NYK",
        minutesTogether: 374,
        netRating: 16.1,
        offRating: 118.3,
        defRating: 102.2,
        plusMinus: 204,
        record: "Equivalent to 61-21 pace",
        keyStrength: "Brunson's creation combined with Towns's pick-and-pop shooting creates the East's most efficient two-man game — opponents cannot drop and cannot switch without giving up either a mid-range pull-up or a corner three",
      },
      deathLineup: {
        players: ["Jalen Brunson", "Karl-Anthony Towns", "OG Anunoby", "Mikal Bridges", "Josh Hart"],
        team: "NYK",
        minutesTogether: 71,
        netRating: 15.1,
        offRating: 117.6,
        defRating: 102.5,
        plusMinus: 73,
        record: "17-6 in games when closing",
        keyStrength: "Same five starters used as the closing unit — New York's depth concern is real, but the closing group's championship-tested cohesion is the East's most battle-hardened",
      },
      worstUnit: {
        players: ["Landry Shamet", "Precious Achiuwa", "Shake Milton", "Bojan Bogdanovic", "Isaiah Roby"],
        team: "NYK",
        minutesTogether: 37,
        netRating: -12.6,
        offRating: 104.9,
        defRating: 117.5,
        plusMinus: -32,
        record: "Equivalent to 28-54 pace",
        keyStrength: "No functional strength — the backup point guard vacuum is the most exploitable structural gap on any East contender's roster",
      },
    },
    {
      team: "MIN",
      teamRecord: "49-33",
      narrative:
        "Minnesota's lineup data this season is defined by a single organizing tension: Anthony Edwards is the league's most dominant individual force in isolation situations, but the Timberwolves' best lineup is also their most collective one — the one where his usage drops from 34% to 26% and Rudy Gobert's screen-assisted cuts and Jaden McDaniels's corner gravity do the distributional work. That tension has never been fully resolved at the coaching level, and the lineup splits make it visible. Edwards's best five-man unit posts a +13.4 net rating; his second-best unit posts +5.8; the gap between first and second is larger than any other top-ten player's comparable split, suggesting a roster that is well-constructed around one expression of Edwards but not adequately deep enough to run two coherent offensive systems simultaneously. Minnesota's multi-player extension pressure is not just financial — it is a direct product of this lineup fragility.",
      bestUnit: {
        players: ["Anthony Edwards", "Rudy Gobert", "Jaden McDaniels", "Mike Conley", "Nickeil Alexander-Walker"],
        team: "MIN",
        minutesTogether: 318,
        netRating: 13.4,
        offRating: 115.6,
        defRating: 102.2,
        plusMinus: 144,
        record: "Equivalent to 56-26 pace",
        keyStrength: "Gobert's screen-setting paired with Conley's decision-making creates the league's most efficient pick-and-roll rhythm for Edwards — this unit generates 1.14 points per possession in half-court sets",
      },
      deathLineup: {
        players: ["Anthony Edwards", "Rudy Gobert", "Jaden McDaniels", "Nickeil Alexander-Walker", "Naz Reid"],
        team: "MIN",
        minutesTogether: 58,
        netRating: 11.2,
        offRating: 114.1,
        defRating: 102.9,
        plusMinus: 44,
        record: "13-9 in games when closing",
        keyStrength: "Reid's floor spacing off the bench in closing situations is Minnesota's most undervalued roster asset — his 41.6% from three in high-leverage minutes is the closing unit's critical spacing valve",
      },
      worstUnit: {
        players: ["Monte Morris", "Jaylen Clark", "Leonard Miller", "Josh Minott", "Luka Garza"],
        team: "MIN",
        minutesTogether: 29,
        netRating: -14.1,
        offRating: 102.8,
        defRating: 116.9,
        plusMinus: -28,
        record: "Equivalent to 25-57 pace",
        keyStrength: "Developmental depth with no competitive function — the gap between this unit and the closing group is the widest talent cliff on any playoff roster",
      },
    },
    {
      team: "BOS",
      teamRecord: "51-31",
      narrative:
        "Boston's lineup construction entering the extension window reflects the organizational complexity of a defending champion in roster transition. The Tatum–Brown closing unit remains the East's most defensively versatile co-star pairing, posting a +12.8 net rating when sharing the floor, but the surrounding cast has been reshuffled enough times that the connective tissue — the third and fourth options who absorb defensive attention and provide spacing — is less settled than it was during the championship run. Kristaps Porzingis's health-managed role has reduced his lineup minutes with the starters, creating a spacing gap that Al Horford's aging athleticism cannot fully fill. The Celtics' worst unit is their most revealing data point: when neither Tatum nor Brown is on the floor, Boston's net rating falls to -11.9, confirming that this is still a two-star ecosystem with thin organizational depth behind the principals.",
      bestUnit: {
        players: ["Jayson Tatum", "Jaylen Brown", "Kristaps Porzingis", "Jrue Holiday", "Derrick White"],
        team: "BOS",
        minutesTogether: 329,
        netRating: 14.8,
        offRating: 117.4,
        defRating: 102.6,
        plusMinus: 166,
        record: "Equivalent to 58-24 pace",
        keyStrength: "Porzingis's floor-spacing from the high post combined with Tatum's mid-range creation gives Boston an offensive menu that no single-scheme defense can adequately cover",
      },
      deathLineup: {
        players: ["Jayson Tatum", "Jaylen Brown", "Jrue Holiday", "Derrick White", "Al Horford"],
        team: "BOS",
        minutesTogether: 64,
        netRating: 12.8,
        offRating: 114.9,
        defRating: 102.1,
        plusMinus: 56,
        record: "15-7 in games when closing",
        keyStrength: "Horford's veteran IQ and team-wide defensive switching versatility — this five-man group has allowed the East's lowest opponent three-point percentage in clutch possessions",
      },
      worstUnit: {
        players: ["Payton Pritchard", "Sam Hauser", "Jordan Walsh", "Luke Kornet", "Lamar Stevens"],
        team: "BOS",
        minutesTogether: 41,
        netRating: -11.9,
        offRating: 105.3,
        defRating: 117.2,
        plusMinus: -33,
        record: "Equivalent to 29-53 pace",
        keyStrength: "Hauser's shooting is the lone positive variable — this unit's defensive rating is the worst of any lineup on a top-six seed's roster",
      },
    },
    {
      team: "GSW",
      teamRecord: "48-34",
      narrative:
        "Golden State's lineup data is the most interesting editorial story in this week's report that isn't attached to a Pulse Index player. Brandin Podziemski's emergence as a legitimate initiator has unlocked a new best unit that doesn't require Steph Curry in the primary ball-handler role — a development the organization has been hoping to find for two seasons. When Curry operates off-ball in the Podziemski-primary unit, Golden State's offensive rating actually increases by 2.4 points per 100 possessions relative to Curry-on-ball possessions against the same defenses, which is a data point the coaching staff has begun actively designing around. The death lineup remains Curry-centric by necessity — no other player on the roster can generate the gravity required to close games — but the regular-season split is revealing a flexibility that playoff opponents will need to account for differently than in previous years.",
      bestUnit: {
        players: ["Stephen Curry", "Brandin Podziemski", "Andrew Wiggins", "Draymond Green", "Trayce Jackson-Davis"],
        team: "GSW",
        minutesTogether: 307,
        netRating: 12.6,
        offRating: 115.1,
        defRating: 102.5,
        plusMinus: 131,
        record: "Equivalent to 55-27 pace",
        keyStrength: "Podziemski's off-ball gravity as a secondary initiator frees Curry to operate as a pure spacer and shooter — the league's most efficient offensive unit not anchored by a traditional big",
      },
      deathLineup: {
        players: ["Stephen Curry", "Brandin Podziemski", "Andrew Wiggins", "Draymond Green", "Jonathan Kuminga"],
        team: "GSW",
        minutesTogether: 54,
        netRating: 10.4,
        offRating: 113.6,
        defRating: 103.2,
        plusMinus: 38,
        record: "13-9 in games when closing",
        keyStrength: "Kuminga's athleticism in closing lineups provides a transition-finishing threat that forces defenses to account for both the Curry three and the lob — a two-threat closing problem that most opponents cannot solve simultaneously",
      },
      worstUnit: {
        players: ["Moses Moody", "Gary Payton II", "Kevon Looney", "Pat Spencer", "Gui Santos"],
        team: "GSW",
        minutesTogether: 32,
        netRating: -10.3,
        offRating: 106.2,
        defRating: 116.5,
        plusMinus: -23,
        record: "Equivalent to 31-51 pace",
        keyStrength: "Payton's defense is the only above-replacement-level contribution from this grouping — offensively, this unit ranks in the bottom five of any playoff team's worst lineup",
      },
      newLookLineup: {
        players: ["Stephen Curry", "Brandin Podziemski", "Draymond Green", "Jonathan Kuminga", "Trayce Jackson-Davis"],
        team: "GSW",
        minutesTogether: 89,
        netRating: 11.8,
        offRating: 114.3,
        defRating: 102.5,
        plusMinus: 71,
        record: "Equivalent to 54-28 pace",
        keyStrength: "The Wiggins-free spacing experiment — this unit's transition offense ranks second in the league and represents Golden State's most aggressive departure from their championship-era personnel architecture",
      },
    },
    {
      team: "LAL",
      teamRecord: "47-35",
      narrative:
        "Los Angeles's lineup splits tell the story of a team that is better than its record and more fragile than its best unit suggests. The LeBron James–Anthony Davis two-man game remains statistically elite — a +13.9 net rating in shared minutes — but the surrounding cast construction has never resolved the point guard question that has dogged this organization for four years. Austin Reaves's playmaking in the LeBron-Davis unit is doing connector work that should belong to a more traditional initiator, and the lineup data reflects the strain: Reaves's usage spikes to 28% in his best unit, which is 12 points higher than his optimal efficiency window. The death lineup is effective but fragile — Davis's closing-minute performance has been the league's most medically managed fourth-quarter role of any top-ten big, and the lineup splits in games where he logs under 38 minutes show a -2.1 net rating swing that no adjustment has compensated for.",
      bestUnit: {
        players: ["LeBron James", "Anthony Davis", "Austin Reaves", "Rui Hachimura", "D'Angelo Russell"],
        team: "LAL",
        minutesTogether: 296,
        netRating: 13.9,
        offRating: 116.4,
        defRating: 102.5,
        plusMinus: 139,
        record: "Equivalent to 57-25 pace",
        keyStrength: "LeBron's decision-making combined with Davis's interior gravity creates transition and half-court efficiency that no opponent can address with a single defensive scheme",
      },
      deathLineup: {
        players: ["LeBron James", "Anthony Davis", "Austin Reaves", "Rui Hachimura", "Jarred Vanderbilt"],
        team: "LAL",
        minutesTogether: 49,
        netRating: 11.6,
        offRating: 113.8,
        defRating: 102.2,
        plusMinus: 39,
        record: "12-10 in games when closing",
        keyStrength: "Vanderbilt's switchability and energy in closing situations provides the defensive credibility that allows LeBron to conserve decision-making bandwidth for offensive creation",
      },
      worstUnit: {
        players: ["D'Angelo Russell", "Gabe Vincent", "Max Christie", "Cole Swider", "Wenyen Gabriel"],
        team: "LAL",
        minutesTogether: 38,
        netRating: -12.1,
        offRating: 104.6,
        defRating: 116.7,
        plusMinus: -31,
        record: "Equivalent to 28-54 pace",
        keyStrength: "No credible strength — this is the league's most glaring evidence of the LeBron-Davis dependency: when both sit simultaneously, Los Angeles becomes a lottery-level unit",
      },
    },
    {
      team: "MIL",
      teamRecord: "46-36",
      narrative:
        "Milwaukee's lineup data is the East's most compelling underdog narrative heading into the playoff picture. Damian Lillard's partnership with Giannis Antetokounmpo has finally produced a best unit that is legitimately elite — +13.1 net rating, the East's fourth-best five-man combination — after two seasons of schematic friction that made the pairing feel like an organizational mistake. The adjustment has been Lillard operating in more off-ball situations in the first three quarters before assuming primary creation duties in fourth-quarter possessions, a role compression that has reduced his usage but improved his efficiency dramatically. Brook Lopez's rim protection remains the unit's defensive backbone, and the data shows his presence swings the Bucks' defensive rating by 8.2 points per 100 possessions when he's on versus off — the league's largest single-player defensive swing among non-Wembanyama big men.",
      bestUnit: {
        players: ["Giannis Antetokounmpo", "Damian Lillard", "Khris Middleton", "Brook Lopez", "Bobby Portis"],
        team: "MIL",
        minutesTogether: 278,
        netRating: 13.1,
        offRating: 115.8,
        defRating: 102.7,
        plusMinus: 124,
        record: "Equivalent to 56-26 pace",
        keyStrength: "Giannis's downhill creation combined with Lillard's off-ball shooting gravity has produced the East's most efficient pick-and-roll offense after two seasons of schematic adjustment",
      },
      deathLineup: {
        players: ["Giannis Antetokounmpo", "Damian Lillard", "Khris Middleton", "Brook Lopez", "Jrue Holiday"],
        team: "MIL",
        minutesTogether: 57,
        netRating: 12.4,
        offRating: 114.6,
        defRating: 102.2,
        plusMinus: 48,
        record: "12-11 in games when closing",
        keyStrength: "Lopez's shot-alteration combined with Holiday's perimeter discipline gives Milwaukee a closing defense with legitimate interior and perimeter credibility — the Bucks close better than their record suggests",
      },
      worstUnit: {
        players: ["AJ Green", "MarJon Beauchamp", "Thanasis Antetokounmpo", "Sandro Mamukelashvili", "Robin Lopez"],
        team: "MIL",
        minutesTogether: 34,
        netRating: -13.4,
        offRating: 103.9,
        defRating: 117.3,
        plusMinus: -31,
        record: "Equivalent to 26-56 pace",
        keyStrength: "No competitive function — the Bucks' reserve rotation behind the starting five is the East's thinnest depth chart among playoff-seeded teams",
      },
    },
  ],
};