// AUTO-GENERATED by scripts/sync-line-movement.mjs — do not edit by hand.

export interface LineMovementRow {
  awayTeam: string;
  homeTeam: string;
  openingSpread: string;
  closingSpread: string;
  updatedAt: string;
}

export const lineMovementEditionDate = "May 31, 2026";

export const lineMovementRows: LineMovementRow[] = [
  {
    awayTeam: "OKC",
    homeTeam: "SAS",
    openingSpread: "SAS -3.0",
    closingSpread: "SAS -4.5",
    updatedAt: "2026-06-05T09:20:58.997Z",
  }
];
