// AUTO-GENERATED by scripts/sync-line-movement.mjs — seed retained when slate is empty.

export interface LineOpenerArchiveGame {
  awayTeam: string;
  homeTeam: string;
  openingSpread: string;
  closingSpread?: string;
}

export interface LineOpenerArchiveEdition {
  editionDate: string;
  games: LineOpenerArchiveGame[];
}

/** Recent opener (and optional closer) snapshots for Betting Intel history. */
export const lineOpenersArchive: LineOpenerArchiveEdition[] = [
  {
    editionDate: "October 4, 2026",
    games: [
      {
        awayTeam: "BOS",
        homeTeam: "TOR",
        openingSpread: "TOR -1.0",
        closingSpread: "BOS -1.5",
      },
      {
        awayTeam: "HOU",
        homeTeam: "SAS",
        openingSpread: "SAS -4.5",
        closingSpread: "SAS -5.0",
      }
    ],
  }
];
