// AUTO-GENERATED by scripts/sync-line-movement.mjs — do not edit by hand.

export interface LineMovementRow {
  awayTeam: string;
  homeTeam: string;
  openingSpread: string;
  closingSpread: string;
  updatedAt: string;
}

export const lineMovementEditionDate = "October 3, 2026";

export const lineMovementRows: LineMovementRow[] = [
  {
    awayTeam: "MIA",
    homeTeam: "TOR",
    openingSpread: "TOR -1.0",
    closingSpread: "TOR -1.5",
    updatedAt: "2026-10-03T16:08:09.973Z",
  }
];
