// GENERATED by scripts/fetch-player-headshots.mjs — do not edit by hand.
// Maps a normalized player name (see normalizePlayerName) to their ESPN athlete id.
// Refreshed by the daily pipeline; empty until the first roster fetch runs in CI,
// where PlayerAvatar falls back to a team-colored initials crest.
export const playerHeadshotIds: Record<string, number> = {};
