// Auto-generated by generate-projections.mjs
// Week of August 3–9, 2026

export interface TeamProjection {
  team: string;
  conference: "east" | "west";
  currentWins: number;
  currentLosses: number;
  projectedWins: number;
  projectedLosses: number;
  winChange: number;
  playoffProb: number;
  championshipProb: number;
  remainingSOS: number;
  remainingSOSLabel: string;
  keyStretch: string;
  projection: string;
  narrative: string;
}

export interface PlayoffMatchup {
  round: string;
  highSeed: string;
  lowSeed: string;
  seriesProb: string;
  keyFactor: string;
}

export interface ProjectionsData {
  generatedDate: string;
  weekLabel: string;
  teams: TeamProjection[];
  projectedBracket: {
    east: PlayoffMatchup[];
    west: PlayoffMatchup[];
    finals: PlayoffMatchup;
  };
  biggestRiser: { team: string; change: string; reason: string };
  biggestFaller: { team: string; change: string; reason: string };
  weeklyNarrative: string;
}

export const projectionsData: ProjectionsData = {
  generatedDate: "August 3, 2026",
  weekLabel: "Week of August 3–9, 2026",
  weeklyNarrative:
    "The offseason's two defining gravitational events are converging this week. De'Aaron Fox's max signature in San Antonio is now hours, not days, away — completing the most consequential Western Conference roster construction since the Golden State dynasty era. Simultaneously, Isaiah Hartenstein's restricted free-agent clock continues ticking in New York, where matching rights make retention a near-certainty and the defending champion Knicks inch closer to a fully locked repeat roster. OKC's Week Two integration work on Shai Gilgeous-Alexander's supporting cast is the quieter but equally meaningful subplot: the Thunder are quietly assembling the architecture to challenge San Antonio's newly minted two-superstar core in what projects as the defining Western Conference rivalry of the next half-decade. The Eastern picture is comparatively settled — New York's championship DNA is intact and their biggest remaining variable, Hartenstein, trends toward resolution. The rest of the league is navigating a summer defined entirely by what San Antonio and Oklahoma City do next.",
  biggestRiser: {
    team: "SAS",
    change: "+3.8 championship probability points",
    reason:
      "Fox's imminent max signature — now at final documentation stage — is being priced in by projection models this week, vaulting San Antonio's title probability as the two-superstar core of Fox and Wembanyama moves from theoretical to contractually locked.",
  },
  biggestFaller: {
    team: "GSW",
    change: "-1.4 championship probability points",
    reason:
      "Golden State's offseason stagnation becomes more costly by the week as San Antonio and OKC accelerate roster construction; the Warriors have added no meaningful pieces to address their aging core's championship window, which narrows measurably with each passing August deadline.",
  },
  teams: [
    // ── WESTERN CONFERENCE ──────────────────────────────────────────────────
    {
      team: "OKC",
      conference: "west",
      currentWins: 64,
      currentLosses: 18,
      projectedWins: 64,
      projectedLosses: 18,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 22.4,
      remainingSOS: 12,
      remainingSOSLabel: "Average",
      keyStretch: "Three consecutive road games vs. playoff West teams in October",
      projection: "Finals",
      narrative:
        "Week Two of SGA's supporting cast integration is the organizational story beneath the Fox headlines — OKC's front office is quietly stress-testing lineup combinations that will define their ceiling come April. The Thunder enter this week as the Western Conference's most structurally sound franchise, with elite depth at every position and the league's best net rating over the past 30 games. Their championship probability holds steady at the top of the West, a reflection of a roster that needs no external moves to contend.",
    },
    {
      team: "SAS",
      conference: "west",
      currentWins: 62,
      currentLosses: 20,
      projectedWins: 62,
      projectedLosses: 20,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 28.1,
      remainingSOS: 8,
      remainingSOSLabel: "Tough",
      keyStretch: "Fox debut game vs. OKC — league's most-watched regular season opener",
      projection: "Finals",
      narrative:
        "Fox's max signature arriving at final documentation stage this week is the single event that reshapes every Western Conference projection model. San Antonio's championship probability surges to the top of all 30 teams the moment that ink dries, converting two years of Wembanyama-era promise into a fully operational two-superstar core. Castle's extension running on the same documentation timeline adds a third pillar to what is shaping up as the most complete young roster construction in a generation.",
    },
    {
      team: "MIN",
      conference: "west",
      currentWins: 54,
      currentLosses: 28,
      projectedWins: 54,
      projectedLosses: 28,
      winChange: -1,
      playoffProb: 100,
      championshipProb: 7.2,
      remainingSOS: 5,
      remainingSOSLabel: "Tough",
      keyStretch: "Six-game homestand to open October featuring two games vs. SAS",
      projection: "Conference Finals",
      narrative:
        "Minnesota's 54-win season positions them as the West's third-best team on paper, but their path to the Finals requires beating either OKC or San Antonio — a gauntlet that tempers their championship upside significantly. Anthony Edwards' continued ascent as a two-way force is the franchise's best argument for an upset, and their defensive infrastructure remains elite. The Fox signing in San Antonio creates a more difficult first-round-avoidance calculus for the Timberwolves as the standings compact behind the top two seeds.",
    },
    {
      team: "DEN",
      conference: "west",
      currentWins: 51,
      currentLosses: 31,
      projectedWins: 51,
      projectedLosses: 31,
      winChange: 1,
      playoffProb: 100,
      championshipProb: 6.8,
      remainingSOS: 17,
      remainingSOSLabel: "Average",
      keyStretch: "Back-to-back sets vs. Golden State and Phoenix in late October",
      projection: "Conference Finals",
      narrative:
        "Denver's Nikola Jokic remains the West's most reliable singular force, and the Nuggets' 51 wins reflect a team that wins despite injury disruptions rather than because of clean health. This week's projection holds steady as the team's offseason activity has been minimal — Jokic-centered continuity is the organizational philosophy and it has a proven track record. The gap between Denver and the top two Western seeds is real but not insurmountable in a playoff series.",
    },
    {
      team: "LAL",
      conference: "west",
      currentWins: 48,
      currentLosses: 34,
      projectedWins: 48,
      projectedLosses: 34,
      winChange: 0,
      playoffProb: 96,
      championshipProb: 5.1,
      remainingSOS: 22,
      remainingSOSLabel: "Easy",
      keyStretch: "Four straight road games through the Pacific Division in November",
      projection: "2nd Round",
      narrative:
        "Los Angeles enters the week as a solidly locked fifth seed, LeBron James' continued productivity defying every actuarial model in professional sports. The Lakers' championship ceiling is realistically capped by the quality gap between their core and the West's top two teams, but their playoff experience and James' postseason IQ make them a dangerous five or six seed. No significant offseason moves this week change their standing.",
    },
    {
      team: "GSW",
      conference: "west",
      currentWins: 46,
      currentLosses: 36,
      projectedWins: 46,
      projectedLosses: 36,
      winChange: -1,
      playoffProb: 91,
      championshipProb: 3.2,
      remainingSOS: 14,
      remainingSOSLabel: "Average",
      keyStretch: "Three-game series vs. OKC and SAS in the same week in December",
      projection: "1st Round Exit",
      narrative:
        "Golden State's offseason inertia is the week's most notable non-story, and that absence of activity is increasingly costly as the West's top teams accelerate construction. The Warriors' aging core — Curry, Thompson, and Green operating in what may be a final championship window together — faces a brutal early-round draw if seeding holds at sixth or lower. Their championship probability dips this week as San Antonio's Fox addition is priced in across the conference.",
    },
    {
      team: "PHX",
      conference: "west",
      currentWins: 44,
      currentLosses: 38,
      projectedWins: 44,
      projectedLosses: 38,
      winChange: 0,
      playoffProb: 85,
      championshipProb: 2.8,
      remainingSOS: 19,
      remainingSOSLabel: "Average",
      keyStretch: "Must-win stretch vs. Golden State and Sacramento in play-in window",
      projection: "1st Round Exit",
      narrative:
        "Phoenix's seventh-seed projection puts them squarely in the play-in conversation, and their championship ceiling is effectively zero unless Kevin Durant produces a historically dominant postseason carry job. The organization's ongoing front-office restructuring adds organizational noise to an already uncertain on-court outlook. This week brings no change to their trajectory — they are a fringe playoff team in a conference that has widened its quality gap at the top.",
    },
    {
      team: "SAC",
      conference: "west",
      currentWins: 43,
      currentLosses: 39,
      projectedWins: 43,
      projectedLosses: 39,
      winChange: 1,
      playoffProb: 78,
      championshipProb: 1.4,
      remainingSOS: 25,
      remainingSOSLabel: "Easy",
      keyStretch: "Six home games in October's first three weeks — favorable schedule start",
      projection: "1st Round Exit",
      narrative:
        "Sacramento's 43-win baseline reflects a team that has found its identity around De'Aaron Fox's absence — ironic timing given that Fox's signature elsewhere this week finalizes what was Sacramento's most significant roster evolution in decades. The Kings' front office has assembled a credible second-tier Western Conference team around Domantas Sabonis, but their ceiling without a genuine star creator is a first-round exit at best. Their easy remaining schedule is the week's brightest note.",
    },
    {
      team: "MEM",
      conference: "west",
      currentWins: 41,
      currentLosses: 41,
      projectedWins: 41,
      projectedLosses: 41,
      winChange: 0,
      playoffProb: 68,
      championshipProb: 0.9,
      remainingSOS: 9,
      remainingSOSLabel: "Tough",
      keyStretch: "Play-in positioning games vs. Phoenix and Sacramento in final two weeks",
      projection: "1st Round Exit",
      narrative:
        "Memphis sits at the .500 line with a play-in berth more likely than a locked top-eight seed, and Ja Morant's health entering training camp remains the single variable that most meaningfully changes their ceiling. The Grizzlies' defensive infrastructure is sound but their offensive gravity lives and dies with Morant's availability. A tough remaining schedule keeps their probability of moving up in the standings limited.",
    },
    {
      team: "NOP",
      conference: "west",
      currentWins: 36,
      currentLosses: 46,
      projectedWins: 36,
      projectedLosses: 46,
      winChange: 0,
      playoffProb: 18,
      championshipProb: 0.2,
      remainingSOS: 3,
      remainingSOSLabel: "Brutal",
      keyStretch: "Brutal four-game road swing through OKC, SAS, MIN, and DEN",
      projection: "1st Round Exit",
      narrative:
        "New Orleans' rebuilding posture has become explicit this summer, with Zion Williamson's future the only question mark that carries meaningful franchise valuation weight. Their play-in probability is low and their championship ceiling is effectively nil; this week's news cycle is entirely consumed by the Fox signing that bypassed them in the process. The Pelicans' lottery positioning is now the more relevant organizational storyline.",
    },
    {
      team: "DAL",
      conference: "west",
      currentWins: 38,
      currentLosses: 44,
      projectedWins: 38,
      projectedLosses: 44,
      winChange: -1,
      playoffProb: 29,
      championshipProb: 0.3,
      remainingSOS: 7,
      remainingSOSLabel: "Tough",
      keyStretch: "Five consecutive games vs. playoff-caliber opponents in November",
      projection: "1st Round Exit",
      narrative:
        "Dallas is navigating a transitional moment after the Luka Doncic era's complicated conclusion, and their 38-win projection reflects a team in active roster reconstruction rather than contention. Their play-in probability is modest and their championship ceiling this cycle is a first-round exit at best. The tough remaining schedule further limits their upside in the standings chase.",
    },
    {
      team: "UTA",
      conference: "west",
      currentWins: 22,
      currentLosses: 60,
      projectedWins: 22,
      projectedLosses: 60,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 1,
      remainingSOSLabel: "Brutal",
      keyStretch: "League's hardest projected schedule through December — lottery positioning at stake",
      projection: "1st Round Exit",
      narrative:
        "Utah's full-scale rebuild is progressing on plan, and their historically brutal remaining schedule is a feature, not a bug — lottery positioning is the organizational North Star. The Jazz have accumulated assets and cap space with disciplined patience, and the Fox signing in San Antonio removes one potential trade target from their board. This week brings no change to a rebuild that is operating exactly as designed.",
    },
    {
      team: "POR",
      conference: "west",
      currentWins: 28,
      currentLosses: 54,
      projectedWins: 28,
      projectedLosses: 54,
      winChange: 0,
      playoffProb: 2,
      championshipProb: 0.0,
      remainingSOS: 2,
      remainingSOSLabel: "Brutal",
      keyStretch: "Consecutive games vs. OKC, SAS, and MIN in the same week",
      projection: "1st Round Exit",
      narrative:
        "Portland's youth movement is the franchise's investment thesis, and Scoot Henderson's development arc remains the single most important data point the organization is tracking. Their win total is modest but intentional — the Trail Blazers are building toward a future that the Fox-Wembanyama era in San Antonio will soon define as their primary Western Conference standard. No playoff probability to speak of this week.",
    },
    {
      team: "HOU",
      conference: "west",
      currentWins: 45,
      currentLosses: 37,
      projectedWins: 45,
      projectedLosses: 37,
      winChange: 1,
      playoffProb: 88,
      championshipProb: 2.1,
      remainingSOS: 16,
      remainingSOSLabel: "Average",
      keyStretch: "Houston hosts OKC and SAS in the same week — defining early statement stretch",
      projection: "2nd Round",
      narrative:
        "Houston's 45-win season represents the Rockets' most credible playoff positioning in years, and Alperen Sengun's development as a legitimate All-Star center has accelerated their timeline meaningfully. They project as a six seed with genuine second-round upside depending on bracket positioning. The Fox signing in San Antonio creates a slightly more difficult divisional landscape but doesn't change Houston's fundamental trajectory this week.",
    },
    {
      team: "LAC",
      conference: "west",
      currentWins: 40,
      currentLosses: 42,
      projectedWins: 40,
      projectedLosses: 42,
      winChange: 0,
      playoffProb: 55,
      championshipProb: 0.5,
      remainingSOS: 21,
      remainingSOSLabel: "Easy",
      keyStretch: "Three home games vs. lottery teams in late October — must-bank wins",
      projection: "1st Round Exit",
      narrative:
        "The Clippers' 40-win projection places them in play-in territory, navigating a roster reset after the Kawhi Leonard era's final chapter. Their easy remaining schedule gives them a path to a locked playoff spot, but their championship ceiling is essentially zero without a transformative addition. This week is quiet for the organization — their offseason moves have been incremental and their trajectory is stable.",
    },
    // ── EASTERN CONFERENCE ──────────────────────────────────────────────────
    {
      team: "NYK",
      conference: "east",
      currentWins: 53,
      currentLosses: 29,
      projectedWins: 53,
      projectedLosses: 29,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 14.8,
      remainingSOS: 13,
      remainingSOSLabel: "Average",
      keyStretch: "Four-game road trip through Boston, Milwaukee, Cleveland, and Miami in November",
      projection: "Champion",
      narrative:
        "The defending champion Knicks' organizational week is defined by Hartenstein's restricted free-agent clock, which ticks toward near-certain retention given New York's matching rights and the absence of any rival offer sheet. Brunson's Finals MVP validation, Anunoby's defensive completeness, and a supporting cast of championship-tested role players give New York the East's most credible repeat architecture. Their championship probability remains the Eastern Conference's highest, a reflection of earned credentials rather than projection optimism.",
    },
    {
      team: "BOS",
      conference: "east",
      currentWins: 58,
      currentLosses: 24,
      projectedWins: 58,
      projectedLosses: 24,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 11.2,
      remainingSOS: 10,
      remainingSOSLabel: "Tough",
      keyStretch: "Back-to-back vs. New York in October — early East hierarchy statement",
      projection: "Finals",
      narrative:
        "Boston's 58-win season is the East's best record and positions them as the conference's top seed entering a summer with minimal roster disruption. Jayson Tatum and Jaylen Brown remain the East's most proven two-way co-star pairing outside of New York, and the Celtics' depth gives them the longest potential winning streak ceiling of any Eastern team. Their championship probability sits second in the East, but the path to the Finals requires navigating New York in a potential conference finals rematch.",
    },
    {
      team: "MIL",
      conference: "east",
      currentWins: 49,
      currentLosses: 33,
      projectedWins: 49,
      projectedLosses: 33,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 5.4,
      remainingSOS: 18,
      remainingSOSLabel: "Average",
      keyStretch: "Giannis availability status entering October training camp — week's key watch",
      projection: "Conference Finals",
      narrative:
        "Milwaukee's 49-win projection is built around Giannis Antetokounmpo's continued force-of-nature dominance, and their Eastern Conference Finals ceiling is genuine if their depth holds through the spring. Damian Lillard's two-way impact remains a critical variable — his health in the back half of the season has been the Bucks' most consistent limiting factor in recent years. No offseason movement this week changes their structural position in the East.",
    },
    {
      team: "CLE",
      conference: "east",
      currentWins: 52,
      currentLosses: 30,
      projectedWins: 52,
      projectedLosses: 30,
      winChange: 1,
      playoffProb: 100,
      championshipProb: 4.6,
      remainingSOS: 20,
      remainingSOSLabel: "Average",
      keyStretch: "Five home games in the first three weeks of October — strong positioning start",
      projection: "Conference Finals",
      narrative:
        "Cleveland's 52 wins represent the East's fourth-best record and reflect a team that has built genuine conference final contention around Donovan Mitchell's elite scoring and Evan Mobley's defensive anchor. Their championship ceiling requires Boston or New York to fall in an upset, which is possible but not probable. The Cavaliers' organizational stability is a genuine strength — no roster drama, no offseason noise, just a team that wins at a predictable and high rate.",
    },
    {
      team: "IND",
      conference: "east",
      currentWins: 46,
      currentLosses: 36,
      projectedWins: 46,
      projectedLosses: 36,
      winChange: 0,
      playoffProb: 93,
      championshipProb: 2.9,
      remainingSOS: 23,
      remainingSOSLabel: "Easy",
      keyStretch: "Favorable October schedule — three home games vs. lottery-bound East teams",
      projection: "2nd Round",
      narrative:
        "Indiana's Tyrese Haliburton-led core has produced its most consistent winning season, and their 46-win projection reflects a team that is genuinely dangerous in a five-versus-four first-round matchup. Their championship ceiling is realistically capped at the second round absent a dominant Haliburton postseason performance, but their pace-and-space offense makes them the East's most difficult stylistic matchup for any of the top seeds. No offseason movement this week.",
    },
    {
      team: "MIA",
      conference: "east",
      currentWins: 44,
      currentLosses: 38,
      projectedWins: 44,
      projectedLosses: 38,
      winChange: 0,
      playoffProb: 87,
      championshipProb: 2.3,
      remainingSOS: 15,
      remainingSOSLabel: "Average",
      keyStretch: "Heat culture November road trip — four games in five nights vs. East contenders",
      projection: "2nd Round",
      narrative:
        "Miami's Heat Culture infrastructure gives them a perennial postseason floor that their raw win total sometimes understates, and their 44-win projection locks them into a six seed with second-round potential. Bam Adebayo's two-way dominance anchors a team that has beaten better teams on paper in the postseason before. This week brings no organizational changes — the Heat are quietly preparing for another October-to-April grind.",
    },
    {
      team: "PHI",
      conference: "east",
      currentWins: 41,
      currentLosses: 41,
      projectedWins: 41,
      projectedLosses: 41,
      winChange: -1,
      playoffProb: 71,
      championshipProb: 1.1,
      remainingSOS: 11,
      remainingSOSLabel: "Tough",
      keyStretch: "Embiid health status entering training camp — defining the entire season's ceiling",
      projection: "1st Round Exit",
      narrative:
        "Philadelphia's .500 projection is an honest assessment of a team whose ceiling is entirely determined by Joel Embiid's availability — when healthy, a legitimate Conference Finals threat; when compromised, a first-round liability. Their tough remaining schedule is the week's most concerning data point for a team that cannot afford to drop games in the East's competitive middle tier. No offseason additions have addressed their supporting cast depth concerns.",
    },
    {
      team: "ATL",
      conference: "east",
      currentWins: 38,
      currentLosses: 44,
      projectedWins: 38,
      projectedLosses: 44,
      winChange: 0,
      playoffProb: 42,
      championshipProb: 0.6,
      remainingSOS: 26,
      remainingSOSLabel: "Easy",
      keyStretch: "Play-in survival games vs. Chicago and Toronto in the final two weeks",
      projection: "1st Round Exit",
      narrative:
        "Atlanta's Trae Young remains the team's most tradeable asset and most irreplaceable offensive engine simultaneously, a paradox that has defined the franchise's direction for three seasons. Their 38-win projection places them in play-in range, and their easy remaining schedule gives them a genuine path to locking a seven or eight seed. Championship upside is essentially nil, but playoff relevance is achievable.",
    },
    {
      team: "CHI",
      conference: "east",
      currentWins: 35,
      currentLosses: 47,
      projectedWins: 35,
      projectedLosses: 47,
      winChange: 0,
      playoffProb: 28,
      championshipProb: 0.2,
      remainingSOS: 27,
      remainingSOSLabel: "Easy",
      keyStretch: "Must-win play-in positioning stretch vs. Atlanta and Toronto",
      projection: "1st Round Exit",
      narrative:
        "Chicago's post-DeMar DeRozan transition has produced a credible young core but not yet a team with reliable playoff positioning. Their 35-win projection puts them on the fringe of play-in contention, and their easy remaining schedule is the most important factor in whether they make the postseason at all. No significant offseason activity this week changes their calculus.",
    },
    {
      team: "TOR",
      conference: "east",
      currentWins: 32,
      currentLosses: 50,
      projectedWins: 32,
      projectedLosses: 50,
      winChange: 0,
      playoffProb: 12,
      championshipProb: 0.1,
      remainingSOS: 28,
      remainingSOSLabel: "Easy",
      keyStretch: "Favorable final month schedule — potential lottery vs. play-in swing games",
      projection: "1st Round Exit",
      narrative:
        "Toronto's rebuild is in active progress, with Scottie Barnes' development as the franchise cornerstone the most important organizational story heading into training camp. Their 32-win projection is consistent with a team that is more invested in asset accumulation than playoff positioning. The easy remaining schedule creates a interesting question about tanking vs. development philosophy that will define their October approach.",
    },
    {
      team: "BKN",
      conference: "east",
      currentWins: 24,
      currentLosses: 58,
      projectedWins: 24,
      projectedLosses: 58,
      winChange: 0,
      playoffProb: 1,
      championshipProb: 0.0,
      remainingSOS: 4,
      remainingSOSLabel: "Brutal",
      keyStretch: "Brutal November gauntlet — six games vs. top-four East teams in 10 days",
      projection: "1st Round Exit",
      narrative:
        "Brooklyn's full-scale rebuild is the East's most clearly defined lottery operation, and their brutal remaining schedule is entirely consistent with an organization that prioritizes future draft capital over present wins. No offseason activity this week changes their trajectory — the Nets are building toward a future that is several years away. Their lottery odds are the franchise's most important current statistic.",
    },
    {
      team: "WAS",
      conference: "east",
      currentWins: 20,
      currentLosses: 62,
      projectedWins: 20,
      projectedLosses: 62,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 6,
      remainingSOSLabel: "Tough",
      keyStretch: "Schedule is irrelevant — lottery positioning is the only metric that matters",
      projection: "1st Round Exit",
      narrative:
        "Washington's 20-win season represents the Eastern Conference's most difficult rebuilding situation, and their organization's patient asset accumulation strategy is the only credible path forward. No offseason activity this week is meaningful beyond draft positioning. The Wizards are multiple years from relevance in any competitive Eastern Conference conversation.",
    },
    {
      team: "ORL",
      conference: "east",
      currentWins: 43,
      currentLosses: 39,
      projectedWins: 43,
      projectedLosses: 39,
      winChange: 1,
      playoffProb: 82,
      championshipProb: 1.7,
      remainingSOS: 24,
      remainingSOSLabel: "Easy",
      keyStretch: "Favorable October home schedule — six of first eight games at home",
      projection: "1st Round Exit",
      narrative:
        "Orlando's Paolo Banchero-led core has produced the franchise's most credible playoff positioning in over a decade, and their 43-win projection locks them into a seven or eight seed depending on tiebreakers. Their easy remaining schedule this week is the most positive organizational note — banking wins against inferior opponents sets up a healthier October position. First-round exit is the realistic ceiling without a Banchero postseason leap.",
    },
    {
      team: "CHA",
      conference: "east",
      currentWins: 26,
      currentLosses: 56,
      projectedWins: 26,
      projectedLosses: 56,
      winChange: 0,
      playoffProb: 3,
      championshipProb: 0.0,
      remainingSOS: 29,
      remainingSOSLabel: "Easy",
      keyStretch: "Young core development games — LaMelo Ball health status the key watch",
      projection: "1st Round Exit",
      narrative:
        "Charlotte's 26-win projection reflects a team caught between rebuild and competition, with LaMelo Ball's health and engagement level the most meaningful variable in either direction. Their extremely easy remaining schedule does not change their championship ceiling but does provide development minutes for a young core that needs game experience. No offseason activity this week is organizationally significant.",
    },
    {
      team: "DET",
      conference: "east",
      currentWins: 39,
      currentLosses: 43,
      projectedWins: 39,
      projectedLosses: 43,
      winChange: 1,
      playoffProb: 58,
      championshipProb: 0.8,
      remainingSOS: 30,
      remainingSOSLabel: "Cupcake",
      keyStretch: "Easiest remaining schedule in the league — Detroit must bank these wins",
      projection: "1st Round Exit",
      narrative:
        "Detroit's unexpected 39-win season has produced genuine playoff conversation, and Cade Cunningham's emergence as a legitimate All-Star has accelerated the franchise's rebuild timeline meaningfully. Their cupcake remaining schedule — the league's easiest — is this week's most actionable data point: if the Pistons cannot add wins now, their October positioning suffers. First-round exit is the realistic ceiling but the organizational momentum is genuinely positive.",
    },
  ],
  projectedBracket: {
    east: [
      // First Round
      {
        round: "First Round",
        highSeed: "BOS",
        lowSeed: "DET",
        seriesProb: "BOS in 5",
        keyFactor:
          "Boston's length and defensive versatility overwhelm a Detroit team that lacks the playoff experience to compete at this level for a full series.",
      },
      {
        round: "First Round",
        highSeed: "NYK",
        lowSeed: "ORL",
        seriesProb: "NYK in 4",
        keyFactor:
          "The defending champion Knicks' championship DNA and Brunson's Finals MVP pedigree give them a decisive edge against a young Orlando team in its first significant postseason test.",
      },
      {
        round: "First Round",
        highSeed: "CLE",
        lowSeed: "MIA",
        seriesProb: "CLE in 6",
        keyFactor:
          "Donovan Mitchell's elite scoring volume overwhelms Miami's defensive scheme over six games, though Heat Culture ensures this series extends beyond five.",
      },
      {
        round: "First Round",
        highSeed: "MIL",
        lowSeed: "IND",
        seriesProb: "MIL in 6",
        keyFactor:
          "Giannis Antetokounmpo's physical dominance creates mismatches that Indiana's pace-and-space system cannot solve, though Haliburton keeps the Pacers competitive throughout.",
      },
      // Second Round
      {
        round: "Second Round",
        highSeed: "BOS",
        lowSeed: "CLE",
        seriesProb: "BOS in 7",
        keyFactor:
          "A physically punishing seven-game series resolved by Boston's superior depth and Tatum's clutch-time advantage over Mitchell in the deciding game.",
      },
      {
        round: "Second Round",
        highSeed: "NYK",
        lowSeed: "MIL",
        seriesProb: "NYK in 6",
        keyFactor:
          "Anunoby's defensive assignment on Giannis — the most demanding in basketball — replicates the Fox containment blueprint from the Finals, neutralizing Milwaukee's primary weapon.",
      },
      // Conference Finals
      {
        round: "Conference Finals",
        highSeed: "NYK",
        lowSeed: "BOS",
        seriesProb: "NYK in 7",
        keyFactor:
          "Brunson's Finals MVP poise and the Knicks' championship experience prove decisive in a seven-game East Finals rematch that goes the distance before New York's depth wins the finale.",
      },
    ],
    west: [
      // First Round
      {
        round: "First Round",
        highSeed: "OKC",
        lowSeed: "GSW",
        seriesProb: "OKC in 5",
        keyFactor:
          "SGA's supporting cast integration work from this week pays immediate dividends as OKC's depth overwhelms Golden State's aging core across five games.",
      },
      {
        round: "First Round",
        highSeed: "SAS",
        lowSeed: "SAC",
        seriesProb: "SAS in 4",
        keyFactor:
          "Fox's first playoff series in a Spurs uniform — opposite his former team — becomes a statement sweep as Wembanyama's defensive dominance renders Sacramento's offense non-functional.",
      },
      {
        round: "First Round",
        highSeed: "MIN",
        lowSeed: "LAL",
        seriesProb: "MIN in 6",
        keyFactor:
          "Minnesota's elite defensive infrastructure limits LeBron James' ability to carry the Lakers offensively for six games, and Edwards outduels James in the series' decisive moments.",
      },
      {
        round: "First Round",
        highSeed: "DEN",
        lowSeed: "HOU",
        seriesProb: "DEN in 6",
        keyFactor:
          "Jokic's positional advantage over Sengun in the pivot — the more experienced and decorated player winning the center matchup that defines the series.",
      },
      // Second Round
      {
        round: "Second Round",
        highSeed: "OKC",
        lowSeed: "DEN",
        seriesProb: "OKC in 6",
        keyFactor:
          "Oklahoma City's depth and SGA's two-way superiority over Denver's aging supporting cast prove decisive, though Jokic extends the series with two vintage triple-double performances.",
      },
      {
        round: "Second Round",
        highSeed: "SAS",
        lowSeed: "MIN",
        seriesProb: "SAS in 6",
        keyFactor:
          "The Fox-Wembanyama two-man game creates defensive problems that Minnesota's scheme has no answer for — Wembanyama's rim protection neutralizes Edwards' drives while Fox punishes every closeout.",
      },
      // Conference Finals
      {
        round: "Conference Finals",
        highSeed: "OKC",
        lowSeed: "SAS",
        seriesProb: "SAS in 7",
        keyFactor:
          "Fox's playoff hunger and Wembanyama's generational skill set prove marginally superior to OKC's depth in a seven-game instant classic that defines the Western Conference's next decade of hierarchy.",
      },
    ],
    finals: {
      round: "NBA Finals",
      highSeed: "NYK",
      lowSeed: "SAS",
      seriesProb: "NYK in 7",
      keyFactor:
        "Brunson's Finals MVP pedigree, Anunoby's defensive assignment on Fox, and the Knicks' championship experience give New York the decisive edge in a seven-game series for the ages — San Antonio's newly assembled core pushes the defending champions to the limit but cannot overcome New York's institutional knowledge of winning in June.",
    },
  },
};