// Auto-generated by generate-projections.mjs
// Week of April 20–26, 2026

export interface TeamProjection {
  team: string;
  conference: "east" | "west";
  currentWins: number;
  currentLosses: number;
  projectedWins: number;
  projectedLosses: number;
  winChange: number;
  playoffProb: number;
  championshipProb: number;
  remainingSOS: number;
  remainingSOSLabel: string;
  keyStretch: string;
  projection: string;
  narrative: string;
}

export interface PlayoffMatchup {
  round: string;
  highSeed: string;
  lowSeed: string;
  seriesProb: string;
  keyFactor: string;
}

export interface ProjectionsData {
  generatedDate: string;
  weekLabel: string;
  teams: TeamProjection[];
  projectedBracket: {
    east: PlayoffMatchup[];
    west: PlayoffMatchup[];
    finals: PlayoffMatchup;
  };
  biggestRiser: { team: string; change: string; reason: string };
  biggestFaller: { team: string; change: string; reason: string };
  weeklyNarrative: string;
}

export const projectionsData: ProjectionsData = {
  generatedDate: "April 20, 2026",
  weekLabel: "Week of April 20–26, 2026",
  weeklyNarrative:
    "The final week of the regular season is delivering seismic storylines. Oklahoma City and San Antonio are in a dead sprint for the West's top seed, separated by just two games as both juggernauts close out their schedules. In the East, Detroit's stunning home loss to Orlando on Sunday night injected chaos into the top-seed race, while Boston watches calmly from a comfortable 57-26 perch. The Magic's 46-37 record is suddenly very alive in the playoff picture after Paolo Banchero's career-high 31-point masterpiece reminded the league he belongs in the conversation with the East's elite. Portland and Philadelphia sit in genuine danger of missing or sliding in the postseason standings, while the Western Conference play-in picture is an absolute war. All eyes now turn to whether OKC can hold off Wembanyama's Spurs, and whether Detroit's flat performance against Orlando was a one-night anomaly or a worrying trend heading into the playoffs.",
  biggestRiser: {
    team: "ORL",
    change: "+3 projected wins",
    reason:
      "Paolo Banchero's career-high 31-point road upset of conference-leading Detroit, paired with Franz Wagner's efficient 23-point complement, vaulted Orlando's remaining-schedule outlook and dramatically boosted their playoff seeding probability after a performance that announced their arrival as a genuine playoff threat.",
  },
  biggestFaller: {
    team: "DET",
    change: "-2 projected wins",
    reason:
      "The Pistons' shocking home loss to Orlando — coupled with Cade Cunningham's below-par 43.5% shooting efficiency — has rattled confidence in Detroit's top-seed standing and raised serious questions about their defensive execution and mental composure heading into the postseason.",
  },
  teams: [
    // ── EASTERN CONFERENCE ──────────────────────────────────────────
    {
      team: "BOS",
      conference: "east",
      currentWins: 57,
      currentLosses: 26,
      projectedWins: 60,
      projectedLosses: 22,
      winChange: 1,
      playoffProb: 100,
      championshipProb: 22.4,
      remainingSOS: 22,
      remainingSOSLabel: "Easy",
      keyStretch:
        "Closes with CHI, WAS, IND — a soft runway to lock up the 2-seed",
      projection: "Champion",
      narrative:
        "Tatum's 35-point, 7-three-pointer demolition of Philadelphia this week was a statement of intent — Boston doesn't just want to win the East, they want to embarrass the competition doing it. With the second-best record in the East and a favorable closing schedule, the Celtics are peaking at the right time. Jaylen Brown's complementary efficiency and the team's blowout margin suggest a well-oiled machine ready for a deep playoff run.",
    },
    {
      team: "DET",
      conference: "east",
      currentWins: 60,
      currentLosses: 23,
      projectedWins: 62,
      projectedLosses: 20,
      winChange: -2,
      playoffProb: 100,
      championshipProb: 18.1,
      remainingSOS: 8,
      remainingSOSLabel: "Tough",
      keyStretch:
        "Remaining games vs. MIL and IND provide crucial seeding battle tests",
      projection: "Finals",
      narrative:
        "Sunday's home upset loss to Orlando was a genuine alarm bell — Cade Cunningham's 43.5% shooting and the team's flat energy raised uncomfortable questions about Detroit's ability to lock in for 48 minutes. The Pistons still hold the East's top seed by a thin margin but their remaining schedule is tougher than Boston's. Cunningham needs to rediscover his shooting efficiency immediately, or this stumble could define how the East bracket shakes out.",
    },
    {
      team: "MIL",
      conference: "east",
      currentWins: 52,
      currentLosses: 31,
      projectedWins: 54,
      projectedLosses: 28,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 7.8,
      remainingSOS: 14,
      remainingSOSLabel: "Average",
      keyStretch: "Back-to-back vs. DET and BOS will define final seeding",
      projection: "Conference Finals",
      narrative:
        "Milwaukee has quietly held the 3-seed while the top of the East drama unfolded around them this week. Giannis Antetokounmpo's steady presence keeps the Bucks dangerous regardless of seeding, and their average remaining schedule gives them a clean path to close strong. The matchup everyone fears is Giannis vs. a banged-up Philly squad in round one — Milwaukee should advance handily from there.",
    },
    {
      team: "IND",
      conference: "east",
      currentWins: 49,
      currentLosses: 34,
      projectedWins: 51,
      projectedLosses: 31,
      winChange: 1,
      playoffProb: 100,
      championshipProb: 5.2,
      remainingSOS: 18,
      remainingSOSLabel: "Average",
      keyStretch: "Three of final five games at home — seeding momentum intact",
      projection: "2nd Round",
      narrative:
        "Indiana continues to quietly rack up wins with Tyrese Haliburton orchestrating one of the league's most efficient offenses. The Pacers benefit from this week's East chaos — Detroit's stumble means Indiana's 4-seed is safe barring a collapse. Their second-round ceiling depends heavily on whether they draw Boston or Detroit, and right now that bracket calculus looks increasingly favorable.",
    },
    {
      team: "ORL",
      conference: "east",
      currentWins: 46,
      currentLosses: 37,
      projectedWins: 48,
      projectedLosses: 34,
      winChange: 3,
      playoffProb: 94,
      championshipProb: 3.1,
      remainingSOS: 25,
      remainingSOSLabel: "Easy",
      keyStretch:
        "Final stretch features CHA and WAS — Magic control their own destiny",
      projection: "1st Round Exit",
      narrative:
        "Paolo Banchero's career-high 31-point road dismantling of conference-leader Detroit was the defining performance of this week and perhaps of the Magic's entire season. The young superstar's arrival has been officially announced, and Franz Wagner's complementary 23-point effort showed Orlando has real playoff-caliber depth. With an easy remaining schedule, the Magic are locked in as the 5-seed and enter the postseason riding a genuine wave of momentum.",
    },
    {
      team: "NYK",
      conference: "east",
      currentWins: 48,
      currentLosses: 35,
      projectedWins: 50,
      projectedLosses: 32,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 4.6,
      remainingSOS: 16,
      remainingSOSLabel: "Average",
      keyStretch: "Road trip through ATL and MIA looms in final week",
      projection: "2nd Round",
      narrative:
        "New York enters playoff week in familiar Knicks fashion — good enough to be dangerous, inconsistent enough to keep fans anxious. Jalen Brunson has steadied the ship after a mid-season wobble, and the Knicks' physicality makes them a nightmare matchup in a short series. Securing the 4-seed ahead of Indiana would be meaningful, but this week's road trip could go either way.",
    },
    {
      team: "MIA",
      conference: "east",
      currentWins: 44,
      currentLosses: 39,
      projectedWins: 46,
      projectedLosses: 36,
      winChange: -1,
      playoffProb: 89,
      championshipProb: 2.3,
      remainingSOS: 11,
      remainingSOSLabel: "Tough",
      keyStretch:
        "Brutal closing stretch vs. NYK and MIL threatens play-in slide",
      projection: "1st Round Exit",
      narrative:
        "Miami's playoff résumé is built on grit and Erik Spoelstra's genius, but the Heat have looked sluggish over their last ten games and their remaining schedule is unforgiving. A loss to the Knicks this week would virtually lock them into play-in territory, which given Miami's postseason pedigree could still be dangerous. The Heat culture demands a response, and this week will tell us whether this group still has the championship DNA.",
    },
    {
      team: "ATL",
      conference: "east",
      currentWins: 41,
      currentLosses: 42,
      projectedWins: 43,
      projectedLosses: 39,
      winChange: 0,
      playoffProb: 72,
      championshipProb: 0.8,
      remainingSOS: 20,
      remainingSOSLabel: "Easy",
      keyStretch:
        "Favorable close vs. CHA and WAS — play-in spot nearly secure",
      projection: "1st Round Exit",
      narrative:
        "Atlanta has played itself into a comfortable play-in position behind Trae Young's scoring exploits, but the Hawks remain a team of unfulfilled potential. Their easy remaining schedule should secure a play-in spot, though advancing past the first round in any format seems a tall order given their defensive deficiencies. This week is about locking up positioning rather than making any bold statements.",
    },
    {
      team: "PHI",
      conference: "east",
      currentWins: 45,
      currentLosses: 38,
      projectedWins: 46,
      projectedLosses: 36,
      winChange: -2,
      playoffProb: 96,
      championshipProb: 1.4,
      remainingSOS: 7,
      remainingSOSLabel: "Tough",
      keyStretch:
        "Final week includes MIL and NYK — seeding and health both at risk",
      projection: "1st Round Exit",
      narrative:
        "Boston's 32-point humiliation of Philadelphia was a sobering reality check — Joel Embiid's 47.4% shooting and the team's inability to even make the game competitive exposed real depth concerns. The 76ers sit in an awkward spot: good enough to make the playoffs, not healthy or deep enough to go far. Embiid needs a strong closing week both to boost his own confidence and to send a warning shot to whoever draws them in round one.",
    },
    {
      team: "CHI",
      conference: "east",
      currentWins: 38,
      currentLosses: 45,
      projectedWins: 39,
      projectedLosses: 43,
      winChange: 0,
      playoffProb: 48,
      championshipProb: 0.3,
      remainingSOS: 27,
      remainingSOSLabel: "Cupcake",
      keyStretch:
        "Cupcake schedule to close — play-in spot depends on ATL result",
      projection: "1st Round Exit",
      narrative:
        "Chicago's season has been defined by inconsistency, but a cupcake closing schedule gives them a legitimate shot at sneaking into the play-in. DeMar DeRozan has shown flashes of his vintage self down the stretch, and the Bulls' veteran experience could make them a dangerous play-in opponent. This week is essentially a must-win scenario to stay mathematically relevant.",
    },
    {
      team: "CLE",
      conference: "east",
      currentWins: 47,
      currentLosses: 36,
      projectedWins: 49,
      projectedLosses: 33,
      winChange: 1,
      playoffProb: 100,
      championshipProb: 3.8,
      remainingSOS: 17,
      remainingSOSLabel: "Average",
      keyStretch: "Home games vs. CHI and TOR — Cavaliers in firm control",
      projection: "2nd Round",
      narrative:
        "Cleveland has been one of the East's most quietly consistent teams, and Donovan Mitchell's health heading into the playoffs is the primary variable determining their ceiling. The Cavaliers' defense has been elite all season, and their average remaining schedule should allow them to coast into the 5-6 range. A potential matchup with Orlando would be fascinating — two young, hungry teams with something to prove.",
    },
    {
      team: "TOR",
      conference: "east",
      currentWins: 33,
      currentLosses: 50,
      projectedWins: 34,
      projectedLosses: 48,
      winChange: 0,
      playoffProb: 8,
      championshipProb: 0.1,
      remainingSOS: 24,
      remainingSOSLabel: "Easy",
      keyStretch: "Lottery positioning matters more than wins this week",
      projection: "1st Round Exit",
      narrative:
        "Toronto is firmly in tank mode, and this week's games are more about draft lottery odds than playoff positioning. The Raptors' young core has shown enough promise to be excited about the future, but the present is a difficult watch. Their easy remaining schedule ironically hurts their lottery odds — expect load management to factor into their final week decisions.",
    },
    {
      team: "BKN",
      conference: "east",
      currentWins: 28,
      currentLosses: 55,
      projectedWins: 29,
      projectedLosses: 53,
      winChange: -1,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 29,
      remainingSOSLabel: "Cupcake",
      keyStretch: "Final stretch is all about securing top-four lottery odds",
      projection: "1st Round Exit",
      narrative:
        "Brooklyn's rebuild is in full swing, and the Nets are wisely focused on lottery positioning as the regular season winds down. Their cupcake schedule closes out what has been a difficult but necessary transitional year. The bright spot is a potential lottery pick that could accelerate their rebuild timeline significantly.",
    },
    {
      team: "WAS",
      conference: "east",
      currentWins: 22,
      currentLosses: 61,
      projectedWins: 23,
      projectedLosses: 59,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 30,
      remainingSOSLabel: "Cupcake",
      keyStretch: "Season finale games are glorified scrimmages at this point",
      projection: "1st Round Exit",
      narrative:
        "Washington's season has been a painful lottery exercise, and with the worst record in the East, they are well-positioned for a top-two pick. The Wizards have played their young players meaningful minutes all season, which will pay dividends when the rebuild accelerates. This week's games are essentially extended auditions for roster spots next season.",
    },
    {
      team: "CHA",
      conference: "east",
      currentWins: 25,
      currentLosses: 58,
      projectedWins: 26,
      projectedLosses: 56,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 28,
      remainingSOSLabel: "Cupcake",
      keyStretch: "Young players get final audition minutes in meaningless games",
      projection: "1st Round Exit",
      narrative:
        "Charlotte continues to develop their young core in a lost season, though the development of their young frontcourt has been genuinely encouraging. Their lottery positioning is secure, and the focus now shifts entirely to player development and draft preparation. LaMelo Ball's health heading into next year remains the franchise's most pressing question.",
    },

    // ── WESTERN CONFERENCE ──────────────────────────────────────────
    {
      team: "OKC",
      conference: "west",
      currentWins: 65,
      currentLosses: 18,
      projectedWins: 68,
      projectedLosses: 14,
      winChange: 2,
      playoffProb: 100,
      championshipProb: 19.6,
      remainingSOS: 12,
      remainingSOSLabel: "Tough",
      keyStretch:
        "Final three games include SAS — a de facto top-seed playoff",
      projection: "Champion",
      narrative:
        "SGA's 29-point, 64.7% shooting masterclass in a 35-point destruction of Phoenix was the perfect response to any doubters — Oklahoma City is playing its best basketball of the season at the perfect moment. Chet Holmgren's efficient 22-point complement showed the Thunder have genuine two-way depth beyond their superstar. The looming matchup with San Antonio this week is essentially a one-game playoff for the West's top seed, and the Thunder enter it with the better recent momentum.",
    },
    {
      team: "SAS",
      conference: "west",
      currentWins: 63,
      currentLosses: 20,
      projectedWins: 66,
      projectedLosses: 16,
      winChange: 2,
      playoffProb: 100,
      championshipProb: 17.3,
      remainingSOS: 6,
      remainingSOSLabel: "Tough",
      keyStretch:
        "OKC clash this week is the season's biggest remaining game in the West",
      projection: "Finals",
      narrative:
        "Wembanyama's 24-point, 11-rebound, 4-block two-way dominance in a controlled win over Portland is exactly the statement the Spurs needed heading into their showdown with Oklahoma City. The 7-foot-4 phenomenon continues to make the impossible look routine, and San Antonio's championship ceiling feels real in a way that still surprises observers given how recently this team was in full rebuild mode. The OKC game this week will define the West's entire playoff bracket.",
    },
    {
      team: "DEN",
      conference: "west",
      currentWins: 54,
      currentLosses: 29,
      projectedWins: 56,
      projectedLosses: 26,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 9.4,
      remainingSOS: 15,
      remainingSOSLabel: "Average",
      keyStretch: "Three home games to close — Nuggets can rest Jokic strategically",
      projection: "Conference Finals",
      narrative:
        "Nikola Jokic's triple-double machine keeps humming, and Denver enters the final week locked into the West's 3-seed with enough cushion to manage minutes strategically. The Nuggets' championship experience from their 2023 title run gives them a psychological edge that younger Western contenders simply haven't earned yet. Health is the variable — if Jokic enters the playoffs at full strength, Denver is everyone's dark-horse Finals pick.",
    },
    {
      team: "MIN",
      conference: "west",
      currentWins: 51,
      currentLosses: 32,
      projectedWins: 53,
      projectedLosses: 29,
      winChange: 1,
      playoffProb: 100,
      championshipProb: 6.1,
      remainingSOS: 19,
      remainingSOSLabel: "Average",
      keyStretch: "Road game at DEN tests their 4-seed security",
      projection: "2nd Round",
      narrative:
        "Minnesota's defensive identity under Chris Finch continues to be elite, and Anthony Edwards has elevated his game to genuine star level down the stretch. The Timberwolves are one of the scariest 4-seeds in recent memory — their length and athleticism create matchup problems for every Western contender. A potential second-round clash with either OKC or SAS would be a genuine litmus test.",
    },
    {
      team: "LAC",
      conference: "west",
      currentWins: 49,
      currentLosses: 34,
      projectedWins: 51,
      projectedLosses: 31,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 3.7,
      remainingSOS: 13,
      remainingSOSLabel: "Tough",
      keyStretch:
        "Closing games vs. PHX and GSW are vital for 5-seed positioning",
      projection: "2nd Round",
      narrative:
        "The Clippers have been one of the West's most resilient teams this season, grinding out wins with depth and defensive versatility even without a clear superstar. Their tough closing schedule is a final exam that will tell us a great deal about their playoff readiness. If they can hold the 5-seed, a first-round matchup against Denver is winnable in an upset — and the Clippers' front office knows it.",
    },
    {
      team: "GSW",
      conference: "west",
      currentWins: 46,
      currentLosses: 37,
      projectedWins: 48,
      projectedLosses: 34,
      winChange: -1,
      playoffProb: 97,
      championshipProb: 2.9,
      remainingSOS: 9,
      remainingSOSLabel: "Tough",
      keyStretch:
        "Three of five remaining games are on the road — seeding at risk",
      projection: "1st Round Exit",
      narrative:
        "Golden State's veteran core is showing signs of age in a brutal Western Conference, but Stephen Curry's gravity and the organization's playoff experience make them dangerous regardless of seeding. Their tough remaining schedule could slide them into play-in territory, which given the Warriors' historical comfort with pressure, may not be the disaster it sounds. The bigger question is whether this group has one more deep run left in the tank.",
    },
    {
      team: "PHX",
      conference: "west",
      currentWins: 43,
      currentLosses: 40,
      projectedWins: 44,
      projectedLosses: 38,
      winChange: -2,
      playoffProb: 82,
      championshipProb: 1.2,
      remainingSOS: 4,
      remainingSOSLabel: "Brutal",
      keyStretch:
        "OKC blowout hangover meets a brutal schedule — play-in looming",
      projection: "1st Round Exit",
      narrative:
        "Oklahoma City's 35-point demolition of Phoenix this week was a humiliating reminder of exactly where the Suns stand in the Western Conference hierarchy. Kevin Durant's absence from the injury report adds another layer of concern as Phoenix navigates a brutal remaining schedule that threatens to push them into play-in territory. The Suns need an immediate response — both for playoff positioning and for organizational morale.",
    },
    {
      team: "LAL",
      conference: "west",
      currentWins: 47,
      currentLosses: 36,
      projectedWins: 49,
      projectedLosses: 33,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 2.8,
      remainingSOS: 21,
      remainingSOSLabel: "Easy",
      keyStretch:
        "Soft close allows full rest for LeBron heading into playoffs",
      projection: "1st Round Exit",
      narrative:
        "LeBron James continues to defy biology at 41, and the Lakers' easy closing schedule is a gift that allows the organization to prioritize health and rest over seeding positioning. Los Angeles is locked into the 6-7 seed range, and their first-round matchup will likely be against Minnesota or the Clippers — both beatable if LeBron and AD are at full strength. This week is about preparation, not accumulation.",
    },
    {
      team: "MEM",
      conference: "west",
      currentWins: 44,
      currentLosses: 39,
      projectedWins: 46,
      projectedLosses: 36,
      winChange: 1,
      playoffProb: 88,
      championshipProb: 1.6,
      remainingSOS: 23,
      remainingSOSLabel: "Easy",
      keyStretch:
        "Favorable close keeps Memphis in playoff contention — Morant health key",
      projection: "1st Round Exit",
      narrative:
        "Memphis sits in an interesting position — talented enough to make the playoffs, young enough that this is a developmental season regardless of outcome. Ja Morant's health and explosiveness heading into the postseason is the only storyline that matters in Memphis right now. A favorable closing schedule should get the Grizzlies locked in, and playing with house money in the playoffs could unleash their best basketball.",
    },
    {
      team: "NOP",
      conference: "west",
      currentWins: 38,
      currentLosses: 45,
      projectedWins: 39,
      projectedLosses: 43,
      winChange: -1,
      playoffProb: 42,
      championshipProb: 0.4,
      remainingSOS: 10,
      remainingSOSLabel: "Tough",
      keyStretch:
        "Tough road close likely ends any play-in hope — lottery awaits",
      projection: "1st Round Exit",
      narrative:
        "New Orleans' season has been derailed by injuries and inconsistency, and their tough remaining schedule makes a play-in appearance increasingly unlikely. Zion Williamson's availability continues to be the franchise's defining question, and this week's games may be more about evaluating the roster for offseason decisions than competing for positioning. The Pelicans are building toward something, but this isn't their year.",
    },
    {
      team: "UTA",
      conference: "west",
      currentWins: 30,
      currentLosses: 53,
      projectedWins: 31,
      projectedLosses: 51,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 26,
      remainingSOSLabel: "Easy",
      keyStretch: "Lottery positioning is Utah's entire remaining agenda",
      projection: "1st Round Exit",
      narrative:
        "Utah's rebuild is progressing exactly as designed, with young players getting extended run and the front office accumulating assets for a future contention window. Their easy remaining schedule won't help their lottery odds, but the development of their young core has been the genuine silver lining of a difficult season. The Jazz are one superstar away from relevance — this week's games are about finding out who on the roster can be part of that future.",
    },
    {
      team: "SAC",
      conference: "west",
      currentWins: 41,
      currentLosses: 42,
      projectedWins: 43,
      projectedLosses: 39,
      winChange: 1,
      playoffProb: 67,
      championshipProb: 0.7,
      remainingSOS: 5,
      remainingSOSLabel: "Brutal",
      keyStretch:
        "Brutal close vs. SAS and OKC is a near-impossible play-in path",
      projection: "1st Round Exit",
      narrative:
        "Sacramento sits in the West's play-in bubble but faces a closing schedule that could charitably be described as sadistic — games against San Antonio and Oklahoma City are essentially unwinnable at full effort. De'Aaron Fox has been brilliant all season, and the Kings deserve better than this scheduling cruelty. If they somehow steal a win from SAS or OKC, it would be the West's other major upset story of the week.",
    },
    {
      team: "DAL",
      conference: "west",
      currentWins: 36,
      currentLosses: 47,
      projectedWins: 37,
      projectedLosses: 45,
      winChange: 0,
      playoffProb: 15,
      championshipProb: 0.2,
      remainingSOS: 3,
      remainingSOSLabel: "Brutal",
      keyStretch:
        "Playoff math is nearly impossible without a miracle closing run",
      projection: "1st Round Exit",
      narrative:
        "Dallas's season has been a disappointment relative to preseason expectations, and their brutal remaining schedule makes any postseason scenario essentially theoretical at this point. Luka Doncic's individual brilliance has been undermined by roster construction issues all season, and the front office faces serious questions this offseason. This week is about pride and audition performances for marginal roster players.",
    },
    {
      team: "HOU",
      conference: "west",
      currentWins: 48,
      currentLosses: 35,
      projectedWins: 50,
      projectedLosses: 32,
      winChange: 2,
      playoffProb: 100,
      championshipProb: 2.1,
      remainingSOS: 2,
      remainingSOSLabel: "Brutal",
      keyStretch:
        "Brutal close vs. SAS, OKC, MEM is a gauntlet that defines their ceiling",
      projection: "1st Round Exit",
      narrative:
        "Houston has been one of the West's most pleasant surprises, with Alperen Şengün's emergence as a legitimate two-way big giving the Rockets genuine playoff credibility. Their brutal closing schedule is simultaneously their biggest threat to seeding and their best audition for playoff readiness. How this young Rockets team responds to elite competition this week will tell us everything about their postseason ceiling.",
    },
    {
      team: "POR",
      conference: "west",
      currentWins: 42,
      currentLosses: 41,
      projectedWins: 43,
      projectedLosses: 39,
      winChange: -1,
      playoffProb: 58,
      championshipProb: 0.5,
      remainingSOS: 1,
      remainingSOSLabel: "Brutal",
      keyStretch:
        "Toughest remaining schedule in the league — play-in spot in serious jeopardy",
      projection: "1st Round Exit",
      narrative:
        "Damian Lillard's 25-point effort against Wembanyama and the Spurs showed the veteran's competitive fire remains burning, but Portland's loss exposed the brutal reality of facing elite rim protection without adequate spacing. The Trail Blazers face the league's toughest remaining schedule, and their play-in spot is genuinely in danger. This is a make-or-break week for Lillard's postseason hopes in what could be one of his final seasons in Portland.",
    },
  ],
  projectedBracket: {
    east: [
      // First Round
      {
        round: "First Round",
        highSeed: "DET",
        lowSeed: "ORL",
        seriesProb: "DET in 6",
        keyFactor:
          "Detroit's top-seed home-court advantage and Cunningham's superior playoff experience should overcome Banchero's breakout momentum, but Orlando's upset win this week guarantees they won't be intimidated.",
      },
      {
        round: "First Round",
        highSeed: "BOS",
        lowSeed: "MIA",
        seriesProb: "BOS in 5",
        keyFactor:
          "Tatum's current unconscious shooting form and Boston's 32-point demolition of Philly signal a team that is locked in, and the Heat's sluggish recent form gives the Celtics a significant edge.",
      },
      {
        round: "First Round",
        highSeed: "MIL",
        lowSeed: "PHI",
        seriesProb: "MIL in 5",
        keyFactor:
          "Giannis's mobility advantage over an aging Embiid, combined with Philadelphia's inability to compete in this week's Boston blowout, makes Milwaukee a comfortable favorite in this matchup.",
      },
      {
        round: "First Round",
        highSeed: "IND",
        lowSeed: "CLE",
        seriesProb: "IND in 7",
        keyFactor:
          "Haliburton's pace-pushing offense against Cleveland's defensive rigidity creates a fascinating chess match, with Indiana's home-court advantage and offensive efficiency ultimately proving decisive.",
      },
      // Second Round
      {
        round: "Second Round",
        highSeed: "DET",
        lowSeed: "IND",
        seriesProb: "DET in 6",
        keyFactor:
          "Cunningham's playmaking superiority over Haliburton and Detroit's defensive physicality should be too much for Indiana, though the Pacers' pace will keep every game close and competitive.",
      },
      {
        round: "Second Round",
        highSeed: "BOS",
        lowSeed: "MIL",
        seriesProb: "BOS in 6",
        keyFactor:
          "Tatum's current three-point barrage is the perfect antidote to Milwaukee's drop coverage, and Boston's depth advantage makes them prohibitive favorites in what should be the East's most entertaining series.",
      },
      // Conference Finals
      {
        round: "Conference Finals",
        highSeed: "BOS",
        lowSeed: "DET",
        seriesProb: "BOS in 7",
        keyFactor:
          "The East Finals rematch of the two best records in the conference will be decided by Boston's championship experience and Tatum's ability to replicate his current peak form against Cunningham's defensive attention.",
      },
    ],
    west: [
      // First Round
      {
        round: "First Round",
        highSeed: "OKC",
        lowSeed: "GSW",
        seriesProb: "OKC in 5",
        keyFactor:
          "SGA's efficiency advantage over an aging Warriors roster is stark, and Oklahoma City's 35-point demolition performances this week demonstrate a team playing well above Golden State's current level.",
      },
      {
        round: "First Round",
        highSeed: "SAS",
        lowSeed: "LAC",
        seriesProb: "SAS in 5",
        keyFactor:
          "Wembanyama's rim protection fundamentally alters the Clippers' drive-and-kick offense, and San Antonio's superior talent and home-court advantage make this a surprisingly one-sided matchup on paper.",
      },
      {
        round: "First Round",
        highSeed: "DEN",
        lowSeed: "LAL",
        seriesProb: "DEN in 6",
        keyFactor:
          "Jokic's triple-double consistency and Denver's championship-tested infrastructure give them the edge over LeBron's Lakers, though the King's playoff motivation makes every game a live wire.",
      },
      {
        round: "First Round",
        highSeed: "MIN",
        lowSeed: "HOU",
        seriesProb: "MIN in 6",
        keyFactor:
          "Minnesota's elite defense and Anthony Edwards' rising star power should contain Houston's offensive firepower, though Şengün's developing two-way game gives the young Rockets a legitimate path to an upset.",
      },
      // Second Round
      {
        round: "Second Round",
        highSeed: "OKC",
        lowSeed: "MIN",
        seriesProb: "OKC in 6",
        keyFactor:
          "The battle of the West's two most athletically gifted young rosters will come down to SGA's ability to consistently get to his spots against Minnesota's length, with Oklahoma City's superior depth proving the difference.",
      },
      {
        round: "Second Round",
        highSeed: "SAS",
        lowSeed: "DEN",
        seriesProb: "SAS in 7",
        keyFactor:
          "Wembanyama versus Jokic is the most intriguing big-man matchup in NBA history at this stage, and the seven-game war that results will define how the West's new generation measures against the previous champion.",
      },
      // Conference Finals
      {
        round: "Conference Finals",
        highSeed: "OKC",
        lowSeed: "SAS",
        seriesProb: "OKC in 7",
        keyFactor:
          "The rematch of the regular season's defining West rivalry will be decided by home-court advantage and SGA's marginal edge over Wembanyama in clutch-time creation, though this series could genuinely go either way.",
      },
    ],
    finals: {
      round: "NBA Finals",
      highSeed: "OKC",
      lowSeed: "BOS",
      seriesProb: "BOS in 7",
      keyFactor:
        "Tatum's championship pedigree, Brown's two-way excellence, and Boston's roster depth ultimately overcome SGA's brilliance and Oklahoma City's youth and athleticism in a seven-game classic that will be remembered as one of the great Finals matchups of the modern era.",
    },
  },
};