// Auto-generated by generate-projections.mjs
// Week of August 17–23, 2026

export interface TeamProjection {
  team: string;
  conference: "east" | "west";
  currentWins: number;
  currentLosses: number;
  projectedWins: number;
  projectedLosses: number;
  winChange: number;
  playoffProb: number;
  championshipProb: number;
  remainingSOS: number;
  remainingSOSLabel: string;
  keyStretch: string;
  projection: string;
  narrative: string;
}

export interface PlayoffMatchup {
  round: string;
  highSeed: string;
  lowSeed: string;
  seriesProb: string;
  keyFactor: string;
}

export interface ProjectionsData {
  generatedDate: string;
  weekLabel: string;
  teams: TeamProjection[];
  projectedBracket: {
    east: PlayoffMatchup[];
    west: PlayoffMatchup[];
    finals: PlayoffMatchup;
  };
  biggestRiser: { team: string; change: string; reason: string };
  biggestFaller: { team: string; change: string; reason: string };
  weeklyNarrative: string;
}

export const projectionsData: ProjectionsData = {
  generatedDate: "August 17, 2026",
  weekLabel: "Week of August 17–23, 2026",
  weeklyNarrative:
    "The extension window's second week arrives with the league's organizational hierarchy crystallizing around a single axis: contractual clarity versus live uncertainty. Oklahoma City and San Antonio sit at opposite poles of the same elite tier — OKC holding the league's best record at 64-18 with zero remaining extension noise, SAS at 62-20 with its Wembanyama-Fox core locked and only the Castle negotiation generating any residual heat. Houston's Sengun commitment window is the West's most consequential near-term storyline below that top tier, while Denver's Murray complexity keeps the two-time champion Nuggets operating under genuine organizational pressure that no projected wins total fully captures. In the East, New York's championship validation holds firm with Brunson and Towns both settled, but the Knicks' path back to the Finals runs through a conference that has tightened considerably. Minnesota's multi-player extension chaos remains the loudest organizational noise of any contender, and until those roster edges resolve, the Wolves' ceiling is functionally capped regardless of Edwards' individual locked status. The rest-of-season picture is one of settled hierarchies at the top and meaningful variance everywhere from the fourth seed downward on both sides.",
  biggestRiser: {
    team: "SAS",
    change: "+2.1 championship probability",
    reason:
      "Castle extension talks accelerating with a number reportedly conveyed shifts SAS's organizational ceiling from theoretically intact to actively consolidating — the Spurs' second-unit depth projection improves the moment that conversation closes.",
  },
  biggestFaller: {
    team: "DEN",
    change: "-1.8 championship probability",
    reason:
      "Murray's chronic knee management timeline is generating more internal uncertainty than Denver's front office is publicly acknowledging; the compound variable of live extension eligibility plus medical ambiguity pulls the Nuggets' ceiling projection downward for a second consecutive week.",
  },
  teams: [
    {
      team: "OKC",
      conference: "west",
      currentWins: 64,
      currentLosses: 18,
      projectedWins: 68,
      projectedLosses: 14,
      winChange: 1,
      playoffProb: 100,
      championshipProb: 27.4,
      remainingSOS: 18,
      remainingSOSLabel: "Average",
      keyStretch: "Four-game homestand closes the regular season against lottery-bound opponents",
      projection: "Champion",
      narrative:
        "OKC enters the week as the league's cleanest organizational picture by every measurable axis — best record, max-locked principal, zero extension noise in the supporting cast. SGA's 31.2 PPG average and the Thunder's 64-18 mark give them the West's top seed by a comfortable margin with a favorable remaining schedule. The extension window generates no new noise around this team, which is precisely the correct and expected outcome for a franchise operating at full organizational expression.",
    },
    {
      team: "SAS",
      conference: "west",
      currentWins: 62,
      currentLosses: 20,
      projectedWins: 66,
      projectedLosses: 16,
      winChange: 2,
      playoffProb: 100,
      championshipProb: 24.1,
      remainingSOS: 22,
      remainingSOSLabel: "Easy",
      keyStretch: "Six of final ten games at home with no back-to-backs remaining on the schedule",
      projection: "Champion",
      narrative:
        "Wembanyama's Finals MVP validation and Fox's locked max status give San Antonio the deepest foundational security of any team in the league, and the Castle acceleration this week adds a near-term organizational catalyst that lifts the Spurs' ceiling projection slightly. The 62-20 record is the West's second-best and their remaining schedule is the conference's most favorable among contenders. If Castle signs before the playoffs, SAS enters the postseason with the league's most complete and contractually settled roster.",
    },
    {
      team: "NYK",
      conference: "east",
      currentWins: 53,
      currentLosses: 29,
      projectedWins: 57,
      projectedLosses: 25,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 12.3,
      remainingSOS: 14,
      remainingSOSLabel: "Average",
      keyStretch: "Three-game road trip through Boston and Milwaukee is the East's defining late-season stretch",
      projection: "Finals",
      narrative:
        "Brunson's 44-point Game 7 performance and championship validation have the Knicks operating at the East's highest organizational confidence level entering week two of the extension window. Towns' complete settlement — champion, healthy, no active variable — removes any roster uncertainty that might otherwise distort the projection. At 53-29, New York holds the East's second seed with a manageable remaining schedule, though the Boston-Milwaukee road trip this week represents a genuine seeding inflection point.",
    },
    {
      team: "DEN",
      conference: "west",
      currentWins: 54,
      currentLosses: 28,
      projectedWins: 57,
      projectedLosses: 25,
      winChange: -1,
      playoffProb: 100,
      championshipProb: 9.8,
      remainingSOS: 7,
      remainingSOSLabel: "Tough",
      keyStretch: "Four consecutive road games against West playoff teams closes the final three weeks",
      projection: "Conference Finals",
      narrative:
        "Denver's Murray complexity is the extension window's most analytically uncertain active storyline, and the chronic knee management variable introduces a genuine downside scenario into what should be a straightforward projection for a two-time champion. Jokic's 26.4/12.7/8.0 line keeps the Nuggets organizationally relevant, but the remaining schedule is the West's fourth-hardest among contenders and Murray's availability projection carries real uncertainty. Denver slides one spot in championship probability this week as the medical timeline remains unresolved.",
    },
    {
      team: "HOU",
      conference: "west",
      currentWins: 52,
      currentLosses: 30,
      projectedWins: 55,
      projectedLosses: 27,
      winChange: 1,
      playoffProb: 100,
      championshipProb: 6.2,
      remainingSOS: 11,
      remainingSOSLabel: "Average",
      keyStretch: "Home-heavy final stretch with five of seven remaining games at Toyota Center",
      projection: "Conference Finals",
      narrative:
        "Houston's Sengun commitment window is the West's most consequential individual extension storyline outside the OKC-SAS tier, and the next two weeks will confirm whether the Rockets' internal evaluation has settled on a number. Sengun's 22.1/10.4/3.1 line gives Houston a legitimate frontcourt anchor, and the home-heavy remaining schedule should protect the fourth seed. The extension window's resolution — or lack thereof — is the primary variable that will move Houston's championship probability in either direction over the coming days.",
    },
    {
      team: "MIN",
      conference: "west",
      currentWins: 49,
      currentLosses: 33,
      projectedWins: 52,
      projectedLosses: 30,
      winChange: -1,
      playoffProb: 97,
      championshipProb: 3.9,
      remainingSOS: 5,
      remainingSOSLabel: "Brutal",
      keyStretch: "Seven-game stretch includes five opponents currently in playoff position",
      projection: "2nd Round",
      narrative:
        "Edwards' personal lock-in remains the Wolves' organizational anchor, but Minnesota's simultaneous multi-player extension pressure creates a compounding drag on clarity that no wins projection fully captures. The remaining schedule is the West's second-hardest and the multi-player uncertainty hasn't generated any new resolution entering week two of the window. At 49-33, Minnesota holds the fifth seed but the brutal remaining SOS makes a fourth-seed finish unlikely without roster clarity arriving soon.",
    },
    {
      team: "GSW",
      conference: "west",
      currentWins: 47,
      currentLosses: 35,
      projectedWins: 50,
      projectedLosses: 32,
      winChange: 0,
      playoffProb: 91,
      championshipProb: 2.8,
      remainingSOS: 16,
      remainingSOSLabel: "Average",
      keyStretch: "Chase Center hosts four straight before a three-game Western road swing to close",
      projection: "2nd Round",
      narrative:
        "Golden State's sixth-seed position reflects a roster that remains competitive without the organizational clarity that defines the league's top tier. The extension window generates modest noise around their secondary contracts but nothing approaching the foundational uncertainty of Minnesota or Denver. Four home games this week give the Warriors a realistic chance to create separation from the play-in bubble and lock a guaranteed playoff position.",
    },
    {
      team: "MEM",
      conference: "west",
      currentWins: 45,
      currentLosses: 37,
      projectedWins: 48,
      projectedLosses: 34,
      winChange: 1,
      playoffProb: 84,
      championshipProb: 1.4,
      remainingSOS: 20,
      remainingSOSLabel: "Easy",
      keyStretch: "Favorable home schedule over next ten days provides a real opportunity to solidify seeding",
      projection: "1st Round Exit",
      narrative:
        "Memphis has quietly assembled one of the West's most efficient offensive units, and the easy remaining schedule gives the Grizzlies a legitimate path to the sixth seed if Golden State stumbles. The extension window is largely quiet around their core, which reflects organizational stability appropriate to their developmental stage. A first-round exit projection reflects matchup reality against the West's top seeds rather than any concern about Memphis's competitive trajectory.",
    },
    {
      team: "LAC",
      conference: "west",
      currentWins: 43,
      currentLosses: 39,
      projectedWins: 46,
      projectedLosses: 36,
      winChange: 0,
      playoffProb: 76,
      championshipProb: 0.8,
      remainingSOS: 9,
      remainingSOSLabel: "Tough",
      keyStretch: "Road-heavy final stretch through Dallas and Phoenix with playoff implications on the line",
      projection: "1st Round Exit",
      narrative:
        "The Clippers sit on the right side of the play-in bubble with enough roster depth to hold the eighth seed, but the tough remaining schedule introduces real variance into their final standing. The extension window is quiet around their key contributors, which is appropriate stability for a team whose ceiling is clearly defined. A first-round exit remains the most likely outcome even if they secure the eighth seed given the West's top-four quality.",
    },
    {
      team: "DAL",
      conference: "west",
      currentWins: 42,
      currentLosses: 40,
      projectedWins: 44,
      projectedLosses: 38,
      winChange: -1,
      playoffProb: 68,
      championshipProb: 0.6,
      remainingSOS: 4,
      remainingSOSLabel: "Brutal",
      keyStretch: "Five of next seven opponents are currently in playoff position in their respective conferences",
      projection: "1st Round Exit",
      narrative:
        "Dallas sits at the West's play-in threshold with a brutal remaining schedule that makes a guaranteed playoff spot genuinely uncertain. The extension window has generated some low-level noise around their secondary contributors but nothing that changes the organizational picture in either direction this week. The Mavericks' championship probability reflects both the ceiling constraints of their current construction and the schedule reality they face over the final stretch.",
    },
    {
      team: "PHX",
      conference: "west",
      currentWins: 40,
      currentLosses: 42,
      projectedWins: 43,
      projectedLosses: 39,
      winChange: 0,
      playoffProb: 58,
      championshipProb: 0.4,
      remainingSOS: 25,
      remainingSOSLabel: "Easy",
      keyStretch: "Suns close with seven of ten at home — a genuine opportunity to play their way into the top eight",
      projection: "1st Round Exit",
      narrative:
        "Phoenix's easy remaining schedule is the one organizational advantage that keeps their play-in probability meaningful, but the roster's ceiling limitations are well-understood at this point in the season. The extension window is quiet around the Suns, which reflects an organization still working through the downstream consequences of earlier roster decisions. Even with a favorable schedule, a first-round exit is the ceiling projection for this group.",
    },
    {
      team: "NOP",
      conference: "west",
      currentWins: 36,
      currentLosses: 46,
      projectedWins: 38,
      projectedLosses: 44,
      winChange: 0,
      playoffProb: 22,
      championshipProb: 0.1,
      remainingSOS: 28,
      remainingSOSLabel: "Cupcake",
      keyStretch: "Favorable final schedule gives New Orleans a theoretical play-in path but roster limitations are the binding constraint",
      projection: "1st Round Exit",
      narrative:
        "New Orleans' play-in probability is kept alive almost entirely by their cupcake remaining schedule rather than any roster development that has materially changed their competitive outlook. The extension window is quiet around the Pelicans, which is appropriate for an organization focused on next offseason rather than this postseason. A 22% playoff probability reflects scheduling math more than competitive merit.",
    },
    {
      team: "UTA",
      conference: "west",
      currentWins: 28,
      currentLosses: 54,
      projectedWins: 30,
      projectedLosses: 52,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 30,
      remainingSOSLabel: "Cupcake",
      keyStretch: "Remaining schedule is the West's most favorable — lottery positioning is the only meaningful variable",
      projection: "1st Round Exit",
      narrative:
        "Utah's organizational focus is entirely on draft positioning rather than win totals, and the cupcake remaining schedule makes lottery math the only analytically relevant question. The extension window generates zero noise around the Jazz, which is correct for a team in full rebuild mode. Their 28-54 record reflects an intentional roster construction that prioritizes future assets over present competitiveness.",
    },
    {
      team: "POR",
      conference: "west",
      currentWins: 26,
      currentLosses: 56,
      projectedWins: 28,
      projectedLosses: 54,
      winChange: 1,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 27,
      remainingSOSLabel: "Cupcake",
      keyStretch: "Portland's final stretch is meaningless in playoff terms — development minutes are the organizational priority",
      projection: "1st Round Exit",
      narrative:
        "Portland's rebuild is at a foundational stage where no rest-of-season outcome changes the long-term organizational picture. The extension window is appropriately quiet around the Trail Blazers, and their winChange of +1 reflects a minor upward correction in lottery positioning math rather than any competitive development. Development minutes and draft asset accumulation are the only metrics that matter for this organization through the end of the regular season.",
    },
    {
      team: "SAC",
      conference: "west",
      currentWins: 24,
      currentLosses: 58,
      projectedWins: 26,
      projectedLosses: 56,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 23,
      remainingSOSLabel: "Easy",
      keyStretch: "Sacramento's remaining schedule is gentle but organizational focus has shifted entirely to the draft",
      projection: "1st Round Exit",
      narrative:
        "Sacramento's 24-58 record reflects a difficult year for a franchise that entered the season with playoff aspirations. The extension window generates no relevant noise around the Kings, and the easy remaining schedule will produce a few additional wins without changing the lottery picture in a meaningful way. The organizational priority for Sacramento is draft positioning and the evaluation of young contributors rather than any postseason variable.",
    },
    {
      team: "BOS",
      conference: "east",
      currentWins: 56,
      currentLosses: 26,
      projectedWins: 59,
      projectedLosses: 23,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 5.1,
      remainingSOS: 8,
      remainingSOSLabel: "Tough",
      keyStretch: "Back-to-back road games in New York and Philadelphia carry genuine East seeding implications",
      projection: "Conference Finals",
      narrative:
        "Boston holds the East's first seed at 56-26 and their championship probability reflects a roster that remains legitimately dangerous despite the Knicks holding the league's reigning title. The tough remaining schedule — anchored by the New York road game this week — is the East's defining late-season matchup for seeding purposes. Boston's organizational clarity is strong entering the extension window's second week, with no active noise around their principal contracts.",
    },
    {
      team: "MIL",
      conference: "east",
      currentWins: 51,
      currentLosses: 31,
      projectedWins: 54,
      projectedLosses: 28,
      winChange: 0,
      playoffProb: 100,
      championshipProb: 3.7,
      remainingSOS: 12,
      remainingSOSLabel: "Average",
      keyStretch: "Milwaukee's final stretch is balanced — no marquee games but no cupcake stretches either",
      projection: "2nd Round",
      narrative:
        "Milwaukee holds the East's third seed at 51-31 with an average remaining schedule that projects them to 54 wins and a comfortable playoff position. The extension window is quiet around the Bucks, which reflects appropriate organizational stability for a team operating in the East's second tier. A second-round exit projection reflects the genuine quality gap between Milwaukee and the East's top two seeds rather than any specific roster concern.",
    },
    {
      team: "IND",
      conference: "east",
      currentWins: 48,
      currentLosses: 34,
      projectedWins: 51,
      projectedLosses: 31,
      winChange: 1,
      playoffProb: 99,
      championshipProb: 2.1,
      remainingSOS: 17,
      remainingSOSLabel: "Average",
      keyStretch: "Indiana's home schedule over the next ten days is the East's most favorable remaining slate for a playoff team",
      projection: "2nd Round",
      narrative:
        "Indiana's 48-34 record and favorable remaining schedule give the Pacers a realistic path to the East's fourth seed, which would represent a meaningful seeding upgrade for their playoff positioning. The extension window is quiet around Indiana's core, and the home-heavy final stretch is the one organizational advantage that lifts their projection slightly this week. A second-round exit is the ceiling projection given the East's top-three quality.",
    },
    {
      team: "CLE",
      conference: "east",
      currentWins: 46,
      currentLosses: 36,
      projectedWins: 49,
      projectedLosses: 33,
      winChange: 0,
      playoffProb: 96,
      championshipProb: 1.6,
      remainingSOS: 13,
      remainingSOSLabel: "Average",
      keyStretch: "Cleveland closes with a mixed schedule — three road games against playoff teams define their seeding floor",
      projection: "1st Round Exit",
      narrative:
        "Cleveland's 46-36 record holds them in the East's fifth seed with an average remaining schedule that projects a 49-win finish. The extension window is quiet around the Cavaliers' core, which reflects appropriate stability for a team with a defined ceiling in the current East hierarchy. A first-round exit projection is the most likely outcome given Cleveland's likely matchup against Boston or New York in the second round.",
    },
    {
      team: "MIA",
      conference: "east",
      currentWins: 44,
      currentLosses: 38,
      projectedWins: 47,
      projectedLosses: 35,
      winChange: 0,
      playoffProb: 89,
      championshipProb: 1.2,
      remainingSOS: 15,
      remainingSOSLabel: "Average",
      keyStretch: "Miami's final stretch includes a home-and-away split against playoff-bound Eastern opponents",
      projection: "1st Round Exit",
      narrative:
        "Miami's 44-38 record keeps them in the East's sixth seed with a manageable remaining schedule. The extension window is quiet around the Heat, which is appropriate for an organization whose offseason architecture is stable. A first-round exit is the most likely projection, though Miami's playoff experience and coaching infrastructure give them a higher series-upset probability than their seed might suggest.",
    },
    {
      team: "ORL",
      conference: "east",
      currentWins: 42,
      currentLosses: 40,
      projectedWins: 45,
      projectedLosses: 37,
      winChange: 1,
      playoffProb: 81,
      championshipProb: 0.7,
      remainingSOS: 19,
      remainingSOSLabel: "Average",
      keyStretch: "Orlando's remaining schedule is mixed — the Amway Center provides a genuine home-court advantage for four remaining games",
      projection: "1st Round Exit",
      narrative:
        "Orlando sits at the East's seventh seed with a roster that has developed steadily throughout the season. The extension window is quiet around the Magic's young core, and the average remaining schedule gives them a realistic path to the seventh seed lock. A first-round exit is the projection, though Orlando's defensive infrastructure is one of the East's underrated structural advantages in a short series.",
    },
    {
      team: "PHI",
      conference: "east",
      currentWins: 40,
      currentLosses: 42,
      projectedWins: 42,
      projectedLosses: 40,
      winChange: -1,
      playoffProb: 63,
      championshipProb: 0.3,
      remainingSOS: 6,
      remainingSOSLabel: "Tough",
      keyStretch: "Philadelphia's brutal final stretch includes the Boston and New York road games that define their play-in fate",
      projection: "1st Round Exit",
      narrative:
        "Philadelphia sits at the East's play-in threshold with a tough remaining schedule that makes a guaranteed playoff spot genuinely uncertain. The extension window has generated some organizational noise around the 76ers' secondary contracts, but nothing that changes the foundational picture this week. The Boston and New York road games this week are the East's most consequential late-season seeding matchups for a bubble team.",
    },
    {
      team: "CHI",
      conference: "east",
      currentWins: 38,
      currentLosses: 44,
      projectedWins: 40,
      projectedLosses: 42,
      winChange: 0,
      playoffProb: 45,
      championshipProb: 0.2,
      remainingSOS: 21,
      remainingSOSLabel: "Easy",
      keyStretch: "Chicago's easy remaining schedule gives them a theoretical play-in path but roster limitations remain the binding constraint",
      projection: "1st Round Exit",
      narrative:
        "Chicago's 38-44 record and easy remaining schedule create a play-in path that is real in scheduling terms but constrained in roster terms. The extension window is quiet around the Bulls, which is appropriate for an organization at the bubble's edge. Even if Chicago plays their way into the play-in, a first-round exit at any seed is the realistic ceiling projection given the East's current competitive landscape.",
    },
    {
      team: "ATL",
      conference: "east",
      currentWins: 35,
      currentLosses: 47,
      projectedWins: 37,
      projectedLosses: 45,
      winChange: 0,
      playoffProb: 18,
      championshipProb: 0.1,
      remainingSOS: 24,
      remainingSOSLabel: "Easy",
      keyStretch: "Atlanta's final stretch is the East's most favorable — play-in math is theoretical but not impossible",
      projection: "1st Round Exit",
      narrative:
        "Atlanta's 35-47 record makes their play-in probability almost entirely schedule-dependent rather than roster-merit dependent. The extension window generates no relevant noise around the Hawks, and the easy remaining schedule will produce a few additional wins without materially changing their organizational picture. Draft positioning and young player evaluation are the metrics that matter most for Atlanta through the end of the regular season.",
    },
    {
      team: "TOR",
      conference: "east",
      currentWins: 30,
      currentLosses: 52,
      projectedWins: 32,
      projectedLosses: 50,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 26,
      remainingSOSLabel: "Easy",
      keyStretch: "Toronto's remaining schedule is the East's most favorable — lottery positioning is the organizational priority",
      projection: "1st Round Exit",
      narrative:
        "Toronto's rebuild is at a foundational stage where draft positioning and young player development are the only meaningful organizational variables. The extension window is appropriately quiet around the Raptors, and the easy remaining schedule will generate a few additional wins without changing the lottery math in a significant way. The 30-52 record reflects an intentional roster construction philosophy rather than any competitive shortfall.",
    },
    {
      team: "WAS",
      conference: "east",
      currentWins: 22,
      currentLosses: 60,
      projectedWins: 24,
      projectedLosses: 58,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 29,
      remainingSOSLabel: "Cupcake",
      keyStretch: "Washington's remaining schedule is the East's most favorable — organizational focus is entirely forward-looking",
      projection: "1st Round Exit",
      narrative:
        "Washington's 22-60 record is the East's worst and the organizational focus is entirely on draft asset accumulation and young player evaluation. The extension window generates zero noise around the Wizards, which is correct for a team in the early stages of a comprehensive rebuild. The cupcake remaining schedule will produce a few additional wins but the lottery positioning calculus is the only variable that carries any analytical weight for this organization.",
    },
    {
      team: "DET",
      conference: "east",
      currentWins: 34,
      currentLosses: 48,
      projectedWins: 36,
      projectedLosses: 46,
      winChange: 1,
      playoffProb: 12,
      championshipProb: 0.1,
      remainingSOS: 10,
      remainingSOSLabel: "Tough",
      keyStretch: "Detroit's tough remaining schedule makes a play-in berth extremely difficult despite their developmental progress",
      projection: "1st Round Exit",
      narrative:
        "Detroit's 34-48 record reflects genuine developmental progress that the wins total doesn't fully capture, but the tough remaining schedule makes a play-in berth functionally out of reach. The extension window is quiet around the Pistons' young core, which reflects appropriate organizational patience for a team still building toward a competitive window that opens in the next one to two seasons. Draft positioning remains more valuable than a play-in appearance for Detroit's long-term architecture.",
    },
    {
      team: "CHA",
      conference: "east",
      currentWins: 20,
      currentLosses: 62,
      projectedWins: 22,
      projectedLosses: 60,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 2,
      remainingSOSLabel: "Brutal",
      keyStretch: "Charlotte's brutal remaining schedule is analytically irrelevant — lottery positioning is the only organizational variable",
      projection: "1st Round Exit",
      narrative:
        "Charlotte's 20-62 record is one of the league's worst and the brutal remaining schedule will not produce any results that change the organizational picture. The extension window generates zero relevant noise around the Hornets, and the lottery positioning math is the only analytical question that carries weight for this franchise through the end of the regular season. Charlotte's rebuild is at the earliest stage of any team in the East.",
    },
    {
      team: "BKN",
      conference: "east",
      currentWins: 18,
      currentLosses: 64,
      projectedWins: 20,
      projectedLosses: 62,
      winChange: 0,
      playoffProb: 0,
      championshipProb: 0.0,
      remainingSOS: 3,
      remainingSOSLabel: "Brutal",
      keyStretch: "Brooklyn's brutal schedule is strategically irrelevant — asset accumulation and draft positioning are the complete organizational agenda",
      projection: "1st Round Exit",
      narrative:
        "Brooklyn's 18-64 record is the league's worst and reflects an organization that has deliberately prioritized future assets over present competitiveness across multiple seasons. The extension window generates zero noise around the Nets, which is correct for a franchise whose organizational agenda is entirely forward-looking. The brutal remaining schedule will likely hold Brooklyn at or near the league's worst record, which serves their draft positioning interests.",
    },
  ],
  projectedBracket: {
    east: [
      {
        round: "First Round",
        highSeed: "BOS",
        lowSeed: "MIA",
        seriesProb: "BOS in 5",
        keyFactor:
          "Boston's home-court advantage and defensive depth are too much for Miami's roster construction to overcome in a short series.",
      },
      {
        round: "First Round",
        highSeed: "NYK",
        lowSeed: "CLE",
        seriesProb: "NYK in 5",
        keyFactor:
          "Brunson's championship-validated clutch performance and Towns' frontcourt dominance give New York decisive advantages at both ends that Cleveland cannot match.",
      },
      {
        round: "First Round",
        highSeed: "MIL",
        lowSeed: "ORL",
        seriesProb: "MIL in 6",
        keyFactor:
          "Milwaukee's veteran playoff experience and offensive firepower ultimately overwhelm Orlando's defensive infrastructure over six games.",
      },
      {
        round: "First Round",
        highSeed: "IND",
        lowSeed: "PHI",
        seriesProb: "IND in 6",
        keyFactor:
          "Indiana's home-court advantage and pace-of-play preferences neutralize Philadelphia's halfcourt strengths across a six-game series.",
      },
      {
        round: "Second Round",
        highSeed: "BOS",
        lowSeed: "IND",
        seriesProb: "BOS in 6",
        keyFactor:
          "Boston's defensive sophistication and experience in high-leverage situations give them the edge over Indiana's up-tempo system in a competitive six-game series.",
      },
      {
        round: "Second Round",
        highSeed: "NYK",
        lowSeed: "MIL",
        seriesProb: "NYK in 5",
        keyFactor:
          "The defending champions' championship infrastructure and Brunson's proven playoff performance overwhelm Milwaukee's second-round ceiling in five decisive games.",
      },
      {
        round: "Conference Finals",
        highSeed: "NYK",
        lowSeed: "BOS",
        seriesProb: "NYK in 7",
        keyFactor:
          "New York's championship experience and Brunson's elite clutch scoring give the Knicks the decisive edge in a seven-game series that replicates last year's Finals intensity.",
      },
    ],
    west: [
      {
        round: "First Round",
        highSeed: "OKC",
        lowSeed: "LAC",
        seriesProb: "OKC in 4",
        keyFactor:
          "SGA's 31.2 PPG average and OKC's league-best defensive infrastructure make this a mismatch that resolves in four games.",
      },
      {
        round: "First Round",
        highSeed: "SAS",
        lowSeed: "MEM",
        seriesProb: "SAS in 5",
        keyFactor:
          "Wembanyama's 4.2 BPG deterrence fundamentally alters Memphis's interior attack, and Fox's playmaking gives San Antonio decisive advantages at both guard spots.",
      },
      {
        round: "First Round",
        highSeed: "DEN",
        lowSeed: "GSW",
        seriesProb: "DEN in 6",
        keyFactor:
          "Jokic's 26.4/12.7/8.0 line is the West's most dominant individual force in a series, and Denver's championship infrastructure holds even with Murray operating on a managed load.",
      },
      {
        round: "First Round",
        highSeed: "HOU",
        lowSeed: "MIN",
        seriesProb: "HOU in 6",
        keyFactor:
          "Sengun's frontcourt dominance against Minnesota's unsettled roster construction gives Houston a decisive matchup advantage that compounds over six games.",
      },
      {
        round: "Second Round",
        highSeed: "OKC",
        lowSeed: "HOU",
        seriesProb: "OKC in 5",
        keyFactor:
          "OKC's league-best defensive rating and SGA's ability to exploit Houston's perimeter vulnerabilities give the Thunder a decisive series advantage.",
      },
      {
        round: "Second Round",
        highSeed: "SAS",
        lowSeed: "DEN",
        seriesProb: "SAS in 6",
        keyFactor:
          "Wembanyama's rim protection neutralizes Jokic's interior game better than any defender in the league, and Murray's chronic knee management reduces Denver's secondary playmaking in high-leverage moments.",
      },
      {
        round: "Conference Finals",
        highSeed: "OKC",
        lowSeed: "SAS",
        seriesProb: "OKC in 7",
        keyFactor:
          "The West's defining series — OKC's 64-win infrastructure versus SAS's Finals MVP — resolves in seven games in favor of the Thunder's superior record and home-court advantage in a series where both teams have eliminated every organizational variable except execution.",
      },
    ],
    finals: {
      round: "NBA Finals",
      highSeed: "OKC",
      lowSeed: "NYK",
      seriesProb: "OKC in 6",
      keyFactor:
        "SGA's max-locked principal at the league's best team facing Brunson's championship-validated Knicks — the Finals resolves in six games as OKC's superior record, defensive infrastructure, and SGA's individual brilliance prove decisive against New York's championship experience and Brunson's elite clutch scoring.",
    },
  },
};