// Auto-generated by generate-sentiment.mjs
// July 20, 2026

export interface SentimentTopic {
  id: string;
  topic: string;
  sentiment: "positive" | "negative" | "mixed" | "neutral";
  intensity: number;
  volume: number;
  summary: string;
  sampleTakes: string[];
  relatedPlayers: string[];
  relatedTeams: string[];
  trending: boolean;
}

export interface TeamSentiment {
  team: string;
  teamFull: string;
  sentiment: "positive" | "negative" | "mixed" | "neutral";
  score: number;
  buzzWords: string[];
  narrativeSummary: string;
}

export interface PlayerSentiment {
  player: string;
  team: string;
  sentiment: "positive" | "negative" | "mixed" | "neutral";
  score: number;
  mentions: number;
  topTake: string;
  narrativeArc: string;
}

export interface SentimentData {
  generatedDate: string;
  displayDate: string;
  overallMood: string;
  topics: SentimentTopic[];
  teamSentiments: TeamSentiment[];
  playerSentiments: PlayerSentiment[];
  hottestTake: string;
  coldestTake: string;
}

export const sentimentData: SentimentData = {
  generatedDate: "2026-07-20",
  displayDate: "July 20, 2026",
  overallMood: "The ink is dry on Wemby's supermax and the internet is already mid-argument about Fox — Day 20 of the standoff has social media split between awe, dread, and pure calculated chaos energy",
  topics: [
    {
      id: "wemby-supermax-official-day-20",
      topic: "Wemby Supermax Is Official — The Internet Immediately Starts Ranking It Historically",
      sentiment: "positive",
      intensity: 97,
      volume: 61200,
      summary: "Victor Wembanyama's supermax signing closed Friday evening and by Sunday morning the discourse had completed its natural lifecycle: initial euphoria, historical contextualization, inevitable contrarianism, and finally the settling of a consensus that is overwhelmingly favorable. The 'what if he gets injured' crowd tried to establish a beachhead on Saturday and was thoroughly routed. The number — approaching $350 million over five years — is now the anchor point for every conversation about NBA franchise valuation, player worth, and what the Spurs have built in San Antonio. The ceremony was quiet and unbothered and NBA Twitter has responded by being neither of those things.",
      sampleTakes: [
        "The Wembanyama supermax is the only transaction in NBA history where the number was announced and everyone's first reaction was 'that feels right.' $350 million. Correct. Next.",
        "Someone said this was an overpay and got 4,000 ratio replies in 45 minutes. The internet has spoken. There is no overpay for the greatest center-slash-everything prospect since basketball was invented.",
        "32.8 PPG. 12.1 RPG. 4.2 BPG. In the FINALS. At 22. The contract is not the story. The contract is the receipt. The story already happened.",
        "Pop didn't even flinch at $350 million. He looked at Wemby's Finals line and said 'seems about right' and signed the paper. That is what organizational clarity looks like from the outside."
      ],
      relatedPlayers: ["Victor Wembanyama"],
      relatedTeams: ["SAS"],
      trending: true,
    },
    {
      id: "fox-offer-sheet-day-20-silence",
      topic: "Day 20 of Fox Silence — The Standoff Has Entered Mythology Territory",
      sentiment: "mixed",
      intensity: 99,
      volume: 58900,
      summary: "Twenty days into the most watched restricted free agency standoff in recent NBA history and De'Aaron Fox has still not signed an offer sheet. What started as a market management play has evolved into something approaching a cultural event — Fox's silence now generates its own daily news cycle independent of any actual development. Every faction has calcified: Spurs fans oscillating between breezy confidence and private existential dread, Heat evangelists treating each day of delay as divine confirmation that Miami is winning, Mavericks and Warriors fans still technically in the conversation but with the energy of people who have already started googling Plan B options. The discourse is no longer about where Fox is going. It is about what the delay itself means.",
      sampleTakes: [
        "Day 20. No offer sheet. Fox is not playing chess. He's playing a game that chess players look at and go 'I don't understand the rules but I respect the energy.'",
        "At this point Fox's agent deserves a monument. Not a raise. A MONUMENT. Twenty days of controlled silence generating daily national headlines without a single leak. This is an art form.",
        "San Antonio fans doing the 'we'll obviously match' thing publicly while their group chats are absolutely on fire. I have sources. The chats are not calm.",
        "Fox staying silent for 20 days tells me exactly one thing: he knows something about his options that we don't. You do not let this breathe this long if the answer was already San Antonio."
      ],
      relatedPlayers: ["De'Aaron Fox", "Victor Wembanyama", "Stephon Castle"],
      relatedTeams: ["SAS", "MIA", "DAL", "GSW"],
      trending: true,
    },
    {
      id: "spurs-payroll-apocalypse-math",
      topic: "Spurs Cap Math After Wemby Extension Is Breaking NBA Twitter's Calculators",
      sentiment: "mixed",
      intensity: 86,
      volume: 38400,
      summary: "The moment the Wembanyama supermax became official, every analytics account, beat writer, and self-appointed cap expert on NBA Twitter pointed their calculators at San Antonio's payroll and arrived at the same uncomfortable destination: if they match Fox and close Castle's extension, the Spurs will be operating a roster of three max-level cornerstones and approximately eleven people willing to accept the veteran minimum. The conversation has developed a genuine philosophical edge — is a roster built around three historic young talents with almost no depth a viable championship construction, or is Pop about to find out exactly how important his 9th and 10th men were? The debate is alive and loud.",
      sampleTakes: [
        "Spurs matching Fox means they're paying three players more than the entire rosters of six franchises combined. This is either the future of NBA roster construction or the most expensive lesson in depth ever taught.",
        "I have run the Spurs' cap sheet eight different ways and it always comes out the same: brilliant at the top, terrifying at the bottom, and absolutely dependent on nobody getting hurt. Ever.",
        "Name a better problem than 'we have Wembanyama, Fox, and Castle locked in for five years and no money left.' I will WAIT. Some teams haven't had one of those names in their history.",
        "Pop has won titles with uneven rosters before. Pop has built dynasties on culture and system. But Pop has never had a $700M payroll commitment in the top three rows of his cap sheet. This is new territory for everyone."
      ],
      relatedPlayers: ["Victor Wembanyama", "De'Aaron Fox", "Stephon Castle"],
      relatedTeams: ["SAS"],
      trending: true,
    },
    {
      id: "miami-fox-closing-argument",
      topic: "Heat Nation Goes Evangelical — Riley's Closing Push Has South Beach Believing",
      sentiment: "positive",
      intensity: 83,
      volume: 33700,
      summary: "Reports of Miami's sustained daily contact with Fox's camp combined with news of a presentation that goes beyond dollars into roster construction vision and lifestyle architecture have turned Heat Twitter from hopeful to zealous. The convergence of Pat Riley mythology, a legitimate basketball fit argument, and twenty days of Fox's apparent deliberateness has convinced a significant portion of the Heat fanbase that the silence is not hesitation — it is Fox savoring the power of the moment before choosing South Beach. The counter-argument that San Antonio simply matches any offer has been effectively quarantined to a small rational corner of the discourse that nobody is visiting right now.",
      sampleTakes: [
        "Pat Riley has been calling Fox every single day for twenty days. Every. Single. Day. He didn't do that for LeBron. He didn't do that for Wade. He is doing it for Fox. Read the room.",
        "The fit argument for Fox in Miami is not lifestyle cope. Fast pace, open floor, a franchise that develops guards. He was MADE for this system. The basketball argument is real.",
        "Day 20 and the Heat haven't blinked once. That is not the energy of an organization that thinks it's losing. Riley does not spend this much time and energy on lost causes. Come to Miami.",
        "Fox to Miami would be the most Pat Riley move since Pat Riley was Pat Riley in his prime. The man is 81 and still the best recruiter alive. Do not bet against him. I refuse."
      ],
      relatedPlayers: ["De'Aaron Fox"],
      relatedTeams: ["MIA", "SAS"],
      trending: true,
    },
    {
      id: "knicks-hartenstein-medical-week-three",
      topic: "Hartenstein Knee Evaluation Enters Week Three — Knicks Twitter Has Given Up Sleeping",
      sentiment: "negative",
      intensity: 81,
      volume: 29600,
      summary: "The New York Knicks are the defending NBA champions and their fanbase is operating with the collective emotional stability of a smoke alarm low on batteries. Isaiah Hartenstein's left knee evaluation stretching into a third week without resolution has transformed what should have been a minor procedural footnote into a full-blown anxiety event, amplified exponentially by the intersection with his restricted free agency timeline. The specific dread of a competing team submitting a sheet before the medical clearance arrives — forcing Leon Rose to sign or decline a contract without complete health information — has become the dominant Knicks narrative and it is getting louder not quieter.",
      sampleTakes: [
        "The Knicks won the NBA Championship 16 days ago. I have enjoyed approximately 4 of those days. The rest have been spent refreshing beat writers' timelines waiting for Hartenstein MRI news. This is what it means to be a Knicks fan. You cannot escape it. Not even with a ring.",
        "Some team is absolutely going to drop a four-year max sheet on Hartenstein at 11:59pm on a Tuesday and Leon Rose is going to have to make a nine-figure medical decision in real time. I feel this in my bones. I hate that I feel this.",
        "Hartenstein played 18 minutes in Game 7 and looked fine. He scored. He rebounded. He was not limping. Everyone please take a breath. The evaluation is a precaution. It is going to be fine. I am also not sleeping.",
        "The specific New York experience of winning a championship and immediately finding the most anxiety-producing possible offseason subplot is so perfectly Knicks that I have to respect it on a structural level."
      ],
      relatedPlayers: ["Isaiah Hartenstein", "Jalen Brunson"],
      relatedTeams: ["NYK"],
      trending: true,
    },
    {
      id: "okc-secondary-playmaker-closing",
      topic: "OKC Reportedly Down to Final Target — The Thunder Are Quietly Building Something Terrifying",
      sentiment: "positive",
      intensity: 78,
      volume: 24300,
      summary: "While the Fox standoff and Wemby extension consumed the majority of the NBA internet's attention this weekend, Oklahoma City made noise of a different frequency: reporting that Presti's front office has effectively narrowed its secondary playmaker search to a final target and is in closing stages has rerouted enough attention from San Antonio to remind the basketball community that the league's most efficient roster-building operation is operating on a parallel track. Thunder fans, who have been right about their team's ceiling for three consecutive seasons, are not celebrating prematurely. They are doing something more dangerous — they are being quietly confident, and that version of the OKC fanbase has an exceptional recent track record.",
      sampleTakes: [
        "Everyone is watching Fox and Wemby and nobody is watching OKC quietly close on a secondary playmaker who is going to make SGA a legitimate title favorite. Classic Presti. Classic Thunder. We're going to wake up one morning and it'll be done.",
        "64 wins with Shai and no true co-star. Add one legitimate secondary creator and tell me this team isn't the consensus West favorite by September. I'll wait here.",
        "The Thunder doing all of this roster work while San Antonio is distracted by a $700M payroll crisis is the most Presti thing Sam Presti has ever done. He sees the window. He is walking through it.",
        "SGA is sitting somewhere watching San Antonio's cap situation combust and knowing that OKC's flexibility is about to become the most valuable asset in the Western Conference. The best player on the best-built team wins. Always."
      ],
      relatedPlayers: ["Shai Gilgeous-Alexander"],
      relatedTeams: ["OKC"],
      trending: true,
    },
    {
      id: "summer-league-breakouts-day-5",
      topic: "Summer League Day 5 — The Next Wave Is Making Arguments in Las Vegas",
      sentiment: "positive",
      intensity: 68,
      volume: 19800,
      summary: "Las Vegas Summer League Day 5 is delivering the compressed, occasionally chaotic, often revelatory evaluations that make mid-July basketball watchable to people who genuinely care about roster construction. The top rookies from the recent class are getting extended minutes against real competition and several are rewarding the investment. More importantly for the league's organizational health, the two-way and roster-bubble tier is producing legitimate arguments that will survive into training camp — names being circled in front offices as 15th-man candidates who could hold a rotation role if injuries emerge. Summer League discourse is always slightly hyperbolic but the underlying evaluation is real and several players are having conversations this week that will change their career trajectories.",
      sampleTakes: [
        "The kid putting up genuine two-way numbers at Summer League tonight is either going to be a two-way contract signing next week or someone is going to be embarrassed they didn't pick him up first. Las Vegas separates the real ones from the camp fillers.",
        "Summer League production does not translate 1:1 to regular season production. This is known. This is also the only basketball happening right now and I will watch every second of it and overreact to all of it.",
        "The best thing about Summer League is watching front offices realize in real time that the guy they drafted in the second round is actually worth protecting and the guy they were high on in the first is not ready. The recalibration is visible from the sidelines.",
        "Someone in Las Vegas is playing their way onto a roster right now while the rest of the league watches Fox not sign a piece of paper. The NBA is very large and very interesting at multiple levels simultaneously."
      ],
      relatedPlayers: ["Stephon Castle", "Dalen Terry"],
      relatedTeams: ["SAS", "OKC", "NYK"],
      trending: false,
    },
    {
      id: "brunson-value-contract-discourse",
      topic: "Brunson Through 2028: The 'Best Value Contract in the East' Discourse Has Taken Over",
      sentiment: "positive",
      intensity: 72,
      volume: 21400,
      summary: "The post-championship offseason has given analytics Twitter a new favorite exercise: ranking the league's most valuable existing contracts against their production and market value equivalents. Jalen Brunson's extension through 2028 keeps surfacing at or near the top of every such ranking with a consistency that is generating genuine secondary discourse about how the Knicks managed to win the championship and then accidentally win the contract room too. Finals MVP numbers locked in at a cap figure that was negotiated before his ceiling was fully understood — the combination is rare enough to generate sustained conversation even in the middle of a summer dominated by new transactions.",
      sampleTakes: [
        "Brunson is locked through 2028 as a Finals MVP at a number that looks increasingly like a typo the further this offseason goes. The Knicks won the title AND the contract game. Other franchises would like to stop looking at this comparison. They cannot.",
        "44 points in Game 7. 7.4 assists in the Finals. Finals MVP. Locked through 2028. Tell me again why Jalen Brunson is not in the top five player conversations in the league. Use your outside voice.",
        "Every GM in the league has looked at Brunson's cap number at least once this weekend and felt something they can't fully articulate. That feeling is called envy. It is correct.",
        "The Knicks' organizational win is not just the championship. It is having the championship AND the most favorable elite player contract in the East simultaneously. That is how dynasties sustain themselves."
      ],
      relatedPlayers: ["Jalen Brunson"],
      relatedTeams: ["NYK"],
      trending: true,
    },
    {
      id: "castle-extension-talks-game7-hangover",
      topic: "Castle Extension Talks Advancing — But Game 7 Film Still Haunts the Discourse",
      sentiment: "mixed",
      intensity: 63,
      volume: 16100,
      summary: "Stephon Castle's extension framework progressing alongside the Fox resolution is the quietly significant Spurs subplot that keeps getting interrupted by Fox discourse on one side and Wemby celebrations on the other. The front office's confidence is publicly unambiguous — Pop's endorsements of Castle have been emphatic throughout the process — but NBA Twitter has not fully moved on from the Game 7 turnover sequence against Brunson. The two camps have not found common ground: process-thinkers looking at the steal production and playmaking upside of a 21-year-old, results-thinkers returning repeatedly to the specific high-leverage failure at the worst possible moment. The extension talks will close. The discourse will not.",
      sampleTakes: [
        "Pop extending Castle is Pop telling the world he has seen something in practice, in film sessions, in one-on-one conversations that the rest of us will spend two regular seasons catching up to. I trust Pop with player development bets the way I trust weather forecasters in San Diego. The record is not debatable.",
        "I understand the ceiling argument for Castle. I understand 21 years old. I understand the steal production. I still see those four turnovers against Brunson when I close my eyes and I am going to see them for a while.",
        "Castle is going to be an All-Star. Not might be. Going to be. The Spurs are getting a genuine bargain on whatever number this closes at and the teams that could have taken him in the draft are going to be studying film of him for years.",
        "The Game 7 film is the teaching tape. Castle knows it. Pop knows it. The extension talks are not happening in spite of that game — they're happening because both parties have already processed it and are aligned on what comes next."
      ],
      relatedPlayers: ["Stephon Castle", "Jalen Brunson"],
      relatedTeams: ["SAS", "NYK"],
      trending: false,
    },
    {
      id: "west-balance-of-power-fox-departure",
      topic: "The West Redraws Itself Depending on Where Fox Lands — Scenario Planning Has Taken Over",
      sentiment: "neutral",
      intensity: 76,
      volume: 27900,
      summary: "With the Fox standoff now consuming its third week of national attention, the discourse has evolved past 'will he stay or go' and into granular scenario mapping: what does the Western Conference hierarchy look like in each possible outcome. OKC is widely identified as the largest beneficiary of Fox departure — they get the dominant roster position in the West without needing to do anything. Miami entering as a legitimate contender reshapes the East-West power balance. Dallas getting Fox remains the outcome that breaks the calculus most completely. The scenario planning is simultaneously the most analytical and most speculative genre of NBA discourse and the Fox situation has produced a particularly rich version of it.",
      sampleTakes: [
        "Fox stays in San Antonio: West has a frontrunner but a cramped one. Fox goes to Miami: East gets dramatically more interesting and OKC inherits the West. Fox goes to Dallas: everyone recalibrates and nobody's model works anymore. The map is this clean. It's also this consequential.",
        "The most underappreciated outcome in the Fox sweepstakes is the scenario where he signs late enough that OKC closes their secondary playmaker deal first and suddenly the Thunder are built perfectly regardless of what happens in San Antonio. Presti is playing a different game.",
        "I have made seventeen scenario trees for Fox's destination and they all have one thing in common: someone in the Western Conference is going to be embarrassed by this offseason. The only question is who.",
        "Whatever Fox decides, the West doesn't look the same in September as it did in June. That is the only certainty in this entire situation and it is enough to keep the whole discourse alive indefinitely."
      ],
      relatedPlayers: ["De'Aaron Fox", "Shai Gilgeous-Alexander", "Victor Wembanyama"],
      relatedTeams: ["SAS", "OKC", "MIA", "DAL"],
      trending: true,
    },
  ],
  teamSentiments: [
    {
      team: "SAS",
      teamFull: "San Antonio Spurs",
      sentiment: "positive",
      score: 76,
      buzzWords: ["supermax done", "Fox standoff", "cap math anxiety", "Castle extension", "Pop trust", "depth questions", "dynasty ceiling", "restricted rights"],
      narrativeSummary: "San Antonio is carrying the most contradictory sentiment profile in the league right now — the Wembanyama supermax official signing has the fanbase at a genuine organizational high, while the Fox standoff and cascading cap math questions are producing a simultaneous low-grade anxiety that refuses to fully recede. The dominant mood is pride with an undercurrent of held breath. Spurs fans are not panicking publicly but the private discourse has developed an edge that the public-facing confidence is working hard to suppress. The organizational trust in Pop and Buford remains a genuine moderating force on sentiment that would otherwise be more volatile.",
    },
    {
      team: "NYK",
      teamFull: "New York Knicks",
      sentiment: "mixed",
      score: 34,
      buzzWords: ["Hartenstein MRI", "luxury tax", "champions", "Brunson locked", "week three evaluation", "Leon Rose", "restricted FA drama", "championship hangover"],
      narrativeSummary: "The Knicks are operating in the specific emotional register that only defending champions who are also New York teams can occupy: genuine championship pride mixed with the compulsive need to find the next existential crisis and nurture it to full maturity. Hartenstein's evaluation is the crisis of the moment and it is metastasizing with each passing day. Brunson's contract value discourse is the one genuine bright spot that is keeping the overall sentiment from collapsing into pure anxiety. The Knicks fanbase won the title and is already in defensive posture about retaining it — this is, historically, exactly what Knicks fans do and will continue to do until the next disaster or triumph clarifies the picture.",
    },
    {
      team: "OKC",
      teamFull: "Oklahoma City Thunder",
      sentiment: "positive",
      score: 88,
      buzzWords: ["secondary playmaker closing", "Presti genius", "SGA elite", "64 wins", "West favorite", "quiet dynasty", "flexibility preserved", "underrated"],
      narrativeSummary: "Oklahoma City's sentiment is the cleanest and most consistently positive of any team in the league entering this week. The combination of a final target reportedly identified for the secondary playmaker addition and the Fox situation potentially delivering conference primacy without requiring San Antonio's headache is giving Thunder fans a very specific kind of controlled optimism — the kind that comes from watching an organization do exactly what it said it would do for three consecutive years. They are not loud about it. They do not need to be. The record speaks at sufficient volume.",
    },
    {
      team: "MIA",
      teamFull: "Miami Heat",
      sentiment: "positive",
      score: 64,
      buzzWords: ["Fox recruitment", "Riley closing", "Heat Culture", "South Beach pitch", "daily contact", "evangelical", "lifestyle package", "believer energy"],
      narrativeSummary: "Miami's sentiment is running hotter than its actual probability of landing Fox would rationally justify, and that is precisely the Pat Riley effect in its purest form. The reported daily contact with Fox's camp has given Heat Twitter a narrative to inhabit rather than merely observe, and the Heat fanbase inhabits narratives with an evangelical commitment that is functionally independent of the underlying odds. The sentiment is genuine because the effort is genuine. Whether the effort produces the outcome is a separate question that nobody in South Beach is ready to engage with yet.",
    },
    {
      team: "DAL",
      teamFull: "Dallas Mavericks",
      sentiment: "neutral",
      score: 11,
      buzzWords: ["contingency planning", "Fox long shot", "Plan B", "offseason pivot", "cap flexibility", "realistic expectations", "next move", "reset"],
      narrativeSummary: "Dallas has moved from active Fox recruitment energy to quiet contingency planning and the fanbase is processing that transition with varying degrees of grace. The dominant sentiment is not despair — it is the specific flatness of a fanbase that spent three weeks invested in a recruitment that was always a long shot and is now recalibrating toward a more realistic offseason conversation. What the Mavericks do next will define whether this summer is remembered as a strategic pivot or a missed opportunity dressed up as a plan.",
    },
    {
      team: "GSW",
      teamFull: "Golden State Warriors",
      sentiment: "neutral",
      score: 16,
      buzzWords: ["Fox interest", "Steph legacy", "41-41 reality", "rebuild watch", "dynasty hangover", "brand strength", "cap questions", "long shot"],
      narrativeSummary: "Golden State's involvement in the Fox conversation continues to generate engagement that is disproportionate to their actual positioning in the offer sheet market. The Warriors finished .500 and their path to landing Fox requires San Antonio to decline matching rights they have every incentive to exercise — which is not a path so much as a prayer. The Steph factor and the organizational brand keep them in the conversation regardless of the math, and the fanbase is split between people running the realistic numbers and people who believe the Golden State brand is its own gravitational field.",
    },
    {
      team: "DET",
      teamFull: "Detroit Pistons",
      sentiment: "positive",
      score: 71,
      buzzWords: ["60 wins", "East's best record", "quiet confidence", "no offseason drama", "contender locked", "foundation solid", "building right", "focused"],
      narrativeSummary: "Detroit is doing what 60-win teams with no offseason drama do — existing in a calm and confident register while the teams generating headlines absorb all the discourse energy. The Pistons' fanbase is in a remarkably settled state for an organization that has been through significant rebuilding cycles in recent memory. The absence of crisis is its own positive sentiment signal and Detroit fans are choosing to enjoy it rather than manufacture catastrophe. This is unusual and admirable and likely to continue until someone gives them a reason to panic, which has not happened yet.",
    },
    {
      team: "BOS",
      teamFull: "Boston Celtics",
      sentiment: "mixed",
      score: 28,
      buzzWords: ["56 wins", "unfinished business", "retool", "4-6 close", "East second seed ceiling", "introspective offseason", "reset narrative", "quiet"],
      narrativeSummary: "Boston's offseason has the quality of a team processing something they have not fully named yet. The 56-win regular season is a genuinely strong foundation but the end-of-season slippage has lingered in the fanbase's subconscious in a way that a normal good-but-short-of-great year would not. Celtics Twitter is more introspective than its usual posture and the offseason moves have been deliberate without being dramatic. The sentiment is mixed because the team's ceiling remains genuinely unclear and the fanbase is honest enough to acknowledge it.",
    },
    {
      team: "DEN",
      teamFull: "Denver Nuggets",
      sentiment: "negative",
      score: -27,
      buzzWords: ["1-9 finish", "window closing", "Jokic peak", "roster overhaul", "West falling", "what happened", "front office pressure", "direction questions"],
      narrativeSummary: "Denver's sentiment is the most straightforwardly negative of any non-rebuilding team in the league and it is not recovering on its own. The 1-9 finish to the regular season is the wound that has not closed and the offseason has not produced the dramatic corrective action that would begin to address it. Jokic's individual brilliance is not in question but it is operating as a complicating factor — the greatest big man in the sport masking the degree to which the supporting cast has declined past the point of championship viability. The front office is under real pressure and the fanbase is not in a patient mood.",
    },
    {
      team: "HOU",
      teamFull: "Houston Rockets",
      sentiment: "positive",
      score: 61,
      buzzWords: ["ascending", "8-2 close", "West sleeper", "Fox implications", "52 wins", "young core breakout", "contender conversation", "next step"],
      narrativeSummary: "Houston is in the most genuinely optimistic non-championship position in the league entering this week. The 8-2 regular season close is the data point that keeps resurfacing in Rockets fan discourse and the Fox situation is being tracked with the intensity of a fanbase that has correctly identified itself as one of the primary beneficiaries of any disruption in San Antonio's roster construction. The sentiment is ascending rather than peaked — there is a real sense that Houston is on the way to somewhere rather than already there, and that specific energy produces the most sustained engagement of any fan community.",
    },
  ],
  playerSentiments: [
    {
      player: "Victor Wembanyama",
      team: "SAS",
      sentiment: "positive",
      score: 98,
      mentions: 34600,
      topTake: "The $350M supermax is officially signed and the discourse has already moved past celebration into all-time ranking arguments where Wembanyama keeps winning every bracket. At 22 years old with a Finals line that no center-adjacent player has ever produced, the contract is not the headline. It is the confirmation of a headline the sport already wrote.",
      narrativeArc: "Wembanyama's sentiment is operating at the ceiling of what is achievable for a player who is not actively playing games. The supermax official signing closed a chapter and opened a larger one — the 'where does he end up historically' conversation that is going to run for the next decade. Every mention is reverent, every comparison ends in his favor, and the contrarianism attempting to gain traction is being ratio'd out of existence with the efficiency of a 4.2 blocks-per-game shot blocker. His sentiment score is the highest in the league and it is not close.",
    },
    {
      player: "De'Aaron Fox",
      team: "SAS",
      sentiment: "mixed",
      score: 71,
      mentions: 41200,
      topTake: "Day 20. No signature. Fox has turned 'not doing anything' into the most compelling daily content in professional sports. His silence is not indecision — it is the most disciplined leverage play the restricted free agency system has ever witnessed, executed with the patience of someone who knows exactly what he is worth and is in absolutely no hurry to let anyone else set the price.",
      narrativeArc: "Fox's mention volume has surpassed Wembanyama's on a raw count basis today, which tells you everything about the difference between settled narratives and live ones. His score is positive-leaning because the basketball community respects the market management play even when it is generating organizational anxiety in San Antonio. The sentiment is mixed rather than positive because every day of uncertainty introduces new scenarios — some flattering, some not — that keep the full range of outcomes in play.",
    },
    {
      player: "Jalen Brunson",
      team: "NYK",
      sentiment: "positive",
      score: 93,
      mentions: 22100,
      topTake: "The 'best value contract in the East' discourse has found its anchor and it is Jalen Brunson locked through 2028 at a cap figure negotiated before his ceiling was fully understood. Finals MVP. 44 points in Game 7. Contract that looks below market and is legally inviolable. The Knicks won the title and the front office simultaneously. This is not supposed to happen to New York teams.",
      narrativeArc: "Brunson has settled into the most comfortable legacy position available to a player in the offseason — celebrated, contractually secure, and generating a new type of appreciation as his deal becomes the benchmark contract-value comparison in every 'best existing contracts' conversation NBA Twitter is running this week. His score is as high as it has been since the Game 7 final buzzer and it is holding with unusual consistency.",
    },
    {
      player: "Shai Gilgeous-Alexander",
      team: "OKC",
      sentiment: "positive",
      score: 89,
      mentions: 19800,
      topTake: "OKC is reportedly down to a final secondary playmaker target and SGA is sitting there with 64 wins and a legitimate top-three player argument watching the entire Western Conference narrative bend his direction. The rest of the West has been too busy watching San Antonio's payroll situation combust to notice what Presti is building around him in real time.",
      narrativeArc: "SGA's offseason narrative is the cleanest ascending arc in the sport — no drama, no health concerns, no contract complexity, just a generational talent whose organizational situation keeps improving while the teams around him deal with entropy. His mention spikes track directly to OKC roster reporting and every spike lands positive. The trajectory is entirely upward and the Fox situation is functioning as a potential tailwind.",
    },
    {
      player: "Karl-Anthony Towns",
      team: "NYK",
      sentiment: "positive",
      score: 80,
      mentions: 10300,
      topTake: "KAT defended Wembanyama in the two most important games of the 2026 Finals and the Knicks won both. The defensive credibility conversation ended in June and should have been buried by now. He is a champion, he answered the only question anyone had left about his career, and the discourse has finally, mercifully, caught up to the reality.",
      narrativeArc: "Towns is in the comfortable post-championship holding pattern of a player whose narrative has fully resolved. His championship validation against the most dominant interior defender in modern basketball history is the definitive closing argument on his career arc, and the sentiment reflects a player who arrived at exactly the right historical moment and took full advantage of it. His mentions are stable and positive without the acute daily energy of players in live transactional situations.",
    },
    {
      player: "Stephon Castle",
      team: "SAS",
      sentiment: "mixed",
      score: 44,
      mentions: 14700,
      topTake: "Castle extension talks advancing is good. Castle being described as 'progressing' while the Game 7 film is still circulating on Twitter is complicated. Pop's confidence is unambiguous and Pop's track record on player development bets is unimpeachable. The Game 7 turnovers happened. Both things are true simultaneously and the discourse is not ready to reconcile them yet.",
      narrativeArc: "Castle's extension progress has reignited a debate that was never really settled — the tension between his undeniable defensive ceiling and the specific high-leverage failure that defined the most watched game of his young career. The Spurs' organizational confidence is the most important signal but it is not sufficient to quiet the skeptics who keep returning to the Brunson tape. His sentiment is genuinely split and will remain so until year-two evidence tips the scales.",
    },
    {
      player: "OG Anunoby",
      team: "NYK",
      sentiment: "positive",
      score: 83,
      mentions: 9800,
      topTake: "+11 series plus/minus. The best individual defensive assignment execution in the 2026 playoffs. OG Anunoby contained De'Aaron Fox across seven games well enough to swing the series and it is still somehow not the first thing people say when they talk about the Knicks' championship. The analytics community sees it. The tape does not lie. It just takes casual fans longer to find the tape.",
      narrativeArc: "Anunoby's offseason narrative is the quietest positive on the Knicks' championship roster — understated, analytically beloved, culturally underhyped relative to the actual quality of his Finals performance. The hamstring is on full offseason rest and has not developed into a genuine storyline. His trajectory is entirely settled and positive and the basketball community is doing the right thing by letting the plus/minus speak without adding unnecessary drama.",
    },
    {
      player: "Isaiah Hartenstein",
      team: "NYK",
      sentiment: "mixed",
      score: -11,
      mentions: 16900,
      topTake: "Week three of Hartenstein's knee evaluation and no resolution. The restricted free agency clock does not care about the medical timeline. Some team is going to figure out that the Knicks are operating with incomplete health information and decide that is the exact moment to submit a sheet. Knicks fans can feel this coming. They cannot stop it. They cannot stop looking at their phones.",
      narrativeArc: "Hartenstein's sentiment has dipped further into negative territory as the evaluation's duration compounds the anxiety of his restricted free agency situation. His mention volume is high for a backup center — driven entirely by compounding dread rather than any positive development — and the score reflects the specific punishment that social media applies to unresolved uncertainty regardless of whose fault it is. He is a champion and a quality player whose offseason is being defined by variables outside his control.",
    },
    {
      player: "Josh Hart",
      team: "NYK",
      sentiment: "positive",
      score: 92,
      mentions: 9200,
      topTake: "Thirteen rebounds in Game 7 of the NBA Finals. Josh Hart is the definitional proof that doing everything right, every night, without complaint or credit-seeking, eventually produces exactly the moment that makes everyone who ever doubted you look directly into a camera and say nothing. He has a ring. He earned it more completely than almost anyone on either roster.",
      narrativeArc: "Hart's post-championship sentiment is pure warmth without a single discordant note and it has sustained longer into the offseason than a role player's news cycle would typically support. The cultural resonance of his Game 7 performance has transcended the basketball discourse and the mainstream sports audience is fully on board. He is the most universally beloved player in Knicks championship history since Willis Reed and the internet is not exaggerating about this.",
    },
    {
      player: "Mikal Bridges",
      team: "NYK",
      sentiment: "positive",
      score: 75,
      mentions: 7900,
      topTake: "2.9 threes per game in the Finals. Contract not a problem. Locked on a championship roster. Mikal Bridges is the most underappreciated piece of the 2026 title team and the only reason nobody is leading with his name is that Brunson and Hart keep giving the discourse bigger stories every single day. The floor spacing was decisive. Someone should say it more.",
      narrativeArc: "Bridges is operating comfortably below the narrative surface in the way that best describes a player who has found exactly the right role on exactly the right team and is excelling in it without requiring the spotlight to function. His sentiment is positive and stable, his contract is uncomplicated, and his championship validation is total. There is nothing wrong with Mikal Bridges' offseason. There is also nothing particularly loud about it.",
    },
    {
      player: "Dalen Terry",
      team: "SAS",
      sentiment: "positive",
      score: 65,
      mentions: 7400,
      topTake: "Two teams reportedly sniffing around Terry as a restricted FA target tells you everything about what 2.0 steals per game in the Finals does for a player's market value. San Antonio will match. But watching a front office already staring down a $700M top-three payroll decide whether to also retain its best defensive reserve is going to be one of the more interesting cap management exercises of the summer.",
      narrativeArc: "Terry has graduated from footnote to genuine subplot as reported offer sheet interest makes his situation financially real. The expectation remains San Antonio retention, but the cap context makes even low-probability outcomes worth discussing and the basketball community has correctly identified that his restricted status represents a possible pressure point for an organization with very limited payroll flexibility below the top three. His sentiment is positive because his Finals value was unambiguous.",
    },
    {
      player: "Nikola Jokic",
      team: "DEN",
      sentiment: "mixed",
      score: 26,
      mentions: 12800,
      topTake: "Jokic is still the most skilled big man alive and that is not the debate. The debate is whether Denver's supporting cast has declined past the point where even the most dominant individual talent can carry them back to championship contention. The 1-9 finish is not a Jokic problem. It is a 'what do you build around Jokic' problem and the Nuggets front office is running out of time to solve it convincingly.",
      narrativeArc: "Jokic's sentiment is being suppressed by Denver's team-level narrative failure despite his individual brilliance remaining beyond reproach. The 'window closing' discourse has become the dominant frame for every Nuggets conversation and Jokic — the most important player on the most troubled roster among genuine contenders — cannot fully escape that gravitational pull. His mentions remain high because he is always a reference point in historical player discussions, but the specific negative cast of Denver's offseason is dampening what should be pure appreciation.",
    },
    {
      player: "Pat Riley",
      team: "MIA",
      sentiment: "positive",
      score: 72,
      mentions: 9600,
      topTake: "Pat Riley reportedly in daily contact with Fox's camp for twenty straight days. He is 81 years old and he is still the single most dangerous recruiter in professional basketball. The man should not be able to do what he is doing at this stage of his career. He is doing it anyway. Do not bet against him on closing arguments. The record does not support betting against him.",
      narrativeArc: "Riley is not a player but his presence in the Fox recruitment narrative has made him one of the most-discussed figures in the offseason. Heat fans treat his involvement as a closing argument in itself and the broader NBA community engages with Riley recruitment stories because they are reliably compelling independent of outcome. His positive sentiment reflects genuine respect from across team lines — the basketball community's recognition that watching a legend operate is worth following regardless of which side you are on.",
    },
    {
      player: "Sam Presti",
      team: "OKC",
      sentiment: "positive",
      score: 81,
      mentions: 8100,
      topTake: "Sam Presti reportedly down to a final secondary playmaker target while maintaining full cap flexibility on a 64-win roster and potentially inheriting the West if Fox leaves San Antonio. This is not roster construction. This is four-dimensional chess being played in a building where everyone else brought checkers.",
      narrativeArc: "Presti's name drives narrative in a way that places him among the most-discussed figures in the offseason despite never playing a minute. OKC's methodical efficiency is attributed almost entirely to his vision and the sentiment is that of a community watching a master class in slow motion — quiet, precise, and correct at a frequency that long ago moved past coincidence into something closer to organizational identity.",
    },
    {
      player: "Leon Rose",
      team: "NYK",
      sentiment: "mixed",
      score: 19,
      mentions: 8800,
      topTake: "Leon Rose is managing championship roster retention, a luxury tax bill that would cause physical symptoms in a normal person, and an unresolved medical evaluation on a restricted free agent simultaneously while the entire fanbase watches through their fingers. This is either the most stressful front office job in basketball or proof that some people are simply built differently. Possibly both.",
      narrativeArc: "Rose is absorbing the organizational anxiety that the Knicks fanbase cannot direct at its universally celebrated players. The Hartenstein situation has made him the focal point of New York's offseason criticism — not unfair criticism but the specific kind that comes with managing a championship roster's cap sheet while a medical clock runs in public and a competing team could force a nine-figure decision at any moment. His sentiment is stuck in mixed territory until the Hartenstein situation resolves.",
    },
  ],
  hottestTake: "Fox needs to sign the Heat offer sheet before Tuesday. Not because Miami is definitively better than San Antonio — it is not, on paper, right now — but because the leverage window has a ceiling and he has been approaching it for twenty days. The Spurs matching his max alongside Wemby's supermax leaves them with championship aspirations and minimum-contract depth. Fox goes to Miami, Riley builds around him inside two years, and in 2028 we're watching a Heat-Thunder Finals while San Antonio's seventh man is someone's cut from training camp. The leverage play was perfect. The exit is the completion of the play. Stop savoring it and sign the sheet.",
  coldestTake: "Victor Wembanyama's $350 million supermax is actually a reasonable argument for overpay risk when you discount the contract value over five years against historical injury rates for players whose game depends on elite length and athleticism at 22. San Antonio should have pushed for a shorter initial term with a player option. The Finals performance was historic. The contract commitment is also historic. These are not the same thing.",
};