// Auto-generated by generate-tactics.mjs
// Week of August 31–6, 2026

export interface TacticalBreakdown {
  team: string;
  coach: string;
  offenseStyle: string;
  defenseScheme: string;
  paceRank: number;
  offRatingRank: number;
  defRatingRank: number;
  keyPlay: {
    name: string;
    description: string;
    frequency: string;
    efficiency: string;
  };
  weeklyAdjustment: string;
  schemeGrade: "A+" | "A" | "A-" | "B+" | "B" | "B-" | "C+" | "C" | "C-" | "D" | "F";
  narrative: string;
}

export interface WeeklySchemeWatch {
  title: string;
  description: string;
  teams: string[];
}

export interface TacticsData {
  generatedDate: string;
  weekLabel: string;
  breakdowns: TacticalBreakdown[];
  schemeOfTheWeek: { team: string; title: string; description: string };
  trendingTactics: WeeklySchemeWatch[];
  coachHotSeat: { coach: string; team: string; reason: string; temperature: "scorching" | "warm" | "lukewarm" }[];
  weeklyNarrative: string;
}

export const tacticsData: TacticsData = {
  generatedDate: "August 31, 2026",
  weekLabel: "Week of August 31–6, 2026",

  weeklyNarrative:
    "The dead period's final week sharpens the gap between organizations that spent the summer building and those that spent it stalling. San Antonio enters September with the cleanest tactical blueprint in the league — a Finals-validated three-star core locked through the decade, a scheme identity so deeply embedded that coaching adjustments in training camp feel like refinements rather than rewrites. Oklahoma City's preparation depth compounds quietly in the background, their pace-and-pressure system now entering its fourth iteration with SGA at full contractual certainty. The organizational drag accumulating in Denver and Minnesota, by contrast, will arrive at camp as a live tactical variable: coaches forced to scheme around roster uncertainty rather than install new wrinkles. Houston's freeze extends to its on-court implications this week — Sengun's read-and-react post game is impossible to fully build around when his long-term presence remains unconfirmed on paper. The teams that resolved their summers early are already coaching. The teams that didn't are still negotiating.",

  schemeOfTheWeek: {
    team: "San Antonio Spurs",
    title: "The Gravity Stack — Wembanyama-Fox Vertical Spacing System",
    description:
      "San Antonio's Finals-winning offensive architecture deserves full structural examination heading into year four. The core mechanism is deceptively simple: Wembanyama stations at the elbow or short corner, his gravity pulling rim-protecting bigs into impossible two-man-game decisions, while Fox operates as the primary ball-handler in the open 45-foot corridor that gravity creates. The system layers a third dimension through Castle's off-ball movement — using his 2.4 SPG reputation defensively to manufacture cautious closeouts that open driving lanes before Fox even initiates contact. What distinguishes this scheme from generic star-spacing is that its efficiency doesn't require Wembanyama to shoot every possession; his threat radius alone dislocates defenses so severely that Fox generates 1.18+ PPP on mid-range pull-ups that would be contested in any other personnel context. After a championship run, Pop's staff enters camp with the rare luxury of installing counter-actions to counters opponents spent all summer designing — a second-order tactical advantage that only Finals participants earn.",
  },

  breakdowns: [
    {
      team: "San Antonio Spurs",
      coach: "Gregg Popovich",
      offenseStyle: "Gravity-stack spacing with Fox pick-and-roll primary",
      defenseScheme: "Wembanyama anchor drop — zone-switch hybrid on perimeter",
      paceRank: 14,
      offRatingRank: 1,
      defRatingRank: 2,
      keyPlay: {
        name: "Horns Flex — Wemby Elbow Pop",
        description:
          "Fox and Castle set up in Horns alignment at each elbow. Fox dribble-enters toward Wembanyama's elbow screen, rejects it, and attacks the open nail as Wembanyama pops to the short corner. Castle curls off a staggered flex screen from the weakside forward, creating a three-way read: Fox attack, Wemby pop three, Castle curl layup. The design punishes any defense that hedges the Fox drive by leaving a 7-foot shooter at 22 feet.",
        frequency: "28% of half-court possessions",
        efficiency: "1.21 PPP",
      },
      weeklyAdjustment:
        "With the Finals MVP cycle complete and no active roster uncertainty, Pop's staff used this week to install two new Horns counter-actions targeting the ice coverage schemes three Eastern opponents ran in the Finals — a luxury available only because organizational architecture is fully sealed entering camp.",
      schemeGrade: "A+",
      narrative:
        "San Antonio's scheme is the most difficult to scout in the league precisely because its efficiency doesn't require any single action to succeed — the system generates advantages through threat multiplication rather than execution reliance. Wembanyama's 4.2 BPG anchors a defensive scheme that can afford to gamble on perimeter switches because rim deterrence is never in question. Fox's 28.0 PPG average is partly a product of the spacing architecture; the same shot diet in a lesser system would yield four fewer points per game. Entering year four with a locked core and zero organizational distraction, Pop's staff is positioned to install the most tactically complex system in the Western Conference — and face opponents who spent the summer reacting to what they just watched instead of preparing for what's coming next.",
    },
    {
      team: "Oklahoma City Thunder",
      coach: "Mark Daigneault",
      offenseStyle: "pace-and-pressure transition with SGA isolation creation",
      defenseScheme: "Aggressive hedge-and-recover on all ball screens, length switching 1-4",
      paceRank: 2,
      offRatingRank: 3,
      defRatingRank: 4,
      keyPlay: {
        name: "Spain PnR — SGA Rejection",
        description:
          "SGA operates as the ball-handler in a traditional Spain PnR set, with a screener on the roll and a back-screener attacking the hedging big. SGA reads the back-screen action and rejects the primary screen entirely, turning the corner in the opposite direction where the back-screener's movement has cleared his primary defender. The play creates a live two-on-one in the mid-paint before the defense can rotate from the Spain back-screen action.",
        frequency: "22% of half-court possessions",
        efficiency: "1.17 PPP",
      },
      weeklyAdjustment:
        "Daigneault's staff used this week to formalize transition-to-halfcourt connective actions, building direct bridges from SGA's push pace into their Spain PnR sets — reducing the organizational delay between open-floor opportunities and structured half-court attack that cost them two close games in last spring's conference semifinals.",
      schemeGrade: "A",
      narrative:
        "OKC's fourth-iteration system under Daigneault is the league's most coherent developmental scheme — every layer was installed with the explicit intention of compounding, meaning year-four adjustments build on year-three counters rather than replacing them. SGA's max certainty removes the single variable that could have disrupted installation sequencing entering camp. The Spain PnR rejection is a microcosm of what Daigneault builds: a play that creates its advantage by making the defense react to a threat that never actually materializes. At 64-18 and fully resolved, Oklahoma City is positioned to enter October as the league's most preparation-complete non-champion — which, historically, is a dangerous thing to be.",
    },
    {
      team: "New York Knicks",
      coach: "Tom Thibodeau",
      offenseStyle: "Brunson isolation-and-creation with Towns lob gravity",
      defenseScheme: "Physical drop coverage on bigs, switching 1-3 on perimeter",
      paceRank: 22,
      offRatingRank: 6,
      defRatingRank: 9,
      keyPlay: {
        name: "Floppy — Brunson DHO Chase",
        description:
          "Towns sets a wide pindown on the weakside for a wing shooter while Brunson receives a dribble handoff (DHO) from the strong-side forward at the elbow. The wing's floppy action occupies one defender, and Brunson attacks off the DHO with a live two-man game against a defensive unit that has redistributed one body to cover the floppy cut. Towns then slips the high ball-screen following Brunson's attack to create a lob opportunity at the rim.",
        frequency: "25% of half-court possessions",
        efficiency: "1.14 PPP",
      },
      weeklyAdjustment:
        "Following the championship validation, Thibodeau's staff is this week formalizing a faster DHO-into-Towns-lob sequencing package specifically designed to attack drop coverages — the scheme opponents leaned on most heavily against New York's half-court attack in the Eastern Conference Finals.",
      schemeGrade: "B+",
      narrative:
        "The Knicks' championship confirms that Thibodeau's deliberately slow pace is a feature, not a limitation — controlling possessions at 22nd in pace while ranking sixth in offensive rating means New York converts a higher percentage of their fewer opportunities than almost any team in the league. Brunson's 44-point Game 7 was the tactical thesis made explicit: when the isolation well runs dry, the DHO-and-Towns-lob counter is waiting. The risk entering year two of the championship core is complacency in scheme installation; Thibodeau's staff historically resists wrinkle-adding in the offseason, which served them well when building from scratch but may limit the counter-counter layer that Finals-experienced opponents will have studied. The championship buys time. It doesn't eliminate the clock.",
    },
    {
      team: "Houston Rockets",
      coach: "Ime Udoka",
      offenseStyle: "Sengun post-initiation with four-out floor spacing",
      defenseScheme: "Aggressive blitz on all post entries, switchable perimeter 2-4",
      paceRank: 11,
      offRatingRank: 8,
      defRatingRank: 7,
      keyPlay: {
        name: "Post-to-Short-Roll — Sengun Read Series",
        description:
          "Sengun receives a post entry on the mid-post block while four perimeter players space to the corners and wings. A guard short-rolls off a ghost screen near the free-throw line as Sengun faces up. Sengun reads the blitz rotation: if two defenders collapse, he kicks to the short-roll guard for a pull-up or drive; if the defense sinks, he pivots to a baby hook over the single defender. The play's efficiency comes from its dual-threat structure that makes blitzing statistically costly.",
        frequency: "31% of half-court possessions",
        efficiency: "1.09 PPP",
      },
      weeklyAdjustment:
        "Despite Houston's front-office freeze on Sengun's extension, Udoka's staff has continued installing his post-read series without modification — a tactical decision that implicitly signals organizational confidence while simultaneously deepening Sengun's read-and-react library ahead of a contract situation that may resolve before camp opens.",
      schemeGrade: "B",
      narrative:
        "Houston's tactical picture this week is inseparable from its organizational one: Udoka is building a Sengun-anchored offensive system around a player whose long-term presence remains unconfirmed on paper. That creates a genuine installation tension — the post-read series is maximally efficient with Sengun as its hub, but its complexity makes it difficult to retrofit around an alternative center if the extension collapses. The four-out spacing is correctly designed to suppress blitz rotations, and Sengun's 3.1 APG from the post suggests he is reading those rotations at an above-average rate for a big. If the freeze breaks before camp, Houston enters October with the league's most unique offensive foundation. If it doesn't, Udoka may spend September scheming contingencies he'd rather not need.",
    },
    {
      team: "Denver Nuggets",
      coach: "David Adelman",
      offenseStyle: "Jokic hub-and-spoke with Murray off-ball creation",
      defenseScheme: "Drop coverage with Murray weak-side help, Jokic as roaming free safety",
      paceRank: 18,
      offRatingRank: 4,
      defRatingRank: 13,
      keyPlay: {
        name: "Dribble-Hand-Off Series — Jokic High Post Hub",
        description:
          "Jokic positions at the high post and initiates a DHO sequence with a guard curling off the action. Murray reads the DHO from the weakside, timing a backdoor cut if his defender overplays the curl, or spacing to the corner if the defense sinks. Jokic retains the ball and reads a secondary roll-man action as defenses collapse on the DHO threat. The play generates 1.19 PPP when Murray's backdoor reading is correctly timed, degrading to 0.94 PPP when his read-timing is disrupted by defensive communication.",
        frequency: "27% of half-court possessions",
        efficiency: "1.06 PPP",
      },
      weeklyAdjustment:
        "With Murray's extension silence now hardened into institutional precedent at sixteen days, Adelman's staff faces a genuine camp-planning tension this week: the DHO series is calibrated around Murray's specific cutting timing and off-ball reading, meaning its installation depth is directly sensitive to his availability and engagement level entering October.",
      schemeGrade: "B-",
      narrative:
        "Denver's offensive system remains individually elite at its Jokic hub — 26.4 PPG, 12.7 RPG, and 8.0 APG from a center still represents the most statistically dominant individual production in the league at his position. The tactical problem is that the system's efficiency ceiling is a function of Murray's off-ball read-timing, which is itself a function of game reps together, which is a function of a training camp relationship that sixteen days of organizational silence has made complicated before it began. Adelman inherited a championship system and a championship roster; he is now managing the gradual institutional calcification of a franchise that won with continuity and is at risk of losing it through inaction. The drop coverage on defense is correctly calibrated for Jokic's help instincts but leaves Murray as a weak-side gambler — a bet that only pays when Murray is locked in, motivated, and present.",
    },
    {
      team: "Minnesota Timberwolves",
      coach: "Chris Finch",
      offenseStyle: "Edwards isolation-and-transition with five-out spacing",
      defenseScheme: "Switch-everything 1-5 with Edwards as primary perimeter stopper",
      paceRank: 7,
      offRatingRank: 10,
      defRatingRank: 6,
      keyPlay: {
        name: "Zipper Cut — Edwards ISO Trigger",
        description:
          "A wing player executes a zipper cut from the corner through the lane to the elbow, receiving a pass from the top-of-key ball-handler and immediately entering a live one-on-one for Edwards off a brush screen at the wing. The zipper cut occupies the weakside helper for a critical half-second, opening the Edwards one-on-one before help can rotate. Edwards reads rim versus pull-up based on whether the helper completes rotation in time — a read he converts at 47% from mid-range in isolation.",
        frequency: "33% of half-court possessions",
        efficiency: "1.11 PPP",
      },
      weeklyAdjustment:
        "With Minnesota's supporting-cast sequencing compression now entering its structural phase, Finch's staff used this week to install a wider Edwards isolation menu — a pragmatic acknowledgment that the five-out spacing may feature different personnel at camp than initially projected, requiring Edwards to operate with reduced screen-setting specificity.",
      schemeGrade: "B-",
      narrative:
        "Minnesota's tactical identity is the clearest star-dependent system in the Western Conference: Edwards is not merely the best player but the literal organizing principle around which every action is constructed. The switch-everything defense works because Edwards can guard 1-through-3 at a championship-level rate; the five-out offense works because his 27.8 PPG scoring threat pulls defensive attention with or without screens. The problem this week is that Finch is installing around a core whose surrounding cast remains a live variable — the zipper-cut action requires specific brush-screening personnel whose presence in October is not confirmed. Installing broadly rather than specifically is tactically sensible; it is also a symptom of organizational sequencing failure that the coaching staff should not have been left to absorb.",
    },
    {
      team: "Golden State Warriors",
      coach: "Steve Kerr",
      offenseStyle: "Motion-heavy off-ball system with Curry catch-and-shoot primary",
      defenseScheme: "Switching 1-4 with drop on five, paint-protection through help rotation",
      paceRank: 9,
      offRatingRank: 7,
      defRatingRank: 11,
      keyPlay: {
        name: "Spread Floppy — Curry Double-Stack Release",
        description:
          "Curry begins on the weakside block and runs off two stacked pindowns set by a big and a wing in sequence. The first screen is designed to be fought over — drawing the defender into contact — while the second screen catches the trailing defender. Curry receives a skip pass at the top of the arc coming off the second screen with a clean look from 28 feet. The play requires two defenders to communicate a switch in under 1.2 seconds; when they fail, the shot is uncontested.",
        frequency: "24% of half-court possessions",
        efficiency: "1.19 PPP",
      },
      weeklyAdjustment:
        "Kerr's staff installed a new double-stack release variation this week that adds a false-motion misdirection from the ball-handler before the skip pass — a counter to the communication improvement three playoff opponents displayed when defending Curry's standard floppy exits last spring.",
      schemeGrade: "A-",
      narrative:
        "Golden State's system has entered its mature evolutionary phase — Kerr is no longer building the motion offense, he is refining it against opponents who have spent a decade studying it. The double-stack floppy remains the league's most efficient shot-creation mechanism for a catch-and-shoot scorer precisely because its advantage is communication-based rather than athleticism-based: no amount of physical preparation eliminates the half-second defensive gap that two sequential screens create. The defensive scheme's 11th-ranked rating reflects a genuine personnel limitation at the five — the drop coverage concedes more short-roll pull-ups than the switching scheme Kerr prefers, but his current roster cannot execute a full switch-five without surrendering post-up advantages. Entering camp, the tactical ceiling is well understood and the floor is well-protected; the risk is that Curry's age curve narrows the margin for execution error that younger systems can absorb.",
    },
    {
      team: "Boston Celtics",
      coach: "Joe Mazzulla",
      offenseStyle: "Read-and-react five-out with Tatum-Brown dual creation",
      defenseScheme: "Aggressive switch-everything 1-5, full-court pressure triggers",
      paceRank: 16,
      offRatingRank: 5,
      defRatingRank: 3,
      keyPlay: {
        name: "Horns — Tatum-Brown Flex Counter",
        description:
          "Tatum and Brown set up in Horns with a center at the top of the key as initiator. The center dribble-enters left, triggering Brown's curl off a flex screen from the weakside forward. Tatum reads the help rotation: if Brown's defender helps on the curl, Tatum back-cuts to the rim for a lob from the reversing ball-handler. If the defense locks onto Tatum's back-cut, Brown continues the curl into a clean catch-and-shoot from the elbow. The play is self-reading and requires no verbal communication between Tatum and Brown.",
        frequency: "26% of half-court possessions",
        efficiency: "1.16 PPP",
      },
      weeklyAdjustment:
        "Mazzulla's staff this week finalized a new defensive pressure package designed to trigger at the 18-second mark of opposing possessions — a scheme built specifically to exploit the late-clock decision-making vulnerabilities that film review identified in their three playoff losses last spring.",
      schemeGrade: "A-",
      narrative:
        "Boston's five-out read-and-react system is the East's most intellectually demanding offensive scheme — it requires every player on the floor to read two actions ahead simultaneously, which is why its efficiency degrades sharply when the core rotation misses games. Tatum and Brown's dual-creation model is genuinely unusual in the modern NBA: two wings who can each initiate primary creation without requiring a point guard to generate their opportunities, which allows Mazzulla to field lineups that are defensively unconventional without sacrificing offensive initiation. The switch-everything defense ranked third last season and is structurally correct for the personnel — five players who can credibly guard every position from the perimeter. The residual tactical risk is familiarity: opponents have now played three full playoff series against this read-and-react system, and the late-clock pressure package Mazzulla installed this week suggests his staff knows the base system's counters have been filed.",
    },
    {
      team: "Los Angeles Lakers",
      coach: "JJ Redick",
      offenseStyle: "LeBron-led pace-push with Bron-as-playmaker primary",
      defenseScheme: "Zone-switch hybrid, conservative drop on ball screens",
      paceRank: 12,
      offRatingRank: 12,
      defRatingRank: 17,
      keyPlay: {
        name: "Push-Transition — LeBron Early Offense DHO",
        description:
          "LeBron initiates immediately off made baskets, pushing the pace before defenses can set. He targets a trailing wing at the three-point line with a DHO as the defense sets up, creating a live one-on-one for the wing before the help has organized. LeBron reads the DHO closeout: if the defender rushes, the wing attacks the gap; if the defender hedges, LeBron continues his own drive path off the DHO fake and attacks a defense in rotation. The play is designed to punish organized defenses by existing before they can organize.",
        frequency: "19% of all possessions",
        efficiency: "1.13 PPP",
      },
      weeklyAdjustment:
        "Redick's staff used this week to install new early-offense DHO counters that specifically target the wing-closeout rotations three Western Conference opponents ran to neutralize LeBron's transition push in last season's second round — the first evidence that his coaching staff is building a second-year adjustment layer rather than simply repeating year-one installation.",
      schemeGrade: "B",
      narrative:
        "Redick's second season as an NBA head coach arrives with the most important question already partially answered: his read-and-react early-offense philosophy is real, not cosmetic, and LeBron is genuinely invested in executing it rather than reverting to isolation-dominant habits when the system stalls. The push-transition DHO is a clever tactical device for a roster that lacks a true lead guard — it converts LeBron's passing instincts into a playmaking mechanism that creates advantages before defensive organization can eliminate them. The defensive scheme's 17th ranking is the honest limitation of this roster: the zone-switch hybrid disguises individual matchup problems but cannot manufacture rim protection that isn't on the floor. Entering year two, Redick's ceiling is defined by how aggressively he is willing to push scheme complexity on a roster whose defensive ceiling is medium by design.",
    },
    {
      team: "Memphis Grizzlies",
      coach: "Taylor Jenkins",
      offenseStyle: "Downhill pace-and-space with Morant transition creation",
      defenseScheme: "Physical blitz on ball screens, hard-hedge with rotation recovery",
      paceRank: 1,
      offRatingRank: 15,
      defRatingRank: 19,
      keyPlay: {
        name: "Push-Early — Morant Advance PnR",
        description:
          "Morant pushes immediately in transition and signals an advance ball screen from a trailing big at the three-point arc level before the defense has retreated. The screen is set at 25 feet, forcing the defending big to hedge at a position so high that the paint is uncontested. Morant reads the hedge: attack the paint directly off the hedge gap, or reset to the screener rolling downhill into an unmanned lane. The play requires a screener with enough pace to both set a credible screen and convert the downhill roll — personnel specificity that limits its use to particular lineup combinations.",
        frequency: "28% of possessions in transition-to-early-offense",
        efficiency: "1.08 PPP",
      },
      weeklyAdjustment:
        "Jenkins' staff used this week to widen the advance PnR screening personnel rotation after identifying that opponents overloaded their primary screener in the second half of last season — installing a secondary screener package that makes the advance screen play operable across four lineup configurations rather than two.",
      schemeGrade: "B-",
      narrative:
        "Memphis at first-in-pace is the league's most volatile tactical identity — it produces the highest variance in efficiency outcomes of any top-ten team, capable of generating 125 offensive rating nights and 101-point collapse performances against the same defensive scheme depending on Morant's decision-making volume on any given night. The advance PnR at 25 feet is a genuinely innovative tactical mechanism: it weaponizes transition momentum to create a ball-screen advantage before the defense can dictate its preferred hedging position. The defensive 19th ranking is the structural cost of playing at maximum pace — rotations that are clean at 18th in pace become a half-step late at first in pace, and those half-steps compound into open threes across a full possession sequence. Jenkins is building a system that prioritizes offensive ceiling over defensive floor, which is the correct decision for this roster and an honest acknowledgment of its personnel limits.",
    },
  ],

  trendingTactics: [
    {
      title: "The Gravity Stack — Spacing Systems Built Around Vertical Threat Bigs",
      description:
        "San Antonio's Finals-winning architecture has accelerated an already-emerging league trend: building offensive systems around bigs whose three-point threat is genuine enough to pull rim-protecting centers 22 feet from the basket, creating driving corridors for primary ball-handlers that would not exist in conventional four-out sets. The tactical innovation isn't the big shooting threes — that has existed since Dirk — it is the deliberate schematic decision to station the shooting big at the elbow or short corner rather than the corner, keeping him active in the offense's read sequence rather than parked as a static safety valve. Golden State's Curry-off-big-screens system operates on the same spacing-through-threat logic from the guard position. The teams most aggressively studying this architecture entering camp are Houston, whose Sengun presents a different but complementary version of the same problem for defenses, and Oklahoma City, whose screener rotation creates adjacent spacing pressures. Expect at least four teams to arrive at training camp with newly installed elbow-pop actions built around bigs who shot 36%+ from three last season.",
      teams: ["SAS", "GSW", "HOU", "OKC"],
    },
    {
      title: "The Communication Blitz — Targeting Defensive Switch Breakdowns at the 18-Second Mark",
      description:
        "Boston's new late-clock pressure package — designed to trigger at the 18-second mark — reflects a broader analytical trend that Synergy and second-spectrum tracking data confirmed this past season: defensive communication accuracy drops measurably after 14 seconds of offensive possession time, particularly on screens set after the primary action has already been defended. Teams that run patient, multi-action half-court offenses are building specific late-clock triggers designed to arrive precisely when opponent defensive communication is statistically most likely to fail. Mazzulla's 18-second trigger is the most formalized version of this trend, but variants are visible in Memphis's advance PnR timing sequencing, New York's DHO-to-Towns-lob chain, and San Antonio's Horns flex counter architecture. The defensive counter-trend — intensive late-clock communication drilling in training camp — is already visible in the scouting reports of at least six teams' preseason practice planning documents.",
      teams: ["BOS", "MEM", "NYK", "SAS"],
    },
    {
      title: "Early-Offense DHO as the New Half-Court Entry — Converting Transition Momentum",
      description:
        "The dribble handoff as an early-offense entry tool — rather than a mid-possession half-court action — is the summer's fastest-proliferating tactical concept. LeBron's push-transition DHO package formalized what several teams had been running informally: using the DHO as the first action off a made basket or inbound, positioning it before the defense has set rather than after. The mechanism converts transition momentum into a structured half-court advantage without requiring a traditional fast-break opportunity — it is, in tactical terms, a bridge between transition and half-court offense that eliminates the dead-ball reset possession most teams waste re-organizing. Daigneault's OKC staff has installed a version that bridges directly from SGA's push pace into their Spain PnR sets. Jenkins' Memphis advance PnR is a related variant. Redick's Lakers DHO counter package and Popovich's Horns-entry series both operate on the same foundational principle. By opening night, this action will appear in at least twelve team playbooks in some recognizable form.",
      teams: ["LAL", "OKC", "MEM", "SAS"],
    },
  ],

  coachHotSeat: [
    {
      coach: "David Adelman",
      team: "Denver Nuggets",
      reason:
        "Adelman inherited a championship system and the most statistically dominant center in the league, and he is now managing the active institutional degradation of both. Sixteen days of organizational silence on Murray has placed Adelman in the impossible position of installing a system calibrated around Murray's specific timing without confirmation that Murray arrives at camp with the motivation and focus that system requires. If October opens with Murray disengaged and the DHO series running at its degraded 0.94 PPP floor rather than its 1.19 PPP ceiling, the organizational failure will be attributed first to Adelman's inability to manage roster relationships — regardless of where the actual culpability lies. The hot-seat temperature is not about coaching competence; it is about organizational architecture creating coaching consequences.",
      temperature: "warm",
    },
    {
      coach: "Ime Udoka",
      team: "Houston Rockets",
      reason:
        "Udoka's seat is warm for a structurally unusual reason: he is coaching excellently inside an organizational freeze that limits the return on that coaching. The post-read series is correctly installed, the defensive blitz scheme is correctly calibrated, and the four-out spacing is the right counter to the double-teams Sengun attracts. None of that scheme quality converts into organizational stability while the front office's model freeze continues to generate leverage consequences in negotiations Udoka didn't initiate. If Sengun's extension breaks down and Houston enters camp with a restructured center rotation, every installation decision Udoka made this week becomes a sunk cost. His seat is warm not because he is coaching poorly but because the organization's inaction is making good coaching tactically irrelevant.",
      temperature: "lukewarm",
    },
    {
      coach: "Chris Finch",
      team: "Minnesota Timberwolves",
      reason:
        "Finch is the coach most directly absorbing the on-court consequences of Minnesota's multi-player sequencing compression. Installing Edwards's isolation menu broadly rather than specifically — because the personnel around him remains unresolved — is the correct pragmatic response to an organizational failure that Finch did not create. But arriving at training camp with a broadly-installed system rather than a specifically-refined one means Minnesota will spend the first two weeks of camp doing installation work that should have been completed in August. Those two weeks are when the league's best-prepared teams — San Antonio, Oklahoma City — are installing third-layer counter-actions. The gap between specific and broad installation is not cosmetic; it compounds across a full season into playoff-series preparation deficits that become visible in May.",
      temperature: "lukewarm",
    },
  ],
};