// Auto-generated by generate-tactics.mjs
// Week of May 25–31, 2026

export interface TacticalBreakdown {
  team: string;
  coach: string;
  offenseStyle: string;
  defenseScheme: string;
  paceRank: number;
  offRatingRank: number;
  defRatingRank: number;
  keyPlay: {
    name: string;
    description: string;
    frequency: string;
    efficiency: string;
  };
  weeklyAdjustment: string;
  schemeGrade: "A+" | "A" | "A-" | "B+" | "B" | "B-" | "C+" | "C" | "C-" | "D" | "F";
  narrative: string;
}

export interface WeeklySchemeWatch {
  title: string;
  description: string;
  teams: string[];
}

export interface TacticsData {
  generatedDate: string;
  weekLabel: string;
  breakdowns: TacticalBreakdown[];
  schemeOfTheWeek: { team: string; title: string; description: string };
  trendingTactics: WeeklySchemeWatch[];
  coachHotSeat: { coach: string; team: string; reason: string; temperature: "scorching" | "warm" | "lukewarm" }[];
  weeklyNarrative: string;
}

export const tacticsData: TacticsData = {
  generatedDate: "May 25, 2026",
  weekLabel: "Week of May 25–31, 2026",

  weeklyNarrative:
    "The 2026 Conference Finals have crystallized into a league-wide tactical referendum on verticality versus switchability. Victor Wembanyama's Game 4 resurrection in San Antonio — 31 points, 18 rebounds, 5 blocks, a plus-24 — was not merely a performance; it was a schematic indictment of OKC's decision to abandon the drop coverage that had contained him in Games 1 and 2. When Mark Daigneault switched to a hedge-and-recover scheme in Game 3, Wembanyama immediately found the mid-roll pocket and destroyed it. Gregg Popovich Jr. recognized the adjustment within four possessions of Game 4 and countered with back-to-back Spain pick-and-rolls that forced OKC's bigs into impossible closeout angles. In the East, Tom Thibodeau's Knicks stand one win from the Finals on the back of a scheme that is deceptively simple — physical early-offense, punishing size mismatches at every level, and a Mikal Bridges free-safety role that is the most underanalyzed element of any defense still alive in the playoffs. Cleveland faces elimination tonight with a tactical identity in full crisis, and the question is no longer whether Kenny Atkinson can fix it in a single game — it is whether the franchise's summer decisions will finally align personnel with the switch-everything philosophy his staff has been trying to force onto a roster built for drop.",

  schemeOfTheWeek: {
    team: "San Antonio Spurs",
    title: "The Wembanyama Vertical Gravity System",
    description:
      "Popovich Jr.'s staff has spent three seasons constructing what amounts to a gravitational field around Wembanyama's unique skill set, and Game 4 of the WCF was its fullest expression. The system operates on two simultaneous threats that no defense has solved: Wembanyama as a perimeter initiator who can skip passes over hedging bigs, and Wembanyama as a screener-roller whose 7-foot-4 wingspan means any drop coverage leaves him with a clean mid-roll catch at the nail. In Game 4, San Antonio ran their 'Tall Spain' action — a Spain pick-and-roll variant where Wembanyama functions as the back-screener rather than the ball-handler — on 11 possessions, generating 1.21 PPP. The adjustment that broke OKC was the addition of a corner pin-down for De'Aaron Fox immediately after the Wembanyama roll, creating a second decision point that arrived before OKC's rotation could reset. It is the most sophisticated two-man game architecture in the playoffs, and it is being run by a 22-year-old and a 27-year-old.",
  },

  breakdowns: [
    {
      team: "San Antonio Spurs",
      coach: "Gregg Popovich Jr.",
      offenseStyle: "Vertical gravity motion with Wembanyama as screener-initiator",
      defenseScheme: "Protective drop with Wembanyama as free-roaming weak-side eraser",
      paceRank: 12,
      offRatingRank: 2,
      defRatingRank: 4,
      keyPlay: {
        name: "Tall Spain PnR",
        description:
          "Wembanyama sets a back-screen on the ball-handler's defender before re-screening as the roll man, exploiting any coverage that tries to account for both his shooting range and his roll threat simultaneously. Fox initiates, Castle spots up in the corner, and Wembanyama's roll to the nail forces the defense to choose between contesting the layup and recovering to the corner three.",
        frequency: "22% of half-court possessions",
        efficiency: "1.21 PPP",
      },
      weeklyAdjustment:
        "After OKC's hedge-and-recover scheme neutralized the standard Horns set in Games 1–2, Popovich Jr.'s staff added the corner pin-down wrinkle for Fox post-roll in Game 4, creating an immediate second decision point that collapsed OKC's rotation. Castle's return to attacking downhill rather than spotting early also opened the paint enough to restore Fox's driving lanes.",
      schemeGrade: "A+",
      narrative:
        "San Antonio's offensive scheme is built on a premise almost no team in NBA history has been able to exploit: a player who is simultaneously the best screener and the best shooter on the floor. Wembanyama's gravity as a perimeter threat means hedges are mandatory; his 7-foot-4 wingspan means any hedge opens a mid-roll pocket that is functionally unguardable. The Spurs' weekly adjustment in Game 4 — adding the Fox pin-down wrinkle immediately post-roll — was not improvisation; it was a prepared answer to a scouted contingency, which says everything about the organizational infrastructure being built around this generational talent. The series being tied 2-2 is not luck; it is the product of a staff that out-adjusted OKC's adjustment within a single game.",
    },
    {
      team: "Oklahoma City Thunder",
      coach: "Mark Daigneault",
      offenseStyle: "SGA-led two-man game with movement shooting off weak-side actions",
      defenseScheme: "Switch-everything on perimeter, ICE on ball-screen with bigs",
      paceRank: 5,
      offRatingRank: 3,
      defRatingRank: 1,
      keyPlay: {
        name: "SGA Elbow Iso into DHO",
        description:
          "SGA receives the ball at the elbow, probes with two dribbles to collapse the paint, then pivots into a dribble hand-off for the trailing shooter — typically McCain or a corner wing. The action is designed to manufacture clean catch-and-shoot threes after the defense over-rotates toward SGA's drive, and it generated OKC's highest-frequency half-court looks all postseason.",
        frequency: "28% of half-court possessions",
        efficiency: "0.97 PPP",
      },
      weeklyAdjustment:
        "After switching to hedge-and-recover on Wembanyama screens in Game 3 — which worked briefly — Daigneault's staff failed to counter San Antonio's Tall Spain counter in Game 4. OKC's bigs were caught in no-man's land on 14 possessions, and the coaching staff did not have a clean answer by the fourth quarter. Game 5 requires either a return to pure drop on Wembanyama or a complete personnel swap to smaller, switchable lineups.",
      schemeGrade: "B-",
      narrative:
        "OKC's defensive scheme — the best in the league by regular-season metrics — is facing an unprecedented challenge in Wembanyama, and the cracks showed badly in Game 4. The decision to hedge rather than drop was defensible in theory but catastrophic in execution because it assumed Wembanyama would not punish the hedge with a clean roll, which he proceeded to do on eleven consecutive possessions. Daigneault is a brilliant schematic mind, but this week exposed the limits of any defensive philosophy when the offensive player it is facing has no true analog. SGA's offensive frustration — held well below his WCF average — compounds the problem: OKC's offense is increasingly predictable when SGA cannot get downhill, and San Antonio's switching scheme has found a way to funnel him into pull-up mid-range situations rather than his preferred paint attacks.",
    },
    {
      team: "New York Knicks",
      coach: "Tom Thibodeau",
      offenseStyle: "Early-offense mismatch hunting with Towns as read-and-react hub",
      defenseScheme: "Physical man-to-man, no-middle ICE coverage, aggressive on-ball denial",
      paceRank: 22,
      offRatingRank: 7,
      defRatingRank: 6,
      keyPlay: {
        name: "Horns Flare — Bridges Back-Cut",
        description:
          "Towns and a second big set Horns at the elbows while Bridges sets up his defender with a hard jab toward the corner before cutting backdoor off a Towns fake-hand-off screen. The action generates layups when Cleveland over-plays Bridges' three-point threat — which, after his 73.3% Game 3, they are now obligated to do. Brunson reads the cut and delivers the skip pass.",
        frequency: "18% of half-court possessions",
        efficiency: "1.18 PPP",
      },
      weeklyAdjustment:
        "With Cleveland likely to shade extra attention onto Brunson as a pick-and-roll initiator in a must-win elimination game, Thibodeau's staff installed the Horns Flare back-cut specifically to punish over-aggressive denial. Bridges' shooting reputation — cemented by Game 3 — now creates defensive pressure that opens the very backdoor cut the Knicks want. The adjustment turns Bridges' efficiency against Cleveland's gameplanning.",
      schemeGrade: "A",
      narrative:
        "Thibodeau's Knicks are the most complete team remaining in the playoffs and their tactical identity is crystallizing at exactly the right moment. The Towns-as-hub concept — not a scorer but an orchestrator who creates the conditions for everyone else — is the most underrated offensive innovation of the 2026 postseason. His near-triple-double with a plus-23 in Game 3 is the statistical signature of a player executing a role that requires sacrificing counting stats for positional dominance. The Bridges situation is tactically delicious: his 73.3% shooting performance has made him so dangerous that Cleveland must now over-commit to his three, which opens the backdoor cut that the Knicks have specifically prepared for this week.",
    },
    {
      team: "Cleveland Cavaliers",
      coach: "Kenny Atkinson",
      offenseStyle: "Mitchell-led isolation with secondary pick-and-roll through Mobley",
      defenseScheme: "Switch-everything perimeter, Mobley as weak-side help anchor",
      paceRank: 14,
      offRatingRank: 11,
      defRatingRank: 8,
      keyPlay: {
        name: "Mitchell Isolation — Side PnR Counter",
        description:
          "Mitchell isolates at the top of the key, reads the hedge, and counters by handing to Mobley in a side pick-and-roll if doubled. The action is designed to use Mitchell's scoring threat to create a clean Mobley short-roll opportunity at the elbow, but New York's switch-everything scheme has been neutralizing it by assigning Anunoby to Mitchell regardless of action.",
        frequency: "31% of half-court possessions",
        efficiency: "0.89 PPP",
      },
      weeklyAdjustment:
        "Facing elimination in Game 4 tonight, Atkinson's staff reportedly installed a series of ghost-screen actions designed to manufacture open Mitchell drives rather than relying on isolation creation. The core problem remains unsolved: Mitchell's minus-53 cumulative ECF plus/minus reflects a team that is being out-schemed at every level, not merely outplayed. Atkinson needs a structural change, not a play call.",
      schemeGrade: "C+",
      narrative:
        "Cleveland's tactical situation is the most alarming in the conference finals: Mitchell's minus-53 cumulative plus/minus while averaging over 26 points is the definitive statistical portrait of high-volume empty scoring, and it reflects a scheme that has no answer for New York's physical, switching, denial-heavy defense. Atkinson's switch-everything defensive philosophy is being exposed by a Knicks team that has specifically assembled players — Towns, Bridges, OG — who exploit switches from every angle. The deeper problem is philosophical: Cleveland built this roster to operate in space with Mitchell as the engine, but Thibodeau's defense eliminates space by design. Tonight's elimination game is less about adjustments and more about whether this team is structurally equipped to survive this matchup.",
    },
    {
      team: "Boston Celtics",
      coach: "Joe Mazzulla",
      offenseStyle: "Five-out motion with Tatum-Brown two-man game hub",
      defenseScheme: "Aggressive switch-everything, blitz ball-screens in fourth quarters",
      paceRank: 9,
      offRatingRank: 1,
      defRatingRank: 3,
      keyPlay: {
        name: "Floppy Double — Tatum Curl",
        description:
          "Brown and Tatum run simultaneous curl and flare reads off a double staggered screen set by White and Horford. The ball-handler — typically Payton Pritchard in late-game — reads which defender cheats and delivers to the open shooter. The action is nearly impossible to guard without a switch, and when Boston switches it themselves, they create mismatches they then immediately attack.",
        frequency: "20% of half-court possessions",
        efficiency: "1.14 PPP",
      },
      weeklyAdjustment:
        "Boston is on the outside looking in after a second-round exit but their tactical evolution this season — specifically the integration of a true five-out spacing scheme alongside their physical switching defense — remains the blueprint most teams are trying to copy. The week's adjustment context is long-term offseason positioning rather than live series management.",
      schemeGrade: "A-",
      narrative:
        "Boston's tactical identity remains the league's most sophisticated blend of offensive freedom and defensive structure, and their second-round exit should be read as an execution failure rather than a scheme failure. Mazzulla's five-out system generates the highest frequency of open three-point attempts in the league while his switching defense simultaneously suppresses opponent paint touches — a combination that only works with elite personnel discipline. The Celtics' scheme will be the model for how the next generation of championship contenders are built, and the offseason question is whether Mazzulla can address the fourth-quarter decision-making breakdowns that cost them without dismantling the system that generated 55-plus wins.",
    },
    {
      team: "Denver Nuggets",
      coach: "David Adelman",
      offenseStyle: "Jokić-hub read-and-react with four-out spacing",
      defenseScheme: "Drop coverage on all ball-screens, pack-the-paint zone variations",
      paceRank: 19,
      offRatingRank: 4,
      defRatingRank: 15,
      keyPlay: {
        name: "Jokić High Post — Dribble-Entry Hand-Off",
        description:
          "Jokić receives at the high post, initiates a dribble series to collapse the nearest help defender, then delivers a pocket hand-off to a wing cutting baseline. The action is the foundation of Denver's entire offensive identity — it works because no defense can send a second defender at Jokić without surrendering a layup, and no single defender can guard his passing angles from the high post.",
        frequency: "34% of half-court possessions",
        efficiency: "1.19 PPP",
      },
      weeklyAdjustment:
        "Denver's second-round exit has redirected tactical analysis toward Adelman's first full offseason as the team's architect post-Malone. The week's context is personnel-scheme fit evaluation: whether the perimeter shooting Jokić needs to sustain the four-out spacing has been adequately addressed, and whether the defensive scheme can be tightened without sacrificing the offensive freedom that makes Denver's system unique.",
      schemeGrade: "B+",
      narrative:
        "The Nuggets' tactical identity is both their greatest asset and their most exploitable liability: Jokić's gravitational pull creates undefendable advantages, but the drop coverage scheme that protects his lateral limitations has become a known quantity that elite postseason teams specifically prepare for. Adelman's challenge is modernizing the defensive architecture without undermining the trust-and-read offensive system that Jokić requires. Denver's future depends on finding perimeter defenders who can switch aggressively enough to compensate for Jokić's drop without breaking the spacing geometry that feeds his playmaking — a personnel puzzle that no GM has fully solved.",
    },
    {
      team: "Minnesota Timberwolves",
      coach: "Chris Finch",
      offenseStyle: "Transition-first with Edwards-Gobert two-man game in the half court",
      defenseScheme: "Physical man-to-man with Gobert as weak-side drop anchor",
      paceRank: 3,
      offRatingRank: 8,
      defRatingRank: 5,
      keyPlay: {
        name: "Edwards Horns Attack — Gobert Lob",
        description:
          "Edwards receives in a Horns set at one elbow, ball-fakes to the opposite elbow screener, then attacks the paint off a Gobert back-screen. If the defense sinks to protect the rim, Edwards pulls up at the free-throw line; if they chase Edwards, Gobert catches the lob. The action exploits the binary choice that all defenses face when Edwards has a runway.",
        frequency: "25% of half-court possessions",
        efficiency: "1.11 PPP",
      },
      weeklyAdjustment:
        "Minnesota's second-round exit has put tactical scrutiny on Finch's late-game offensive execution — specifically the tendency to over-rely on Edwards isolation rather than running the Horns actions that generate cleaner looks. The week's adjustment context is scheme refinement for a team that has the talent to compete for a title but has not fully solved its late-game decision architecture.",
      schemeGrade: "B+",
      narrative:
        "Minnesota's tactical profile is fascinatingly bifurcated: they have arguably the most physical and disruptive defensive scheme in the Western Conference and an offensive system that has not yet been fully optimized around Edwards' specific skill set. Finch deserves credit for building a cohesive defensive identity around Gobert's drop coverage while manufacturing enough half-court offense to compete — but the second-round exit revealed that the late-game playbook lacks the variety needed against elite switching defenses. The Edwards-Gobert Horns action is one of the most efficient two-man plays in the league when it is run correctly; the challenge is that Finch's staff has not yet made it the default rather than the occasional counter.",
    },
    {
      team: "Golden State Warriors",
      coach: "Steve Kerr",
      offenseStyle: "Read-and-react motion with Curry off-ball movement as primary generator",
      defenseScheme: "Switching man-to-man with zone variations in second units",
      paceRank: 7,
      offRatingRank: 6,
      defRatingRank: 12,
      keyPlay: {
        name: "Zipper Cut — Curry DHO Flare",
        description:
          "Curry receives via a zipper cut from the paint to the elbow, immediately initiates a dribble hand-off to the trailing wing, and uses the screener's body to generate separation for a curl into a catch-and-shoot three. The action is the fundamental unit of Golden State's offense — it manufactures open threes for Curry using his off-ball movement as the primary deception mechanism rather than ball-screen creation.",
        frequency: "23% of half-court possessions",
        efficiency: "1.16 PPP",
      },
      weeklyAdjustment:
        "Golden State's early postseason exit has brought fresh scrutiny to Kerr's personnel usage decisions — specifically the degree to which the motion system can survive the transition from Curry as a 38-year-old primary initiator to a next-generation identity. The week's adjustment is long-term philosophical rather than in-series tactical.",
      schemeGrade: "B",
      narrative:
        "Kerr's motion offense remains the most beautiful tactical system in the NBA when it is operating at full efficiency, and Curry's ability to generate open looks through pure off-ball movement — without requiring the ball-screen creation that 38-year-old legs cannot reliably execute — is a testament to the schematic depth Kerr has built. The honest assessment, however, is that Golden State's defensive scheme has been steadily declining for three seasons, and no amount of offensive sophistication compensates for a defense that cannot contain playoff-caliber pick-and-roll attacks. The franchise is at a genuine inflection point: the motion system is perpetual, but the defensive infrastructure needs a generational rebuild.",
    },
    {
      team: "Memphis Grizzlies",
      coach: "Taylor Jenkins",
      offenseStyle: "Transition chaos with Morant push-pace and Bane spot-up anchoring",
      defenseScheme: "Aggressive on-ball pressure with gambling help rotations",
      paceRank: 1,
      offRatingRank: 13,
      defRatingRank: 18,
      keyPlay: {
        name: "Morant Push-Pitch — Trail Three",
        description:
          "Morant attacks in transition off every defensive rebound, probing the retreating defense with a speed-dribble baseline attack before pitching to a trail shooter — typically Bane or a wing filling the center lane — for an open three. The action is not a designed play so much as a conditioned habit: Memphis runs this sequence on over 60% of their transition possessions and it generates their highest-volume open looks.",
        frequency: "19% of all possessions (transition and early offense)",
        efficiency: "1.08 PPP",
      },
      weeklyAdjustment:
        "Memphis was eliminated in the first round but the tactical week is relevant for Jenkins' scheme evaluation: the Grizzlies' gambling help-rotation defense — which ranks in the bottom third of the league in defensive rating — is increasingly at odds with the physical, switching schemes that characterize championship-caliber defenses. Jenkins' adjustment mandate heading into the offseason is defensive structural reform without sacrificing the pace and chaos that makes Memphis uniquely dangerous.",
      schemeGrade: "B-",
      narrative:
        "Memphis' tactical identity is the most entertainingly reckless in the NBA and Taylor Jenkins deserves enormous credit for building a system that maximizes Morant's unique ability to make defenses collapse in transition — but the league's best coaches have identified the Grizzlies' gambling help rotations as exploitable, and consecutive early-round exits are the consequence. The fundamental tension in Jenkins' scheme is that the same aggressive gambles that generate fast-break points also create the defensive breakdowns that allow elite half-court teams to dissect them late in games. The offseason imperative is finding a version of this identity that can sustain defensive integrity in the fourth quarter without eliminating the chaos that makes Memphis uniquely dangerous.",
    },
    {
      team: "Miami Heat",
      coach: "Erik Spoelstra",
      offenseStyle: "Positionless motion with Herro ball-screen creation and scramble-drive scoring",
      defenseScheme: "Versatile switch-everything with physical denial principles",
      paceRank: 17,
      offRatingRank: 9,
      defRatingRank: 9,
      keyPlay: {
        name: "Spain PnR — Herro Rejection Counter",
        description:
          "Miami initiates a standard Spain PnR with Herro as the ball-handler, but the primary read is the rejection — Herro rejects the screen entirely and attacks the opposite side of the floor where the back-screener has cleared. The counter-cut by the back-screener simultaneously occupies the weak-side helper, leaving Herro with a clean driving lane or a pull-up at the elbow.",
        frequency: "21% of half-court possessions",
        efficiency: "1.09 PPP",
      },
      weeklyAdjustment:
        "Miami's early playoff exit has redirected focus to Spoelstra's offseason scheme evolution — specifically whether the positionless motion system can generate sufficient offensive efficiency without a true primary ball-handler in the Herro mold, as trade speculation swirls around the roster. The week's tactical context is preparatory schematic flexibility.",
      schemeGrade: "A-",
      narrative:
        "Spoelstra's system remains the most scheme-efficient operation in the NBA — consistently generating better results than raw talent projections would suggest — and his positionless motion principles have become the foundational influence on an entire generation of NBA offensive design. The Heat's tactical ceiling is perpetually limited by the gap between Spoelstra's schematic sophistication and the franchise's roster-building constraints, but what is remarkable is how rarely that gap produces genuinely bad basketball. The Spain PnR rejection counter is a microcosm of how Miami operates: every action has a designed counter, and every counter has a designed read, which means defenses that prepare for the primary are perpetually vulnerable to the secondary.",
    },
  ],

  trendingTactics: [
    {
      title: "The Verticality Exploitation: Screening Above the Break",
      description:
        "The WCF has crystallized a league-wide tactical trend that will define the next three offseasons: teams are increasingly designing screens above the arc specifically to exploit the verticality rule, forcing drop-coverage bigs into perimeter closeout situations their footwork cannot handle. Wembanyama's Tall Spain action is the apex version of this trend, but Minnesota's Horns Attack and Golden State's Zipper-DHO sequences operate on identical principles — use screen geometry to manufacture a coverage decision that the defensive big physically cannot execute correctly from a drop position. The countering adjustment — switching — then creates the mismatch problems that skilled playmakers like SGA, Brunson, and Towns feast on. Every front office watching this postseason is identifying perimeter-switch-capable bigs as the premier offseason acquisition target.",
      teams: ["SAS", "OKC", "MIN", "GSW", "NYK"],
    },
    {
      title: "Free-Safety Wing Defense: The Bridges Blueprint",
      description:
        "Mikal Bridges' role in New York's ECF run is the tactical template that teams will spend the next two years trying to replicate: a wing defender with the lateral quickness to serve as a primary on-ball stopper and the off-ball awareness to function as a free safety reading skip passes before they arrive. Thibodeau's defense assigns Bridges a roaming brief that is almost impossible to define in traditional positional terms — he guards Mitchell on one possession, collapses into a driving lane the next, and closes out to a corner shooter the possession after that without a single verbal call from the coaching staff. The league's response will be a surge in demand for wings with elite defensive IQ rather than merely elite athletic tools, because Bridges' value is overwhelmingly cognitive.",
      teams: ["NYK", "MIA", "BOS", "SAS"],
    },
    {
      title: "Transition Denial as Playoff Prerequisite",
      description:
        "The teams still alive in the 2026 Conference Finals share one tactical characteristic that eliminated teams uniformly lacked: disciplined transition defense that converts defensive rebounds into controlled outlets rather than scramble pushes. San Antonio's transition defense — organized around Wembanyama's rim deterrence and Fox's ability to get back as a sprinting safety — allowed the fewest fast-break points of any WCF participant in Game 4. New York's early-offense system, paradoxically, also functions as transition defense: by pushing pace in controlled bursts rather than gambling on full-speed breaks, Thibodeau's team avoids the scramble situations that create easy buckets at the other end. Memphis and Cleveland — the two most elimination-adjacent teams in recent weeks — both rank in the bottom eight in opponent fast-break points allowed, which is not coincidence.",
      teams: ["SAS", "NYK", "OKC", "CLE", "MEM"],
    },
  ],

  coachHotSeat: [
    {
      coach: "Kenny Atkinson",
      team: "Cleveland Cavaliers",
      reason:
        "Facing elimination in Game 4 of the ECF with a roster that outspent the league average on contracts and a star player posting a minus-53 cumulative plus/minus while averaging 26 points, Atkinson's tactical reputation is under genuine institutional pressure. The switch-everything defensive philosophy was supposed to be Cleveland's identity — instead it has been systematically dismantled by a Knicks team that was built to counter it at every position. The organizational question is whether Atkinson gets a full year to rebuild around a corrected scheme, or whether the front office decides the philosophy mismatch is too fundamental to repair.",
      temperature: "scorching",
    },
    {
      coach: "Mark Daigneault",
      team: "Oklahoma City Thunder",
      reason:
        "Daigneault is not on a hot seat in the traditional sense — OKC's 64-18 regular season and WCF appearance are institutional victories — but his in-series adjustment failures in Games 3 and 4 have introduced a new narrative: can the league's best regular-season coach translate his defensive architecture to a seven-game adjustment war against a tactically sophisticated opponent? The hedge-versus-drop debate on Wembanyama coverage is now public, and if OKC loses in five, the questions about Daigneault's in-series flexibility will intensify heading into next season.",
      temperature: "warm",
    },
    {
      coach: "Taylor Jenkins",
      team: "Memphis Grizzlies",
      reason:
        "Jenkins' seat is more bureaucratic than performance-based: Memphis has now exited in the first round in consecutive seasons despite having a healthy Morant, and the front office's patience with a defensive scheme that ranks in the bottom third of the league is visibly thinning. The gambling-rotation defense that generates Jenkins' pace-and-chaos offense is also the liability that makes playoff survival nearly impossible against disciplined half-court teams. The summer will determine whether the organization doubles down on the chaos identity or demands a defensive structural reform that Jenkins' track record does not clearly support.",
      temperature: "lukewarm",
    },
  ],
};