// Auto-generated by generate-trade-value.mjs
// Week of June 8–14, 2026

export interface TVIPlayer {
  rank: number;
  prevRank: number;
  player: string;
  team: string;
  age: number;
  contract: string;
  tradeValue: number;
  trend: "up" | "down" | "stable";
  rationale: string;
}

export interface TVIData {
  generatedDate: string;
  weekLabel: string;
  players: TVIPlayer[];
}

export const tradeValueData: TVIData = {
  generatedDate: "June 8, 2026",
  weekLabel: "Week of June 8–14, 2026",
  players: [
    {
      rank: 1,
      prevRank: 2,
      player: "Victor Wembanyama",
      team: "SAS",
      age: 22,
      contract: "4 yrs / $196M remaining (max)",
      tradeValue: 99,
      trend: "up",
      rationale:
        "Wembanyama's 34-point, 13-rebound, 4-block Finals Game 1 performance — capped by a near-miraculous fourth-quarter comeback attempt — is the most compelling individual showcase in this year's postseason. At 22 on a max deal that looks like a bargain against his production ceiling, he is the unambiguous top trade asset in the league. No team would decline this contract at any price.",
    },
    {
      rank: 2,
      prevRank: 1,
      player: "Jalen Brunson",
      team: "NYK",
      age: 29,
      contract: "3 yrs / $117M remaining",
      tradeValue: 96,
      trend: "up",
      rationale:
        "Brunson hit the go-ahead pull-up with 14 seconds left in Finals Game 1 — the single most pressure-tested shot of the 2026 postseason — cementing his status as the most clutch guard available on the market if New York ever moved him. His contract is team-friendly relative to his demonstrated ceiling, and he ranks second this week only because of the seven-year age gap separating him from Wembanyama's upside. Any rebuilding or contending team would clear cap space immediately for this package.",
    },
    {
      rank: 3,
      prevRank: 4,
      player: "De'Aaron Fox",
      team: "SAS",
      age: 28,
      contract: "3 yrs / $132M remaining (max)",
      tradeValue: 93,
      trend: "up",
      rationale:
        "Fox's 27-point Finals Game 1 output — including a clutch converted layup with 22 seconds left — reaffirmed that he is Wembanyama's ideal co-star: a north-south attacker who collapses defenses in ways that open Wemby's post-catch game. His max contract is fully justified by that two-man infrastructure, and the Spurs' 62-20 record is the proof of concept every acquiring GM would study. Drops him to third only because the contract years are slightly shorter than Brunson's window.",
    },
    {
      rank: 4,
      prevRank: 3,
      player: "Karl-Anthony Towns",
      team: "NYK",
      age: 30,
      contract: "3 yrs / $141M remaining (max)",
      tradeValue: 89,
      trend: "up",
      rationale:
        "Towns posted a 22-point, 11-rebound double-double in Finals Game 1 as an unguardable face-up four who pulled Wembanyama completely out of the paint — the structural reason Brunson had open driving lanes all night. His age-30 tag and heavy max contract keep him off the top tier, but any contender seeking a modern stretch-big with Finals-proven production would pay a king's ransom. The concern is durability across a full playoff run, which history has occasionally flagged.",
    },
    {
      rank: 5,
      prevRank: 6,
      player: "Stephon Castle",
      team: "SAS",
      age: 21,
      contract: "3 yrs / $38M remaining (rookie)",
      tradeValue: 88,
      trend: "up",
      rationale:
        "Castle's strip of OG Anunoby with 22 seconds left in Game 1 was the defining defensive play of the NBA Finals so far, and his 19-point complementary line proved he belongs in these moments offensively too. At 21 on a cheap rookie deal with two All-Defensive caliber seasons already on his résumé, he has the highest surplus value of any player outside the top four. The Spurs would never move him, which is precisely what makes him so coveted.",
    },
    {
      rank: 6,
      prevRank: 5,
      player: "Mikal Bridges",
      team: "NYK",
      age: 29,
      contract: "4 yrs / $124M remaining",
      tradeValue: 84,
      trend: "stable",
      rationale:
        "Three steals, 18 points, and a +12 in Finals Game 1 is exactly the two-way wing production that championship rosters are built around, and Bridges delivered it against the league's most athletic backcourt. His contract is reasonable for a player of his caliber entering his prime defensive years, and the Finals stage has only amplified his market. Slides one spot this week as Castle's age-adjusted surplus value edges past him.",
    },
    {
      rank: 7,
      prevRank: 8,
      player: "Chet Holmgren",
      team: "OKC",
      age: 23,
      contract: "4 yrs / $148M remaining (max)",
      tradeValue: 83,
      trend: "stable",
      rationale:
        "Holmgren's WCF Game 7 double-double in San Antonio — 21 points, 10 rebounds, 3 blocks against the team that just reached the Finals — is the freshest evidence that he is a legitimate center-of-gravity big on both ends. OKC's elimination doesn't diminish his value; if anything, it signals that Thunder leadership may face pressure to retool around him in the offseason. His max extension looks defensible given his age and two-way profile.",
    },
    {
      rank: 8,
      prevRank: 7,
      player: "OG Anunoby",
      team: "NYK",
      age: 28,
      contract: "4 yrs / $116M remaining",
      tradeValue: 81,
      trend: "stable",
      rationale:
        "Anunoby's two-block, five-rebound, 14-point effort in Finals Game 1 demonstrated that he remains one of the five best defensive wings in the league — his first three quarters against Wembanyama were a masterclass in length and positioning. The Castle strip on his final possession was a bad break in an otherwise elite defensive night, not a pattern, and acquiring teams would not overweight it. His contract and age align perfectly for a team looking for a three-to-five year championship window.",
    },
    {
      rank: 9,
      prevRank: 10,
      player: "Shai Gilgeous-Alexander",
      team: "OKC",
      age: 27,
      contract: "4 yrs / $212M remaining (supermax)",
      tradeValue: 80,
      trend: "down",
      rationale:
        "SGA's absence from the Pulse Index this week reflects OKC's WCF elimination — his season is over and the supermax contract now comes under a harsher lens without a Finals appearance to justify it. He remains a genuinely elite scorer and the kind of foundational piece any team rebuilds around, but the $212M remaining on his deal limits the pool of acquiring teams dramatically. The down trend is about offseason uncertainty and contract logistics, not his talent.",
    },
    {
      rank: 10,
      prevRank: 9,
      player: "Tyrese Haliburton",
      team: "IND",
      age: 26,
      contract: "4 yrs / $188M remaining (max)",
      tradeValue: 79,
      trend: "stable",
      rationale:
        "Haliburton's Indiana squad fell short of the Finals but his playmaking — averaging 11 assists in the second half of the season — remains among the most transferable skills in the league for any offense needing a point-of-attack organizer. His max contract is the biggest obstacle to a trade, but at 26 with zero serious injury history, the risk profile is manageable. A contender that lost its starting PG would make him the top priority call.",
    },
    {
      rank: 11,
      prevRank: 12,
      player: "Evan Mobley",
      team: "CLE",
      age: 25,
      contract: "4 yrs / $172M remaining (max)",
      tradeValue: 77,
      trend: "stable",
      rationale:
        "Mobley's Defensive Player of the Year campaign finished with Cleveland falling in the second round, but his profile — a 7-foot switch-everything big who can guard one through five — is exactly what every Finals team is missing right now. His offensive game has taken genuine strides this season, giving him a two-way ceiling that justifies the max. Cleveland is unlikely to move him, but the market would be historically deep if they did.",
    },
    {
      rank: 12,
      prevRank: 11,
      player: "Anthony Edwards",
      team: "MIN",
      age: 24,
      contract: "4 yrs / $204M remaining (supermax)",
      tradeValue: 76,
      trend: "down",
      rationale:
        "Edwards' Timberwolves missed the playoffs entirely this season, a result that puts the supermax under immediate scrutiny and creates legitimate front-office pressure in Minnesota. His individual talent — explosive scoring, lockdown defensive capability, generational athleticism — is undeniable, but the lack of team context and the size of the contract suppress his TVI ranking relative to his raw ability. A trade would require taking back significant salary, narrowing the acquiring field considerably.",
    },
    {
      rank: 13,
      prevRank: 14,
      player: "Jaren Jackson Jr.",
      team: "MEM",
      age: 26,
      contract: "3 yrs / $128M remaining",
      tradeValue: 75,
      trend: "stable",
      rationale:
        "JJJ's two-time Defensive Player of the Year pedigree and elite shot-blocking footprint make him one of the most coveted defensive anchors on the trade market, and Memphis' missed playoffs open the door to exploratory conversations. His offensive consistency remains the limiting factor — he needs to be surrounded by playmakers — but the contract is fair for his impact level. Watch for his name in summer trade rumors as Memphis evaluates its rebuild timeline.",
    },
    {
      rank: 14,
      prevRank: 13,
      player: "Dalen Terry",
      team: "SAS",
      age: 23,
      contract: "2 yrs / $14M remaining (rookie)",
      tradeValue: 74,
      trend: "up",
      rationale:
        "Four steals off the bench in Finals Game 1 is the kind of disruptive defensive performance that launches careers, and Terry's per-minute defensive impact across the Spurs' championship run has been one of the league's best-kept secrets. His rookie contract makes him arguably the highest surplus-value player outside the top ten, and Pop leaning on him in the Finals only strengthens the case that he is ready for a starting role elsewhere. Any team building around a defensive identity would prioritize this call.",
    },
    {
      rank: 15,
      prevRank: 16,
      player: "Josh Hart",
      team: "NYK",
      age: 29,
      contract: "3 yrs / $57M remaining",
      tradeValue: 72,
      trend: "stable",
      rationale:
        "Twelve rebounds in Finals Game 1 — none of them offensive — is the exact brand of positionally disciplined hustle that championship rosters require in a sixth or seventh rotation spot, and Hart has delivered it at an elite level all postseason. His contract is one of the most team-friendly in the league for what he provides, and the Finals stage has only raised his market. He's the archetype every contender tries to replicate and rarely can.",
    },
    {
      rank: 16,
      prevRank: 15,
      player: "Bam Adebayo",
      team: "MIA",
      age: 28,
      contract: "2 yrs / $64M remaining",
      tradeValue: 70,
      trend: "down",
      rationale:
        "Adebayo's two-year contract window actually makes him one of the most actionable trade targets this summer — a team on the Finals bubble can acquire him for a two-year championship run without a long-term commitment. Miami's first-round exit this postseason creates internal pressure, and Bam's defensive versatility and elite pick-and-roll reads translate to any system immediately. Slides down slightly as the short contract length limits return value for the Heat.",
    },
    {
      rank: 17,
      prevRank: 18,
      player: "Donovan Mitchell",
      team: "CLE",
      age: 29,
      contract: "3 yrs / $138M remaining",
      tradeValue: 69,
      trend: "stable",
      rationale:
        "Mitchell's Cleveland tenure has produced consistent All-Star output but not a Finals appearance, and the contract structure means any acquiring team is committing through his age-32 season. His scoring in big moments — particularly a 38-point performance in the second-round Game 5 elimination game — demonstrates he still has elite offensive gear remaining. The market for him is real but stratified; only teams with a clear championship window in the next two years would pay the asking price.",
    },
    {
      rank: 18,
      prevRank: 17,
      player: "Jaylen Brown",
      team: "BOS",
      age: 29,
      contract: "4 yrs / $192M remaining (supermax)",
      tradeValue: 67,
      trend: "down",
      rationale:
        "Boston's second-round exit this postseason has reignited the internal debate about Brown's fit alongside Tatum as a co-primary scorer, and the supermax contract limits flexibility in either direction. His individual talent — particularly as an isolation scorer and defensive stopper — is not in question, but the contract size means any trade conversation starts from an extremely high price floor. Down this week as the Boston offseason storyline begins to dominate his market narrative.",
    },
    {
      rank: 19,
      prevRank: 20,
      player: "Nikola Jokic",
      team: "DEN",
      age: 31,
      contract: "2 yrs / $116M remaining (supermax)",
      tradeValue: 66,
      trend: "stable",
      rationale:
        "Three MVP awards and still the most complete offensive big in the league, but Denver's early exit this postseason and the two-year contract horizon place him in a unique position: a generational talent approaching the back end of his peak. Any team acquiring Jokic gets an immediate Finals contender for two years, which is a genuine value proposition. Ranks here because the age curve and contract length cap the long-term upside for an acquiring front office.",
    },
    {
      rank: 20,
      prevRank: 19,
      player: "Trae Young",
      team: "ATL",
      age: 27,
      contract: "3 yrs / $144M remaining",
      tradeValue: 64,
      trend: "stable",
      rationale:
        "Young's Atlanta tenure has stalled structurally — the team missed the playoffs again this season — and the max contract creates a high price floor that has cooled offseason trade discussions despite multiple reported calls. His offensive profile remains elite: a top-five playmaker when healthy with the ability to generate offense from nothing. The right team gets an instant offensive identity; the wrong team gets a one-dimensional fit problem with a heavy price tag.",
    },
    {
      rank: 21,
      prevRank: 22,
      player: "Scottie Barnes",
      team: "TOR",
      age: 24,
      contract: "4 yrs / $168M remaining (max)",
      tradeValue: 63,
      trend: "stable",
      rationale:
        "Barnes is the most confusing valuation in the league right now — a 24-year-old max player on a rebuilding team whose role, position, and offensive identity are still unresolved four years into his career. His physical tools and defensive versatility are legitimate, and a change of scenery with a defined role could unlock the former Rookie of the Year upside. Toronto's rebuild timeline makes him theoretically available, but the max contract demands a premium return.",
    },
    {
      rank: 22,
      prevRank: 21,
      player: "Zion Williamson",
      team: "NOP",
      age: 25,
      contract: "3 yrs / $147M remaining (max)",
      tradeValue: 61,
      trend: "down",
      rationale:
        "Williamson's injury history — he missed 22 games this season with a recurring hamstring strain — remains the single largest risk variable attached to any max-contract player in the league. When healthy, his force-of-nature offensive profile has no equivalent; when unavailable, the contract is a paralytic. New Orleans missed the playoffs again, and the front office is actively listening on his availability. Any acquiring team is essentially betting $147M on a durability profile that has never held for a full season.",
    },
    {
      rank: 23,
      prevRank: 24,
      player: "Jayson Tatum",
      team: "BOS",
      age: 28,
      contract: "4 yrs / $212M remaining (supermax)",
      tradeValue: 60,
      trend: "down",
      rationale:
        "Tatum's Boston tenure has produced one title and multiple Finals appearances, but this postseason's second-round exit — in which he shot 38% from the field in the final three games — has opened legitimate questions about his ability to be the primary closer on a championship team. The $212M supermax is the most expensive contract in league history and limits any trade to a narrow band of teams with the cap infrastructure to absorb it. Down this week as the Boston offseason looks increasingly combustible.",
    },
    {
      rank: 24,
      prevRank: 23,
      player: "LaMelo Ball",
      team: "CHA",
      age: 24,
      contract: "4 yrs / $176M remaining (max)",
      tradeValue: 59,
      trend: "stable",
      rationale:
        "Ball's playmaking ceiling is as high as any guard in the league when he is healthy and engaged, but Charlotte's lottery standing for the fourth consecutive season raises real questions about whether his development environment is producing results. His assist numbers and creativity remain elite, but his defensive effort grades are among the worst at his position. A contending team with defensive infrastructure around him could unlock a genuinely dangerous offensive weapon.",
    },
    {
      rank: 25,
      prevRank: 26,
      player: "Devin Booker",
      team: "PHX",
      age: 29,
      contract: "3 yrs / $162M remaining (supermax)",
      tradeValue: 57,
      trend: "down",
      rationale:
        "Phoenix's third consecutive first-round exit has created one of the most unstable front-office environments in the league, and Booker's name has appeared in trade speculation for the first time since his max extension. His individual scoring package — elite off the dribble, one of the best pull-up midrange artists in the game — is legitimate Finals-level production. The concern is whether the supporting cast will ever be assembled correctly in Phoenix, or whether a trade is the only path to a championship.",
    },
    {
      rank: 26,
      prevRank: 25,
      player: "Paolo Banchero",
      team: "ORL",
      age: 23,
      contract: "4 yrs / $196M remaining (max)",
      tradeValue: 56,
      trend: "stable",
      rationale:
        "Banchero's Orlando team made the playoffs for the second consecutive year and he continued his development as a primary creator, but a second-round exit and a max extension that kicked in this season raise the stakes on his growth trajectory. His post-up game and pick-and-roll creation are legitimately elite for his age, and the four-year runway gives an acquiring team significant time to build around him. Ranks here because the upside is real but the Orlando rebuild is not yet proven as a Finals-viable structure.",
    },
    {
      rank: 27,
      prevRank: 28,
      player: "Brandon Ingram",
      team: "NOP",
      age: 28,
      contract: "2 yrs / $48M remaining",
      tradeValue: 54,
      trend: "stable",
      rationale:
        "Ingram's two-year deal makes him one of the most actionable wing trade targets this summer for a contending team that needs a long-range scoring option without a multi-year commitment. New Orleans is in full rebuild mode following their lottery positioning, and Ingram has been the subject of consistent calls from Eastern Conference contenders. His offensive versatility — attack-off-the-dribble, catch-and-shoot, and post creation — translates cleanly to a complementary role on a team with infrastructure already in place.",
    },
    {
      rank: 28,
      prevRank: 27,
      player: "Damian Lillard",
      team: "MIL",
      age: 35,
      contract: "2 yrs / $92M remaining",
      tradeValue: 48,
      trend: "down",
      rationale:
        "Lillard's Milwaukee experiment has not produced the championship contention both sides envisioned, and his age-35 tag with $92M remaining represents the most difficult contract to move in the top thirty. His scoring production has dipped to 21 points per game — still All-Star level but not the 30-point engine that justified the trade — and his defensive limitations are now a consistent playoff liability. Down this week as Milwaukee's offseason appears likely to accelerate a rebuild.",
    },
    {
      rank: 29,
      prevRank: 30,
      player: "CJ McCollum",
      team: "NOP",
      age: 34,
      contract: "1 yr / $32M remaining",
      tradeValue: 44,
      trend: "stable",
      rationale:
        "McCollum's expiring contract is actually his primary trade value at this stage — a team that needs a playoff-experienced secondary ball-handler for one season at a known price can acquire him without long-term risk. His playmaking and shooting efficiency have remained respectable even as New Orleans declined around him. Best fit is as a third offensive option on a contending team that needs a competent veteran in the postseason rotation.",
    },
    {
      rank: 30,
      prevRank: 29,
      player: "Kevin Durant",
      team: "PHX",
      age: 37,
      contract: "2 yrs / $108M remaining",
      tradeValue: 41,
      trend: "down",
      rationale:
        "Durant's scoring brilliance has not faded — he averaged 25.4 points this season — but his age-37 profile and the $108M remaining on his contract create a trade calculus that almost no team can solve cleanly. Phoenix's dysfunction means the calls will come this summer, but the acquiring team must be committed to a short two-year window with significant cap burden and real injury risk. Ranks thirtieth because the contract-to-production ratio is the most challenging value equation in the top thirty.",
    },
  ],
};