// Auto-generated by generate-trade-value.mjs
// Week of May 18–24, 2026

export interface TVIPlayer {
  rank: number;
  prevRank: number;
  player: string;
  team: string;
  age: number;
  contract: string;
  tradeValue: number;
  trend: "up" | "down" | "stable";
  rationale: string;
}

export interface TVIData {
  generatedDate: string;
  weekLabel: string;
  players: TVIPlayer[];
}

export const tradeValueData: TVIData = {
  generatedDate: "May 18, 2026",
  weekLabel: "Week of May 18–24, 2026",
  players: [
    {
      rank: 1,
      prevRank: 1,
      player: "Shai Gilgeous-Alexander",
      team: "OKC",
      age: 27,
      contract: "4 yrs / $198M remaining",
      tradeValue: 99,
      trend: "stable",
      rationale:
        "SGA is the uncontested No. 1 trade asset in the league — 8-0 in the playoffs, averaging 30.1 PPG, and leading the best record in basketball into tonight's WCF opener against Wembanyama. His age-27 prime, elite two-way profile, and team-friendly supermax extension make him essentially untouchable on the open market. No acquiring team could realistically offer equal value, which is precisely what makes him the gold standard of the TVI.",
    },
    {
      rank: 2,
      prevRank: 4,
      player: "Evan Mobley",
      team: "CLE",
      age: 24,
      contract: "4 yrs / $172M remaining",
      tradeValue: 97,
      trend: "up",
      rationale:
        "The 21-12-6 Game 7 masterpiece on the road — at 70% shooting and a +31 — is the kind of performance that reshuffles trade boards permanently. Mobley is 24 years old, on a max extension, and has just proven he can be the best player in a playoff series against a legitimate contender. Any front office not aggressively pursuing him in a hypothetical trade scenario simply isn't paying attention.",
    },
    {
      rank: 3,
      prevRank: 3,
      player: "Victor Wembanyama",
      team: "SAS",
      age: 22,
      contract: "4 yrs / $164M remaining (rookie)",
      tradeValue: 96,
      trend: "stable",
      rationale:
        "Wemby enters tonight's WCF Game 1 as the most physically unique player in the sport — 24.3 PPG, 10.8 RPG, and 3.2 BPG through 11 playoff games on a rookie-scale deal that will look like highway robbery by mid-summer. His trade value is anchored by a ceiling so high that evaluators are still inventing new frameworks to describe it. The only reason he isn't No. 1 is that SGA's sustained team success gives the Thunder a fractional organizational edge.",
    },
    {
      rank: 4,
      prevRank: 6,
      player: "Stephon Castle",
      team: "SAS",
      age: 21,
      contract: "3 yrs / $28M remaining (rookie)",
      tradeValue: 94,
      trend: "up",
      rationale:
        "Castle's 32/11/6 series clincher against Minnesota was the most surprising breakout performance of the 2026 postseason, and his rookie contract makes him the single most cost-efficient asset in these rankings. At 21 years old stepping into a WCF role, his ascent is happening faster than any comparable projection model predicted. An acquiring team would be getting a likely All-Star at a price that warps every salary-matching exercise in his favor.",
    },
    {
      rank: 5,
      prevRank: 5,
      player: "Donovan Mitchell",
      team: "CLE",
      age: 29,
      contract: "3 yrs / $138M remaining",
      tradeValue: 91,
      trend: "up",
      rationale:
        "The Game 7 redemption arc — 26 points, 8 assists, zero turnovers after a 6-of-20 Game 6 — reaffirmed exactly what Mitchell's ceiling looks like when the pressure is highest. He's now averaging 27.7 PPG across seven playoff games with the ECF on deck against New York. His value rises this week specifically because the bounce-back performance silenced the durability-of-clutch concerns that suppressed his ranking heading into the series.",
    },
    {
      rank: 6,
      prevRank: 7,
      player: "Jalen Brunson",
      team: "NYK",
      age: 29,
      contract: "3 yrs / $117M remaining",
      tradeValue: 89,
      trend: "stable",
      rationale:
        "Brunson enters the ECF as the most rested star in the entire postseason field, having not played since May 11, and carries the most dominant sweep on any active player's 2026 resume. His 27.8 PPG playoff average underscores a scorer who has completely outgrown the 'overachieving point guard' narrative. The Cleveland matchup — with Harden and Mitchell clogging passing lanes — is the one legitimate question mark suppressing his TVI ceiling this week.",
    },
    {
      rank: 7,
      prevRank: 8,
      player: "De'Aaron Fox",
      team: "SAS",
      age: 28,
      contract: "3 yrs / $132M remaining",
      tradeValue: 87,
      trend: "stable",
      rationale:
        "Fox's 21/9 efficiency clincher against Minnesota was the most understated great performance of the conference semifinals — he controlled pace against a physical Wolves backcourt and never once looked out of his depth. His role as the third star on a 62-win team that's now in the WCF actually elevates his value, because it demonstrates he can produce without the ball being run exclusively through him. Tonight's matchup against OKC's pressure defense will be the truest diagnostic of his upside limit.",
    },
    {
      rank: 8,
      prevRank: 9,
      player: "Karl-Anthony Towns",
      team: "NYK",
      age: 30,
      contract: "3 yrs / $151M remaining",
      tradeValue: 84,
      trend: "stable",
      rationale:
        "Towns has averaged 24.5 PPG and 10.2 RPG through the Knicks' playoff run, and the ECF matchup against Mobley and Jarrett Allen sets up as the most physically demanding test of his postseason. His trade value this week is buoyed by the fact that the Knicks enter with home court and genuine Finals ambitions — context that inflates his immediate leverage as a complementary superstar. The contract is the only soft ceiling: three years and $151M remaining is a real cap anchor for any acquiring team to absorb.",
    },
    {
      rank: 9,
      prevRank: 10,
      player: "James Harden",
      team: "CLE",
      age: 36,
      contract: "1 yr / $36M remaining",
      tradeValue: 72,
      trend: "up",
      rationale:
        "The +31 on 2-of-10 shooting in Game 7 is the most confounding — and ultimately convincing — argument for Harden's remaining value as a playoff conductor. He clearly doesn't need to score to win games anymore, which paradoxically makes him more useful to a contender than a team trying to build around his offense. His trade value is capped by age and a one-year deal that limits return yield, but any team that watched Game 7 would still make that call.",
    },
    {
      rank: 10,
      prevRank: 12,
      player: "Cade Cunningham",
      team: "DET",
      age: 24,
      contract: "4 yrs / $176M remaining",
      tradeValue: 82,
      trend: "up",
      rationale:
        "Cunningham's regular season culminated in 25.8 PPG and 8.7 APG on a Pistons team that punched well above its projected ceiling — and his max extension makes him one of the only top-ten trade assets available on a non-contending team. Detroit's first-round exit doesn't damage his stock; it simply accelerates the offseason speculation about whether the organization will build around him or cash in. At 24, he's the most coveted available star heading into the summer.",
    },
    {
      rank: 11,
      prevRank: 11,
      player: "Anthony Edwards",
      team: "MIN",
      age: 24,
      contract: "4 yrs / $204M remaining",
      tradeValue: 88,
      trend: "down",
      rationale:
        "Edwards' value takes a contextual hit this week after Minnesota's conference semifinals exit at the hands of Castle and San Antonio — his 28.2 PPG series average was spectacular, but losing in six to a team that then swept into the WCF raises real questions about the Wolves' roster construction around him. His individual TVI remains elite at 88, anchored by age and contract, but the team failure prevents him from climbing above Brunson or Mitchell in this cycle.",
    },
    {
      rank: 12,
      prevRank: 13,
      player: "Jaren Jackson Jr.",
      team: "MEM",
      age: 26,
      contract: "3 yrs / $126M remaining",
      tradeValue: 80,
      trend: "stable",
      rationale:
        "Jackson finished the regular season as the consensus best defensive player in the Western Conference not named Wembanyama, and Memphis' first-round exit only fuels trade speculation about whether the Grizzlies will accelerate their timeline or pivot. His 3.4 BPG, 20.1 PPG regular season profile is exactly what contenders shop for at the trade deadline, and his age-26 contract window aligns perfectly with a championship-chasing team's needs. He's the most coveted defensive anchor on the board.",
    },
    {
      rank: 13,
      prevRank: 14,
      player: "Tyrese Haliburton",
      team: "IND",
      age: 26,
      contract: "3 yrs / $141M remaining",
      tradeValue: 79,
      trend: "stable",
      rationale:
        "Haliburton's 10.9 APG led the league this season and Indiana's second-round exit — despite his 24.1 PPG, 11.2 APG playoff average — reflects roster limitations more than individual failure. His playmaking grade is matched only by Brunson among non-Finals-bound guards, and his age-26 contract is structured efficiently enough to be absorbed without wrecking a contender's cap. The question this week is whether Indiana treats him as untouchable or listens to the calls that are certainly coming.",
    },
    {
      rank: 14,
      prevRank: 15,
      player: "Scottie Barnes",
      team: "TOR",
      age: 24,
      contract: "4 yrs / $168M remaining",
      tradeValue: 78,
      trend: "stable",
      rationale:
        "Barnes posted another 22/8/5 season for a rebuilding Toronto squad and is widely regarded as the most patient rebuild asset in the Eastern Conference — teams know what they're getting and are willing to wait for the right price. His Swiss Army knife versatility at 6-foot-8 and 24 years old fills almost every positional need a contender could identify. Toronto's lack of urgency to move him actually elevates his trade value by keeping demand artificially suppressed heading into the offseason.",
    },
    {
      rank: 15,
      prevRank: 16,
      player: "Trae Young",
      team: "ATL",
      age: 27,
      contract: "2 yrs / $92M remaining",
      tradeValue: 74,
      trend: "up",
      rationale:
        "Young's trade value is climbing this week because Atlanta's front office has reportedly opened internal discussions about a full rebuild pivot — the first credible signal that the Young era in Atlanta may be ending sooner than the roster timeline suggested. His 27.3 PPG, 10.8 APG regular season profile remains elite and any team willing to absorb the defensive limitations gets one of the five best playmakers alive. Two years and $92M is a manageable price for that level of offensive creation.",
    },
    {
      rank: 16,
      prevRank: 17,
      player: "LaMelo Ball",
      team: "CHA",
      age: 24,
      contract: "4 yrs / $188M remaining",
      tradeValue: 75,
      trend: "stable",
      rationale:
        "Ball's injury history is the only thing preventing him from ranking in the top ten — when healthy, he's a 24-year-old with the highest playmaking ceiling outside the current playoff field. Charlotte's lottery position this summer makes a front office reset increasingly likely, and his name has surfaced in more trade conversations this week than any other non-playoff star. The contract is heavy but the upside remains generational for a team willing to absorb the availability risk.",
    },
    {
      rank: 17,
      prevRank: 19,
      player: "Bam Adebayo",
      team: "MIA",
      age: 28,
      contract: "2 yrs / $58M remaining",
      tradeValue: 77,
      trend: "up",
      rationale:
        "Adebayo's TVI rises this week on the strength of his 18.4 PPG, 10.1 RPG, 5.2 APG regular season and the crystallizing reality that Miami is likely to restructure around Jimmy Butler's departure timeline. His two-year, $58M remaining deal is the most team-friendly contract for a player of his caliber in the top 20, making him the most cost-efficient trade target for a contender needing a defensive anchor and connective passer. Cleveland's Mobley-Allen success story has reminded every front office exactly how valuable elite defensive bigs are in May.",
    },
    {
      rank: 18,
      prevRank: 18,
      player: "Alperen Şengün",
      team: "HOU",
      age: 23,
      contract: "4 yrs / $144M remaining",
      tradeValue: 76,
      trend: "stable",
      rationale:
        "Şengün averaged 22.1 PPG, 11.4 RPG, and 5.9 APG this season — numbers that would rank him among the five most productive centers in NBA history at his age. Houston's second-round exit didn't diminish his individual standing; the Rockets simply ran into a better roster. His trade value is theoretical for now, as Houston isn't moving him, but the market would clear $90M+ in return assets instantly if that call was ever made.",
    },
    {
      rank: 19,
      prevRank: 20,
      player: "Jaylen Brown",
      team: "BOS",
      age: 29,
      contract: "4 yrs / $184M remaining",
      tradeValue: 73,
      trend: "down",
      rationale:
        "Boston's first-round exit — their earliest postseason departure in the Tatum-Brown era — puts Brown's contract under a fresh microscope this week. His 23.1 PPG regular season is real, but $184M over four years for a player whose playoff efficiency has been inconsistent is a harder sell than it was 12 months ago. Teams still want him, but the asking price has shifted from 'untouchable' to 'negotiable' after another postseason disappointment.",
    },
    {
      rank: 20,
      prevRank: 21,
      player: "Nikola Jokić",
      team: "DEN",
      age: 31,
      contract: "2 yrs / $118M remaining",
      tradeValue: 83,
      trend: "stable",
      rationale:
        "Jokić's TVI ranking defies his age because no player in the sport produces at a higher per-possession rate — he averaged 28.4 PPG, 13.1 RPG, and 10.2 APG this season and remains the most statistically dominant force in basketball. Denver's second-round exit and the looming two-year contract window make this the offseason where trade speculation will be loudest since his first MVP year. Any contender adding him instantly becomes a championship favorite, which is why his value sits at 83 despite the age and timeline concerns.",
    },
    {
      rank: 21,
      prevRank: 22,
      player: "Paolo Banchero",
      team: "ORL",
      age: 23,
      contract: "4 yrs / $196M remaining",
      tradeValue: 81,
      trend: "up",
      rationale:
        "Banchero's 26.7 PPG on an Orlando team that finished above .500 for the first time since the Dwight Howard era is one of the more underappreciated developmental arcs in the league. His age-23 max extension makes him a long-term cornerstone asset, and the Magic's decision this summer about whether to add around him or reset their timeline entirely will define the next era of the franchise. If available, he would generate the most competitive bidding war of any non-top-10 asset.",
    },
    {
      rank: 22,
      prevRank: 23,
      player: "Franz Wagner",
      team: "ORL",
      age: 24,
      contract: "4 yrs / $172M remaining",
      tradeValue: 79,
      trend: "stable",
      rationale:
        "Wagner and Banchero as a duo give Orlando one of the two best young frontcourt pairings in the Eastern Conference, and the question this week is whether the Magic keep both or use one to accelerate. His 22.4 PPG and elite defensive versatility on a reasonable max extension make him the more coveted of the two on the trade market — primarily because his defensive impact solves a problem that more contenders are currently trying to address.",
    },
    {
      rank: 23,
      prevRank: 24,
      player: "Darius Garland",
      team: "CLE",
      age: 26,
      contract: "2 yrs / $76M remaining",
      tradeValue: 68,
      trend: "up",
      rationale:
        "Garland's role has been compressed in Cleveland's playoff run — Harden and Mitchell have absorbed most of the ball-handling duties — but his 19.8 PPG regular season and $38M AAV make him one of the most plausible trade chips on a team that no longer needs him as the primary initiator. His TVI rises this week because Cleveland's ECF run proves the Cavs can win without leaning on him, which paradoxically makes him more attractive to a team that would feature him first.",
    },
    {
      rank: 24,
      prevRank: 25,
      player: "Zion Williamson",
      team: "NOP",
      age: 25,
      contract: "3 yrs / $138M remaining",
      tradeValue: 62,
      trend: "down",
      rationale:
        "The injury risk is the whole story: Zion played 54 games this season — his most since his rookie year — and averaged 27.9 PPG when healthy. The talent is undeniable and the contract is executable, but no front office analyst can build a legitimate championship projection around a player with his availability history. His TVI sits at 62 because the upside curve is steep but the probability-weighted outcome remains too uncertain for a true contender to bet a rebuild on.",
    },
    {
      rank: 25,
      prevRank: 26,
      player: "Mikal Bridges",
      team: "BKN",
      age: 27,
      contract: "3 yrs / $96M remaining",
      tradeValue: 71,
      trend: "stable",
      rationale:
        "Bridges quietly posted 24.2 PPG on a Brooklyn team with no supporting cast and zero playoff ambitions — a stat line that undersells how dominant his two-way profile actually is. His trade value sits in a productive middle tier because any contender acquiring him would immediately see a 4-6 win improvement, yet his lack of playoff context makes projecting his ceiling in a high-leverage environment genuinely uncertain. The contract is clean enough that the ask from Brooklyn would be steep.",
    },
    {
      rank: 26,
      prevRank: 27,
      player: "Devin Booker",
      team: "PHX",
      age: 29,
      contract: "3 yrs / $162M remaining",
      tradeValue: 70,
      trend: "down",
      rationale:
        "Phoenix's lottery position for the second consecutive season has pushed Booker's trade value into uncomfortable territory — the contract is large, the playoff track record without Durant is unimpressive, and the organization is in a genuine identity crisis. He still averaged 26.1 PPG and his scoring efficiency remains elite, but $54M AAV for a 29-year-old on a lottery team is the kind of asset that requires a specific acquiring-team profile to make sense. Trade calls are coming.",
    },
    {
      rank: 27,
      prevRank: 28,
      player: "Jarrett Allen",
      team: "CLE",
      age: 27,
      contract: "2 yrs / $42M remaining",
      tradeValue: 74,
      trend: "up",
      rationale:
        "Allen has been the invisible engine of Cleveland's playoff run — anchoring the paint defensively while Mobley ranges the perimeter, and his two-year, $21M AAV deal is the most underpriced contract in the Eastern Conference for a starting-caliber center. His TVI surges this week because the Mobley-Allen frontcourt combination is now recognized league-wide as the most physically imposing defensive pairing remaining in the postseason. Any contender seeking a shot-blocker, rebounder, and low-usage big would make him a top-three phone call this summer.",
    },
    {
      rank: 28,
      prevRank: 29,
      player: "Josh Giddey",
      team: "CHI",
      age: 21,
      contract: "3 yrs / $62M remaining",
      tradeValue: 69,
      trend: "up",
      rationale:
        "Giddey's 18.4 PPG, 9.1 RPG, 8.2 APG season for a non-playoff Chicago team is one of the most overlooked developmental stories of the 2025-26 season — he's a 21-year-old triple-double machine on a below-market extension. His trade value is underappreciated specifically because the Bulls' rebuild hasn't generated national attention, leaving him as a relative unknown to casual fans while front offices have been watching very carefully. The first team to make a serious move for him will win the offseason press conference.",
    },
    {
      rank: 29,
      prevRank: 30,
      player: "Brandon Ingram",
      team: "TOR",
      age: 28,
      contract: "2 yrs / $52M remaining",
      tradeValue: 67,
      trend: "stable",
      rationale:
        "Ingram's TVI has stabilized after a quietly excellent Toronto season — 21.7 PPG and elite mid-range efficiency — but the two-year window and history of soft-tissue injuries keep him from climbing higher. Toronto's willingness to move him as part of a younger-player-focused rebuild makes him one of the more realistically acquirable wings on the market, and his scoring profile would fit seamlessly alongside any of the top-ten players on this board. The price is likely to drop as his contract window shortens.",
    },
    {
      rank: 30,
      prevRank: 32,
      player: "Sam Merrill",
      team: "CLE",
      age: 29,
      contract: "2 yrs / $18M remaining",
      tradeValue: 58,
      trend: "up",
      rationale:
        "Merrill earns his first-ever TVI top-30 appearance on the strength of the single most impactful bench performance of the 2026 playoffs — 23 points and 5-of-8 from three in a road Game 7 against Boston's defense. His $9M AAV is the most affordable contract for a proven playoff performer in the current market, and his catch-and-shoot profile is the most repeatable skill set a contender can add at the trade deadline price point. One game doesn't make a career, but it absolutely makes a ranking.",
    },
  ],
};