// Auto-generated by generate-trade-value.mjs
// Week of May 25–31, 2026

export interface TVIPlayer {
  rank: number;
  prevRank: number;
  player: string;
  team: string;
  age: number;
  contract: string;
  tradeValue: number;
  trend: "up" | "down" | "stable";
  rationale: string;
}

export interface TVIData {
  generatedDate: string;
  weekLabel: string;
  players: TVIPlayer[];
}

export const tradeValueData: TVIData = {
  generatedDate: "May 25, 2026",
  weekLabel: "Week of May 25–31, 2026",
  players: [
    {
      rank: 1,
      prevRank: 1,
      player: "Victor Wembanyama",
      team: "SAS",
      age: 22,
      contract: "4 yrs / $196M remaining (rookie max)",
      tradeValue: 100,
      trend: "up",
      rationale:
        "Wembanyama's 31/18/5BLK series-saving performance in WCF Game 4 is the definitive reminder that no player on the planet operates at his ceiling — a 22-year-old on a rookie max deal who just carried San Antonio to a 2-2 series tie against the best record in the West. He is untradeable in the most literal sense: no front office in the league would move him, which is precisely why he anchors the top of this index. The gap between Wembanyama and the rest of this list is not a gap — it is a canyon.",
    },
    {
      rank: 2,
      prevRank: 2,
      player: "Shai Gilgeous-Alexander",
      team: "OKC",
      age: 27,
      contract: "3 yrs / $162M remaining",
      tradeValue: 97,
      trend: "stable",
      rationale:
        "A difficult WCF Game 4 in which San Antonio's switching scheme frustrated him all night does not meaningfully dent SGA's trade value — acquiring teams buy the body of work, and his body of work is an MVP-caliber regular season and three-plus rounds of playoff dominance. At 27, he is entering the heart of his prime on a contract that will look reasonable by 2028 standards. The series being tied 2-2 adds urgency to his Game 5 response, but no front office is reassessing his value based on one neutralized outing.",
    },
    {
      rank: 3,
      prevRank: 4,
      player: "Jalen Brunson",
      team: "NYK",
      age: 29,
      contract: "2 yrs / $113M remaining",
      tradeValue: 94,
      trend: "up",
      rationale:
        "Brunson's ECF body of work — 38, 29, and 30 points with zero turnovers in Game 2 across three games — is the most complete point-guard playoff resume of the 2026 postseason outside of Wembanyama's singular performance. At 29 he is at absolute peak, and the Knicks are one win from the Finals with him as the engine. His two-year remaining deal is the one knock that keeps him from the 96-plus tier, but any team acquiring him knows exactly what they are getting: a closer.",
    },
    {
      rank: 4,
      prevRank: 3,
      player: "Stephon Castle",
      team: "SAS",
      age: 21,
      contract: "3 yrs / $38M remaining (rookie)",
      tradeValue: 93,
      trend: "up",
      rationale:
        "Castle's bounce-back performance in WCF Game 4 — coming out attacking downhill after back-to-back shooting disasters — is exactly the kind of competitive DNA that elevates a prospect into a tradeable star. He is 21 years old on a rookie deal, playing lead guard minutes in the Western Conference Finals, and just delivered a response game in a series-saving win. His upside trajectory on this contract makes him the most cost-controlled asset in the top five of this index.",
    },
    {
      rank: 5,
      prevRank: 6,
      player: "Mikal Bridges",
      team: "NYK",
      age: 29,
      contract: "3 yrs / $87M remaining",
      tradeValue: 91,
      trend: "stable",
      rationale:
        "Bridges' 73.3% shooting masterclass in ECF Game 3 — 22 points on 11-of-15 — is the most efficient individual performance of the 2026 Conference Finals and a showcase of what he provides to a contender as a silent closer. His value to an acquiring team is specifically his ability to thrive without offensive creation burden, making him uniquely complementary to any star. Three years at $87M for a 29-year-old two-way wing who just shot 73% in a conference final is a contract that holds value.",
    },
    {
      rank: 6,
      prevRank: 8,
      player: "Karl-Anthony Towns",
      team: "NYK",
      age: 30,
      contract: "3 yrs / $154M remaining",
      tradeValue: 88,
      trend: "up",
      rationale:
        "Towns' game-high plus-23 and near triple-double in ECF Game 3 crystallized his role as the Knicks' connective tissue — the player whose gravity and passing create the conditions for Brunson and Bridges to operate freely. His trade value has quietly climbed all postseason as the analytics community catches up to how well-constructed his role is in Tom Thibodeau's system. The contract is large but three years for a 30-year-old stretch-five who can post a plus-23 in a conference final is a moveable asset.",
    },
    {
      rank: 7,
      prevRank: 5,
      player: "OG Anunoby",
      team: "NYK",
      age: 28,
      contract: "4 yrs / $212M remaining",
      tradeValue: 87,
      trend: "stable",
      rationale:
        "Anunoby's ECF Game 3 line — 21 points, 7 rebounds, 3-of-4 from three, plus-11, and relentless defense on Donovan Mitchell — is the prototype of what every contender wants from their third star. His slight drop from fifth reflects the weight of his four-year/$212M remaining obligation, which makes him expensive to acquire via trade; a team taking on that deal needs total certainty. Everything on the court says he is worth it — the contract math is the only conversation.",
    },
    {
      rank: 8,
      prevRank: 9,
      player: "De'Aaron Fox",
      team: "SAS",
      age: 28,
      contract: "3 yrs / $141M remaining",
      tradeValue: 86,
      trend: "up",
      rationale:
        "Fox's visible improvement in WCF Game 4 — sharper cuts, cleaner decision-making, better pace management as the ankle heals — is a meaningful data point for teams who spent the last week worried about his health trajectory. He is 28 years old, playing in the Western Conference Finals on a team that just evened the series, and his performance floor appears to be rising with each additional recovery day. The next two weeks of playoff basketball will be the most consequential stretch of his trade stock in years.",
    },
    {
      rank: 9,
      prevRank: 7,
      player: "Jared McCain",
      team: "OKC",
      age: 21,
      contract: "3 yrs / $22M remaining (rookie)",
      tradeValue: 84,
      trend: "down",
      rationale:
        "McCain's WCF Game 3 breakout — 24 points, plus-28 — injected genuine star-upside conversation into his profile, but San Antonio made him a near non-factor in Game 4 and that neutralization matters. The underlying trade value remains high because he is 21 on a rookie deal and the Game 3 tape is real, but acquiring teams will want to see Game 5 before locking in their valuation. His ranking reflects the tension between elite ceiling and the reality that a veteran defense just solved him in one game.",
    },
    {
      rank: 10,
      prevRank: 12,
      player: "Chet Holmgren",
      team: "OKC",
      age: 23,
      contract: "4 yrs / $54M remaining (rookie max)",
      tradeValue: 82,
      trend: "stable",
      rationale:
        "Holmgren's WCF body of work has been quietly consistent — elite rim protection, floor spacing, and the ability to switch across all five positions — and a 23-year-old on a rookie max deal with four years remaining is exactly the kind of building block that accelerates a contender's timeline. His value is partly suppressed by playing alongside SGA and winning enough that no team expects OKC to move him. He belongs in any honest top-ten trade value conversation.",
    },
    {
      rank: 11,
      prevRank: 13,
      player: "Evan Mobley",
      team: "CLE",
      age: 24,
      contract: "4 yrs / $191M remaining",
      tradeValue: 80,
      trend: "stable",
      rationale:
        "Mobley is the lone Cavalier whose trade stock has not been meaningfully damaged by Cleveland's 0-3 ECF hole — his two-way contributions and defensive anchor role are scheme-proof in a way Mitchell's volume scoring is not. At 24 on a max extension, he is expensive to acquire but cheap relative to his ceiling; a team pairing him with a lead guard would unlock his full value immediately. The Cavs' series situation creates legitimate questions about whether Cleveland might retool around him this summer.",
    },
    {
      rank: 12,
      prevRank: 10,
      player: "Donovan Mitchell",
      team: "CLE",
      age: 29,
      contract: "2 yrs / $98M remaining",
      tradeValue: 78,
      trend: "down",
      rationale:
        "Mitchell's minus-53 cumulative ECF plus/minus while averaging 26 points per game is the most damaging single-series stat line of the 2026 postseason — it has reopened every front-office conversation about whether he is a genuine franchise cornerstone or an elite empty scorer. He drops two spots this week not because his talent is in question but because his fit questions are louder than ever, and an acquisition now comes with the baggage of that narrative. Two years and $98M is a palatable contract if a team believes they have the right system; the series loss will create motivated-seller conditions this summer.",
    },
    {
      rank: 13,
      prevRank: 14,
      player: "Anthony Edwards",
      team: "MIN",
      age: 24,
      contract: "4 yrs / $188M remaining",
      tradeValue: 77,
      trend: "stable",
      rationale:
        "Edwards' playoff run ended earlier than expected but his regular-season dominance — and the fact that he is 24 on a max deal — keeps him firmly in the top-fifteen regardless of postseason result. The Timberwolves' front office situation this summer will generate trade speculation, and his name will be attached to every conversation whether or not Minnesota is a motivated seller. Any team acquiring him gets a top-five NBA talent entering his theoretical prime.",
    },
    {
      rank: 14,
      prevRank: 15,
      player: "Tyrese Haliburton",
      team: "IND",
      age: 25,
      contract: "3 yrs / $156M remaining",
      tradeValue: 75,
      trend: "stable",
      rationale:
        "Haliburton's postseason run is complete but his value as a 25-year-old lead orchestrator on a three-year deal makes him one of the most coveted non-playoff assets in the league this week. Indiana's direction this offseason — whether they push for a star upgrade around him or consider moving him to a contender — is the central trade story of the 2026 summer. A team acquiring him gets a top-ten point guard at cost-controlled rates by star-player standards.",
    },
    {
      rank: 15,
      prevRank: 16,
      player: "Nikola Jokic",
      team: "DEN",
      age: 31,
      contract: "2 yrs / $121M remaining",
      tradeValue: 74,
      trend: "stable",
      rationale:
        "Jokic remains one of the five most skilled basketball players on earth and his regular-season numbers remain historic, but 31 years old with two years remaining on a supermax creates legitimate questions about what an acquiring team is actually buying. Denver's first-round exit has intensified internal retooling conversations, and if the Nuggets enter a genuine rebuild, Jokic's preference on his destination becomes the dominant variable. His floor is still All-NBA — his ceiling as a trade chip is capped by age and timeline.",
    },
    {
      rank: 16,
      prevRank: 17,
      player: "Scottie Barnes",
      team: "TOR",
      age: 24,
      contract: "4 yrs / $178M remaining",
      tradeValue: 73,
      trend: "stable",
      rationale:
        "Barnes is the most coveted long-term asset on a non-contending team in the Eastern Conference — 24 years old, max extension, legitimate two-way upside, and on a Toronto team whose trajectory makes him a perennial trade-rumor centerpiece. His value is specifically in his age-contract combination: an acquiring contender gets four years of cost-controlled star potential. The knock is that his offensive ceiling remains undefined, which is also the reason his upside is priced in generously.",
    },
    {
      rank: 17,
      prevRank: 18,
      player: "LaMelo Ball",
      team: "CHA",
      age: 24,
      contract: "3 yrs / $144M remaining",
      tradeValue: 71,
      trend: "stable",
      rationale:
        "Ball's injury history is the one variable that keeps him from ranking five spots higher — when healthy, his playmaking and shot creation are legitimately elite, and a 24-year-old on three years remaining is a trade target that contenders will call about every single summer. Charlotte's perpetual rebuild creates a motivated-seller context that could make him available at a below-market price if the right offer materializes. His value is real; the discount reflects durability risk.",
    },
    {
      rank: 18,
      prevRank: 20,
      player: "Jaylen Brown",
      team: "BOS",
      age: 29,
      contract: "4 yrs / $219M remaining",
      tradeValue: 69,
      trend: "down",
      rationale:
        "Brown's trade value has been a front-office conversation topic all season, and Boston's early postseason exit has restarted those discussions with new urgency. At 29 on a four-year supermax, the contract structure is the dominant obstacle — $219M remaining is a commitment that limits the field of acquiring teams to a small number of cap-flexible contenders. His talent is unquestioned; his fit with the right system would unlock significant value that the Celtics structure may have suppressed.",
    },
    {
      rank: 19,
      prevRank: 19,
      player: "Alperen Sengun",
      team: "HOU",
      age: 23,
      contract: "4 yrs / $112M remaining",
      tradeValue: 68,
      trend: "up",
      rationale:
        "Sengun's development into one of the league's most creative interior scorers at 23 is precisely the kind of trajectory that makes his contract look like a bargain in year three. Houston is building around him and Amen Thompson as their long-term core, which means his availability is effectively zero — but his hypothetical trade value reflects what a creative-passing, high-usage center on a below-market deal would cost in a real negotiation. He is ascending.",
    },
    {
      rank: 20,
      prevRank: 21,
      player: "Amen Thompson",
      team: "HOU",
      age: 22,
      contract: "3 yrs / $28M remaining (rookie)",
      tradeValue: 67,
      trend: "up",
      rationale:
        "Thompson's emergence as one of the league's most dynamic transition and defensive players at 22 on a rookie deal makes him among the ten most cost-efficient assets in basketball regardless of team context. Houston has no intention of moving him, but a team willing to overpay in a trade package would be buying a player whose ceiling — elite two-way wing who can initiate offense — is still not fully realized. His value here reflects upside pricing on a bargain contract.",
    },
    {
      rank: 21,
      prevRank: 22,
      player: "Darius Garland",
      team: "CLE",
      age: 25,
      contract: "3 yrs / $98M remaining",
      tradeValue: 65,
      trend: "down",
      rationale:
        "Cleveland's 0-3 ECF hole has accelerated offseason retooling conversations, and Garland's name will be central to any discussion about reshaping the Cavaliers' core. His trade value is moderately suppressed this week by questions about his fit alongside the Mitchell-Mobley axis — acquiring teams will evaluate him as a lead guard who needs the right system, not just the right star. Three years at $98M is a moveable contract for a 25-year-old playmaker with a clean bill of health.",
    },
    {
      rank: 22,
      prevRank: 24,
      player: "Zion Williamson",
      team: "NOP",
      age: 25,
      contract: "3 yrs / $143M remaining",
      tradeValue: 62,
      trend: "stable",
      rationale:
        "Zion's talent remains genuinely generational when healthy — the problem, as always, is that qualifier. New Orleans' rebuild trajectory makes him theoretically available, and a contender willing to absorb his injury risk gets a player who, at full health, would immediately become one of the three most dominant interior forces in basketball. Three years and $143M is manageable for that upside; the medical evaluation on any potential deal is the entire conversation.",
    },
    {
      rank: 23,
      prevRank: 23,
      player: "Brandon Ingram",
      team: "TOR",
      age: 28,
      contract: "1 yr / $36M remaining",
      tradeValue: 60,
      trend: "stable",
      rationale:
        "Ingram's one-year deal makes him the quintessential deadline rental target — a 28-year-old primary creator who can get his own shot in the half-court and has playoff experience. Toronto acquired him as a bridge asset, and his value to a contender as a third or fourth offensive option at the deadline is well-established. The single year remaining limits his ranking here; a team trading for him is buying a half-season window, not a long-term piece.",
    },
    {
      rank: 24,
      prevRank: 26,
      player: "Jaren Jackson Jr.",
      team: "MEM",
      age: 26,
      contract: "3 yrs / $126M remaining",
      tradeValue: 59,
      trend: "stable",
      rationale:
        "Jackson is the most underrated trade chip in the league right now — a 26-year-old two-time Defensive Player of the Year finalist who can stretch the floor to the three-point line, protect the rim, and defend in space. Memphis' rebuild timeline creates a realistic scenario in which he is shopped this summer, and a contender adding him as a third piece around an established star-guard combination would immediately become a Finals contender. His value is real; his team context suppresses his visibility.",
    },
    {
      rank: 25,
      prevRank: 27,
      player: "Keegan Murray",
      team: "SAC",
      age: 24,
      contract: "3 yrs / $72M remaining",
      tradeValue: 57,
      trend: "up",
      rationale:
        "Murray's growth into a legitimate two-way wing starter — elite three-point shooting, improving defensive versatility, and consistent motor — on a below-market extension makes him one of the most appealing third-piece trade targets in the league. Sacramento's perpetual contention ceiling creates ongoing motivation to evaluate whether reshaping the roster around De'Aaron Fox's departure makes Murray available. At 24 and on that contract, he would fit immediately on any playoff team.",
    },
    {
      rank: 26,
      prevRank: 25,
      player: "Trae Young",
      team: "ATL",
      age: 27,
      contract: "2 yrs / $88M remaining",
      tradeValue: 55,
      trend: "down",
      rationale:
        "Young's trade value has been actively discussed league-wide all season, and Atlanta's direction post-Fox departure makes a summer deal more plausible than at any point in the last two years. His two-year contract is the most tradeable structure on his resume — an acquiring team is not committing beyond 2028 — but fit questions around his defense and the specific system requirements of his offense limit the field of realistic partners. He remains elite in the right situation; finding that situation via trade is Atlanta's summer project.",
    },
    {
      rank: 27,
      prevRank: 28,
      player: "Franz Wagner",
      team: "ORL",
      age: 24,
      contract: "4 yrs / $168M remaining",
      tradeValue: 53,
      trend: "stable",
      rationale:
        "Wagner's max extension locks in one of the league's best two-way forwards through his prime years, and Orlando's rebuild ceiling — with Paolo Banchero — creates a scenario in which one of the two could be moved to acquire veteran help. His value as an acquiring asset is his age-skill combination: 24, elite shot creation for a wing, improving playmaking, and enough defensive versatility to guard multiple positions. The contract size suppresses demand but the talent justifies it.",
    },
    {
      rank: 28,
      prevRank: 29,
      player: "Josh Giddey",
      team: "CHI",
      age: 21,
      contract: "3 yrs / $67M remaining",
      tradeValue: 51,
      trend: "stable",
      rationale:
        "Giddey's development in Chicago has been quietly encouraging — his playmaking and rebounding translate regardless of team context, and a 21-year-old with his passing instincts on a reasonable contract is a long-term asset that contenders will circle in future trade discussions. His ranking reflects a player whose ceiling is projected rather than demonstrated at the star level, but the raw tools are real. Chicago's rebuilding posture makes him hypothetically available at the right price.",
    },
    {
      rank: 29,
      prevRank: 30,
      player: "Bam Adebayo",
      team: "MIA",
      age: 28,
      contract: "2 yrs / $58M remaining",
      tradeValue: 49,
      trend: "down",
      rationale:
        "Adebayo's trade value has quietly declined as Miami's retooling has accelerated and his offensive limitations in a star-creation role have become more pronounced. Two years and $58M remaining is manageable, and his defensive versatility and pick-and-roll IQ remain top-ten at the center position — but an acquiring team is buying a complementary piece, not a franchise cornerstone. His ranking reflects genuine value in the right system paired with the reality of a narrowing prime window.",
    },
    {
      rank: 30,
      prevRank: 28,
      player: "Draymond Green",
      team: "GSW",
      age: 36,
      contract: "1 yr / $22M remaining",
      tradeValue: 42,
      trend: "down",
      rationale:
        "Green's trade value in 2026 is almost entirely contextual — on the right contending team running a modern switching scheme, he still provides elite defensive communication, playmaking from the center position, and championship DNA that cannot be taught. The one remaining year limits the cost and the risk simultaneously. His ranking at 30 reflects that acquiring him is a very specific bet on a very specific use case — and that fewer teams in 2026 run the system that maximizes him than at any prior point in his career.",
    },
  ],
};