// Auto-generated Trade Simulator data
// Weekly "What If" trade proposals and tradeable player database

export interface TradeablePlayer {
  name: string;
  team: string;
  position: string;
  age: number;
  salary: string;
  contractYears: number;
  ppg: number;
  rpg: number;
  apg: number;
  tradeValue: number;
  tradeable: boolean;
  untouchable: boolean;
}

export interface TradeProposal {
  id: string;
  team1: { team: string; sending: string[]; receiving: string[] };
  team2: { team: string; sending: string[]; receiving: string[] };
  salaryMatch: boolean;
  salaryDiff: string;
  aiVerdict: "approve" | "reject" | "conditional";
  aiAnalysis: string;
  team1Impact: { offense: number; defense: number; chemistry: number; future: number };
  team2Impact: { offense: number; defense: number; chemistry: number; future: number };
  winProjectionChange: { team1: string; team2: string };
}

export interface TradeSimData {
  generatedDate: string;
  players: TradeablePlayer[];
  featuredTrades: TradeProposal[];
  hottest: { player: string; team: string; reason: string }[];
}

export const tradeSimData: TradeSimData = {
  generatedDate: "April 20, 2026",
  players: [
    {
      name: "Paolo Banchero",
      team: "ORL",
      position: "PF",
      age: 23,
      salary: "$34.8M",
      contractYears: 3,
      ppg: 27.4,
      rpg: 7.8,
      apg: 5.6,
      tradeValue: 97,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Jayson Tatum",
      team: "BOS",
      position: "SF",
      age: 28,
      salary: "$54.6M",
      contractYears: 4,
      ppg: 29.2,
      rpg: 8.1,
      apg: 4.8,
      tradeValue: 96,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Shai Gilgeous-Alexander",
      team: "OKC",
      position: "PG",
      age: 27,
      salary: "$52.1M",
      contractYears: 4,
      ppg: 32.1,
      rpg: 5.2,
      apg: 6.4,
      tradeValue: 98,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Victor Wembanyama",
      team: "SAS",
      position: "C",
      age: 22,
      salary: "$14.1M",
      contractYears: 3,
      ppg: 24.8,
      rpg: 11.3,
      apg: 3.7,
      tradeValue: 99,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Cade Cunningham",
      team: "DET",
      position: "PG",
      age: 24,
      salary: "$40.2M",
      contractYears: 4,
      ppg: 26.3,
      rpg: 6.1,
      apg: 8.9,
      tradeValue: 93,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Franz Wagner",
      team: "ORL",
      position: "SF",
      age: 24,
      salary: "$26.4M",
      contractYears: 3,
      ppg: 22.7,
      rpg: 5.4,
      apg: 4.1,
      tradeValue: 88,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Jaylen Brown",
      team: "BOS",
      position: "SG",
      age: 29,
      salary: "$49.7M",
      contractYears: 3,
      ppg: 23.8,
      rpg: 5.5,
      apg: 3.4,
      tradeValue: 82,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Chet Holmgren",
      team: "OKC",
      position: "C",
      age: 23,
      salary: "$12.6M",
      contractYears: 2,
      ppg: 20.4,
      rpg: 8.6,
      apg: 2.3,
      tradeValue: 87,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Joel Embiid",
      team: "PHI",
      position: "C",
      age: 31,
      salary: "$59.5M",
      contractYears: 2,
      ppg: 28.1,
      rpg: 10.9,
      apg: 3.8,
      tradeValue: 74,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Damian Lillard",
      team: "POR",
      position: "PG",
      age: 35,
      salary: "$48.8M",
      contractYears: 1,
      ppg: 24.6,
      rpg: 3.9,
      apg: 7.2,
      tradeValue: 58,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Evan Mobley",
      team: "CLE",
      position: "PF",
      age: 24,
      salary: "$31.5M",
      contractYears: 3,
      ppg: 19.8,
      rpg: 9.4,
      apg: 2.8,
      tradeValue: 85,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Donovan Mitchell",
      team: "CLE",
      position: "SG",
      age: 29,
      salary: "$43.9M",
      contractYears: 2,
      ppg: 27.6,
      rpg: 4.4,
      apg: 5.9,
      tradeValue: 80,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Anthony Davis",
      team: "LAL",
      position: "C",
      age: 32,
      salary: "$46.2M",
      contractYears: 1,
      ppg: 24.3,
      rpg: 12.7,
      apg: 2.9,
      tradeValue: 72,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "LeBron James",
      team: "LAL",
      position: "SF",
      age: 41,
      salary: "$51.4M",
      contractYears: 1,
      ppg: 21.2,
      rpg: 7.1,
      apg: 8.4,
      tradeValue: 60,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Nikola Jokic",
      team: "DEN",
      position: "C",
      age: 31,
      salary: "$57.3M",
      contractYears: 2,
      ppg: 28.9,
      rpg: 12.8,
      apg: 9.4,
      tradeValue: 91,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Luka Doncic",
      team: "DAL",
      position: "PG",
      age: 26,
      salary: "$53.8M",
      contractYears: 3,
      ppg: 30.4,
      rpg: 8.7,
      apg: 9.1,
      tradeValue: 95,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Giannis Antetokounmpo",
      team: "MIL",
      position: "PF",
      age: 31,
      salary: "$55.9M",
      contractYears: 2,
      ppg: 29.7,
      rpg: 11.4,
      apg: 5.8,
      tradeValue: 89,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Tyrese Haliburton",
      team: "IND",
      position: "PG",
      age: 25,
      salary: "$38.7M",
      contractYears: 3,
      ppg: 22.4,
      rpg: 4.1,
      apg: 11.3,
      tradeValue: 86,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Pascal Siakam",
      team: "IND",
      position: "PF",
      age: 31,
      salary: "$37.8M",
      contractYears: 2,
      ppg: 21.6,
      rpg: 7.3,
      apg: 4.2,
      tradeValue: 71,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Bam Adebayo",
      team: "MIA",
      position: "C",
      age: 28,
      salary: "$35.2M",
      contractYears: 3,
      ppg: 19.4,
      rpg: 10.2,
      apg: 3.6,
      tradeValue: 78,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jimmy Butler",
      team: "MIA",
      position: "SF",
      age: 36,
      salary: "$48.3M",
      contractYears: 1,
      ppg: 20.8,
      rpg: 5.3,
      apg: 4.9,
      tradeValue: 55,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Karl-Anthony Towns",
      team: "NYK",
      position: "C",
      age: 30,
      salary: "$50.1M",
      contractYears: 2,
      ppg: 23.9,
      rpg: 10.6,
      apg: 3.1,
      tradeValue: 76,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jalen Brunson",
      team: "NYK",
      position: "PG",
      age: 29,
      salary: "$43.7M",
      contractYears: 3,
      ppg: 26.8,
      rpg: 3.7,
      apg: 7.6,
      tradeValue: 84,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Devin Booker",
      team: "PHX",
      position: "SG",
      age: 29,
      salary: "$47.3M",
      contractYears: 2,
      ppg: 26.1,
      rpg: 4.8,
      apg: 6.3,
      tradeValue: 79,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Bradley Beal",
      team: "PHX",
      position: "SG",
      age: 32,
      salary: "$50.2M",
      contractYears: 2,
      ppg: 17.4,
      rpg: 3.9,
      apg: 4.7,
      tradeValue: 38,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "De'Aaron Fox",
      team: "SAC",
      position: "PG",
      age: 27,
      salary: "$36.4M",
      contractYears: 2,
      ppg: 25.3,
      rpg: 4.2,
      apg: 7.8,
      tradeValue: 81,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jaren Jackson Jr.",
      team: "MEM",
      position: "PF",
      age: 26,
      salary: "$33.6M",
      contractYears: 3,
      ppg: 21.2,
      rpg: 7.1,
      apg: 1.8,
      tradeValue: 80,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Trae Young",
      team: "ATL",
      position: "PG",
      age: 27,
      salary: "$41.2M",
      contractYears: 2,
      ppg: 27.3,
      rpg: 3.6,
      apg: 10.8,
      tradeValue: 69,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Brandon Ingram",
      team: "NOP",
      position: "SF",
      age: 28,
      salary: "$35.7M",
      contractYears: 1,
      ppg: 23.1,
      rpg: 5.6,
      apg: 4.4,
      tradeValue: 62,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Scottie Barnes",
      team: "TOR",
      position: "PF",
      age: 24,
      salary: "$30.8M",
      contractYears: 3,
      ppg: 20.6,
      rpg: 8.2,
      apg: 5.3,
      tradeValue: 82,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Zach LaVine",
      team: "CHI",
      position: "SG",
      age: 30,
      salary: "$43.9M",
      contractYears: 2,
      ppg: 24.2,
      rpg: 4.7,
      apg: 4.9,
      tradeValue: 63,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Alperen Sengun",
      team: "HOU",
      position: "C",
      age: 23,
      salary: "$18.2M",
      contractYears: 3,
      ppg: 20.1,
      rpg: 9.3,
      apg: 4.6,
      tradeValue: 83,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Amen Thompson",
      team: "HOU",
      position: "SF",
      age: 22,
      salary: "$11.4M",
      contractYears: 3,
      ppg: 16.8,
      rpg: 7.4,
      apg: 4.1,
      tradeValue: 77,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "OG Anunoby",
      team: "NYK",
      position: "SF",
      age: 28,
      salary: "$38.1M",
      contractYears: 3,
      ppg: 17.9,
      rpg: 4.8,
      apg: 2.1,
      tradeValue: 75,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Draymond Green",
      team: "GSW",
      position: "PF",
      age: 35,
      salary: "$24.8M",
      contractYears: 1,
      ppg: 10.4,
      rpg: 7.2,
      apg: 7.8,
      tradeValue: 46,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Stephen Curry",
      team: "GSW",
      position: "PG",
      age: 37,
      salary: "$59.7M",
      contractYears: 1,
      ppg: 25.3,
      rpg: 4.6,
      apg: 6.4,
      tradeValue: 67,
      tradeable: true,
      untouchable: false,
    },
  ],
  featuredTrades: [
    {
      id: "trade-1",
      team1: {
        team: "PHI",
        sending: ["Joel Embiid", "2027 First-Round Pick (PHI)"],
        receiving: ["Giannis Antetokounmpo"],
      },
      team2: {
        team: "MIL",
        sending: ["Giannis Antetokounmpo"],
        receiving: ["Joel Embiid", "2027 First-Round Pick (PHI)"],
      },
      salaryMatch: true,
      salaryDiff: "+$3.4M (within threshold)",
      aiVerdict: "conditional",
      aiAnalysis:
        "Philadelphia's embarrassing 32-point blowout loss at Boston this week exposed the 76ers' ceiling as currently constructed — swapping Embiid's injury-prone dominance for Giannis's durability and motor could be the franchise reset PHI desperately needs. However, Milwaukee takes on a 31-year-old center with $59.5M on the books and limited runway, which is a steep price for a team already needing a rebuild. This deal reshapes both franchises dramatically but hinges on whether Embiid can stay healthy enough to justify the Bucks' transition cost.",
      team1Impact: { offense: +3, defense: +4, chemistry: +2, future: -1 },
      team2Impact: { offense: +2, defense: -2, chemistry: -3, future: -4 },
      winProjectionChange: { team1: "+4.5 wins", team2: "-2.0 wins" },
    },
    {
      id: "trade-2",
      team1: {
        team: "BOS",
        sending: ["Jaylen Brown"],
        receiving: ["Donovan Mitchell", "2026 First-Round Pick (CLE)"],
      },
      team2: {
        team: "CLE",
        sending: ["Donovan Mitchell", "2026 First-Round Pick (CLE)"],
        receiving: ["Jaylen Brown"],
      },
      salaryMatch: true,
      salaryDiff: "+$5.8M (within threshold)",
      aiVerdict: "approve",
      aiAnalysis:
        "Brown was outstanding again in Boston's 32-point demolition of Philadelphia this week, but his $49.7M salary and expiring window make him the most logical trade piece as Boston looks to reinforce its championship roster. Mitchell brings a more dynamic offensive profile to pair with Tatum, and Cleveland's pick sweetens a deal that gives the Cavs a proven co-star alongside Evan Mobley. Boston upgrades its second scorer while Cleveland finally acquires the wing versatility their roster has been missing all season.",
      team1Impact: { offense: +2, defense: -1, chemistry: +1, future: +3 },
      team2Impact: { offense: +3, defense: +2, chemistry: +2, future: +1 },
      winProjectionChange: { team1: "+2.0 wins", team2: "+3.5 wins" },
    },
    {
      id: "trade-3",
      team1: {
        team: "DET",
        sending: ["2027 First-Round Pick (DET)", "2028 First-Round Pick (DET)"],
        receiving: ["De'Aaron Fox"],
      },
      team2: {
        team: "SAC",
        sending: ["De'Aaron Fox"],
        receiving: ["2027 First-Round Pick (DET)", "2028 First-Round Pick (DET)"],
      },
      salaryMatch: true,
      salaryDiff: "+$3.8M (within threshold)",
      aiVerdict: "approve",
      aiAnalysis:
        "Detroit's stunning home loss to Orlando on Sunday revealed that Cade Cunningham needs a more explosive co-star to elevate the Pistons beyond fringe contenders — Fox's speed and scoring would transform the Pistons' backcourt into one of the league's most dynamic. Sacramento, sitting on a stagnant roster with Fox entering the final stretch of his prime, hits the rebuild button with two premium Detroit first-round picks from a 60-win franchise. This is a win-now move for Detroit and a smart future-building decision for Sacramento.",
      team1Impact: { offense: +5, defense: +1, chemistry: +3, future: -4 },
      team2Impact: { offense: -4, defense: -2, chemistry: -2, future: +7 },
      winProjectionChange: { team1: "+5.0 wins", team2: "-4.5 wins" },
    },
    {
      id: "trade-4",
      team1: {
        team: "PHX",
        sending: ["Bradley Beal", "2027 Second-Round Pick (PHX)"],
        receiving: ["Pascal Siakam"],
      },
      team2: {
        team: "IND",
        sending: ["Pascal Siakam"],
        receiving: ["Bradley Beal", "2027 Second-Round Pick (PHX)"],
      },
      salaryMatch: false,
      salaryDiff: "+$12.4M (exceeds threshold — requires third team or TPE)",
      aiVerdict: "reject",
      aiAnalysis:
        "Phoenix's continued struggles, highlighted by SGA and the Thunder dropping a 35-point demolition on them this week, expose a roster built around Beal's underperforming $50.2M contract as fundamentally flawed. Indiana has no incentive to absorb Beal's dead weight — his 17.4 PPG and declining athleticism would be a massive downgrade from Siakam's two-way versatility, and the salary mismatch of over $12M makes this a hard no without a third team involved. Phoenix needs to eat Beal's contract or find a willing cap-space team; Indiana should not be that team.",
      team1Impact: { offense: +2, defense: +3, chemistry: +1, future: +1 },
      team2Impact: { offense: -4, defense: -3, chemistry: -4, future: -5 },
      winProjectionChange: { team1: "+2.5 wins", team2: "-6.0 wins" },
    },
    {
      id: "trade-5",
      team1: {
        team: "LAL",
        sending: ["Anthony Davis", "LeBron James"],
        receiving: ["Karl-Anthony Towns", "OG Anunoby", "2027 First-Round Pick (NYK)"],
      },
      team2: {
        team: "NYK",
        sending: ["Karl-Anthony Towns", "OG Anunoby", "2027 First-Round Pick (NYK)"],
        receiving: ["Anthony Davis", "LeBron James"],
      },
      salaryMatch: true,
      salaryDiff: "+$9.5M (within threshold)",
      aiVerdict: "approve",
      aiAnalysis:
        "With both LeBron and Davis in the final year of their deals and the Lakers locked out of the playoffs, Los Angeles finally pulls the full rebuild trigger by packaging its two stars for a younger, longer-term core in Towns and Anunoby. New York gets two last-dance legends to make a legitimate Finals push alongside Brunson, potentially transforming the Knicks from contenders to favorites in the East. The Lakers absorb versatile youth and a future first, resetting the franchise for a post-LeBron era while New York bets big on a championship window in 2026.",
      team1Impact: { offense: -3, defense: -2, chemistry: -2, future: +8 },
      team2Impact: { offense: +5, defense: +4, chemistry: +3, future: -5 },
      winProjectionChange: { team1: "-5.0 wins", team2: "+6.5 wins" },
    },
    {
      id: "trade-6",
      team1: {
        team: "POR",
        sending: ["Damian Lillard"],
        receiving: ["Trae Young", "Scottie Barnes"],
      },
      team2: {
        team: "ATL",
        sending: ["Trae Young", "Scottie Barnes"],
        receiving: ["Damian Lillard", "2027 First-Round Pick (POR)"],
      },
      salaryMatch: false,
      salaryDiff: "+$7.9M (requires TPE or minor salary filler)",
      aiVerdict: "conditional",
      aiAnalysis:
        "Portland's 42-41 record and Lillard's 45.5% shooting performance in Sunday's loss to Wembanyama and San Antonio crystallize why this marriage has run its course — a trade to Atlanta gives Lillard one last shot at a contender rebuild while Portland gets a younger building block in Barnes and a dynamic playmaker in Young. The catch is Atlanta must involve Toronto in a three-team structure to handle the salary gap, and Portland trading Lillard mid-playoff push requires buy-in from a locker room that still rallies around its veteran leader. A conditional yes if the salary filler can be resolved with a third team.",
      team1Impact: { offense: -1, defense: +2, chemistry: +1, future: +5 },
      team2Impact: { offense: +3, defense: -1, chemistry: +2, future: -2 },
      winProjectionChange: { team1: "+1.0 wins", team2: "+3.0 wins" },
    },
  ],
  hottest: [
    {
      player: "Joel Embiid",
      team: "PHI",
      reason:
        "Embiid's inability to prevent Philadelphia's 32-point humiliation in Boston this week has league executives questioning the franchise's direction. With $59.5M owed over two years and whispers of a front-office reset, Embiid is the most discussed trade asset in the Eastern Conference.",
    },
    {
      player: "Giannis Antetokounmpo",
      team: "MIL",
      reason:
        "Milwaukee's slide out of playoff relevance has intensified trade rumors around the Greek Freak, who has two years left on a max deal. Multiple contenders are reportedly circling as the Bucks quietly gauge returns for their franchise cornerstone.",
    },
    {
      player: "Damian Lillard",
      team: "POR",
      reason:
        "Sunday's loss to San Antonio — in which Wembanyama's rim protection neutralized Lillard repeatedly — has accelerated conversations about moving the veteran guard before his expiring deal walks. Portland's 42-41 record suggests the rebuild clock is ticking louder than ever.",
    },
    {
      player: "Jaylen Brown",
      team: "BOS",
      reason:
        "Brown's excellence in Boston's demolition of Philadelphia this week has paradoxically increased his trade appeal — teams see peak value right now, and with $49.7M on the books, Boston may use this moment of peak leverage to restructure its long-term roster around Tatum.",
    },
    {
      player: "Devin Booker",
      team: "PHX",
      reason:
        "Oklahoma City's 35-point hammering of Phoenix exposed the Suns' roster as fundamentally broken around Booker. With two years left and the franchise at a crossroads post-Beal experiment, Booker's name has resurfaced in trade talks with at least three teams according to league sources.",
    },
    {
      player: "De'Aaron Fox",
      team: "SAC",
      reason:
        "Fox has quietly emerged as the most coveted guard available outside of the untouchable tier following Sacramento's stagnant season. Detroit, Miami, and Cleveland have all been linked to the 27-year-old speedster as teams look to upgrade their backcourt before the playoff stretch.",
    },
  ],
};