// Auto-generated Trade Simulator data
// Weekly "What If" trade proposals and tradeable player database

export interface TradeablePlayer {
  name: string;
  team: string;
  position: string;
  age: number;
  salary: string;
  contractYears: number;
  ppg: number;
  rpg: number;
  apg: number;
  tradeValue: number;
  tradeable: boolean;
  untouchable: boolean;
}

export interface TradeProposal {
  id: string;
  team1: { team: string; sending: string[]; receiving: string[] };
  team2: { team: string; sending: string[]; receiving: string[] };
  salaryMatch: boolean;
  salaryDiff: string;
  aiVerdict: "approve" | "reject" | "conditional";
  aiAnalysis: string;
  team1Impact: { offense: number; defense: number; chemistry: number; future: number };
  team2Impact: { offense: number; defense: number; chemistry: number; future: number };
  winProjectionChange: { team1: string; team2: string };
}

export interface TradeSimData {
  generatedDate: string;
  players: TradeablePlayer[];
  featuredTrades: TradeProposal[];
  hottest: { player: string; team: string; reason: string }[];
}

export const tradeSimData: TradeSimData = {
  generatedDate: "May 18, 2026",
  players: [
    // ── FRANCHISE CORNERSTONES (untouchable) ──────────────────────────
    {
      name: "Shai Gilgeous-Alexander",
      team: "OKC",
      position: "PG",
      age: 27,
      salary: "$43.8M",
      contractYears: 4,
      ppg: 30.1,
      rpg: 6.2,
      apg: 6.5,
      tradeValue: 99,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Victor Wembanyama",
      team: "SAS",
      position: "C",
      age: 22,
      salary: "$14.1M",
      contractYears: 4,
      ppg: 24.3,
      rpg: 10.8,
      apg: 3.6,
      tradeValue: 99,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Evan Mobley",
      team: "CLE",
      position: "PF",
      age: 24,
      salary: "$38.5M",
      contractYears: 4,
      ppg: 21.0,
      rpg: 12.0,
      apg: 6.0,
      tradeValue: 98,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Donovan Mitchell",
      team: "CLE",
      position: "SG",
      age: 29,
      salary: "$37.1M",
      contractYears: 3,
      ppg: 27.7,
      rpg: 4.8,
      apg: 5.9,
      tradeValue: 96,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Stephon Castle",
      team: "SAS",
      position: "PG",
      age: 21,
      salary: "$11.4M",
      contractYears: 3,
      ppg: 18.5,
      rpg: 6.2,
      apg: 3.8,
      tradeValue: 95,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Jalen Brunson",
      team: "NYK",
      position: "PG",
      age: 29,
      salary: "$40.2M",
      contractYears: 3,
      ppg: 27.8,
      rpg: 3.8,
      apg: 6.3,
      tradeValue: 94,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "De'Aaron Fox",
      team: "SAS",
      position: "PG",
      age: 28,
      salary: "$34.9M",
      contractYears: 3,
      ppg: 19.5,
      rpg: 3.8,
      apg: 7.2,
      tradeValue: 88,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Karl-Anthony Towns",
      team: "NYK",
      position: "C",
      age: 30,
      salary: "$49.1M",
      contractYears: 2,
      ppg: 24.5,
      rpg: 10.2,
      apg: 3.1,
      tradeValue: 82,
      tradeable: false,
      untouchable: true,
    },
    // ── TRADEABLE STARS & ROTATION PIECES ────────────────────────────
    {
      name: "James Harden",
      team: "CLE",
      position: "PG",
      age: 36,
      salary: "$18.4M",
      contractYears: 1,
      ppg: 14.2,
      rpg: 4.1,
      apg: 9.8,
      tradeValue: 58,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Sam Merrill",
      team: "CLE",
      position: "SG",
      age: 29,
      salary: "$7.2M",
      contractYears: 2,
      ppg: 10.4,
      rpg: 2.8,
      apg: 1.4,
      tradeValue: 52,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jarrett Allen",
      team: "CLE",
      position: "C",
      age: 27,
      salary: "$21.0M",
      contractYears: 2,
      ppg: 12.1,
      rpg: 9.4,
      apg: 1.8,
      tradeValue: 64,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Chet Holmgren",
      team: "OKC",
      position: "PF",
      age: 23,
      salary: "$10.9M",
      contractYears: 2,
      ppg: 17.6,
      rpg: 7.8,
      apg: 2.3,
      tradeValue: 80,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jalen Williams",
      team: "OKC",
      position: "SF",
      age: 24,
      salary: "$19.7M",
      contractYears: 3,
      ppg: 20.4,
      rpg: 4.6,
      apg: 4.9,
      tradeValue: 84,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Luguentz Dort",
      team: "OKC",
      position: "SG",
      age: 26,
      salary: "$15.3M",
      contractYears: 2,
      ppg: 11.8,
      rpg: 3.5,
      apg: 1.7,
      tradeValue: 60,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Isaiah Hartenstein",
      team: "OKC",
      position: "C",
      age: 26,
      salary: "$17.8M",
      contractYears: 3,
      ppg: 10.2,
      rpg: 8.6,
      apg: 3.1,
      tradeValue: 70,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "OG Anunoby",
      team: "NYK",
      position: "SF",
      age: 28,
      salary: "$36.8M",
      contractYears: 3,
      ppg: 16.7,
      rpg: 5.2,
      apg: 2.1,
      tradeValue: 78,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Miles McBride",
      team: "NYK",
      position: "PG",
      age: 24,
      salary: "$8.6M",
      contractYears: 2,
      ppg: 12.4,
      rpg: 2.9,
      apg: 3.8,
      tradeValue: 62,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Josh Hart",
      team: "NYK",
      position: "SF",
      age: 29,
      salary: "$14.5M",
      contractYears: 2,
      ppg: 9.4,
      rpg: 7.8,
      apg: 3.2,
      tradeValue: 60,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Mikal Bridges",
      team: "NYK",
      position: "SF",
      age: 28,
      salary: "$22.3M",
      contractYears: 3,
      ppg: 18.9,
      rpg: 4.2,
      apg: 3.6,
      tradeValue: 76,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Devin Booker",
      team: "PHX",
      position: "SG",
      age: 29,
      salary: "$39.5M",
      contractYears: 3,
      ppg: 26.3,
      rpg: 4.7,
      apg: 5.6,
      tradeValue: 85,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Bradley Beal",
      team: "PHX",
      position: "SG",
      age: 32,
      salary: "$47.6M",
      contractYears: 2,
      ppg: 14.1,
      rpg: 3.7,
      apg: 4.2,
      tradeValue: 34,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "LeBron James",
      team: "LAL",
      position: "SF",
      age: 41,
      salary: "$51.4M",
      contractYears: 1,
      ppg: 22.1,
      rpg: 7.4,
      apg: 8.9,
      tradeValue: 72,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Anthony Davis",
      team: "LAL",
      position: "C",
      age: 32,
      salary: "$43.2M",
      contractYears: 2,
      ppg: 24.6,
      rpg: 12.1,
      apg: 3.2,
      tradeValue: 79,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Austin Reaves",
      team: "LAL",
      position: "SG",
      age: 27,
      salary: "$24.7M",
      contractYears: 3,
      ppg: 18.4,
      rpg: 4.1,
      apg: 5.0,
      tradeValue: 72,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jayson Tatum",
      team: "BOS",
      position: "SF",
      age: 28,
      salary: "$54.2M",
      contractYears: 4,
      ppg: 27.9,
      rpg: 8.4,
      apg: 4.6,
      tradeValue: 93,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Jaylen Brown",
      team: "BOS",
      position: "SG",
      age: 29,
      salary: "$49.5M",
      contractYears: 3,
      ppg: 23.4,
      rpg: 5.3,
      apg: 3.4,
      tradeValue: 80,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Trae Young",
      team: "ATL",
      position: "PG",
      age: 27,
      salary: "$37.1M",
      contractYears: 2,
      ppg: 25.6,
      rpg: 3.2,
      apg: 11.8,
      tradeValue: 74,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Zach LaVine",
      team: "CHI",
      position: "SG",
      age: 30,
      salary: "$43.9M",
      contractYears: 2,
      ppg: 22.8,
      rpg: 4.6,
      apg: 5.3,
      tradeValue: 62,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "DeMar DeRozan",
      team: "SAC",
      position: "SF",
      age: 36,
      salary: "$28.7M",
      contractYears: 1,
      ppg: 21.9,
      rpg: 4.1,
      apg: 4.7,
      tradeValue: 55,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Darius Garland",
      team: "CLE",
      position: "PG",
      age: 25,
      salary: "$33.4M",
      contractYears: 2,
      ppg: 16.8,
      rpg: 2.9,
      apg: 7.4,
      tradeValue: 68,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Paolo Banchero",
      team: "ORL",
      position: "PF",
      age: 23,
      salary: "$16.2M",
      contractYears: 2,
      ppg: 22.6,
      rpg: 6.9,
      apg: 4.8,
      tradeValue: 86,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Franz Wagner",
      team: "ORL",
      position: "SF",
      age: 24,
      salary: "$22.1M",
      contractYears: 3,
      ppg: 20.4,
      rpg: 5.4,
      apg: 4.1,
      tradeValue: 82,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Tyrese Haliburton",
      team: "IND",
      position: "PG",
      age: 26,
      salary: "$38.6M",
      contractYears: 3,
      ppg: 21.4,
      rpg: 4.0,
      apg: 10.9,
      tradeValue: 87,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Giannis Antetokounmpo",
      team: "MIL",
      position: "PF",
      age: 31,
      salary: "$55.8M",
      contractYears: 3,
      ppg: 29.8,
      rpg: 11.6,
      apg: 5.8,
      tradeValue: 91,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Nikola Jokic",
      team: "DEN",
      position: "C",
      age: 31,
      salary: "$56.9M",
      contractYears: 3,
      ppg: 28.4,
      rpg: 13.1,
      apg: 9.8,
      tradeValue: 97,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Kevin Durant",
      team: "PHX",
      position: "SF",
      age: 37,
      salary: "$51.2M",
      contractYears: 2,
      ppg: 26.8,
      rpg: 6.9,
      apg: 4.1,
      tradeValue: 78,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jimmy Butler",
      team: "GSW",
      position: "SF",
      age: 36,
      salary: "$48.8M",
      contractYears: 1,
      ppg: 18.6,
      rpg: 5.4,
      apg: 4.9,
      tradeValue: 60,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Brandon Ingram",
      team: "TOR",
      position: "SF",
      age: 28,
      salary: "$33.5M",
      contractYears: 2,
      ppg: 23.1,
      rpg: 5.8,
      apg: 4.4,
      tradeValue: 71,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Scottie Barnes",
      team: "TOR",
      position: "PF",
      age: 24,
      salary: "$35.4M",
      contractYears: 3,
      ppg: 19.2,
      rpg: 8.4,
      apg: 6.1,
      tradeValue: 83,
      tradeable: true,
      untouchable: false,
    },
  ],

  featuredTrades: [
    // ── TRADE 1 ── APPROVED ───────────────────────────────────────────
    {
      id: "trade-1",
      team1: {
        team: "LAL",
        sending: ["Anthony Davis", "Austin Reaves"],
        receiving: ["Giannis Antetokounmpo", "2027 MIL 1st Round Pick"],
      },
      team2: {
        team: "MIL",
        sending: ["Giannis Antetokounmpo", "2027 MIL 1st Round Pick"],
        receiving: ["Anthony Davis", "Austin Reaves"],
      },
      salaryMatch: true,
      salaryDiff: "+$1.9M (comfortably within threshold)",
      aiVerdict: "approve",
      aiAnalysis:
        "With the WCF in full swing and Cleveland looking like the East's best shot, Milwaukee's rebuild window is open. Sending Giannis to a LeBron-led Lakers squad creates an immediate title contender pairing two all-time talents in their final championship windows, while Davis's two-way gravity gives Milwaukee a credible anchor to build around post-Giannis era. The attached 2027 first sweetens the deal enough to make this realistic, and both front offices have the most to gain from a seismic reset heading into the 2026-27 offseason.",
      team1Impact: { offense: 7, defense: 4, chemistry: 4, future: -3 },
      team2Impact: { offense: -2, defense: 6, chemistry: 3, future: 7 },
      winProjectionChange: { team1: "+9.5 wins", team2: "-4.0 wins" },
    },
    // ── TRADE 2 ── APPROVED ───────────────────────────────────────────
    {
      id: "trade-2",
      team1: {
        team: "PHX",
        sending: ["Devin Booker"],
        receiving: ["Jaylen Brown", "2027 BOS 1st Round Pick", "2028 BOS 1st Round Pick"],
      },
      team2: {
        team: "BOS",
        sending: ["Jaylen Brown", "2027 BOS 1st Round Pick", "2028 BOS 1st Round Pick"],
        receiving: ["Devin Booker"],
      },
      salaryMatch: true,
      salaryDiff: "-$0.7M (essentially even)",
      aiVerdict: "approve",
      aiAnalysis:
        "Boston, watching the ECF between Cleveland and New York from their couch after an early exit, needs a cleaner co-star timeline beside Tatum — Booker's scoring versatility and clutch credentials are a generational fit that Brown's inconsistency never provided. Phoenix, drowning under the Bradley Beal albatross and with Durant entering the final stretch of his career, gets a younger two-way wing in Brown plus two lottery-protected firsts to pivot toward a proper rebuild. This deal makes both franchises materially better on their respective timelines.",
      team1Impact: { offense: -3, defense: 4, chemistry: 5, future: 8 },
      team2Impact: { offense: 5, defense: -2, chemistry: 3, future: -5 },
      winProjectionChange: { team1: "+2.0 wins", team2: "+4.5 wins" },
    },
    // ── TRADE 3 ── CONDITIONAL ────────────────────────────────────────
    {
      id: "trade-3",
      team1: {
        team: "OKC",
        sending: ["Chet Holmgren", "Luguentz Dort"],
        receiving: ["Paolo Banchero", "Franz Wagner"],
      },
      team2: {
        team: "ORL",
        sending: ["Paolo Banchero", "Franz Wagner"],
        receiving: ["Chet Holmgren", "Luguentz Dort"],
      },
      salaryMatch: true,
      salaryDiff: "+$4.1M (within 25% threshold)",
      aiVerdict: "conditional",
      aiAnalysis:
        "This trade is conditionally approved with one critical asterisk: OKC should only pull the trigger if they exit the WCF against San Antonio without a title. Banchero's two-way upside and Wagner's off-ball craft would give SGA a more versatile second and third option than Holmgren's injury-prone profile currently allows. Orlando, however, should demand a protected first-round pick be added before finalizing — giving up two ascending 23-24-year-olds for a rim-running seven-footer and a 3-and-D wing is a lateral move at best without additional draft capital.",
      team1Impact: { offense: 4, defense: -1, chemistry: 2, future: 3 },
      team2Impact: { offense: 2, defense: 3, chemistry: -2, future: -1 },
      winProjectionChange: { team1: "+2.5 wins", team2: "+1.0 wins" },
    },
    // ── TRADE 4 ── REJECT ─────────────────────────────────────────────
    {
      id: "trade-4",
      team1: {
        team: "CLE",
        sending: ["Darius Garland", "Jarrett Allen"],
        receiving: ["Kevin Durant", "Bradley Beal"],
      },
      team2: {
        team: "PHX",
        sending: ["Kevin Durant", "Bradley Beal"],
        receiving: ["Darius Garland", "Jarrett Allen"],
      },
      salaryMatch: false,
      salaryDiff: "+$25.4M over threshold — CLE absorbs significant cap damage",
      aiVerdict: "reject",
      aiAnalysis:
        "Cleveland should run screaming from this proposal. The Cavaliers are currently in the ECF against New York with Mobley and Mitchell as a championship-caliber core — absorbing Durant's $51.2M expiring AND Beal's radioactive $47.6M for two more years would cripple their cap flexibility precisely when they need to extend Mobley on a max deal this summer. Durant at 37 doesn't improve CLE's ceiling meaningfully given their existing big-man depth, and Beal's decline curve is a franchise-altering liability. Phoenix doesn't get better either — Garland redundantly duplicates Fox/Castle-type guards they've already moved on from.",
      team1Impact: { offense: 2, defense: -4, chemistry: -6, future: -9 },
      team2Impact: { offense: -3, defense: -2, chemistry: -4, future: 3 },
      winProjectionChange: { team1: "-1.5 wins", team2: "-3.0 wins" },
    },
    // ── TRADE 5 ── APPROVED ───────────────────────────────────────────
    {
      id: "trade-5",
      team1: {
        team: "NYK",
        sending: ["Mikal Bridges", "2027 NYK 1st Round Pick"],
        receiving: ["Scottie Barnes"],
      },
      team2: {
        team: "TOR",
        sending: ["Scottie Barnes"],
        receiving: ["Mikal Bridges", "2027 NYK 1st Round Pick"],
      },
      salaryMatch: true,
      salaryDiff: "+$3.2M (within threshold)",
      aiVerdict: "approve",
      aiAnalysis:
        "New York's ECF run against Cleveland has exposed a critical weakness: they lack a credible switchable forward who can contain Evan Mobley in space. Barnes — a 24-year-old point-forward who can guard 1-through-4 and create off the dribble — solves that problem immediately and grows with the Brunson/KAT core for years. Toronto, in full teardown mode after missing the playoffs, gets Bridges's steady two-way production plus a future first from a Knicks team that could be Finals-bound, making this a clean win-now vs. win-later swap that both front offices should jump at.",
      team1Impact: { offense: 3, defense: 6, chemistry: 4, future: -2 },
      team2Impact: { offense: -2, defense: -3, chemistry: 2, future: 8 },
      winProjectionChange: { team1: "+4.0 wins", team2: "-3.5 wins" },
    },
    // ── TRADE 6 ── CONDITIONAL ────────────────────────────────────────
    {
      id: "trade-6",
      team1: {
        team: "ATL",
        sending: ["Trae Young"],
        receiving: ["James Harden", "Darius Garland", "2026 CLE 2nd Round Pick"],
      },
      team2: {
        team: "CLE",
        sending: ["James Harden", "Darius Garland", "2026 CLE 2nd Round Pick"],
        receiving: ["Trae Young"],
      },
      salaryMatch: true,
      salaryDiff: "+$6.7M (within threshold)",
      aiVerdict: "conditional",
      aiAnalysis:
        "This proposal is conditionally intriguing for Cleveland but hinges entirely on their ECF outcome. If the Cavaliers beat New York and advance to the Finals with Mobley and Mitchell leading the way, Trae Young becomes a logical offseason acquisition to replace Harden's aging playmaking and Garland's redundant skillset with younger, more explosive creation — Young's elite pull-up shooting space the floor around Mobley in ways Harden simply can't anymore. The condition: Cleveland should only proceed if they're convinced Trae can accept a third-option role, which his Atlanta usage patterns suggest he cannot without a significant culture negotiation.",
      team1Impact: { offense: -4, defense: -2, chemistry: -3, future: 5 },
      team2Impact: { offense: 5, defense: -1, chemistry: -3, future: 4 },
      winProjectionChange: { team1: "-2.5 wins", team2: "+3.0 wins" },
    },
  ],

  hottest: [
    {
      player: "Giannis Antetokounmpo",
      team: "MIL",
      reason:
        "With Milwaukee's playoff window firmly closed and no realistic championship path alongside the current roster, Giannis has been quietly linked to both the Lakers and multiple cap-space teams seeking a franchise reset. His $55.8M salary for three more years is the only obstacle to a bidding war that would reshape the league.",
    },
    {
      player: "Devin Booker",
      team: "PHX",
      reason:
        "Phoenix's front office has signaled openness to moving Booker as the Bradley Beal buyout fallout and Kevin Durant's age create an impossible roster construction problem. Boston, San Antonio, and the Lakers have all been connected this week, making Booker the most coveted guard on the summer trade market.",
    },
    {
      player: "Darius Garland",
      team: "CLE",
      reason:
        "Garland's role has effectively evaporated in Cleveland's playoff run — he's played under 18 minutes in the last three postseason games as Harden controls the point-guard minutes alongside Mitchell and Mobley. Multiple Western Conference teams are monitoring his availability, knowing Cleveland must make a decision before his $33.4M comes off the books.",
    },
    {
      player: "Paolo Banchero",
      team: "ORL",
      reason:
        "Orlando's failed playoff push this season has triggered internal discussions about whether to build exclusively around Banchero or explore a blockbuster return. His age-23 profile and two-way versatility make him arguably the most coveted non-contender star available, with OKC and Dallas both rumored to have made preliminary inquiries.",
    },
    {
      player: "Jarrett Allen",
      team: "CLE",
      reason:
        "Allen's minutes have been squeezed to near irrelevance by the Mobley era in Cleveland, and with Mobley's max extension coming this summer, the cap math almost certainly forces Allen onto the trade market. He's one of the most coveted defensive bigs available for contenders seeking frontcourt insurance, with the Warriors and Timberwolves both reportedly interested.",
    },
    {
      player: "Kevin Durant",
      team: "PHX",
      reason:
        "Durant's trade buzz has reached a fever pitch this week as Phoenix's lottery odds crystallize and the franchise faces a historic crossroads. At 37, with two years and $103M remaining, KD is still a top-15 player — the Lakers, Warriors, and Spurs have all been mentioned in speculative packages as teams willing to absorb his contract for one final championship window.",
    },
  ],
};