// Auto-generated Trade Simulator data
// Weekly "What If" trade proposals and tradeable player database

export interface TradeablePlayer {
  name: string;
  team: string;
  position: string;
  age: number;
  salary: string;
  contractYears: number;
  ppg: number;
  rpg: number;
  apg: number;
  tradeValue: number;
  tradeable: boolean;
  untouchable: boolean;
}

export interface TradeProposal {
  id: string;
  team1: { team: string; sending: string[]; receiving: string[] };
  team2: { team: string; sending: string[]; receiving: string[] };
  salaryMatch: boolean;
  salaryDiff: string;
  aiVerdict: "approve" | "reject" | "conditional";
  aiAnalysis: string;
  team1Impact: { offense: number; defense: number; chemistry: number; future: number };
  team2Impact: { offense: number; defense: number; chemistry: number; future: number };
  winProjectionChange: { team1: string; team2: string };
}

export interface TradeSimData {
  generatedDate: string;
  players: TradeablePlayer[];
  featuredTrades: TradeProposal[];
  hottest: { player: string; team: string; reason: string }[];
}

export const tradeSimData: TradeSimData = {
  generatedDate: "September 28, 2026",
  players: [
    {
      name: "Victor Wembanyama",
      team: "SAS",
      position: "C",
      age: 22,
      salary: "$55.0M",
      contractYears: 4,
      ppg: 32.8,
      rpg: 12.1,
      apg: 4.1,
      tradeValue: 100,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Shai Gilgeous-Alexander",
      team: "OKC",
      position: "G",
      age: 28,
      salary: "$52.8M",
      contractYears: 3,
      ppg: 31.2,
      rpg: 5.2,
      apg: 6.1,
      tradeValue: 99,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "De'Aaron Fox",
      team: "SAS",
      position: "G",
      age: 28,
      salary: "$42.0M",
      contractYears: 3,
      ppg: 28.0,
      rpg: 3.8,
      apg: 6.0,
      tradeValue: 97,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Stephon Castle",
      team: "SAS",
      position: "G",
      age: 22,
      salary: "$18.2M",
      contractYears: 5,
      ppg: 15.8,
      rpg: 4.0,
      apg: 4.6,
      tradeValue: 96,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Alperen Sengun",
      team: "HOU",
      position: "C",
      age: 24,
      salary: "$38.5M",
      contractYears: 4,
      ppg: 22.1,
      rpg: 10.4,
      apg: 3.1,
      tradeValue: 94,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Jalen Brunson",
      team: "NYK",
      position: "G",
      age: 30,
      salary: "$48.0M",
      contractYears: 2,
      ppg: 26.4,
      rpg: 3.5,
      apg: 7.4,
      tradeValue: 91,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Anthony Edwards",
      team: "MIN",
      position: "G",
      age: 25,
      salary: "$45.6M",
      contractYears: 4,
      ppg: 27.8,
      rpg: 5.3,
      apg: 5.1,
      tradeValue: 93,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Karl-Anthony Towns",
      team: "NYK",
      position: "C",
      age: 31,
      salary: "$49.2M",
      contractYears: 2,
      ppg: 21.0,
      rpg: 11.0,
      apg: 3.2,
      tradeValue: 82,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Nikola Jokic",
      team: "DEN",
      position: "C",
      age: 31,
      salary: "$51.4M",
      contractYears: 2,
      ppg: 26.4,
      rpg: 12.7,
      apg: 8.0,
      tradeValue: 78,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jamal Murray",
      team: "DEN",
      position: "G",
      age: 29,
      salary: "$38.0M",
      contractYears: 2,
      ppg: 20.1,
      rpg: 4.0,
      apg: 6.2,
      tradeValue: 52,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Fred VanVleet",
      team: "HOU",
      position: "G",
      age: 32,
      salary: "$43.0M",
      contractYears: 1,
      ppg: 16.2,
      rpg: 3.1,
      apg: 6.8,
      tradeValue: 48,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Darius Garland",
      team: "CLE",
      position: "G",
      age: 26,
      salary: "$36.0M",
      contractYears: 3,
      ppg: 22.4,
      rpg: 3.0,
      apg: 7.8,
      tradeValue: 74,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Evan Mobley",
      team: "CLE",
      position: "F",
      age: 25,
      salary: "$34.0M",
      contractYears: 4,
      ppg: 18.6,
      rpg: 9.4,
      apg: 2.8,
      tradeValue: 85,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Donovan Mitchell",
      team: "CLE",
      position: "G",
      age: 30,
      salary: "$44.8M",
      contractYears: 2,
      ppg: 25.3,
      rpg: 4.2,
      apg: 5.6,
      tradeValue: 76,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Trae Young",
      team: "ATL",
      position: "G",
      age: 28,
      salary: "$40.5M",
      contractYears: 2,
      ppg: 24.8,
      rpg: 3.4,
      apg: 10.2,
      tradeValue: 72,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Zion Williamson",
      team: "NOP",
      position: "F",
      age: 26,
      salary: "$37.8M",
      contractYears: 2,
      ppg: 23.2,
      rpg: 6.8,
      apg: 3.5,
      tradeValue: 62,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Brandon Ingram",
      team: "NOP",
      position: "F",
      age: 29,
      salary: "$36.2M",
      contractYears: 1,
      ppg: 21.5,
      rpg: 5.2,
      apg: 4.1,
      tradeValue: 60,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jaylen Brown",
      team: "BOS",
      position: "G",
      age: 30,
      salary: "$49.0M",
      contractYears: 3,
      ppg: 23.1,
      rpg: 5.8,
      apg: 3.4,
      tradeValue: 77,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jayson Tatum",
      team: "BOS",
      position: "F",
      age: 28,
      salary: "$54.0M",
      contractYears: 3,
      ppg: 27.1,
      rpg: 8.3,
      apg: 4.8,
      tradeValue: 90,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Bam Adebayo",
      team: "MIA",
      position: "C",
      age: 29,
      salary: "$35.4M",
      contractYears: 2,
      ppg: 19.8,
      rpg: 10.2,
      apg: 3.6,
      tradeValue: 79,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Tyler Herro",
      team: "MIA",
      position: "G",
      age: 26,
      salary: "$32.6M",
      contractYears: 3,
      ppg: 21.7,
      rpg: 4.1,
      apg: 4.8,
      tradeValue: 71,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "LaMelo Ball",
      team: "CHA",
      position: "G",
      age: 25,
      salary: "$36.8M",
      contractYears: 3,
      ppg: 24.1,
      rpg: 6.3,
      apg: 8.4,
      tradeValue: 80,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Paolo Banchero",
      team: "ORL",
      position: "F",
      age: 24,
      salary: "$30.4M",
      contractYears: 4,
      ppg: 22.8,
      rpg: 6.9,
      apg: 4.2,
      tradeValue: 86,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Cade Cunningham",
      team: "DET",
      position: "G",
      age: 25,
      salary: "$34.2M",
      contractYears: 4,
      ppg: 23.6,
      rpg: 4.8,
      apg: 7.2,
      tradeValue: 84,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Devin Booker",
      team: "PHX",
      position: "G",
      age: 30,
      salary: "$47.5M",
      contractYears: 2,
      ppg: 25.6,
      rpg: 4.4,
      apg: 5.2,
      tradeValue: 74,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Kevin Durant",
      team: "PHX",
      position: "F",
      age: 38,
      salary: "$51.2M",
      contractYears: 1,
      ppg: 22.4,
      rpg: 7.1,
      apg: 4.0,
      tradeValue: 55,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Luka Doncic",
      team: "DAL",
      position: "G",
      age: 27,
      salary: "$53.6M",
      contractYears: 3,
      ppg: 28.8,
      rpg: 8.7,
      apg: 8.1,
      tradeValue: 89,
      tradeable: false,
      untouchable: true,
    },
    {
      name: "Kyrie Irving",
      team: "DAL",
      position: "G",
      age: 34,
      salary: "$38.0M",
      contractYears: 1,
      ppg: 22.2,
      rpg: 3.8,
      apg: 5.2,
      tradeValue: 50,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jaren Jackson Jr.",
      team: "MEM",
      position: "F",
      age: 26,
      salary: "$38.4M",
      contractYears: 3,
      ppg: 20.4,
      rpg: 7.2,
      apg: 1.8,
      tradeValue: 80,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Ja Morant",
      team: "MEM",
      position: "G",
      age: 27,
      salary: "$41.0M",
      contractYears: 3,
      ppg: 24.6,
      rpg: 5.8,
      apg: 7.6,
      tradeValue: 78,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Domantas Sabonis",
      team: "SAC",
      position: "C",
      age: 30,
      salary: "$30.8M",
      contractYears: 2,
      ppg: 18.8,
      rpg: 13.2,
      apg: 6.4,
      tradeValue: 68,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "De'Anthony Melton",
      team: "PHI",
      position: "G",
      age: 28,
      salary: "$14.2M",
      contractYears: 2,
      ppg: 12.4,
      rpg: 3.8,
      apg: 3.2,
      tradeValue: 54,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Tobias Harris",
      team: "PHI",
      position: "F",
      age: 34,
      salary: "$26.8M",
      contractYears: 1,
      ppg: 14.6,
      rpg: 6.4,
      apg: 2.8,
      tradeValue: 40,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Aaron Gordon",
      team: "DEN",
      position: "F",
      age: 31,
      salary: "$22.4M",
      contractYears: 1,
      ppg: 13.8,
      rpg: 6.6,
      apg: 2.4,
      tradeValue: 55,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Michael Porter Jr.",
      team: "DEN",
      position: "F",
      age: 28,
      salary: "$33.6M",
      contractYears: 2,
      ppg: 18.2,
      rpg: 7.4,
      apg: 1.6,
      tradeValue: 60,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Mikal Bridges",
      team: "BKN",
      position: "G",
      age: 30,
      salary: "$22.0M",
      contractYears: 2,
      ppg: 19.6,
      rpg: 4.4,
      apg: 3.6,
      tradeValue: 66,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Brook Lopez",
      team: "MIL",
      position: "C",
      age: 38,
      salary: "$14.0M",
      contractYears: 1,
      ppg: 11.2,
      rpg: 4.8,
      apg: 1.2,
      tradeValue: 38,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Khris Middleton",
      team: "MIL",
      position: "F",
      age: 35,
      salary: "$31.2M",
      contractYears: 1,
      ppg: 14.8,
      rpg: 5.2,
      apg: 4.0,
      tradeValue: 42,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Giannis Antetokounmpo",
      team: "MIL",
      position: "F",
      age: 32,
      salary: "$54.4M",
      contractYears: 2,
      ppg: 28.6,
      rpg: 11.4,
      apg: 5.6,
      tradeValue: 88,
      tradeable: true,
      untouchable: false,
    },
    {
      name: "Jrue Holiday",
      team: "BOS",
      position: "G",
      age: 36,
      salary: "$36.8M",
      contractYears: 1,
      ppg: 12.8,
      rpg: 4.6,
      apg: 4.4,
      tradeValue: 44,
      tradeable: true,
      untouchable: false,
    },
  ],
  featuredTrades: [
    {
      id: "trade-1",
      team1: {
        team: "DEN",
        sending: ["Nikola Jokic", "Michael Porter Jr."],
        receiving: ["Donovan Mitchell", "Darius Garland", "2027 First-Round Pick"],
      },
      team2: {
        team: "CLE",
        sending: ["Donovan Mitchell", "Darius Garland", "2027 First-Round Pick"],
        receiving: ["Nikola Jokic", "Michael Porter Jr."],
      },
      salaryMatch: true,
      salaryDiff: "+$1.6M (within threshold)",
      aiVerdict: "conditional",
      aiAnalysis:
        "Denver's stabilized-permanence classification entering its fifth day makes this the last viable window to extract maximum value from Jokic before camp-open architecture calcifies; Cleveland gets a generational talent but inherits a permanent organizational cost structure that the framework now describes in terminal language. Conditional approval hinges on Cleveland's willingness to absorb two years of embedded context drag with no remediation window remaining before October.",
      team1Impact: { offense: -4, defense: +2, chemistry: +3, future: +5 },
      team2Impact: { offense: +6, defense: +1, chemistry: -3, future: -4 },
      winProjectionChange: { team1: "-1.5 wins", team2: "+4.0 wins" },
    },
    {
      id: "trade-2",
      team1: {
        team: "MIL",
        sending: ["Giannis Antetokounmpo", "Khris Middleton"],
        receiving: ["LaMelo Ball", "Miles Bridges", "2027 First-Round Pick", "2028 First-Round Pick"],
      },
      team2: {
        team: "CHA",
        sending: ["LaMelo Ball", "Miles Bridges", "2027 First-Round Pick", "2028 First-Round Pick"],
        receiving: ["Giannis Antetokounmpo", "Khris Middleton"],
      },
      salaryMatch: true,
      salaryDiff: "+$3.4M (within threshold)",
      aiVerdict: "approve",
      aiAnalysis:
        "Milwaukee's championship window is firmly closed entering camp-open week with no compound or mature-integration classification to compete against SAS and HOU's elevated infrastructure tiers; Charlotte secures the biggest star in franchise history with two years of runway and Giannis's individual ceiling towers over every non-locked player in the East outside New York's settled champions. Milwaukee's youth-and-picks rebuild is the correct organizational response given the four-day foreclosure on any realistic contention path.",
      team1Impact: { offense: -5, defense: -4, chemistry: +2, future: +8 },
      team2Impact: { offense: +8, defense: +5, chemistry: -1, future: -5 },
      winProjectionChange: { team1: "-6.0 wins", team2: "+9.5 wins" },
    },
    {
      id: "trade-3",
      team1: {
        team: "PHX",
        sending: ["Kevin Durant", "Devin Booker"],
        receiving: ["Ja Morant", "Jaren Jackson Jr.", "2027 First-Round Pick"],
      },
      team2: {
        team: "MEM",
        sending: ["Ja Morant", "Jaren Jackson Jr.", "2027 First-Round Pick"],
        receiving: ["Kevin Durant", "Devin Booker"],
      },
      salaryMatch: true,
      salaryDiff: "+$0.9M (within threshold)",
      aiVerdict: "reject",
      aiAnalysis:
        "Phoenix acquires youth and a pick but surrenders a Finals-caliber scoring duo for a Morant who carries unresolved durability questions entering camp open with no organizational infrastructure classification to counterbalance the risk; Memphis wins on paper but Durant's age-38 expiring contract and Booker's declining trade value signal a contention window shorter than Jackson's developmental arc demands. The AI rejects this trade because both teams absorb structural liabilities that worsen their standing relative to the West's compound-tier leaders.",
      team1Impact: { offense: +1, defense: +2, chemistry: -4, future: +3 },
      team2Impact: { offense: -2, defense: -1, chemistry: -3, future: -2 },
      winProjectionChange: { team1: "-3.5 wins", team2: "-2.0 wins" },
    },
    {
      id: "trade-4",
      team1: {
        team: "ATL",
        sending: ["Trae Young", "2027 First-Round Pick"],
        receiving: ["Tyler Herro", "Bam Adebayo"],
      },
      team2: {
        team: "MIA",
        sending: ["Tyler Herro", "Bam Adebayo"],
        receiving: ["Trae Young", "2027 First-Round Pick"],
      },
      salaryMatch: true,
      salaryDiff: "+$2.1M (within threshold)",
      aiVerdict: "approve",
      aiAnalysis:
        "Atlanta breaks the Trae-era ceiling by adding proven two-way infrastructure in Adebayo alongside Herro's scoring punch, entering camp open with a more balanced roster construction than any organizational clarity Atlanta has displayed since the Hawks' 2021 Finals run; Miami converts Trae's elite playmaking into an asset that resets their offensive architecture around a true lead guard with ten-plus assists per game upside. Both franchises improve their preparation posture heading into October and the salary matching is clean.",
      team1Impact: { offense: -1, defense: +5, chemistry: +3, future: +2 },
      team2Impact: { offense: +4, defense: -3, chemistry: +1, future: +3 },
      winProjectionChange: { team1: "+3.5 wins", team2: "+2.0 wins" },
    },
    {
      id: "trade-5",
      team1: {
        team: "DEN",
        sending: ["Jamal Murray", "Aaron Gordon"],
        receiving: ["Mikal Bridges", "2026 First-Round Pick"],
      },
      team2: {
        team: "BKN",
        sending: ["Mikal Bridges", "2026 First-Round Pick"],
        receiving: ["Jamal Murray", "Aaron Gordon"],
      },
      salaryMatch: true,
      salaryDiff: "-$4.2M (within threshold)",
      aiVerdict: "conditional",
      aiAnalysis:
        "Denver sheds Murray's chronic knee management — now operating inside stabilized-permanence day five's terminal framework language — and Gordon's expiring deal in exchange for Bridges's reliable two-way production and a pick, giving the Nuggets a cleaner supporting cast around Jokic as they build inside permanent new architecture; Brooklyn absorbs Murray's health risk and Gordon's age but gains proven playoff contributors that elevate the Nets above pure development mode. Conditional on Denver using the salary savings and pick capital to close the infrastructure gap with Houston's day-twelve confirmed tier before camp open.",
      team1Impact: { offense: -2, defense: +3, chemistry: +4, future: +4 },
      team2Impact: { offense: +3, defense: +2, chemistry: -2, future: -3 },
      winProjectionChange: { team1: "+2.0 wins", team2: "+3.0 wins" },
    },
    {
      id: "trade-6",
      team1: {
        team: "MIN",
        sending: ["2027 First-Round Pick", "2028 First-Round Pick", "Domantas Sabonis"],
        receiving: ["Donovan Mitchell"],
      },
      team2: {
        team: "CLE",
        sending: ["Donovan Mitchell"],
        receiving: ["2027 First-Round Pick", "2028 First-Round Pick", "Domantas Sabonis"],
      },
      salaryMatch: false,
      salaryDiff: "+$13.6M (exceeds threshold — requires third team)",
      aiVerdict: "reject",
      aiAnalysis:
        "Minnesota's multi-player sequencing drag is actively accumulating as the four-day foreclosure window eliminates any remaining resolution scenarios before camp open, making this the worst possible moment to commit two first-round picks and a starter for a Mitchell whose own organizational context at Cleveland carries unresolved variables entering October; the salary mismatch further complicates execution and Minnesota's future cost without guaranteed resolution of the sequencing drag makes this a compounding liability acquisition. The AI rejects on both structural and timing grounds.",
      team1Impact: { offense: +3, defense: -1, chemistry: -5, future: -7 },
      team2Impact: { offense: -4, defense: +1, chemistry: +2, future: +6 },
      winProjectionChange: { team1: "+1.5 wins", team2: "-3.0 wins" },
    },
  ],
  hottest: [
    {
      player: "Nikola Jokic",
      team: "DEN",
      reason: "Stabilized-permanence day five is the framework's terminal language, and every contender knows Denver is a motivated seller; rival front offices are calling before camp open forecloses the final negotiating window on the most statistically decorated trade chip in the league.",
    },
    {
      player: "Jamal Murray",
      team: "DEN",
      reason: "Chronic knee management now described in permanent-architecture terms by the Hoops Intel framework makes Murray the most urgently movable secondary star in the West, and Denver's need to rebuild around a clarified Jokic context puts Murray at the top of every team's inquiry list this week.",
    },
    {
      player: "Trae Young",
      team: "ATL",
      reason: "Atlanta's organizational ceiling has flatlined with no compound or mature-integration classification entering the four-day foreclosure window, making Young's elite playmaking a misaligned asset on a roster with no realistic contention path and maximum trade-value urgency before October.",
    },
    {
      player: "Giannis Antetokounmpo",
      team: "MIL",
      reason: "Milwaukee's complete absence from the West's elevated infrastructure tiers — no compound, no mature-integration classification — has reignited league-wide speculation that Giannis will force a decision before camp open rather than inherit another season inside a stalled organizational architecture.",
    },
    {
      player: "Donovan Mitchell",
      team: "CLE",
      reason: "Cleveland's crowded backcourt and Mitchell's max-level salary with two years remaining make him the most actionable high-tier scoring guard available, and at least four teams with sequencing drag problems are using him as the targeted resolution asset this week.",
    },
    {
      player: "Kevin Durant",
      team: "PHX",
      reason: "Durant's age-38 expiring at $51.2M represents the league's highest-stakes one-year rental entering camp open, and Phoenix's total absence from any preparation-infrastructure classification makes contenders willing to absorb the salary for a single legitimate championship window.",
    },
  ],
};