// Auto-generated by generate-watch-guide.mjs
// April 25, 2026

export interface WatchGuideGame {
  rank: number;
  awayTeam: string;
  awayTeamFull: string;
  awayRecord: string;
  homeTeam: string;
  homeTeamFull: string;
  homeRecord: string;
  time: string;
  tv: string;
  venue: string;
  entertainmentScore: number;
  starPower: number;
  playoffImplications: number;
  rivalry: number;
  storyline: string;
  keyMatchup: string;
  mustWatch: boolean;
}

export interface WatchGuideData {
  generatedDate: string;
  displayDate: string;
  gamesCount: number;
  games: WatchGuideGame[];
  topPick: string;
  nightOverview: string;
}

export const watchGuideData: WatchGuideData = {
  generatedDate: "2026-04-25",
  displayDate: "April 25, 2026",
  gamesCount: 4,
  games: [
    {
      rank: 1,
      awayTeam: "OKC",
      awayTeamFull: "Oklahoma City Thunder",
      awayRecord: "64-18",
      homeTeam: "PHX",
      homeTeamFull: "Phoenix Suns",
      homeRecord: "45-37",
      time: "4/25 - 3:30 PM EDT",
      tv: "NBC, Peacock",
      venue: "Mortgage Matchup Center",
      entertainmentScore: 92,
      starPower: 9,
      playoffImplications: 10,
      rivalry: 7,
      storyline: "The West's #1 seed Thunder face a desperate Suns team fighting for playoff positioning in what could be a playoff preview. Phoenix needs every win to secure their postseason spot while OKC looks to maintain their grip on home-court advantage throughout the playoffs.",
      keyMatchup: "Shai Gilgeous-Alexander vs. Devin Booker",
      mustWatch: true
    },
    {
      rank: 2,
      awayTeam: "DEN",
      awayTeamFull: "Denver Nuggets",
      awayRecord: "54-28",
      homeTeam: "MIN",
      homeTeamFull: "Minnesota Timberwolves",
      homeRecord: "49-33",
      time: "4/25 - 8:30 PM EDT",
      tv: "ABC",
      venue: "Target Center",
      entertainmentScore: 87,
      starPower: 10,
      playoffImplications: 9,
      rivalry: 6,
      storyline: "Defending champion Nuggets clash with the hungry Timberwolves in a potential Western Conference playoff matchup. Both teams are jockeying for seeding position with Minnesota desperate to prove they can compete with the elite.",
      keyMatchup: "Nikola Jokic vs. Karl-Anthony Towns",
      mustWatch: true
    },
    {
      rank: 3,
      awayTeam: "NY",
      awayTeamFull: "New York Knicks",
      awayRecord: "53-29",
      homeTeam: "ATL",
      homeTeamFull: "Atlanta Hawks",
      homeRecord: "46-36",
      time: "4/25 - 6:00 PM EDT",
      tv: "NBC, Peacock",
      venue: "State Farm Arena",
      entertainmentScore: 81,
      starPower: 7,
      playoffImplications: 8,
      rivalry: 8,
      storyline: "Eastern Conference playoff positioning takes center stage as the Knicks look to solidify their seeding while Atlanta fights to improve their postseason standing. This matchup could determine playoff matchups with major implications for both franchises.",
      keyMatchup: "Jalen Brunson vs. Trae Young",
      mustWatch: true
    },
    {
      rank: 4,
      awayTeam: "DET",
      awayTeamFull: "Detroit Pistons",
      awayRecord: "60-22",
      homeTeam: "ORL",
      homeTeamFull: "Orlando Magic",
      homeRecord: "45-37",
      time: "4/25 - 1:00 PM EDT",
      tv: "Peacock, NBCSN",
      venue: "Kia Center",
      entertainmentScore: 73,
      starPower: 6,
      playoffImplications: 7,
      rivalry: 5,
      storyline: "Surging Pistons continue their remarkable turnaround season against a Magic team fighting to maintain their playoff position. Detroit's young core looks to prove their legitimacy against Orlando's experienced playoff-bound roster.",
      keyMatchup: "Cade Cunningham vs. Paolo Banchero",
      mustWatch: false
    }
  ],
  topPick: "Thunder at Suns delivers elite playoff-level intensity with massive seeding implications",
  nightOverview: "Tonight's slate features crucial playoff positioning battles across both conferences, headlined by the West's top seed Thunder visiting a desperate Suns team. All four games carry significant postseason implications with star-studded matchups throughout."
};