// Auto-generated by generate-watch-guide.mjs
// June 13, 2026

export interface WatchGuideFactors {
  starPower: number;
  playoffImplications: number;
  rivalry: number;
  entertainment: number;
  storyline: number;
}

export interface WatchGuideGame {
  rank: number;
  awayTeam: string;
  awayTeamFull: string;
  awayRecord: string;
  homeTeam: string;
  homeTeamFull: string;
  homeRecord: string;
  time: string;
  tv: string;
  venue: string;
  entertainmentScore: number;
  starPower: number;
  playoffImplications: number;
  rivalry: number;
  storyline: string;
  keyMatchup: string;
  mustWatch: boolean;
  factors: WatchGuideFactors;
  watchScore: number;
  headline: string;
}

export interface WatchGuidePick {
  gameIndex: number;
  reason: string;
}

export interface WatchGuideData {
  generatedDate: string;
  displayDate: string;
  date: string;
  gamesCount: number;
  games: WatchGuideGame[];
  topPick: WatchGuidePick;
  sleeper: WatchGuidePick;
  skipIt: WatchGuidePick;
  nightOverview: string;
}

export const watchGuideData: WatchGuideData = {
  generatedDate: "2026-06-13",
  displayDate: "June 13, 2026",
  date: "June 13, 2026",
  gamesCount: 1,
  games: [
    {
      rank: 1,
      awayTeam: "NYK",
      awayTeamFull: "New York Knicks",
      awayRecord: "53-29",
      homeTeam: "SAS",
      homeTeamFull: "San Antonio Spurs",
      homeRecord: "62-20",
      time: "6/13 - 8:30 PM EDT",
      tv: "ABC",
      venue: "Frost Bank Center",
      entertainmentScore: 97,
      starPower: 10,
      playoffImplications: 10,
      rivalry: 9,
      storyline:
        "The Spurs return home with a 2-1 series lead and a chance to put the Knicks in a near-impossible hole — but New York knows a loss tonight turns the Finals into a desperate, backs-against-the-wall mission. Wembanyama torched Madison Square Garden for 38; now the alien faces a Knicks team that must respond or face elimination pressure of the highest order.",
      keyMatchup: "Victor Wembanyama vs. Jalen Brunson",
      mustWatch: true,
      factors: {
        starPower: 20,
        playoffImplications: 20,
        rivalry: 18,
        entertainment: 20,
        storyline: 19,
      },
      watchScore: 97,
      headline: "NBA Finals Game 4: Spurs Seek the Stranglehold, Knicks Fight for Their Season",
    },
  ],
  topPick: {
    gameIndex: 0,
    reason:
      "It's NBA Finals Game 4 on ABC — the only game on the slate and it carries the full weight of a potential 3-1 series deficit for New York. Wembanyama is playing at an all-time level, Brunson needs a signature response, and Frost Bank Center will be rocking. This is must-see television from tip-off.",
  },
  sleeper: {
    gameIndex: 0,
    reason:
      "With only one game on the schedule, the sleeper is the game itself — specifically the Knicks' supporting cast. If OG Anunoby, Josh Hart, or Miles McBride catches fire alongside Brunson, New York has the firepower to steal one in San Antonio and reset the entire series narrative.",
  },
  skipIt: {
    gameIndex: 0,
    reason:
      "There is genuinely no game to skip tonight — this is a standalone NBA Finals game. If you have any interest in basketball, clear your evening. The only reason to 'skip' would be if a lopsided first half signals a blowout, but given the series competitiveness, expect a fourth-quarter battle.",
  },
  nightOverview:
    "Tonight's slate is a single-game Finals showcase: Game 4 of the NBA Finals at Frost Bank Center, with San Antonio holding a 2-1 series lead and Victor Wembanyama coming off a 38-point masterpiece at Madison Square Garden. The Knicks desperately need a road win to avoid the precipice of a 3-1 deficit, setting the stage for the highest-stakes game of the 2026 NBA season so far.",
};