// Auto-generated by generate-watch-guide.mjs
// May 5, 2026

export interface WatchGuideGame {
  rank: number;
  awayTeam: string;
  awayTeamFull: string;
  awayRecord: string;
  homeTeam: string;
  homeTeamFull: string;
  homeRecord: string;
  time: string;
  tv: string;
  venue: string;
  entertainmentScore: number;
  starPower: number;
  playoffImplications: number;
  rivalry: number;
  storyline: string;
  keyMatchup: string;
  mustWatch: boolean;
}

export interface WatchGuideData {
  generatedDate: string;
  displayDate: string;
  gamesCount: number;
  games: WatchGuideGame[];
  topPick: string;
  nightOverview: string;
}

export const watchGuideData: WatchGuideData = {
  generatedDate: "2026-05-05",
  displayDate: "May 5, 2026",
  gamesCount: 2,
  games: [
    {
      rank: 1,
      awayTeam: "LAL",
      awayTeamFull: "Los Angeles Lakers",
      awayRecord: "53-29",
      homeTeam: "OKC",
      homeTeamFull: "Oklahoma City Thunder",
      homeRecord: "64-18",
      time: "5/5 - 8:30 PM EDT",
      tv: "NBC, Peacock",
      venue: "Paycom Center",
      entertainmentScore: 94,
      starPower: 10,
      playoffImplications: 10,
      rivalry: 6,
      storyline: "LeBron James and the Lakers face the league's best record Thunder in a potential Conference Finals preview. Oklahoma City's home court advantage meets championship experience in primetime.",
      keyMatchup: "LeBron James vs. Shai Gilgeous-Alexander",
      mustWatch: true
    },
    {
      rank: 2,
      awayTeam: "CLE",
      awayTeamFull: "Cleveland Cavaliers",
      awayRecord: "52-30",
      homeTeam: "DET",
      homeTeamFull: "Detroit Pistons",
      homeRecord: "60-22",
      time: "5/5 - 7:00 PM EDT",
      tv: "NBCSN, Peacock",
      venue: "Little Caesars Arena",
      entertainmentScore: 86,
      starPower: 8,
      playoffImplications: 10,
      rivalry: 7,
      storyline: "Eastern Conference semifinals clash between two teams coming off grueling seven-game first-round battles. Detroit's dominant season meets Cleveland's playoff-tested resilience.",
      keyMatchup: "Cade Cunningham vs. Donovan Mitchell",
      mustWatch: true
    }
  ],
  topPick: "Lakers at Thunder features LeBron's championship experience against the league's best record in a potential Conference Finals preview",
  nightOverview: "Conference semifinals action continues with two elite matchups as Detroit hosts Cleveland in an Eastern slugfest before Lakers-Thunder delivers a primetime West showdown. Both games feature championship implications and star power worthy of must-watch status."
};