#!/usr/bin/env node
// generate-tactics.mjs — Weekly Coach's Corner tactical breakdown generator
// Run manually or via GitHub Actions once per week (e.g., Monday 6am PST)
//
// Usage:
//   node scripts/generate-tactics.mjs
//   node scripts/generate-tactics.mjs --week "Week of March 23–29, 2026"

import Anthropic from "@anthropic-ai/sdk";
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..");

// ── CLI args ────────────────────────────────────────────────

function getArg(flag) {
  const idx = process.argv.indexOf(flag);
  if (idx !== -1 && process.argv[idx + 1]) {
    return process.argv[idx + 1];
  }
  return null;
}

// Compute default week label: "Week of <Mon>–<Sun>, YYYY"
function defaultWeekLabel() {
  const now = new Date(new Date().toLocaleString("en-US", { timeZone: "America/Los_Angeles" }));
  const dayOfWeek = now.getDay();
  const daysToMon = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
  const mon = new Date(now);
  mon.setDate(now.getDate() + daysToMon);
  const sun = new Date(mon);
  sun.setDate(mon.getDate() + 6);

  const fmt = (d) =>
    d.toLocaleDateString("en-US", { month: "long", day: "numeric" });
  const year = sun.getFullYear();
  return `Week of ${fmt(mon)}–${fmt(sun).replace(/\D.*/, sun.getDate().toString())}, ${year}`;
}

function displayDate() {
  return new Date(
    new Date().toLocaleString("en-US", { timeZone: "America/Los_Angeles" })
  ).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
}

// ── Read pulseData.ts as context ────────────────────────────

function readPulseContext() {
  const pulseDataPath = join(ROOT, "client", "src", "lib", "pulseData.ts");
  try {
    const raw = readFileSync(pulseDataPath, "utf8");
    const match = raw.match(/export const pulseIndex\s*=\s*(\[[\s\S]*?\]);/);
    if (match) {
      return `Current Pulse Index (top 10 players by today's performance score):\n${match[1]}`;
    }
    return raw.slice(0, 3000);
  } catch (err) {
    console.warn("⚠  Could not read pulseData.ts:", err.message);
    return "(pulseData.ts not available)";
  }
}

// ── Claude prompt ───────────────────────────────────────────

function buildPrompt(weekLabel, pulseContext) {
  return `You are the Hoops Intel AI tactical analyst. Generate the weekly Coach's Corner — tactical breakdowns for 10 featured NBA teams.

Context: ${pulseContext}

Week: ${weekLabel}

Return ONLY a valid TypeScript module with this exact structure — no markdown fences, no commentary, just the TypeScript:

// Auto-generated by generate-tactics.mjs
// ${weekLabel}

export interface TacticalBreakdown {
  team: string;
  coach: string;
  offenseStyle: string;
  defenseScheme: string;
  paceRank: number;
  offRatingRank: number;
  defRatingRank: number;
  keyPlay: {
    name: string;
    description: string;
    frequency: string;
    efficiency: string;
  };
  weeklyAdjustment: string;
  schemeGrade: "A+" | "A" | "A-" | "B+" | "B" | "B-" | "C+" | "C" | "C-" | "D" | "F";
  narrative: string;
}

export interface WeeklySchemeWatch {
  title: string;
  description: string;
  teams: string[];
}

export interface TacticsData {
  generatedDate: string;
  weekLabel: string;
  breakdowns: TacticalBreakdown[];
  schemeOfTheWeek: { team: string; title: string; description: string };
  trendingTactics: WeeklySchemeWatch[];
  coachHotSeat: { coach: string; team: string; reason: string; temperature: "scorching" | "warm" | "lukewarm" }[];
  weeklyNarrative: string;
}

export const tacticsData: TacticsData = {
  generatedDate: "${displayDate()}",
  weekLabel: "${weekLabel}",
  weeklyNarrative: "...",
  schemeOfTheWeek: { team: "...", title: "...", description: "..." },
  breakdowns: [
    // 10 teams with full tactical breakdowns
    // Include real coaching names, realistic scheme descriptions
    // offenseStyle: "Motion-heavy", "Pick-and-roll dominant", etc.
    // defenseScheme: "Switch-everything", "Drop coverage", etc.
    // paceRank, offRatingRank, defRatingRank: 1-30
    // keyPlay: specific play with name, description, frequency ("X% of possessions"), efficiency ("X.XX PPP")
    // weeklyAdjustment: what changed this week specifically
    // schemeGrade: letter grade A+ through F
    // narrative: 3-4 sentences of analytical depth
  ],
  trendingTactics: [
    // 3 league-wide tactical trends, each with title, description (3-4 sentences), and relevant teams
  ],
  coachHotSeat: [
    // 3 coaches on varying heat levels: "scorching", "warm", "lukewarm"
  ],
};

Rules:
- Include exactly 10 team breakdowns featuring the most tactically interesting teams this week
- Use REAL current NBA coaching names
- Scheme descriptions must be specific and basketball-literate (not generic)
- Key play names should reference actual NBA terminology (Spain PnR, Horns, Floppy, etc.)
- Frequencies should be realistic (15-35% range for key actions)
- Efficiency in PPP (points per possession) format, realistic range 0.85-1.25
- Weekly adjustments must reference THIS week's context
- Narratives should be editorial and insightful, not just descriptive
- The TypeScript must be syntactically valid and importable`;
}

// ── Write output ────────────────────────────────────────────

function writeOutput(content) {
  const outPath = join(ROOT, "client", "src", "lib", "tacticsData.ts");
  writeFileSync(outPath, content, "utf8");
  return outPath;
}

// ── Main ────────────────────────────────────────────────────

async function main() {
  const weekLabel = getArg("--week") ?? defaultWeekLabel();
  const generatedDate = displayDate();

  console.log("🏀 Hoops Intel — Coach's Corner Generator");
  console.log(`   Week:      ${weekLabel}`);
  console.log(`   Generated: ${generatedDate}`);
  console.log("");

  const pulseContext = readPulseContext();
  console.log("📊 Loaded pulseData.ts context");

  const client = new Anthropic();

  console.log("🤖 Calling Claude (claude-sonnet-4-6)...");
  const prompt = buildPrompt(weekLabel, pulseContext);

  let responseText;
  try {
    const message = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 12000,
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    const block = message.content.find((b) => b.type === "text");
    if (!block) throw new Error("No text block in Claude response");
    responseText = block.text;
  } catch (err) {
    console.error("❌ Claude API error:", err.message);
    process.exit(1);
  }

  // Strip any accidental markdown fences
  responseText = responseText
    .replace(/^```(?:typescript|ts)?\n?/m, "")
    .replace(/\n?```$/m, "")
    .trim();

  let outPath;
  try {
    outPath = writeOutput(responseText);
  } catch (err) {
    console.error("❌ Failed to write output:", err.message);
    process.exit(1);
  }

  console.log(`✅ Coach's Corner written to: ${outPath}`);
  console.log("");
  console.log("Next steps:");
  console.log("  1. Review client/src/lib/tacticsData.ts for accuracy");
  console.log("  2. Commit and deploy");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
